In [3]:
!pip install lifelines

# Fix numpy/pyarrow conflict caused by mixed conda+pip environments
!pip install numpy --force-reinstall
!pip install pyarrow --force-reinstall

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: lifelines in c:\users\malosett\appdata\roaming\python\python311\site-packages (0.30.3)
Requirement already satisfied: numpy>=1.14.0 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from lifelines) (2.4.4)
Requirement already satisfied: scipy>=1.7.0 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from lifelines) (1.16.3)
Requirement already satisfied: pandas<3.0,>=2.1 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from lifelines) (2.3.3)
Requirement already satisfied: matplotlib>=3.0 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from lifelines) (3.10.7)
Requirement already satisfied: autograd>=1.5 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from lifelines) (1.8.0)
Requirement already satisfied: autograd-gamma>=0.3 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from lifelines) (0.5.0)
Requirement already satisfied: formulaic>=0.2.2 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from lifelines) (1.2.1)
Requirement already satisfied: interface-meta>=1.2.0 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from formulaic>=0.2.2->lifelines) (1.3.0)
Requirement already satisfied: narwhals>=1.17 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from formulaic>=0.2.2->lifelines) (2.18.1)
Requirement already satisfied: typing-extensions>=4.2.0 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from formulaic>=0.2.2->lifelines) (4.15.0)
Requirement already satisfied: wrapt>=1.0 in c:\programdata\anaconda3\lib\site-packages (from formulaic>=0.2.2->lifelines) (1.14.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from matplotlib>=3.0->lifelines) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0->lifelines) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0->lifelines) (4.25.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0->lifelines) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from matplotlib>=3.0->lifelines) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from matplotlib>=3.0->lifelines) (12.0.0)
Requirement already satisfied: pyparsing>=3 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0->lifelines) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0->lifelines) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas<3.0,>=2.1->lifelines) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas<3.0,>=2.1->lifelines) (2023.3)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.0->lifelines) (1.16.0)
Defaulting to user installation because normal site-packages is not writeable
Collecting numpy
  Using cached numpy-2.4.4-cp311-cp311-win_amd64.whl.metadata (6.6 kB)
Using cached numpy-2.4.4-cp311-cp311-win_amd64.whl (12.6 MB)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.4.4
    Uninstalling numpy-2.4.4:
      Successfully uninstalled numpy-2.4.4
Successfully installed numpy-2.4.4

  WARNING: The scripts f2py.exe and numpy-config.exe are installed in 'C:\Users\malosett\AppData\Roaming\Python\Python311\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\malosett\AppData\Roaming\Python\Python311\site-packages\~.mpy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\malosett\AppData\Roaming\Python\Python311\site-packages\~.mpy'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gensim 4.3.0 requires FuzzyTM>=0.4.0, which is not installed.
genai-core 2.7.1 requires numpy==1.26.4, but you have numpy 2.4.4 which is incompatible.
genai-core 2.7.1 requires openai<2.0.0,>=1.34.0, but you have openai 2.14.0 which is incompatible.
mlflow 3.9.0 requires pyarrow<23,>=4.0.0, but you have pyarrow 23.0.1 which is incompatible.
opencv-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 2.4.4 which is incompatible.
unstructured 0.16.25 requires numpy<2, but you have numpy 2.4.4 which is incompatible.
astropy 5.3.4 requires numpy<2,>=1.21, but you have numpy 2.4.4 which is incompatible.
pywavelets 1.5.0 requires numpy<2.0,>=1.22.4, but you have numpy 2.4.4 which is incompatible.
streamlit 1.30.0 requires cachetools<6,>=4.0, but you have cachetools 6.2.2 which is incompatible.
streamlit 1.30.0 requires numpy<2,>=1.19.3, but you have numpy 2.4.4 which is incompatible.
streamlit 1.30.0 requires packaging<24,>=16.8, but you have packaging 25.0 which is incompatible.
streamlit 1.30.0 requires pillow<11,>=7.1.0, but you have pillow 12.0.0 which is incompatible.
streamlit 1.30.0 requires protobuf<5,>=3.20, but you have protobuf 5.29.5 which is incompatible.
streamlit 1.30.0 requires rich<14,>=10.14.0, but you have rich 14.2.0 which is incompatible.
streamlit 1.30.0 requires tenacity<9,>=8.1.0, but you have tenacity 9.1.2 which is incompatible.

Defaulting to user installation because normal site-packages is not writeable
Collecting pyarrow
  Using cached pyarrow-23.0.1-cp311-cp311-win_amd64.whl.metadata (3.1 kB)
Using cached pyarrow-23.0.1-cp311-cp311-win_amd64.whl (27.5 MB)
Installing collected packages: pyarrow
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 23.0.1
    Uninstalling pyarrow-23.0.1:
      Successfully uninstalled pyarrow-23.0.1
Successfully installed pyarrow-23.0.1

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\malosett\AppData\Roaming\Python\Python311\site-packages\~-arrow.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\malosett\AppData\Roaming\Python\Python311\site-packages\~-arrow'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mlflow 3.9.0 requires pyarrow<23,>=4.0.0, but you have pyarrow 23.0.1 which is incompatible.
streamlit 1.30.0 requires cachetools<6,>=4.0, but you have cachetools 6.2.2 which is incompatible.
streamlit 1.30.0 requires numpy<2,>=1.19.3, but you have numpy 2.4.4 which is incompatible.
streamlit 1.30.0 requires packaging<24,>=16.8, but you have packaging 25.0 which is incompatible.
streamlit 1.30.0 requires pillow<11,>=7.1.0, but you have pillow 12.0.0 which is incompatible.
streamlit 1.30.0 requires protobuf<5,>=3.20, but you have protobuf 5.29.5 which is incompatible.
streamlit 1.30.0 requires rich<14,>=10.14.0, but you have rich 14.2.0 which is incompatible.
streamlit 1.30.0 requires tenacity<9,>=8.1.0, but you have tenacity 9.1.2 which is incompatible.

# Pricing Optimisation — Acceptance Probability & Expected Financial Loss

## Purpose
This notebook implements the **black-box model generation pipeline** used downstream by the pricing optimisation module.  
It produces four output CSV files consumed by the optimiser:

| Output file | Content | Model source |
|---|---|---|
| `df_acceptance_xgb_black_box.csv` | Acceptance probability per policy | XGBoost classifier |
| `df_exp_financial_loss_xgb_black_box.csv` | Expected financial loss per policy | XGBoost regressor |
| `df_acceptance_linear_model_black_box.csv` | Acceptance probability per policy | GLM (Logistic Regression) |
| `df_acceptance_gam_model_black_box.csv` | Acceptance probability per policy | GAM (LogisticGAM) |
| `df_exp_financial_loss_lner_black_box.csv` | Expected financial loss per policy | Linear  |
| 

Additionally, it serialises all trained models to `artifacts/` as pickle files for reuse (see Section 17).

## Workflow Overview
1. **Setup** — install dependencies  
2. **Data ingestion** — load and clean the 3m-1006 parquet dataset  
3. **Feature engineering** — rename columns, compute premium change ratio `U`  
4. **Outlier filtering** — apply per-column IQR / percentile bounds  
5. **Model training (cross-validation with OOF predictions)**  
   - XGBoost regressor: predicts current policy premium `Y`  
   - XGBoost classifier: predicts churn probability  
   - GLM (logistic regression): interpretable churn alternative  
   - GAM (LogisticGAM): semi-parametric churn alternative  
   - Linear regression: interpretable premium baseline  
6. **Output generation** — derive acceptance probability and save CSVs  
7. **Model serialisation** — save all four models to `artifacts/`

In [4]:
!pip install --upgrade scikit-learn optuna

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scikit-learn in c:\users\malosett\appdata\roaming\python\python311\site-packages (1.8.0)
Requirement already satisfied: optuna in c:\users\malosett\appdata\roaming\python\python311\site-packages (4.8.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from scikit-learn) (2.4.4)
Requirement already satisfied: scipy>=1.10.0 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.3.0 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from scikit-learn) (1.3.2)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: alembic>=1.5.0 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from optuna) (1.17.2)
Requirement already satisfied: colorlog in c:\users\malosett\appdata\roaming\python\python311\site-packages (from optuna) (6.10.1)
Requirement already satisfied: packaging>=20.0 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from optuna) (25.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in c:\programdata\anaconda3\lib\site-packages (from optuna) (2.0.25)
Requirement already satisfied: tqdm in c:\programdata\anaconda3\lib\site-packages (from optuna) (4.65.0)
Requirement already satisfied: PyYAML in c:\programdata\anaconda3\lib\site-packages (from optuna) (6.0.1)
Requirement already satisfied: Mako in c:\users\malosett\appdata\roaming\python\python311\site-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy>=1.4.2->optuna) (3.0.1)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from colorlog->optuna) (0.4.6)
Requirement already satisfied: MarkupSafe>=0.9.2 in c:\programdata\anaconda3\lib\site-packages (from Mako->alembic>=1.5.0->optuna) (2.1.3)

## Section 2 — Data Ingestion & Preprocessing

Loads the anonymised 3-month policy dataset (`full_dataset_anonimized_processed_3m_1006.parquet`) and applies the following quality filters:

- **Missing upcoming renewal data** — rows with sentinel values for premium (`9999`), premium % change (`9`) or driver age (`100`) are dropped.
- **Duplicate churn rows** — only the first churn event per policy is retained; subsequent rows after churn are removed.
- **Mismatch policies** — policies where the *supposed* next-year premium differs from the *actual* premium by more than €40 (or the % change differs by more than 0.2) are excluded entirely to avoid noisy training signal.

The analysis is restricted to `year == 7` through the `df_sub` filter below.

In [5]:
import pandas as pd

def preprocess_3m_1006(parquet_path: str):
    """"
    #### Args
    - parquet_path: path to parquet file containing the 3m_1006 dataset

    #### Returns
    - df: preprocessed dataframe
    """
    df = pd.read_parquet(parquet_path)
    # make sure df is sorted by policy number first then year
    df = df.sort_values(['encoded_policy_number', 'year']).reset_index(drop=True)
    print(f"Original rows {len(df)}, Unique policies: {df['encoded_policy_number'].nunique()}")

    # get rid of rows with missing upcoming renewal data
    df = df[
        (df['premio_total_continuado_x_impute_GTE100_LTE1500_missing_9999'] != 9999) & # upcoming renewal premium
        (df['tx_pt_continuado_x_impute_inflation_this_renewal_6m_GTEminus1_LTE1_missing_9'] != 9) & # cur renewal % change
        (df['idade_condutor_x_impute_GTE18_LTE100_map_missing_100'] != 100) # age
    ]

    # remove churned rows that are not the first churned row of each policy
    is_first_policy_row = df["encoded_policy_number"] != df["encoded_policy_number"].shift(1)
    mask = (
        (df["is_churn"] == False) |
        (
            (df["is_churn"] == True) &
            (
                is_first_policy_row |
                (df["is_churn"].shift(1) == False)
            )
        )
    )
    df = df[mask]

    # ----- remove entire policies with mismatches (supposed increase vs actual increase) 
    # ----- over the thresholds
    # premium mismatch
    supposed = "premio_total_continuado_x_impute_GTE100_LTE1500_missing_9999"
    actual = "valor_vigor_pt_apol"

    temp = df[['encoded_policy_number', actual, supposed]].copy()
    temp['diff'] = (temp[actual] - temp[supposed].shift(1)).fillna(0).abs()

    same_policy_mask = temp['encoded_policy_number'] == temp['encoded_policy_number'].shift(1)
    temp = temp[same_policy_mask]
    mismatches = temp.groupby('encoded_policy_number')['diff'].max() > 40 # threshold

    bad_policies = set(mismatches.index[mismatches])
    
    # premium % change mismatch
    actual = "tx_pt_continuado_ant_x_impute_inflation_last_renewal_6m_GTEminus1_LTE1_missing_9"
    supposed = "tx_pt_continuado_x_impute_inflation_this_renewal_6m_GTEminus1_LTE1_missing_9"

    temp = df[['encoded_policy_number', actual, supposed]].copy()
    temp = temp[temp[actual] != 9.0]
    temp['diff'] = (temp[actual] - temp[supposed].shift(1)).fillna(0).abs()

    same_policy_mask = temp['encoded_policy_number'] == temp['encoded_policy_number'].shift(1)
    temp = temp[same_policy_mask]
    mismatches = temp.groupby('encoded_policy_number')['diff'].max() > 0.2 # threshold

    bad_policies |= set(mismatches.index[mismatches])

    # remove bad policies from df
    df = df[~df['encoded_policy_number'].isin(bad_policies)]
    print(f"Remaining rows {len(df)}, Remaining unique policies: {df['encoded_policy_number'].nunique()}")

    return df

## Section 1 — Setup & Dependencies

In [190]:
from preprocessing import *
import numpy as np
import pprint as pp
from matplotlib import pyplot as plt

In [7]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

%matplotlib inline


from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder

In [8]:
import sklearn

In [305]:
file_path = r"full_dataset_anonimized_processed_3m_1006.parquet"
df = preprocess_3m_1006(file_path)

Original rows 3370487, Unique policies: 1103634
Remaining rows 3075795, Remaining unique policies: 1034510

In [306]:
df.head()

,encoded_policy_number,idade_condutor_x_impute_GTE18_LTE100_map_missing_100,indice_bonus_malus,canal_distribuicao_h4_x_grouping_all_products,cod_estatistico_classe_risco,num_sin_tot,num_apolices_tot,ind_cliente_b_x_grouping_all_products,idade_construcao_veiculo_x_impute_GTE0_LTE50_missing_0,antiguidade_apolice_x_impute_GTE0_LTE30_missing_0,valor_vigor_pt_apol,tx_pt_continuado_ant_x_impute_inflation_last_renewal_6m_GTEminus1_LTE1_missing_9,premio_total_continuado_x_impute_GTE100_LTE1500_missing_9999,tx_pt_continuado_x_impute_inflation_this_renewal_6m_GTEminus1_LTE1_missing_9,year,is_churn
0,5,86.0,50.000,19,T4005040,0,1,0,17.0,17.0,174.4700,-0.108391,157.14,-0.111998,0,False
1,5,87.0,47.500,19,T4005040,0,1,0,18.0,18.0,157.1400,-0.111998,156.74,-0.011103,1,False
2,5,88.0,45.125,19,T4005040,0,1,0,19.0,19.0,156.7400,-0.011103,156.36,-0.009236,2,False
3,5,89.0,45.000,19,T4005040,0,1,0,20.0,20.0,155.9369,-0.011918,164.11,0.051139,3,False
4,5,90.0,45.000,19,T4005040,0,1,0,21.0,21.0,164.1100,0.048342,163.72,-0.007067,4,False

In [11]:
!pip install -U glum

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: glum in c:\users\malosett\appdata\roaming\python\python311\site-packages (3.2.3)
Requirement already satisfied: formulaic>=1.2.0 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from glum) (1.2.1)
Requirement already satisfied: joblib in c:\users\malosett\appdata\roaming\python\python311\site-packages (from glum) (1.3.2)
Requirement already satisfied: narwhals>=2.0.0 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from glum) (2.18.1)
Requirement already satisfied: numexpr in c:\programdata\anaconda3\lib\site-packages (from glum) (2.8.7)
Requirement already satisfied: numpy>=1.24 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from glum) (2.4.4)
Requirement already satisfied: packaging in c:\users\malosett\appdata\roaming\python\python311\site-packages (from glum) (25.0)
Requirement already satisfied: pandas>=1.4 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from glum) (2.3.3)
Requirement already satisfied: pyarrow in c:\users\malosett\appdata\roaming\python\python311\site-packages (from glum) (23.0.1)
Requirement already satisfied: scikit-learn>=1.1.0 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from glum) (1.8.0)
Requirement already satisfied: scipy>=1.8.0 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from glum) (1.16.3)
Requirement already satisfied: tabmat>=4.1.5 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from glum) (4.2.1)
Requirement already satisfied: tqdm in c:\programdata\anaconda3\lib\site-packages (from glum) (4.65.0)
Requirement already satisfied: interface-meta>=1.2.0 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from formulaic>=1.2.0->glum) (1.3.0)
Requirement already satisfied: typing-extensions>=4.2.0 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from formulaic>=1.2.0->glum) (4.15.0)
Requirement already satisfied: wrapt>=1.0 in c:\programdata\anaconda3\lib\site-packages (from formulaic>=1.2.0->glum) (1.14.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas>=1.4->glum) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas>=1.4->glum) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas>=1.4->glum) (2023.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from scikit-learn>=1.1.0->glum) (3.6.0)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from tqdm->glum) (0.4.6)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.4->glum) (1.16.0)

In [230]:
df_sub.columns

Index(['encode_policy_number', 'X_age', 'X_bonus_malus_rating',
       'X_distr_channel', 'X_vehicle_type', 'ttm_claims', 'X_policy_count',
       'X_risk_code', 'X_vehicle_age', 'X_policy_tenure', 'X_policy_premium',
       'X_prev_renewal_perc', 'X_upcoming_premium', 'X_cur_renewal_perc',
       'year', 'is_churn'],
      dtype='object')

In [307]:
df_sub = df.loc[df.year==7]

## Section 3 — Feature Name Mapping

Raw column names in the parquet file use verbose Portuguese/encoded names.  
This section defines a mapping to clean `X_` prefixed names used throughout the modelling pipeline.

| Clean name | Meaning |
|---|---|
| `X_age` | Driver age (clamped 18–100) |
| `X_vehicle_age` | Vehicle age in years |
| `X_policy_tenure` | Policy seniority in years |
| `X_policy_count` | Number of policies held by this client |
| `X_risk_code` | Risk segment code (higher = lower risk) |
| `X_distr_channel` | Distribution channel group |
| `X_ttm_claims` | Total claims in trailing 12 months |
| `X_bonus_malus_rating` | Bonus-malus coefficient |
| `X_vehicle_type` | Vehicle statistical risk class |
| `X_policy_premium` | Current active premium (`Y` in regression) |
| `X_upcoming_premium` | Proposed renewal premium |
| `X_cur_renewal_perc` | % premium change at this renewal |
| `U` | Relative premium increase: `(upcoming - current) / current` |

In [308]:

age = 'idade_condutor_x_impute_GTE18_LTE100_map_missing_100'
vehicle_age = 'idade_construcao_veiculo_x_impute_GTE0_LTE50_missing_0' # 0 = new car
policy_tenure = 'antiguidade_apolice_x_impute_GTE0_LTE30_missing_0'
policy_count = 'num_apolices_tot'
risk_code = 'ind_cliente_b_x_grouping_all_products' # integers, larger = higher survival chance
distr_channel = 'canal_distribuicao_h4_x_grouping_all_products' # larger = higher obs survival in training
ttm_claims = 'num_sin_tot'
bonus_malus_rating = 'indice_bonus_malus'
vehicle_type = 'cod_estatistico_classe_risco'
policy_premium = 'valor_vigor_pt_apol'
upcoming_premium = 'premio_total_continuado_x_impute_GTE100_LTE1500_missing_9999'
prev_renewal_perc = "tx_pt_continuado_ant_x_impute_inflation_last_renewal_6m_GTEminus1_LTE1_missing_9"
cur_renewal_perc = 'tx_pt_continuado_x_impute_inflation_this_renewal_6m_GTEminus1_LTE1_missing_9' # % change of total premium
id_number = 'encode_policy_number'

# for selecting the features to build the model
covariate_cols = [age, vehicle_age, policy_count, risk_code, distr_channel, ttm_claims,bonus_malus_rating, vehicle_type,
                  policy_premium, upcoming_premium, cur_renewal_perc]
col_name_map = {
    id_number: 'encode_policy_number',
    age: 'X_age',
    vehicle_age: 'X_vehicle_age',
    policy_tenure: 'X_policy_tenure',
    policy_count: 'X_policy_count',
    risk_code: 'X_risk_code',
    distr_channel: 'X_distr_channel',
    ttm_claims: 'X_ttm_claims',
    bonus_malus_rating: 'X_bonus_malus_rating',
    vehicle_type: 'X_vehicle_type',
    policy_premium: 'X_policy_premium',
    upcoming_premium: 'X_upcoming_premium',
    prev_renewal_perc:"X_prev_renewal_perc",
    cur_renewal_perc: 'X_cur_renewal_perc'
}

In [309]:
df_sub = df_sub.rename(columns=col_name_map)

In [310]:
df_sub.columns

Index(['encoded_policy_number', 'X_age', 'X_bonus_malus_rating',
       'X_distr_channel', 'X_vehicle_type', 'X_ttm_claims', 'X_policy_count',
       'X_risk_code', 'X_vehicle_age', 'X_policy_tenure', 'X_policy_premium',
       'X_prev_renewal_perc', 'X_upcoming_premium', 'X_cur_renewal_perc',
       'year', 'is_churn'],
      dtype='object')

In [245]:
# common function to filter out rows fro xgb regression and classification

## Section 4 — Outlier Filtering: `filter_middle_advanced`

`filter_middle_advanced` applies **per-column** outlier filtering before model training.  
Three methods are supported:

- **`iqr`** — keeps rows within `[Q1 − k·IQR, Q3 + k·IQR]` (default `k = 1.5`)
- **`percentile`** — keeps rows between specified quantiles (e.g., 5th–95th)
- **`zscore`** — keeps rows within `mean ± threshold·std`

Categorical filtering reduces cardinality by keeping the top-N most frequent values.

**Why filter?**  
Extreme premium values and very rare distribution channels create poor generalisation.  
The filtered datasets vary per model (XGBoost, GLM, GAM, Linear) to allow independent tuning of cleaning thresholds.

In [311]:
def filter_middle_advanced(df, 
                          numeric_filters=None, 
                          categorical_filters=None,
                          keep_id_cols=None):
    """
    Advanced filtering with per-column configuration
    
    Parameters:
    -----------
    numeric_filters : dict
        {column_name: {'multiplier': 1.5, 'method': 'iqr'}}
    categorical_filters : dict
        {column_name: {'min_freq': 0.01, 'max_categories': 10, 'keep_values': [...]}}
    keep_id_cols : list
        Columns to preserve in output (like 'encoded_policy_number')
    """
    df_filtered = df.copy()
    
    if keep_id_cols is None:
        keep_id_cols = ['encoded_policy_number']
    
    # Numeric filtering
    if numeric_filters:
        for col, config in numeric_filters.items():
            multiplier = config.get('multiplier', 1.5)
            method = config.get('method', 'iqr')
            
            if method == 'iqr':
                Q1 = df[col].quantile(0.25)
                Q3 = df[col].quantile(0.75)
                IQR = Q3 - Q1
                lower = Q1 - multiplier * IQR
                upper = Q3 + multiplier * IQR
            elif method == 'percentile':
                lower = df[col].quantile(config.get('lower_q', 0.05))
                upper = df[col].quantile(config.get('upper_q', 0.95))
            elif method == 'zscore':
                mean = df[col].mean()
                std = df[col].std()
                threshold = config.get('threshold', 3)
                lower = mean - threshold * std
                upper = mean + threshold * std
            
            df_filtered = df_filtered[(df_filtered[col] >= lower) & (df_filtered[col] <= upper)]
            print(f"{col}: [{lower:.2f}, {upper:.2f}]")
    
    # Categorical filtering
    if categorical_filters:
        for col, config in categorical_filters.items():
            # Option 1: Explicit list of values to keep
            if 'keep_values' in config:
                valid_values = config['keep_values']
            # Option 2: By frequency or top N
            else:
                value_counts = df[col].value_counts()
                
                if 'max_categories' in config:
                    valid_values = value_counts.nlargest(config['max_categories']).index.tolist()
                elif 'min_freq' in config:
                    min_count = int(len(df) * config['min_freq'])
                    valid_values = value_counts[value_counts >= min_count].index.tolist()
                else:
                    valid_values = value_counts.index.tolist()
            
            df_filtered = df_filtered[df_filtered[col].isin(valid_values)]
            print(f"{col}: Kept {len(valid_values)} categories")
    
    print(f"\nTotal: {len(df)} → {len(df_filtered)} rows")
    
    return df_filtered


# Usage
df_middle = filter_middle_advanced(
    df_sub,
    numeric_filters={
        'X_age': {'multiplier': 1.5, 'method': 'iqr'},
        'X_policy_premium': {'multiplier': 2.0, 'method': 'iqr'},
        'X_upcoming_premium':{'multiplier':2.0,'method':'iqr'},
        'X_vehicle_age': {'method': 'percentile', 'lower_q': 0.05, 'upper_q': 0.95},
        'X_cur_renewal_perc':{'method': 'percentile', 'lower_q': 0.05, 'upper_q': 0.95}
    },
    categorical_filters={
        'X_distr_channel': {'max_categories':12},
        'X_risk_code': {'max_categories': 6},
        'X_vehicle_type': {'max_categories': 8}  # explicit list
    },
    keep_id_cols=['encoded_policy_number']
)

X_age: [8.50, 100.50]
X_policy_premium: [-14.06, 444.14]
X_upcoming_premium: [-15.07, 480.13]
X_vehicle_age: [4.00, 31.00]
X_cur_renewal_perc: [-0.02, 0.11]
X_distr_channel: Kept 12 categories
X_risk_code: Kept 6 categories
X_vehicle_type: Kept 8 categories

Total: 463400 → 194373 rows

## Section 5 — Model Architecture Definitions

Three model classes are defined here and reused across datasets:

### `ModelRegressor`
XGBoost regressor with **Optuna hyperparameter tuning**.  
- Objective: `reg:absoluteerror` (MAE-optimised)
- Tuned parameters: `learning_rate`, `max_depth`, `subsample`, `colsample_bytree`, `min_child_weight`
- Used to predict `X_policy_premium` (target `Y`)

### `ModelClassifier`
XGBoost binary classifier with **Optuna hyperparameter tuning**.  
- Metric: ROC-AUC
- Used to predict churn (`is_churn`), which is then converted to acceptance probability: `Z = 1 − is_churn`, `prob_acceptance = 1 − churn_proba`

### `ModelRegressorCV`  
Extended version of `ModelRegressor` that runs **fully nested Optuna + KFold CV** in a single call. Used for the policy premium regression CV experiment.

In [312]:

from sklearn import metrics
import pandas as pd
import numpy as np
import xgboost as xgb
import optuna
from optuna.trial import Trial
N_ESTIMATORS = 200
OBJECTIVE = 'reg:absoluteerror'
class ModelRegressor():
    
    def objective(self,trial : Trial, X_train : pd.DataFrame, y_train : pd.Series,X_val : pd.DataFrame, y_val : pd.Series)-> float:
        params = {
            "learning_rate": trial.suggest_float("learning_rate", 1e-3, 0.1, log=True),
            "max_depth": trial.suggest_int("max_depth", 1, 10),
            "subsample": trial.suggest_float("subsample", 0.05, 1.0),
            "colsample_bytree": trial.suggest_float("colsample_bytree", 0.05, 1.0),
            "min_child_weight": trial.suggest_int("min_child_weight", 1, 20),
        }
        model = xgb.XGBRegressor(**params,random_state=123,n_estimators=N_ESTIMATORS,early_stopping_rounds=5,objective = OBJECTIVE)
        model.fit(X_train, y_train,verbose=0,eval_set=[(X_val, y_val)])
        y_pred = model.predict(X_val)
        loss = metrics.mean_absolute_error(y_true=y_val,y_pred=y_pred)
        return loss
    
    def tuning(self,X_train:pd.DataFrame,y_train:pd.Series,X_val:pd.DataFrame, y_val:pd.Series,n_trials:int)->dict:
        y_train = y_train
        y_val = y_val
        study = optuna.create_study(study_name='Xgboost', direction='minimize')
        study.optimize(lambda trial: self.objective(trial, X_train, y_train, X_val, y_val), n_trials=n_trials)
        best_params = study.best_params
        return best_params
    
    def train(self,X_train:pd.DataFrame,y_train:pd.Series,X_val:pd.DataFrame, y_val:pd.Series,best_params:dict)->xgb.XGBRegressor:
        y_train = y_train
        y_val = y_val
        model = xgb.XGBRegressor(**best_params,random_state=123,n_estimators=N_ESTIMATORS,early_stopping_rounds=5,objective = OBJECTIVE)
        model.fit(X_train, y_train,verbose=0,eval_set=[(X_val, y_val)])
        return model

In [313]:
from sklearn import metrics
import pandas as pd
import xgboost as xgb
import optuna
from optuna.trial import Trial

N_ESTIMATORS = 200

class ModelClassifier():
    
    def objective(self,trial : Trial, X_train : pd.DataFrame, y_train : pd.Series,X_val : pd.DataFrame, y_val : pd.Series)-> float:
        params = {
            "learning_rate": trial.suggest_float("learning_rate", 1e-3, 0.1, log=True),
            "max_depth": trial.suggest_int("max_depth", 1, 10),
            "subsample": trial.suggest_float("subsample", 0.05, 1.0),
            "colsample_bytree": trial.suggest_float("colsample_bytree", 0.05, 1.0),
            "min_child_weight": trial.suggest_int("min_child_weight", 1, 20),
        }

        model = xgb.XGBClassifier(**params,random_state=123,n_estimators=N_ESTIMATORS,early_stopping_rounds=5)
        model.fit(X_train, y_train,verbose=0,eval_set=[(X_val, y_val)])
        y_score = model.predict_proba(X_val)[:,1]
        roc_auc = metrics.roc_auc_score(y_true=y_val,y_score=y_score)
        return roc_auc
    
    def tuning(self,X_train:pd.DataFrame,y_train:pd.Series,X_val:pd.DataFrame, y_val:pd.Series,n_trials:int)->dict:
        study = optuna.create_study(study_name='Xgboost', direction='maximize')
        study.optimize(lambda trial: self.objective(trial, X_train, y_train, X_val, y_val), n_trials=n_trials)
        best_params = study.best_params
        return best_params
    
    def train(self,X_train:pd.DataFrame,y_train:pd.Series,X_val:pd.DataFrame, y_val:pd.Series,best_params:dict)->xgb.XGBClassifier:
        model = xgb.XGBClassifier(**best_params,random_state= 123,n_estimators= N_ESTIMATORS,
                                  early_stopping_rounds= 5)
        model.fit(X_train, y_train,verbose=0,eval_set=[(X_val, y_val)])
        return model

In [314]:
# generate dset for class xgb and xgb reg

In [316]:
df_middle.columns

Index(['encoded_policy_number', 'X_age', 'X_bonus_malus_rating',
       'X_distr_channel', 'X_vehicle_type', 'X_ttm_claims', 'X_policy_count',
       'X_risk_code', 'X_vehicle_age', 'X_policy_tenure', 'X_policy_premium',
       'X_prev_renewal_perc', 'X_upcoming_premium', 'X_cur_renewal_perc',
       'year', 'is_churn'],
      dtype='object')

In [317]:
df_middle_class = filter_middle_advanced(
    df_sub,
    numeric_filters={
        'X_age': {'multiplier': 1.5, 'method': 'iqr'},
        'X_policy_premium': {'multiplier': 2.0, 'method': 'iqr'},
        'X_upcoming_premium':{'multiplier':2.0,'method':'iqr'},
        'X_vehicle_age': {'method': 'percentile', 'lower_q': 0.05, 'upper_q': 0.95},
        'X_cur_renewal_perc':{'method': 'percentile', 'lower_q': 0.05, 'upper_q': 0.95}
    },
    categorical_filters={
        'X_distr_channel': {'max_categories':12},
        'X_risk_code': {'max_categories': 6},
        'X_vehicle_type': {'max_categories': 8}  # explicit list
    },
    keep_id_cols=['encode_policy_number']
)

X_age: [8.50, 100.50]
X_policy_premium: [-14.06, 444.14]
X_upcoming_premium: [-15.07, 480.13]
X_vehicle_age: [4.00, 31.00]
X_cur_renewal_perc: [-0.02, 0.11]
X_distr_channel: Kept 12 categories
X_risk_code: Kept 6 categories
X_vehicle_type: Kept 8 categories

Total: 463400 → 194373 rows

In [318]:
def filter_middle_iqr(df, columns=None, multiplier=1.5):
    """Keep observations within Q1 - multiplier*IQR to Q3 + multiplier*IQR"""
    df_filtered = df.copy()
    
    # Use numeric columns only if not specified
    if columns is None:
        columns = df.select_dtypes(include=['number']).columns
        columns = [col for col in columns if col not in ['encoded_policy_number', 'is_churn']]
    
    for col in columns:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1
        lower = Q1 - multiplier * IQR
        upper = Q3 + multiplier * IQR
        df_filtered = df_filtered[(df_filtered[col] >= lower) & (df_filtered[col] <= upper)]
    
    return df_filtered

In [320]:
df_middle_class.columns

Index(['encoded_policy_number', 'X_age', 'X_bonus_malus_rating',
       'X_distr_channel', 'X_vehicle_type', 'X_ttm_claims', 'X_policy_count',
       'X_risk_code', 'X_vehicle_age', 'X_policy_tenure', 'X_policy_premium',
       'X_prev_renewal_perc', 'X_upcoming_premium', 'X_cur_renewal_perc',
       'year', 'is_churn'],
      dtype='object')

In [321]:
from sklearn import metrics
from sklearn.model_selection import KFold, cross_val_score
import pandas as pd
import numpy as np
import xgboost as xgb
import optuna
from optuna.trial import Trial

N_ESTIMATORS = 200
OBJECTIVE = 'reg:absoluteerror'
N_FOLDS = 5
RANDOM_STATE = 123

class ModelRegressorCV():
    
    def __init__(self, n_folds=N_FOLDS, random_state=RANDOM_STATE):
        self.n_folds = n_folds
        self.random_state = random_state
        self.best_params = None
        self.cv_scores = None
        self.final_model = None
        
    def objective(self, trial: Trial, X: pd.DataFrame, y: pd.Series) -> float:
        """Optuna objective with cross-validation"""
        params = {
            "learning_rate": trial.suggest_float("learning_rate", 1e-3, 0.1, log=True),
            "max_depth": trial.suggest_int("max_depth", 1, 10),
            "subsample": trial.suggest_float("subsample", 0.05, 1.0),
            "colsample_bytree": trial.suggest_float("colsample_bytree", 0.05, 1.0),
            "min_child_weight": trial.suggest_int("min_child_weight", 1, 20),
        }
        
        # Cross-validation with the suggested parameters
        kfold = KFold(n_splits=self.n_folds, shuffle=True, random_state=self.random_state)
        cv_scores = []
        
        for train_idx, val_idx in kfold.split(X):
            X_train_fold, X_val_fold = X.iloc[train_idx], X.iloc[val_idx]
            y_train_fold, y_val_fold = y.iloc[train_idx], y.iloc[val_idx]
            
            # Apply log transformation
            y_train_transformed = np.log(y_train_fold) + 1
            y_val_transformed = np.log(y_val_fold) + 1
            
            model = xgb.XGBRegressor(
                **params,
                random_state=self.random_state,
                n_estimators=N_ESTIMATORS,
                early_stopping_rounds=5,
                objective=OBJECTIVE
            )
            
            model.fit(
                X_train_fold, 
                y_train_transformed,
                verbose=0,
                eval_set=[(X_val_fold, y_val_transformed)]
            )
            
            y_pred = model.predict(X_val_fold)
            fold_mae = metrics.mean_absolute_error(y_val_transformed, y_pred)
            cv_scores.append(fold_mae)
        
        # Return mean CV score
        return np.mean(cv_scores)
    
    def tuning(self, X: pd.DataFrame, y: pd.Series, n_trials: int) -> dict:
        """Hyperparameter tuning with cross-validation"""
        print(f"Starting hyperparameter tuning with {n_trials} trials and {self.n_folds}-fold CV...")
        
        study = optuna.create_study(study_name='XGBoost_CV', direction='minimize')
        study.optimize(
            lambda trial: self.objective(trial, X, y), 
            n_trials=n_trials,
            show_progress_bar=True
        )
        
        self.best_params = study.best_params
        print(f"\nBest CV MAE: {study.best_value:.6f}")
        print(f"Best parameters: {self.best_params}")
        
        return self.best_params
    
    def train_with_cv(self, X: pd.DataFrame, y: pd.Series, params: dict = None) -> tuple:
        """Train model with cross-validation and return CV scores"""
        if params is None:
            if self.best_params is None:
                raise ValueError("No parameters provided. Run tuning() first or provide params.")
            params = self.best_params
        
        print(f"\nTraining with {self.n_folds}-fold cross-validation...")
        kfold = KFold(n_splits=self.n_folds, shuffle=True, random_state=self.random_state)
        
        cv_scores = []
        fold_models = []
        
        for fold_num, (train_idx, val_idx) in enumerate(kfold.split(X), 1):
            X_train_fold, X_val_fold = X.iloc[train_idx], X.iloc[val_idx]
            y_train_fold, y_val_fold = y.iloc[train_idx], y.iloc[val_idx]
            
            # Apply log transformation
            y_train_transformed = y_train_fold 
            y_val_transformed = y_val_fold 
            
            model = xgb.XGBRegressor(
                **params,
                random_state=self.random_state,
                n_estimators=N_ESTIMATORS,
                early_stopping_rounds=5,
                objective=OBJECTIVE
            )
            
            model.fit(
                X_train_fold, 
                y_train_transformed,
                verbose=0,
                eval_set=[(X_val_fold, y_val_transformed)]
            )
            
            y_pred = model.predict(X_val_fold)
            fold_mae = metrics.mean_absolute_error(y_val_transformed, y_pred)
            cv_scores.append(fold_mae)
            fold_models.append(model)
            
            print(f"Fold {fold_num}: MAE = {fold_mae:.6f}")
        
        self.cv_scores = cv_scores
        print(f"\nMean CV MAE: {np.mean(cv_scores):.6f} (+/- {np.std(cv_scores):.6f})")
        
        return fold_models, cv_scores
    
    def train_final(self, X: pd.DataFrame, y: pd.Series, params: dict = None) -> xgb.XGBRegressor:
        """Train final model on full dataset"""
        if params is None:
            if self.best_params is None:
                raise ValueError("No parameters provided. Run tuning() first or provide params.")
            params = self.best_params
        
        print("\nTraining final model on full dataset...")
        y_transformed = np.log(y) + 1
        
        # Use a portion for validation (20%)
        split_idx = int(len(X) * 0.8)
        X_train, X_val = X.iloc[:split_idx], X.iloc[split_idx:]
        y_train, y_val = y_transformed.iloc[:split_idx], y_transformed.iloc[split_idx:]
        
        model = xgb.XGBRegressor(
            **params,
            random_state=self.random_state,
            n_estimators=N_ESTIMATORS,
            early_stopping_rounds=5,
            objective=OBJECTIVE
        )
        
        model.fit(
            X_train, 
            y_train,
            verbose=0,
            eval_set=[(X_val, y_val)]
        )
        
        self.final_model = model
        print("Final model training complete!")
        
        return model
    
    def predict(self, X: pd.DataFrame, inverse_transform: bool = True) -> np.ndarray:
        """Make predictions using the final model"""
        if self.final_model is None:
            raise ValueError("No model trained. Run train_final() first.")
        
        predictions = self.final_model.predict(X)
        
        if inverse_transform:
            # Inverse log transformation
            predictions = predictions
        
        return predictions

In [322]:
from sklearn.model_selection import KFold, cross_val_score
import pandas as pd
import numpy as np
import xgboost as xgb
import optuna
from optuna.trial import Trial

N_ESTIMATORS = 200
OBJECTIVE = 'reg:absoluteerror'
N_FOLDS = 5
RANDOM_STATE = 123

class ModelRegressorCV():
    
    def __init__(self, n_folds=N_FOLDS, random_state=RANDOM_STATE):
        self.n_folds = n_folds
        self.random_state = random_state
        self.best_params = None
        self.cv_scores = None
        self.final_model = None
        
    def objective(self, trial: Trial, X: pd.DataFrame, y: pd.Series) -> float:
        """Optuna objective with cross-validation"""
        params = {
            "learning_rate": trial.suggest_float("learning_rate", 1e-3, 0.1, log=True),
            "max_depth": trial.suggest_int("max_depth", 1, 10),
            "subsample": trial.suggest_float("subsample", 0.05, 1.0),
            "colsample_bytree": trial.suggest_float("colsample_bytree", 0.05, 1.0),
            "min_child_weight": trial.suggest_int("min_child_weight", 1, 20),
        }
        
        # Cross-validation with the suggested parameters
        kfold = KFold(n_splits=self.n_folds, shuffle=True, random_state=self.random_state)
        cv_scores = []
        
        for train_idx, val_idx in kfold.split(X):
            X_train_fold, X_val_fold = X.iloc[train_idx], X.iloc[val_idx]
            y_train_fold, y_val_fold = y.iloc[train_idx], y.iloc[val_idx]
            
            # Apply log transformation
            y_train_transformed = np.log(y_train_fold) + 1
            y_val_transformed = np.log(y_val_fold) + 1
            
            model = xgb.XGBRegressor(
                **params,
                random_state=self.random_state,
                n_estimators=N_ESTIMATORS,
                early_stopping_rounds=5,
                objective=OBJECTIVE
            )
            
            model.fit(
                X_train_fold, 
                y_train_transformed,
                verbose=0,
                eval_set=[(X_val_fold, y_val_transformed)]
            )
            
            y_pred = model.predict(X_val_fold)
            fold_mae = metrics.mean_absolute_error(y_val_transformed, y_pred)
            cv_scores.append(fold_mae)
        
        # Return mean CV score
        return np.mean(cv_scores)
    
    def tuning(self, X: pd.DataFrame, y: pd.Series, n_trials: int) -> dict:
        """Hyperparameter tuning with cross-validation"""
        print(f"Starting hyperparameter tuning with {n_trials} trials and {self.n_folds}-fold CV...")
        
        study = optuna.create_study(study_name='XGBoost_CV', direction='minimize')
        study.optimize(
            lambda trial: self.objective(trial, X, y), 
            n_trials=n_trials,
            show_progress_bar=True
        )
        
        self.best_params = study.best_params
        print(f"\nBest CV MAE: {study.best_value:.6f}")
        print(f"Best parameters: {self.best_params}")
        
        return self.best_params
    
    def train_with_cv(self, X: pd.DataFrame, y: pd.Series, params: dict = None) -> tuple:
        """Train model with cross-validation and return CV scores"""
        if params is None:
            if self.best_params is None:
                raise ValueError("No parameters provided. Run tuning() first or provide params.")
            params = self.best_params
        
        print(f"\nTraining with {self.n_folds}-fold cross-validation...")
        kfold = KFold(n_splits=self.n_folds, shuffle=True, random_state=self.random_state)
        
        cv_scores = []
        fold_models = []
        
        for fold_num, (train_idx, val_idx) in enumerate(kfold.split(X), 1):
            X_train_fold, X_val_fold = X.iloc[train_idx], X.iloc[val_idx]
            y_train_fold, y_val_fold = y.iloc[train_idx], y.iloc[val_idx]
            
            # Apply log transformation
            y_train_transformed = np.log(y_train_fold) + 1
            y_val_transformed = np.log(y_val_fold) + 1
            
            model = xgb.XGBRegressor(
                **params,
                random_state=self.random_state,
                n_estimators=N_ESTIMATORS,
                early_stopping_rounds=5,
                objective=OBJECTIVE
            )
            
            model.fit(
                X_train_fold, 
                y_train_transformed,
                verbose=0,
                eval_set=[(X_val_fold, y_val_transformed)]
            )
            
            y_pred = model.predict(X_val_fold)
            fold_mae = metrics.mean_absolute_error(y_val_transformed, y_pred)
            cv_scores.append(fold_mae)
            fold_models.append(model)
            
            print(f"Fold {fold_num}: MAE = {fold_mae:.6f}")
        
        self.cv_scores = cv_scores
        print(f"\nMean CV MAE: {np.mean(cv_scores):.6f} (+/- {np.std(cv_scores):.6f})")
        
        return fold_models, cv_scores
    
    def train_final(self, X: pd.DataFrame, y: pd.Series, params: dict = None) -> xgb.XGBRegressor:
        """Train final model on full dataset"""
        if params is None:
            if self.best_params is None:
                raise ValueError("No parameters provided. Run tuning() first or provide params.")
            params = self.best_params
        
        print("\nTraining final model on full dataset...")
        y_transformed = np.log(y) + 1
        
        # Use a portion for validation (20%)
        split_idx = int(len(X) * 0.8)
        X_train, X_val = X.iloc[:split_idx], X.iloc[split_idx:]
        y_train, y_val = y_transformed.iloc[:split_idx], y_transformed.iloc[split_idx:]
        
        model = xgb.XGBRegressor(
            **params,
            random_state=self.random_state,
            n_estimators=N_ESTIMATORS,
            early_stopping_rounds=5,
            objective=OBJECTIVE
        )
        
        model.fit(
            X_train, 
            y_train,
            verbose=0,
            eval_set=[(X_val, y_val)]
        )
        
        self.final_model = model
        print("Final model training complete!")
        
        return model
    
    def predict(self, X: pd.DataFrame, inverse_transform: bool = True) -> np.ndarray:
        """Make predictions using the final model"""
        if self.final_model is None:
            raise ValueError("No model trained. Run train_final() first.")
        
        predictions = self.final_model.predict(X)
        
        if inverse_transform:
            # Inverse log transformation
            predictions = np.exp(predictions - 1)
        
        return predictions

In [323]:
# encode category feats

In [324]:
cat_cols = list(df_middle.select_dtypes('object').columns)

from sklearn.preprocessing import LabelEncoder
for cat in cat_cols:
    le = LabelEncoder()
    le.fit(df_middle[cat])
    df_middle[cat] = le.transform(df_middle[cat])
    df_middle_class[cat] = le.transform(df_middle_class[cat])

## Section 6 — Dataset Preparation for XGBoost

Two filtered datasets are created from `df_sub`:

- **`df_middle`** — used for the **premium regressor** (target: `X_policy_premium`)  
- **`df_middle_class`** — used for the **churn classifier** (target: `is_churn`)

Both use identical `filter_middle_advanced` thresholds.  
Categorical columns (`X_distr_channel`, `X_risk_code`, `X_vehicle_type`) are **label-encoded** here so XGBoost can consume them directly.

The premium change ratio `U` is computed as:  
$$U = \frac{\text{upcoming\_premium} - \text{policy\_premium}}{\text{policy\_premium}}$$  
This is a core feature driving churn behaviour: larger premium increases lead to higher churn probability.  
`U` is later adjusted to `1 + U` (i.e., the *uplift factor*) for the optimisation module.

In [325]:
df_middle.columns

Index(['encoded_policy_number', 'X_age', 'X_bonus_malus_rating',
       'X_distr_channel', 'X_vehicle_type', 'X_ttm_claims', 'X_policy_count',
       'X_risk_code', 'X_vehicle_age', 'X_policy_tenure', 'X_policy_premium',
       'X_prev_renewal_perc', 'X_upcoming_premium', 'X_cur_renewal_perc',
       'year', 'is_churn'],
      dtype='object')

In [326]:
df_middle['U'] = (df_middle['X_upcoming_premium'] - df_middle['X_policy_premium']) / df_middle['X_policy_premium']
df_middle_class['U'] = (df_middle_class['X_upcoming_premium'] - df_middle_class['X_policy_premium']) / df_middle_class['X_policy_premium']

In [327]:
df_middle_class['U'].describe()

count    194373.000000
mean          0.083095
std           0.029994
min          -0.001829
25%           0.061570
50%           0.094024
75%           0.103913
max           0.418037
Name: U, dtype: float64

In [328]:
df_middle.columns

Index(['encoded_policy_number', 'X_age', 'X_bonus_malus_rating',
       'X_distr_channel', 'X_vehicle_type', 'X_ttm_claims', 'X_policy_count',
       'X_risk_code', 'X_vehicle_age', 'X_policy_tenure', 'X_policy_premium',
       'X_prev_renewal_perc', 'X_upcoming_premium', 'X_cur_renewal_perc',
       'year', 'is_churn', 'U'],
      dtype='object')

In [329]:
model_features_class = ['X_age','X_bonus_malus_rating','X_distr_channel','X_vehicle_type','X_ttm_claims','X_policy_count','X_risk_code','X_vehicle_age','X_policy_tenure','X_policy_premium','U']

model_features_reg = ['X_age','X_bonus_malus_rating','X_distr_channel','X_vehicle_type','X_ttm_claims','X_policy_count','X_risk_code','X_vehicle_age','X_policy_tenure']

In [330]:
from sklearn.model_selection import KFold, cross_val_score
from sklearn import metrics
import pandas as pd
import numpy as np
import xgboost as xgb

# Assuming 'df' is your dataframe with the columns you mentioned
# First, filter to middle of distribution (using IQR method)
def filter_middle_distribution(df, multiplier=1.5):
    """Remove outliers using IQR method"""
    df_filtered = df.copy()
    
    # Select numeric columns, exclude ID and target
    numeric_cols = df.select_dtypes(include=['number']).columns
    numeric_cols = [col for col in numeric_cols if col not in ['encoded_policy_number', 'is_churn']]
    
    for col in numeric_cols:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1
        lower = Q1 - multiplier * IQR
        upper = Q3 + multiplier * IQR
        df_filtered = df_filtered[(df_filtered[col] >= lower) & (df_filtered[col] <= upper)]
    
    print(f"Original rows: {len(df)}, Filtered rows: {len(df_filtered)}")
    return df_filtered

# Apply filtering


# Separate features and target
X = df_middle.loc[:, model_features_reg]
y = df_middle['X_upcoming_premium']

# Initialize the model
model_regressor = ModelRegressor()

# Cross-validation approach 1: Using sklearn's cross_val_score
kfold = KFold(n_splits=5, shuffle=True, random_state=123)

# Simple CV without hyperparameter tuning
default_params = {
    'learning_rate': 0.01,
    'max_depth': 5,
    'subsample': 0.8,
    'colsample_bytree': 0.8,
    'min_child_weight': 1,
    'random_state': 123,
    'n_estimators': 200,
    'objective': 'reg:absoluteerror'
}

xgb_model = xgb.XGBRegressor(**default_params, enable_categorical=True)

# Perform cross-validation
cv_scores = cross_val_score(
    xgb_model, 
    X, 
    y,  # Apply log transformation
    cv=kfold, 
    scoring='neg_mean_absolute_error',
    n_jobs=-1
)

print(f"CV MAE Scores: {-cv_scores}")
print(f"Mean CV MAE: {-cv_scores.mean():.4f} (+/- {cv_scores.std():.4f})")

CV MAE Scores: [35.9154529  35.24502254 35.43045504 35.25128434 35.34746308]
Mean CV MAE: 35.4379 (+/- 0.2483)

In [331]:
df_middle.columns

Index(['encoded_policy_number', 'X_age', 'X_bonus_malus_rating',
       'X_distr_channel', 'X_vehicle_type', 'X_ttm_claims', 'X_policy_count',
       'X_risk_code', 'X_vehicle_age', 'X_policy_tenure', 'X_policy_premium',
       'X_prev_renewal_perc', 'X_upcoming_premium', 'X_cur_renewal_perc',
       'year', 'is_churn', 'U'],
      dtype='object')

## Section 7 — XGBoost Policy Premium Regression (5-Fold OOF)

**Target variable:** `X_policy_premium` (current active premium, `Y`)  
**Features:** `model_features_reg` — 9 policy/client covariates (excluding premium-related features)

`cross_validate_with_oof_predictions` runs a **nested cross-validation**:
1. Outer KFold (5 splits) — for generating honest out-of-fold (OOF) predictions  
2. Inner 80/20 split — for Optuna hyperparameter tuning within each fold  

**Outputs stored in `df_middle`:**
- `fold_number` — which fold each row was validated in
- `oof_prediction` (`Y_hat`) — predicted policy premium  
- `oof_residual` / `oof_absolute_error` — residual diagnostics  

These OOF predictions are used as the regressor output in `df_exp_financial_loss_xgb_black_box.csv`.

In [333]:
from sklearn.model_selection import KFold
import pandas as pd
import numpy as np

def cross_validate_with_oof_predictions(X, y, n_splits=5, n_trials=30):
    """
    Perform cross-validation and generate out-of-fold predictions
    Returns: DataFrame with original data + fold number + OOF predictions
    """
    kfold = KFold(n_splits=n_splits, shuffle=True, random_state=123)
    
    # Initialize arrays to store fold numbers and OOF predictions
    fold_numbers = np.zeros(len(X))
    oof_predictions = np.zeros(len(X))
    
    fold_results = []
    best_params_per_fold = []
    
    for fold_idx, (train_idx, val_idx) in enumerate(kfold.split(X)):
        print(f"\n{'='*50}")
        print(f"Fold {fold_idx + 1}/{n_splits}")
        print(f"{'='*50}")
        
        # Assign fold number to validation indices
        fold_numbers[val_idx] = fold_idx + 1
        
        # Split data for this fold
        X_train_fold, X_val_fold = X.iloc[train_idx], X.iloc[val_idx]
        y_train_fold, y_val_fold = y.iloc[train_idx], y.iloc[val_idx]
        
        # Further split training data for Optuna tuning
        from sklearn.model_selection import train_test_split
        X_train_tune, X_val_tune, y_train_tune, y_val_tune = train_test_split(
            X_train_fold, y_train_fold, test_size=0.2, random_state=123
        )
        
        # Tune hyperparameters
        model_reg = ModelRegressor()
        
        
        best_params = model_reg.tuning(
            X_train_tune, y_train_tune, 
            X_val_tune, y_val_tune, 
            n_trials=n_trials
        )
        
        
        print(f"Best params for fold {fold_idx + 1}: {best_params}")
        best_params_per_fold.append(best_params)
        
        # Train final model on full training fold
        final_model = model_reg.train(
            X_train_fold, y_train_fold,
            X_val_fold, y_val_fold,
            best_params
        )
        
        # Generate predictions for validation fold (log scale)
        y_pred_log = final_model.predict(X_val_fold)
        
        # Store OOF predictions (in original scale)
        oof_predictions[val_idx] = y_pred_log
        
        # Calculate metrics
        y_val_transformed = y_val_fold
        mae_log = metrics.mean_absolute_error(y_val_transformed, y_pred_log)
        
        # Original scale metrics
        mae_original = metrics.mean_absolute_error(y_val_fold, oof_predictions[val_idx])
        
        fold_results.append({
            'fold': fold_idx + 1,
            'mae_log_scale': mae_log,
            'mae_original_scale': mae_original,
            'n_train': len(train_idx),
            'n_val': len(val_idx)
        })
        
        print(f"Fold {fold_idx + 1} MAE (log scale): {mae_log:.4f}")
        print(f"Fold {fold_idx + 1} MAE (original scale): {mae_original:.4f}")
    
    # Create result dataframe
    results_df = pd.DataFrame(fold_results)
    
    # Summary
    print(f"\n{'='*50}")
    print("Cross-Validation Summary")
    print(f"{'='*50}")
    print(f"Mean MAE (log scale): {results_df['mae_log_scale'].mean():.4f} (+/- {results_df['mae_log_scale'].std():.4f})")
    print(f"Mean MAE (original scale): {results_df['mae_original_scale'].mean():.4f} (+/- {results_df['mae_original_scale'].std():.4f})")
    
    # Calculate overall OOF score
    overall_oof_mae = metrics.mean_absolute_error(y, oof_predictions)
    print(f"\nOverall OOF MAE: {overall_oof_mae:.4f}")
    
    return fold_numbers, oof_predictions, results_df, best_params_per_fold


# Usage example:
# Assuming df_filtered is your filtered dataframe
X = df_middle.loc[:, model_features_reg]
y = df_middle['X_policy_premium']

# Run cross-validation and get OOF predictions
fold_numbers, oof_predictions, results_df, best_params_list = cross_validate_with_oof_predictions(
    X, y, n_splits=5, n_trials=30
)

# Add columns to the original filtered dataframe
df_middle['fold_number'] = fold_numbers.astype(int)
df_middle['oof_prediction'] = oof_predictions

# Calculate residuals
df_middle['oof_residual'] = df_middle['X_policy_premium'] - df_middle['oof_prediction']
df_middle['oof_absolute_error'] = np.abs(df_middle['oof_residual'])



# Display sample
print("\nSample of dataframe with OOF predictions:")
print(df_middle[['encoded_policy_number', 'is_churn', 'fold_number', 
                    'oof_prediction', 'oof_residual']].head(10))

# Summary statistics by fold
print("\nOOF Performance by Fold:")
fold_summary = df_middle.groupby('fold_number').agg({
    'is_churn': 'count',
    'oof_absolute_error': 'mean'
}).rename(columns={'is_churn': 'count', 'oof_absolute_error': 'mae'})
print(fold_summary)

[I 2026-03-31 09:34:10,565] A new study created in memory with name: Xgboost

==================================================
Fold 1/5
==================================================

[I 2026-03-31 09:34:15,242] Trial 0 finished with value: 35.31442955440254 and parameters: {'learning_rate': 0.008196409789504, 'max_depth': 8, 'subsample': 0.44613004381289956, 'colsample_bytree': 0.43581056141495667, 'min_child_weight': 4}. Best is trial 0 with value: 35.31442955440254.
[I 2026-03-31 09:34:21,231] Trial 1 finished with value: 40.925125837107174 and parameters: {'learning_rate': 0.001856373194872954, 'max_depth': 1, 'subsample': 0.6812599677930663, 'colsample_bytree': 0.2784029066031313, 'min_child_weight': 8}. Best is trial 0 with value: 35.31442955440254.
[I 2026-03-31 09:34:24,814] Trial 2 finished with value: 37.439017607291554 and parameters: {'learning_rate': 0.007017761474311904, 'max_depth': 6, 'subsample': 0.3687838856545533, 'colsample_bytree': 0.31045880128781733, 'min_child_weight': 3}. Best is trial 0 with value: 35.31442955440254.
[I 2026-03-31 09:34:29,011] Trial 3 finished with value: 39.61213976453853 and parameters: {'learning_rate': 0.0012917639043107875, 'max_depth': 9, 'subsample': 0.3606768809425923, 'colsample_bytree': 0.5843500103553622, 'min_child_weight': 13}. Best is trial 0 with value: 35.31442955440254.
[I 2026-03-31 09:34:33,809] Trial 4 finished with value: 40.838073064318884 and parameters: {'learning_rate': 0.002375948287046263, 'max_depth': 7, 'subsample': 0.6191023804097652, 'colsample_bytree': 0.20579900288346487, 'min_child_weight': 8}. Best is trial 0 with value: 35.31442955440254.
[I 2026-03-31 09:34:37,931] Trial 5 finished with value: 31.44400312035348 and parameters: {'learning_rate': 0.03455452070548322, 'max_depth': 3, 'subsample': 0.5348571093371338, 'colsample_bytree': 0.5842234261580624, 'min_child_weight': 4}. Best is trial 5 with value: 31.44400312035348.
[I 2026-03-31 09:34:42,458] Trial 6 finished with value: 38.31218013552082 and parameters: {'learning_rate': 0.005815955097648941, 'max_depth': 3, 'subsample': 0.6990126228306288, 'colsample_bytree': 0.2460313796584644, 'min_child_weight': 16}. Best is trial 5 with value: 31.44400312035348.
[I 2026-03-31 09:34:46,853] Trial 7 finished with value: 32.52648539343929 and parameters: {'learning_rate': 0.0074090709293993555, 'max_depth': 9, 'subsample': 0.6924008959677095, 'colsample_bytree': 0.8661696464870319, 'min_child_weight': 15}. Best is trial 5 with value: 31.44400312035348.
[I 2026-03-31 09:34:50,026] Trial 8 finished with value: 31.37377334267884 and parameters: {'learning_rate': 0.04352342275685137, 'max_depth': 8, 'subsample': 0.21913639506810917, 'colsample_bytree': 0.3160734382559138, 'min_child_weight': 9}. Best is trial 8 with value: 31.37377334267884.
[I 2026-03-31 09:34:54,397] Trial 9 finished with value: 30.549462528113853 and parameters: {'learning_rate': 0.0341727390356408, 'max_depth': 7, 'subsample': 0.6226260753655755, 'colsample_bytree': 0.7480623652270941, 'min_child_weight': 17}. Best is trial 9 with value: 30.549462528113853.
[I 2026-03-31 09:35:00,103] Trial 10 finished with value: 30.595311643238716 and parameters: {'learning_rate': 0.09592594732707356, 'max_depth': 4, 'subsample': 0.905266945432009, 'colsample_bytree': 0.9972329160802803, 'min_child_weight': 19}. Best is trial 9 with value: 30.549462528113853.
[I 2026-03-31 09:35:05,925] Trial 11 finished with value: 30.602871170767735 and parameters: {'learning_rate': 0.098146336075283, 'max_depth': 4, 'subsample': 0.9799356408702597, 'colsample_bytree': 0.9930226334604934, 'min_child_weight': 20}. Best is trial 9 with value: 30.549462528113853.
[I 2026-03-31 09:35:11,315] Trial 12 finished with value: 30.780620238254166 and parameters: {'learning_rate': 0.03511555374848262, 'max_depth': 5, 'subsample': 0.9060072677502508, 'colsample_bytree': 0.788313771863799, 'min_child_weight': 20}. Best is trial 9 with value: 30.549462528113853.
[I 2026-03-31 09:35:16,770] Trial 13 finished with value: 30.502534111734374 and parameters: {'learning_rate': 0.08672498947466874, 'max_depth': 6, 'subsample': 0.887865020907656, 'colsample_bytree': 0.7574048344011544, 'min_child_weight': 17}. Best is trial 13 with value: 30.502534111734374.
[I 2026-03-31 09:35:21,163] Trial 14 finished with value: 31.063598719827045 and parameters: {'learning_rate': 0.019154816615691097, 'max_depth': 6, 'subsample': 0.8453256648056661, 'colsample_bytree': 0.7315080037434564, 'min_child_weight': 16}. Best is trial 13 with value: 30.502534111734374.
[I 2026-03-31 09:35:25,886] Trial 15 finished with value: 30.848138619799254 and parameters: {'learning_rate': 0.01779171360476655, 'max_depth': 10, 'subsample': 0.7613059596480616, 'colsample_bytree': 0.6869772702948604, 'min_child_weight': 12}. Best is trial 13 with value: 30.502534111734374.
[I 2026-03-31 09:35:28,368] Trial 16 finished with value: 30.60709424999568 and parameters: {'learning_rate': 0.05855378196494934, 'max_depth': 7, 'subsample': 0.1840321469034647, 'colsample_bytree': 0.8756172921107135, 'min_child_weight': 18}. Best is trial 13 with value: 30.502534111734374.
[I 2026-03-31 09:35:32,826] Trial 17 finished with value: 31.97712403143605 and parameters: {'learning_rate': 0.01745881858674566, 'max_depth': 5, 'subsample': 0.5727243676041491, 'colsample_bytree': 0.44824094810290893, 'min_child_weight': 13}. Best is trial 13 with value: 30.502534111734374.
[I 2026-03-31 09:35:38,367] Trial 18 finished with value: 32.182075452633185 and parameters: {'learning_rate': 0.06262691711784397, 'max_depth': 7, 'subsample': 0.8222246057843122, 'colsample_bytree': 0.054481882209456434, 'min_child_weight': 17}. Best is trial 13 with value: 30.502534111734374.
[I 2026-03-31 09:35:43,833] Trial 19 finished with value: 30.627356905191792 and parameters: {'learning_rate': 0.031631895072236384, 'max_depth': 10, 'subsample': 0.9868694492260023, 'colsample_bytree': 0.6166496822878578, 'min_child_weight': 14}. Best is trial 13 with value: 30.502534111734374.
[I 2026-03-31 09:35:46,111] Trial 20 finished with value: 39.61168407120428 and parameters: {'learning_rate': 0.0036591034302941037, 'max_depth': 1, 'subsample': 0.0913560871508805, 'colsample_bytree': 0.8331003398421695, 'min_child_weight': 11}. Best is trial 13 with value: 30.502534111734374.
[I 2026-03-31 09:35:52,204] Trial 21 finished with value: 30.616045072717792 and parameters: {'learning_rate': 0.08759364842283068, 'max_depth': 4, 'subsample': 0.8899813821866905, 'colsample_bytree': 0.9959067734142819, 'min_child_weight': 18}. Best is trial 13 with value: 30.502534111734374.
[I 2026-03-31 09:35:57,560] Trial 22 finished with value: 30.705720915792288 and parameters: {'learning_rate': 0.06318789142899958, 'max_depth': 4, 'subsample': 0.786700375995556, 'colsample_bytree': 0.9331095261624996, 'min_child_weight': 19}. Best is trial 13 with value: 30.502534111734374.
[I 2026-03-31 09:36:02,797] Trial 23 finished with value: 30.50069885794941 and parameters: {'learning_rate': 0.08183929751834249, 'max_depth': 6, 'subsample': 0.9011046527832598, 'colsample_bytree': 0.7194125919171591, 'min_child_weight': 17}. Best is trial 23 with value: 30.50069885794941.
[I 2026-03-31 09:36:06,678] Trial 24 finished with value: 30.81903326258973 and parameters: {'learning_rate': 0.025089200141089125, 'max_depth': 6, 'subsample': 0.4762441161360066, 'colsample_bytree': 0.7118121559203316, 'min_child_weight': 15}. Best is trial 23 with value: 30.50069885794941.
[I 2026-03-31 09:36:11,101] Trial 25 finished with value: 30.521182493942405 and parameters: {'learning_rate': 0.0528167469485994, 'max_depth': 8, 'subsample': 0.7503706347713684, 'colsample_bytree': 0.7898708688063509, 'min_child_weight': 17}. Best is trial 23 with value: 30.50069885794941.
[I 2026-03-31 09:36:15,693] Trial 26 finished with value: 30.518526958610707 and parameters: {'learning_rate': 0.060291887125600775, 'max_depth': 8, 'subsample': 0.7534966445330025, 'colsample_bytree': 0.6630690083056672, 'min_child_weight': 10}. Best is trial 23 with value: 30.50069885794941.
[I 2026-03-31 09:36:20,982] Trial 27 finished with value: 32.54953201098319 and parameters: {'learning_rate': 0.01230015397033422, 'max_depth': 9, 'subsample': 0.9298588577862156, 'colsample_bytree': 0.5133705915664197, 'min_child_weight': 6}. Best is trial 23 with value: 30.50069885794941.
[I 2026-03-31 09:36:26,246] Trial 28 finished with value: 30.534803383460925 and parameters: {'learning_rate': 0.07306073298900327, 'max_depth': 5, 'subsample': 0.8305439711178997, 'colsample_bytree': 0.6400947428161964, 'min_child_weight': 1}. Best is trial 23 with value: 30.50069885794941.
[I 2026-03-31 09:36:31,212] Trial 29 finished with value: 30.616336011730915 and parameters: {'learning_rate': 0.043106651626207054, 'max_depth': 6, 'subsample': 0.995926876675358, 'colsample_bytree': 0.49537342313309873, 'min_child_weight': 10}. Best is trial 23 with value: 30.50069885794941.

Best params for fold 1: {'learning_rate': 0.08183929751834249, 'max_depth': 6, 'subsample': 0.9011046527832598, 'colsample_bytree': 0.7194125919171591, 'min_child_weight': 17}

[I 2026-03-31 09:36:38,506] A new study created in memory with name: Xgboost

Fold 1 MAE (log scale): 31.0302
Fold 1 MAE (original scale): 31.0302

==================================================
Fold 2/5
==================================================

[I 2026-03-31 09:36:44,664] Trial 0 finished with value: 36.61808699054053 and parameters: {'learning_rate': 0.01711347687076992, 'max_depth': 8, 'subsample': 0.9242840573632566, 'colsample_bytree': 0.2065401280311726, 'min_child_weight': 5}. Best is trial 0 with value: 36.61808699054053.
[I 2026-03-31 09:36:49,239] Trial 1 finished with value: 33.64922965587319 and parameters: {'learning_rate': 0.011349004214376438, 'max_depth': 4, 'subsample': 0.9054920661305593, 'colsample_bytree': 0.4618884293511265, 'min_child_weight': 19}. Best is trial 1 with value: 33.64922965587319.
[I 2026-03-31 09:36:53,201] Trial 2 finished with value: 31.06355044866335 and parameters: {'learning_rate': 0.01507140051936602, 'max_depth': 8, 'subsample': 0.4332098370907003, 'colsample_bytree': 0.870471924358069, 'min_child_weight': 4}. Best is trial 2 with value: 31.06355044866335.
[I 2026-03-31 09:36:58,289] Trial 3 finished with value: 34.4274049432636 and parameters: {'learning_rate': 0.031149200539601317, 'max_depth': 5, 'subsample': 0.7362520433865731, 'colsample_bytree': 0.20180526928157783, 'min_child_weight': 18}. Best is trial 2 with value: 31.06355044866335.
[I 2026-03-31 09:37:04,215] Trial 4 finished with value: 39.04663586206447 and parameters: {'learning_rate': 0.007723458732294881, 'max_depth': 7, 'subsample': 0.7873876130165006, 'colsample_bytree': 0.10807452494918919, 'min_child_weight': 15}. Best is trial 2 with value: 31.06355044866335.
[I 2026-03-31 09:37:07,565] Trial 5 finished with value: 35.456743998313776 and parameters: {'learning_rate': 0.004557373185446483, 'max_depth': 6, 'subsample': 0.15541902506461908, 'colsample_bytree': 0.6693875180417614, 'min_child_weight': 17}. Best is trial 2 with value: 31.06355044866335.
[I 2026-03-31 09:37:13,280] Trial 6 finished with value: 33.59165070309674 and parameters: {'learning_rate': 0.009259807111584953, 'max_depth': 10, 'subsample': 0.9918257021444492, 'colsample_bytree': 0.5251111910026254, 'min_child_weight': 1}. Best is trial 2 with value: 31.06355044866335.
[I 2026-03-31 09:37:17,998] Trial 7 finished with value: 31.59199154575439 and parameters: {'learning_rate': 0.05577494366185178, 'max_depth': 2, 'subsample': 0.42385141062211035, 'colsample_bytree': 0.5169207240066094, 'min_child_weight': 20}. Best is trial 2 with value: 31.06355044866335.
[I 2026-03-31 09:37:23,166] Trial 8 finished with value: 35.63499902297748 and parameters: {'learning_rate': 0.006671256859356074, 'max_depth': 4, 'subsample': 0.5234794980926165, 'colsample_bytree': 0.49569699867089606, 'min_child_weight': 8}. Best is trial 2 with value: 31.06355044866335.
[I 2026-03-31 09:37:26,065] Trial 9 finished with value: 39.666714096849255 and parameters: {'learning_rate': 0.005906935469431438, 'max_depth': 5, 'subsample': 0.14997116166568675, 'colsample_bytree': 0.10799313257407298, 'min_child_weight': 2}. Best is trial 2 with value: 31.06355044866335.
[I 2026-03-31 09:37:31,411] Trial 10 finished with value: 38.872772832347614 and parameters: {'learning_rate': 0.0011634035271011669, 'max_depth': 10, 'subsample': 0.3452176793614664, 'colsample_bytree': 0.9487989988821631, 'min_child_weight': 11}. Best is trial 2 with value: 31.06355044866335.
[I 2026-03-31 09:37:35,845] Trial 11 finished with value: 32.129786675157156 and parameters: {'learning_rate': 0.09143451733114392, 'max_depth': 1, 'subsample': 0.4488605398205652, 'colsample_bytree': 0.8903202627441668, 'min_child_weight': 12}. Best is trial 2 with value: 31.06355044866335.
[I 2026-03-31 09:37:39,393] Trial 12 finished with value: 32.59455036826533 and parameters: {'learning_rate': 0.06449936013957343, 'max_depth': 1, 'subsample': 0.3177836774555065, 'colsample_bytree': 0.7487623185431204, 'min_child_weight': 6}. Best is trial 2 with value: 31.06355044866335.
[I 2026-03-31 09:37:44,901] Trial 13 finished with value: 31.457279662039117 and parameters: {'learning_rate': 0.034866715767802446, 'max_depth': 3, 'subsample': 0.6437319074019363, 'colsample_bytree': 0.7035876470317086, 'min_child_weight': 13}. Best is trial 2 with value: 31.06355044866335.
[I 2026-03-31 09:37:49,316] Trial 14 finished with value: 30.6946050428298 and parameters: {'learning_rate': 0.0254200146435809, 'max_depth': 8, 'subsample': 0.6350452885784648, 'colsample_bytree': 0.7911757962512325, 'min_child_weight': 14}. Best is trial 14 with value: 30.6946050428298.
[I 2026-03-31 09:37:53,540] Trial 15 finished with value: 36.33691486484344 and parameters: {'learning_rate': 0.0029385558911979703, 'max_depth': 8, 'subsample': 0.5733748199791078, 'colsample_bytree': 0.8463575328108416, 'min_child_weight': 7}. Best is trial 14 with value: 30.6946050428298.
[I 2026-03-31 09:37:58,318] Trial 16 finished with value: 30.8163879301856 and parameters: {'learning_rate': 0.01993012007269446, 'max_depth': 8, 'subsample': 0.6906996967733563, 'colsample_bytree': 0.9909153872286371, 'min_child_weight': 9}. Best is trial 14 with value: 30.6946050428298.
[I 2026-03-31 09:38:03,149] Trial 17 finished with value: 30.710633065279357 and parameters: {'learning_rate': 0.023891009114880724, 'max_depth': 9, 'subsample': 0.7237883456339919, 'colsample_bytree': 0.9513399027127877, 'min_child_weight': 9}. Best is trial 14 with value: 30.6946050428298.
[I 2026-03-31 09:38:08,503] Trial 18 finished with value: 30.618623194164016 and parameters: {'learning_rate': 0.030620698778946253, 'max_depth': 9, 'subsample': 0.8071982704863996, 'colsample_bytree': 0.7817850722002141, 'min_child_weight': 15}. Best is trial 18 with value: 30.618623194164016.
[I 2026-03-31 09:38:13,217] Trial 19 finished with value: 30.598279549806648 and parameters: {'learning_rate': 0.04674703410788932, 'max_depth': 7, 'subsample': 0.8290230315663114, 'colsample_bytree': 0.6129471345234138, 'min_child_weight': 15}. Best is trial 19 with value: 30.598279549806648.
[I 2026-03-31 09:38:19,409] Trial 20 finished with value: 30.63498296933719 and parameters: {'learning_rate': 0.045140655392265354, 'max_depth': 6, 'subsample': 0.8295873817858231, 'colsample_bytree': 0.6317825635156873, 'min_child_weight': 15}. Best is trial 19 with value: 30.598279549806648.
[I 2026-03-31 09:38:24,009] Trial 21 finished with value: 30.63777135649241 and parameters: {'learning_rate': 0.045685726861551194, 'max_depth': 6, 'subsample': 0.8226708782877037, 'colsample_bytree': 0.6094806840266657, 'min_child_weight': 16}. Best is trial 19 with value: 30.598279549806648.
[I 2026-03-31 09:38:27,631] Trial 22 finished with value: 30.572273153793287 and parameters: {'learning_rate': 0.07707865273480803, 'max_depth': 7, 'subsample': 0.8598954323564867, 'colsample_bytree': 0.625309601206214, 'min_child_weight': 15}. Best is trial 22 with value: 30.572273153793287.
[I 2026-03-31 09:38:32,282] Trial 23 finished with value: 30.58515096265512 and parameters: {'learning_rate': 0.08934618312645548, 'max_depth': 7, 'subsample': 0.8985727651655668, 'colsample_bytree': 0.3815391153147647, 'min_child_weight': 13}. Best is trial 22 with value: 30.572273153793287.
[I 2026-03-31 09:38:36,095] Trial 24 finished with value: 30.598087892119676 and parameters: {'learning_rate': 0.09259307919139749, 'max_depth': 7, 'subsample': 0.9931336230561784, 'colsample_bytree': 0.38988617720242486, 'min_child_weight': 12}. Best is trial 22 with value: 30.572273153793287.
[I 2026-03-31 09:38:41,295] Trial 25 finished with value: 30.577345788730828 and parameters: {'learning_rate': 0.08906774808112036, 'max_depth': 7, 'subsample': 0.9934673343870492, 'colsample_bytree': 0.374500597034479, 'min_child_weight': 12}. Best is trial 22 with value: 30.572273153793287.
[I 2026-03-31 09:38:45,960] Trial 26 finished with value: 30.620376386539373 and parameters: {'learning_rate': 0.07628976153952052, 'max_depth': 7, 'subsample': 0.9167506857079301, 'colsample_bytree': 0.34085696778379276, 'min_child_weight': 10}. Best is trial 22 with value: 30.572273153793287.
[I 2026-03-31 09:38:50,107] Trial 27 finished with value: 30.641511242716206 and parameters: {'learning_rate': 0.09960124087208357, 'max_depth': 9, 'subsample': 0.9028026471626022, 'colsample_bytree': 0.3606198442524446, 'min_child_weight': 13}. Best is trial 22 with value: 30.572273153793287.
[I 2026-03-31 09:38:55,450] Trial 28 finished with value: 30.97590456743737 and parameters: {'learning_rate': 0.06592003735541829, 'max_depth': 5, 'subsample': 0.9756232733316174, 'colsample_bytree': 0.27598482533500057, 'min_child_weight': 17}. Best is trial 22 with value: 30.572273153793287.
[I 2026-03-31 09:39:00,743] Trial 29 finished with value: 40.37212502674321 and parameters: {'learning_rate': 0.0019737934536263424, 'max_depth': 6, 'subsample': 0.8888823058725754, 'colsample_bytree': 0.22779615550807844, 'min_child_weight': 11}. Best is trial 22 with value: 30.572273153793287.

Best params for fold 2: {'learning_rate': 0.07707865273480803, 'max_depth': 7, 'subsample': 0.8598954323564867, 'colsample_bytree': 0.625309601206214, 'min_child_weight': 15}

[I 2026-03-31 09:39:06,986] A new study created in memory with name: Xgboost

Fold 2 MAE (log scale): 30.3870
Fold 2 MAE (original scale): 30.3870

==================================================
Fold 3/5
==================================================

[I 2026-03-31 09:39:09,658] Trial 0 finished with value: 37.67710868384967 and parameters: {'learning_rate': 0.014022382747945615, 'max_depth': 2, 'subsample': 0.10738144424729185, 'colsample_bytree': 0.19979046019171215, 'min_child_weight': 17}. Best is trial 0 with value: 37.67710868384967.
[I 2026-03-31 09:39:15,330] Trial 1 finished with value: 38.25711785713455 and parameters: {'learning_rate': 0.003859437946712189, 'max_depth': 4, 'subsample': 0.9570973093672545, 'colsample_bytree': 0.37650423764278557, 'min_child_weight': 20}. Best is trial 0 with value: 37.67710868384967.
[I 2026-03-31 09:39:21,529] Trial 2 finished with value: 33.13499252965131 and parameters: {'learning_rate': 0.04507599851731144, 'max_depth': 6, 'subsample': 0.8612883161411926, 'colsample_bytree': 0.15369915951129154, 'min_child_weight': 18}. Best is trial 2 with value: 33.13499252965131.
[I 2026-03-31 09:39:25,375] Trial 3 finished with value: 35.489218644733775 and parameters: {'learning_rate': 0.004733967274167997, 'max_depth': 4, 'subsample': 0.4338790399988999, 'colsample_bytree': 0.8527438412989004, 'min_child_weight': 18}. Best is trial 2 with value: 33.13499252965131.
[I 2026-03-31 09:39:29,728] Trial 4 finished with value: 41.25778371199413 and parameters: {'learning_rate': 0.0011930949860466478, 'max_depth': 7, 'subsample': 0.4499940897846645, 'colsample_bytree': 0.21838549150692727, 'min_child_weight': 3}. Best is trial 2 with value: 33.13499252965131.
[I 2026-03-31 09:39:32,153] Trial 5 finished with value: 39.03278690590302 and parameters: {'learning_rate': 0.0017433259897463307, 'max_depth': 3, 'subsample': 0.08396796874918955, 'colsample_bytree': 0.8663422889128736, 'min_child_weight': 9}. Best is trial 2 with value: 33.13499252965131.
[I 2026-03-31 09:39:35,050] Trial 6 finished with value: 40.67485175805036 and parameters: {'learning_rate': 0.0027955838261080547, 'max_depth': 4, 'subsample': 0.22296947020595964, 'colsample_bytree': 0.1962098653466559, 'min_child_weight': 14}. Best is trial 2 with value: 33.13499252965131.
[I 2026-03-31 09:39:38,726] Trial 7 finished with value: 36.4148707858031 and parameters: {'learning_rate': 0.00486020148745952, 'max_depth': 6, 'subsample': 0.3912627936872139, 'colsample_bytree': 0.4779186103144049, 'min_child_weight': 9}. Best is trial 2 with value: 33.13499252965131.
[I 2026-03-31 09:39:42,436] Trial 8 finished with value: 30.6657010775119 and parameters: {'learning_rate': 0.06579924107013553, 'max_depth': 8, 'subsample': 0.8502361124910235, 'colsample_bytree': 0.4531720823115204, 'min_child_weight': 10}. Best is trial 8 with value: 30.6657010775119.
[I 2026-03-31 09:39:48,281] Trial 9 finished with value: 40.81086047062855 and parameters: {'learning_rate': 0.0014354746949662347, 'max_depth': 1, 'subsample': 0.7695425092061019, 'colsample_bytree': 0.7671313714624557, 'min_child_weight': 8}. Best is trial 8 with value: 30.6657010775119.
[I 2026-03-31 09:39:50,153] Trial 10 finished with value: 30.828756430853645 and parameters: {'learning_rate': 0.09531361435341947, 'max_depth': 10, 'subsample': 0.7098507524516815, 'colsample_bytree': 0.6398512123816602, 'min_child_weight': 3}. Best is trial 8 with value: 30.6657010775119.
[I 2026-03-31 09:39:52,083] Trial 11 finished with value: 30.83684703592557 and parameters: {'learning_rate': 0.08530300716340973, 'max_depth': 10, 'subsample': 0.6671227385181095, 'colsample_bytree': 0.6861992156973664, 'min_child_weight': 1}. Best is trial 8 with value: 30.6657010775119.
[I 2026-03-31 09:39:56,971] Trial 12 finished with value: 30.805246628792027 and parameters: {'learning_rate': 0.029118263155040593, 'max_depth': 10, 'subsample': 0.6246183652790359, 'colsample_bytree': 0.574494104923322, 'min_child_weight': 6}. Best is trial 8 with value: 30.6657010775119.
[I 2026-03-31 09:40:01,110] Trial 13 finished with value: 31.969450772354566 and parameters: {'learning_rate': 0.02130777282484556, 'max_depth': 8, 'subsample': 0.5944308083106372, 'colsample_bytree': 0.42968825272258326, 'min_child_weight': 6}. Best is trial 8 with value: 30.6657010775119.
[I 2026-03-31 09:40:06,058] Trial 14 finished with value: 30.72966796714307 and parameters: {'learning_rate': 0.0313059179003989, 'max_depth': 8, 'subsample': 0.9523782723056324, 'colsample_bytree': 0.6066893492237541, 'min_child_weight': 13}. Best is trial 8 with value: 30.6657010775119.
[I 2026-03-31 09:40:11,371] Trial 15 finished with value: 30.8413448639022 and parameters: {'learning_rate': 0.04746415999431272, 'max_depth': 8, 'subsample': 0.989578633580751, 'colsample_bytree': 0.36419283220543913, 'min_child_weight': 13}. Best is trial 8 with value: 30.6657010775119.
[I 2026-03-31 09:40:16,462] Trial 16 finished with value: 33.08949752972 and parameters: {'learning_rate': 0.010791051394535744, 'max_depth': 8, 'subsample': 0.8503511296798472, 'colsample_bytree': 0.5236896373037168, 'min_child_weight': 13}. Best is trial 8 with value: 30.6657010775119.
[I 2026-03-31 09:40:20,985] Trial 17 finished with value: 30.653701261448703 and parameters: {'learning_rate': 0.049414935097784746, 'max_depth': 9, 'subsample': 0.8549701305081788, 'colsample_bytree': 0.7087650608117986, 'min_child_weight': 11}. Best is trial 17 with value: 30.653701261448703.
[I 2026-03-31 09:40:25,824] Trial 18 finished with value: 30.707163677235105 and parameters: {'learning_rate': 0.05888796923532298, 'max_depth': 9, 'subsample': 0.808315721952012, 'colsample_bytree': 0.9996552397015736, 'min_child_weight': 11}. Best is trial 17 with value: 30.653701261448703.
[I 2026-03-31 09:40:30,257] Trial 19 finished with value: 36.27739344455025 and parameters: {'learning_rate': 0.018663856208380302, 'max_depth': 7, 'subsample': 0.5302953036963853, 'colsample_bytree': 0.05694236668812719, 'min_child_weight': 15}. Best is trial 17 with value: 30.653701261448703.
[I 2026-03-31 09:40:35,396] Trial 20 finished with value: 36.79251173394638 and parameters: {'learning_rate': 0.008170346675166038, 'max_depth': 9, 'subsample': 0.7349482806283232, 'colsample_bytree': 0.32062966154934414, 'min_child_weight': 11}. Best is trial 17 with value: 30.653701261448703.
[I 2026-03-31 09:40:39,031] Trial 21 finished with value: 30.694178101144868 and parameters: {'learning_rate': 0.061121721319606234, 'max_depth': 9, 'subsample': 0.8371921576862174, 'colsample_bytree': 0.9995546033963818, 'min_child_weight': 11}. Best is trial 17 with value: 30.653701261448703.
[I 2026-03-31 09:40:41,998] Trial 22 finished with value: 30.734236334836513 and parameters: {'learning_rate': 0.06639880309552758, 'max_depth': 9, 'subsample': 0.8807130435529928, 'colsample_bytree': 0.9851489405197155, 'min_child_weight': 11}. Best is trial 17 with value: 30.653701261448703.
[I 2026-03-31 09:40:46,463] Trial 23 finished with value: 30.67681982755861 and parameters: {'learning_rate': 0.036317666721960115, 'max_depth': 7, 'subsample': 0.8927428302323756, 'colsample_bytree': 0.7453159369802485, 'min_child_weight': 8}. Best is trial 17 with value: 30.653701261448703.
[I 2026-03-31 09:40:51,038] Trial 24 finished with value: 30.69497528210567 and parameters: {'learning_rate': 0.035199214307878715, 'max_depth': 7, 'subsample': 0.9134724180922862, 'colsample_bytree': 0.7249546916740379, 'min_child_weight': 7}. Best is trial 17 with value: 30.653701261448703.
[I 2026-03-31 09:40:55,270] Trial 25 finished with value: 31.165095596761326 and parameters: {'learning_rate': 0.024054722205138785, 'max_depth': 5, 'subsample': 0.7783554386125351, 'colsample_bytree': 0.8014821305195454, 'min_child_weight': 5}. Best is trial 17 with value: 30.653701261448703.
[I 2026-03-31 09:41:00,055] Trial 26 finished with value: 30.639921807064145 and parameters: {'learning_rate': 0.09918840689830649, 'max_depth': 6, 'subsample': 0.9986094061179576, 'colsample_bytree': 0.5515667836351683, 'min_child_weight': 9}. Best is trial 26 with value: 30.639921807064145.
[I 2026-03-31 09:41:05,142] Trial 27 finished with value: 30.692075832627864 and parameters: {'learning_rate': 0.08791504304195187, 'max_depth': 5, 'subsample': 0.9826353534252549, 'colsample_bytree': 0.5203537105168321, 'min_child_weight': 9}. Best is trial 26 with value: 30.639921807064145.
[I 2026-03-31 09:41:08,346] Trial 28 finished with value: 30.770460709446752 and parameters: {'learning_rate': 0.047268263539934935, 'max_depth': 6, 'subsample': 0.30149476035758316, 'colsample_bytree': 0.45240495594015473, 'min_child_weight': 15}. Best is trial 26 with value: 30.639921807064145.
[I 2026-03-31 09:41:11,299] Trial 29 finished with value: 30.662414748677637 and parameters: {'learning_rate': 0.07614465244274667, 'max_depth': 8, 'subsample': 0.6856616819108692, 'colsample_bytree': 0.60725570575868, 'min_child_weight': 10}. Best is trial 26 with value: 30.639921807064145.

Best params for fold 3: {'learning_rate': 0.09918840689830649, 'max_depth': 6, 'subsample': 0.9986094061179576, 'colsample_bytree': 0.5515667836351683, 'min_child_weight': 9}

[I 2026-03-31 09:41:17,525] A new study created in memory with name: Xgboost

Fold 3 MAE (log scale): 30.6161
Fold 3 MAE (original scale): 30.6161

==================================================
Fold 4/5
==================================================

[I 2026-03-31 09:41:21,351] Trial 0 finished with value: 39.69099165222364 and parameters: {'learning_rate': 0.0012437964771440991, 'max_depth': 8, 'subsample': 0.44400467118704573, 'colsample_bytree': 0.7087231890517068, 'min_child_weight': 6}. Best is trial 0 with value: 39.69099165222364.
[I 2026-03-31 09:41:24,912] Trial 1 finished with value: 34.03717221817301 and parameters: {'learning_rate': 0.0050481088630640845, 'max_depth': 9, 'subsample': 0.21088186688756683, 'colsample_bytree': 0.9613915930527493, 'min_child_weight': 16}. Best is trial 1 with value: 34.03717221817301.
[I 2026-03-31 09:41:28,816] Trial 2 finished with value: 34.23735207527695 and parameters: {'learning_rate': 0.017144899946266067, 'max_depth': 10, 'subsample': 0.44693655879035943, 'colsample_bytree': 0.32562010148727605, 'min_child_weight': 4}. Best is trial 1 with value: 34.03717221817301.
[I 2026-03-31 09:41:34,406] Trial 3 finished with value: 41.09146132858581 and parameters: {'learning_rate': 0.002707034212640486, 'max_depth': 4, 'subsample': 0.9914679557383052, 'colsample_bytree': 0.11573080456425189, 'min_child_weight': 6}. Best is trial 1 with value: 34.03717221817301.
[I 2026-03-31 09:41:38,832] Trial 4 finished with value: 41.0365071348504 and parameters: {'learning_rate': 0.0014546671551509955, 'max_depth': 6, 'subsample': 0.7222556231568398, 'colsample_bytree': 0.24663674945883252, 'min_child_weight': 10}. Best is trial 1 with value: 34.03717221817301.
[I 2026-03-31 09:41:42,330] Trial 5 finished with value: 35.753257406798724 and parameters: {'learning_rate': 0.006188095392733118, 'max_depth': 7, 'subsample': 0.21622773588222421, 'colsample_bytree': 0.5406412273169356, 'min_child_weight': 3}. Best is trial 1 with value: 34.03717221817301.
[I 2026-03-31 09:41:46,637] Trial 6 finished with value: 32.302958261998214 and parameters: {'learning_rate': 0.014941269391705958, 'max_depth': 8, 'subsample': 0.7665165313923039, 'colsample_bytree': 0.5127016566249044, 'min_child_weight': 14}. Best is trial 6 with value: 32.302958261998214.
[I 2026-03-31 09:41:50,826] Trial 7 finished with value: 40.73022949830123 and parameters: {'learning_rate': 0.0036273165665876, 'max_depth': 6, 'subsample': 0.5288554863467864, 'colsample_bytree': 0.09111301984744538, 'min_child_weight': 1}. Best is trial 6 with value: 32.302958261998214.
[I 2026-03-31 09:41:54,660] Trial 8 finished with value: 40.64297571892742 and parameters: {'learning_rate': 0.001314239914712251, 'max_depth': 10, 'subsample': 0.3800390229911215, 'colsample_bytree': 0.35204476509450744, 'min_child_weight': 7}. Best is trial 6 with value: 32.302958261998214.
[I 2026-03-31 09:41:59,375] Trial 9 finished with value: 34.469972028554245 and parameters: {'learning_rate': 0.03704420674290633, 'max_depth': 1, 'subsample': 0.5172257262867717, 'colsample_bytree': 0.3310104020514725, 'min_child_weight': 4}. Best is trial 6 with value: 32.302958261998214.
[I 2026-03-31 09:42:04,572] Trial 10 finished with value: 30.988219157518593 and parameters: {'learning_rate': 0.08772335181049197, 'max_depth': 4, 'subsample': 0.8492889721396446, 'colsample_bytree': 0.6638652715234724, 'min_child_weight': 18}. Best is trial 10 with value: 30.988219157518593.
[I 2026-03-31 09:42:09,887] Trial 11 finished with value: 31.135042914056218 and parameters: {'learning_rate': 0.09628264377175931, 'max_depth': 3, 'subsample': 0.8429735409608049, 'colsample_bytree': 0.6977946238478311, 'min_child_weight': 20}. Best is trial 10 with value: 30.988219157518593.
[I 2026-03-31 09:42:15,525] Trial 12 finished with value: 31.18754242418099 and parameters: {'learning_rate': 0.09042719843817185, 'max_depth': 3, 'subsample': 0.9997803956359896, 'colsample_bytree': 0.7983384261213137, 'min_child_weight': 18}. Best is trial 10 with value: 30.988219157518593.
[I 2026-03-31 09:42:21,169] Trial 13 finished with value: 31.133155563218292 and parameters: {'learning_rate': 0.09754339266749072, 'max_depth': 3, 'subsample': 0.7949414436478582, 'colsample_bytree': 0.6638685226320502, 'min_child_weight': 20}. Best is trial 10 with value: 30.988219157518593.
[I 2026-03-31 09:42:26,638] Trial 14 finished with value: 33.61044314494496 and parameters: {'learning_rate': 0.04776201445408253, 'max_depth': 1, 'subsample': 0.6799552886854348, 'colsample_bytree': 0.550455762908505, 'min_child_weight': 13}. Best is trial 10 with value: 30.988219157518593.
[I 2026-03-31 09:42:31,329] Trial 15 finished with value: 31.292382998405625 and parameters: {'learning_rate': 0.03881776884602336, 'max_depth': 4, 'subsample': 0.8140051640534017, 'colsample_bytree': 0.870630902951089, 'min_child_weight': 19}. Best is trial 10 with value: 30.988219157518593.
[I 2026-03-31 09:42:35,688] Trial 16 finished with value: 31.071156887694528 and parameters: {'learning_rate': 0.05878506529390624, 'max_depth': 4, 'subsample': 0.6240548503836549, 'colsample_bytree': 0.656067730212357, 'min_child_weight': 15}. Best is trial 10 with value: 30.988219157518593.
[I 2026-03-31 09:42:39,667] Trial 17 finished with value: 31.69048848036748 and parameters: {'learning_rate': 0.023139250326894886, 'max_depth': 5, 'subsample': 0.6156144078731702, 'colsample_bytree': 0.46282620169970196, 'min_child_weight': 16}. Best is trial 10 with value: 30.988219157518593.
[I 2026-03-31 09:42:44,360] Trial 18 finished with value: 31.89189909030181 and parameters: {'learning_rate': 0.056314717889382276, 'max_depth': 2, 'subsample': 0.6226843969875231, 'colsample_bytree': 0.6133676744011726, 'min_child_weight': 13}. Best is trial 10 with value: 30.988219157518593.
[I 2026-03-31 09:42:46,778] Trial 19 finished with value: 33.46701573505404 and parameters: {'learning_rate': 0.009843004375080159, 'max_depth': 4, 'subsample': 0.07241352496736875, 'colsample_bytree': 0.80249180935072, 'min_child_weight': 10}. Best is trial 10 with value: 30.988219157518593.
[I 2026-03-31 09:42:51,204] Trial 20 finished with value: 31.34341325395924 and parameters: {'learning_rate': 0.025527137312313604, 'max_depth': 5, 'subsample': 0.9013209841837959, 'colsample_bytree': 0.9552526831793019, 'min_child_weight': 16}. Best is trial 10 with value: 30.988219157518593.
[I 2026-03-31 09:42:56,398] Trial 21 finished with value: 31.265090201437996 and parameters: {'learning_rate': 0.06703318033476684, 'max_depth': 3, 'subsample': 0.8816278999564187, 'colsample_bytree': 0.669535563577998, 'min_child_weight': 18}. Best is trial 10 with value: 30.988219157518593.
[I 2026-03-31 09:43:01,538] Trial 22 finished with value: 31.690485276790707 and parameters: {'learning_rate': 0.07229719545354067, 'max_depth': 2, 'subsample': 0.6840430487493294, 'colsample_bytree': 0.7866043322464098, 'min_child_weight': 20}. Best is trial 10 with value: 30.988219157518593.
[I 2026-03-31 09:43:06,513] Trial 23 finished with value: 30.877086918685475 and parameters: {'learning_rate': 0.09941117810726005, 'max_depth': 5, 'subsample': 0.781827600058718, 'colsample_bytree': 0.6397640277685516, 'min_child_weight': 17}. Best is trial 23 with value: 30.877086918685475.
[I 2026-03-31 09:43:11,126] Trial 24 finished with value: 31.203941008966478 and parameters: {'learning_rate': 0.03073845942397751, 'max_depth': 5, 'subsample': 0.9280981672828659, 'colsample_bytree': 0.6048843885418187, 'min_child_weight': 15}. Best is trial 23 with value: 30.877086918685475.
[I 2026-03-31 09:43:15,017] Trial 25 finished with value: 30.972130334562145 and parameters: {'learning_rate': 0.05490872651590187, 'max_depth': 6, 'subsample': 0.5843483686839319, 'colsample_bytree': 0.43509181020340937, 'min_child_weight': 12}. Best is trial 23 with value: 30.877086918685475.
[I 2026-03-31 09:43:19,795] Trial 26 finished with value: 31.072135530141164 and parameters: {'learning_rate': 0.043209310109075735, 'max_depth': 7, 'subsample': 0.7309040921153594, 'colsample_bytree': 0.4340381019016138, 'min_child_weight': 12}. Best is trial 23 with value: 30.877086918685475.
[I 2026-03-31 09:43:23,696] Trial 27 finished with value: 31.149918324046048 and parameters: {'learning_rate': 0.07085004443171633, 'max_depth': 6, 'subsample': 0.54740344054475, 'colsample_bytree': 0.22595031565141382, 'min_child_weight': 11}. Best is trial 23 with value: 30.877086918685475.
[I 2026-03-31 09:43:28,189] Trial 28 finished with value: 32.86159377356075 and parameters: {'learning_rate': 0.017063081099091746, 'max_depth': 7, 'subsample': 0.8498328648744712, 'colsample_bytree': 0.4043162817454273, 'min_child_weight': 18}. Best is trial 23 with value: 30.877086918685475.
[I 2026-03-31 09:43:31,892] Trial 29 finished with value: 32.13166812258058 and parameters: {'learning_rate': 0.011185748340499587, 'max_depth': 8, 'subsample': 0.3749210568395004, 'colsample_bytree': 0.763360318489998, 'min_child_weight': 9}. Best is trial 23 with value: 30.877086918685475.

Best params for fold 4: {'learning_rate': 0.09941117810726005, 'max_depth': 5, 'subsample': 0.781827600058718, 'colsample_bytree': 0.6397640277685516, 'min_child_weight': 17}

[I 2026-03-31 09:43:37,933] A new study created in memory with name: Xgboost

Fold 4 MAE (log scale): 30.3800
Fold 4 MAE (original scale): 30.3800

==================================================
Fold 5/5
==================================================

[I 2026-03-31 09:43:41,808] Trial 0 finished with value: 34.701354916027405 and parameters: {'learning_rate': 0.005102080518360063, 'max_depth': 7, 'subsample': 0.54095115355461, 'colsample_bytree': 0.8180156810298919, 'min_child_weight': 3}. Best is trial 0 with value: 34.701354916027405.
[I 2026-03-31 09:43:45,242] Trial 1 finished with value: 40.80846708497035 and parameters: {'learning_rate': 0.0013323819977196544, 'max_depth': 8, 'subsample': 0.1817351567996618, 'colsample_bytree': 0.4244761444915307, 'min_child_weight': 10}. Best is trial 0 with value: 34.701354916027405.
[I 2026-03-31 09:43:49,010] Trial 2 finished with value: 36.50238662494583 and parameters: {'learning_rate': 0.016719803142563595, 'max_depth': 1, 'subsample': 0.37622658181559104, 'colsample_bytree': 0.45596330148623526, 'min_child_weight': 5}. Best is trial 0 with value: 34.701354916027405.
[I 2026-03-31 09:43:51,995] Trial 3 finished with value: 34.196836291721354 and parameters: {'learning_rate': 0.01781509975981025, 'max_depth': 2, 'subsample': 0.2911435461620799, 'colsample_bytree': 0.526114978658383, 'min_child_weight': 18}. Best is trial 3 with value: 34.196836291721354.
[I 2026-03-31 09:43:55,805] Trial 4 finished with value: 40.35262599991757 and parameters: {'learning_rate': 0.0010013368015707599, 'max_depth': 6, 'subsample': 0.6185703842513526, 'colsample_bytree': 0.7074288646288152, 'min_child_weight': 16}. Best is trial 3 with value: 34.196836291721354.
[I 2026-03-31 09:44:00,340] Trial 5 finished with value: 31.358512136862018 and parameters: {'learning_rate': 0.018327599906845213, 'max_depth': 7, 'subsample': 0.6432354865134401, 'colsample_bytree': 0.9159328535211375, 'min_child_weight': 11}. Best is trial 5 with value: 31.358512136862018.
[I 2026-03-31 09:44:04,035] Trial 6 finished with value: 31.935091028307752 and parameters: {'learning_rate': 0.015934942009900446, 'max_depth': 7, 'subsample': 0.4920924623412635, 'colsample_bytree': 0.5611791178778783, 'min_child_weight': 19}. Best is trial 5 with value: 31.358512136862018.
[I 2026-03-31 09:44:07,638] Trial 7 finished with value: 39.18676125990771 and parameters: {'learning_rate': 0.0012642108964366792, 'max_depth': 8, 'subsample': 0.30257078694500245, 'colsample_bytree': 0.9896214136228734, 'min_child_weight': 13}. Best is trial 5 with value: 31.358512136862018.
[I 2026-03-31 09:44:11,248] Trial 8 finished with value: 39.383513549094246 and parameters: {'learning_rate': 0.0017503998528590127, 'max_depth': 3, 'subsample': 0.5795466106646553, 'colsample_bytree': 0.95719337994873, 'min_child_weight': 7}. Best is trial 5 with value: 31.358512136862018.
[I 2026-03-31 09:44:15,545] Trial 9 finished with value: 32.22564640485738 and parameters: {'learning_rate': 0.017724045227709977, 'max_depth': 6, 'subsample': 0.7718426328001771, 'colsample_bytree': 0.4968233032788211, 'min_child_weight': 5}. Best is trial 5 with value: 31.358512136862018.
[I 2026-03-31 09:44:21,576] Trial 10 finished with value: 32.12028702123513 and parameters: {'learning_rate': 0.08590117975543052, 'max_depth': 10, 'subsample': 0.9582622301236656, 'colsample_bytree': 0.13276619917169985, 'min_child_weight': 11}. Best is trial 5 with value: 31.358512136862018.
[I 2026-03-31 09:44:26,647] Trial 11 finished with value: 33.01882702017418 and parameters: {'learning_rate': 0.058468812150304736, 'max_depth': 4, 'subsample': 0.7627059502831603, 'colsample_bytree': 0.15683956515233505, 'min_child_weight': 20}. Best is trial 5 with value: 31.358512136862018.
[I 2026-03-31 09:44:30,693] Trial 12 finished with value: 34.662213629657515 and parameters: {'learning_rate': 0.006692860154829225, 'max_depth': 10, 'subsample': 0.42743051937312326, 'colsample_bytree': 0.6358050086410607, 'min_child_weight': 15}. Best is trial 5 with value: 31.358512136862018.
[I 2026-03-31 09:44:34,896] Trial 13 finished with value: 32.09149564950395 and parameters: {'learning_rate': 0.03987868597553116, 'max_depth': 5, 'subsample': 0.7072215061281182, 'colsample_bytree': 0.3081452048496876, 'min_child_weight': 9}. Best is trial 5 with value: 31.358512136862018.
[I 2026-03-31 09:44:39,866] Trial 14 finished with value: 30.960777568691046 and parameters: {'learning_rate': 0.034246048121965446, 'max_depth': 8, 'subsample': 0.9186392086849763, 'colsample_bytree': 0.7991524248780792, 'min_child_weight': 20}. Best is trial 14 with value: 30.960777568691046.
[I 2026-03-31 09:44:45,199] Trial 15 finished with value: 30.987536262305156 and parameters: {'learning_rate': 0.03349946693367109, 'max_depth': 9, 'subsample': 0.9390852452514571, 'colsample_bytree': 0.8139897049574676, 'min_child_weight': 1}. Best is trial 14 with value: 30.960777568691046.
[I 2026-03-31 09:44:50,273] Trial 16 finished with value: 30.972517748265894 and parameters: {'learning_rate': 0.036278518283084336, 'max_depth': 9, 'subsample': 0.9223178828470131, 'colsample_bytree': 0.7623671568924505, 'min_child_weight': 1}. Best is trial 14 with value: 30.960777568691046.
[I 2026-03-31 09:44:55,382] Trial 17 finished with value: 30.975116530993688 and parameters: {'learning_rate': 0.034893749114489524, 'max_depth': 9, 'subsample': 0.856674594522241, 'colsample_bytree': 0.7486200352250977, 'min_child_weight': 1}. Best is trial 14 with value: 30.960777568691046.
[I 2026-03-31 09:44:59,560] Trial 18 finished with value: 30.9581753188924 and parameters: {'learning_rate': 0.08246885250072053, 'max_depth': 9, 'subsample': 0.9968166604178665, 'colsample_bytree': 0.854527721433489, 'min_child_weight': 15}. Best is trial 18 with value: 30.9581753188924.
[I 2026-03-31 09:45:04,494] Trial 19 finished with value: 30.95385656859802 and parameters: {'learning_rate': 0.08829317050200625, 'max_depth': 8, 'subsample': 0.9985366554876887, 'colsample_bytree': 0.8845579479192476, 'min_child_weight': 17}. Best is trial 19 with value: 30.95385656859802.
[I 2026-03-31 09:45:13,279] Trial 20 finished with value: 30.926999448129536 and parameters: {'learning_rate': 0.09053729139915631, 'max_depth': 5, 'subsample': 0.8227393113736939, 'colsample_bytree': 0.907286873915653, 'min_child_weight': 15}. Best is trial 20 with value: 30.926999448129536.
[I 2026-03-31 09:45:19,341] Trial 21 finished with value: 30.958688461978827 and parameters: {'learning_rate': 0.0769670337693288, 'max_depth': 5, 'subsample': 0.8444277002453119, 'colsample_bytree': 0.9102987075272491, 'min_child_weight': 16}. Best is trial 20 with value: 30.926999448129536.
[I 2026-03-31 09:45:25,183] Trial 22 finished with value: 31.026842511206524 and parameters: {'learning_rate': 0.09794412343155931, 'max_depth': 4, 'subsample': 0.9931976307461077, 'colsample_bytree': 0.8763725976781402, 'min_child_weight': 14}. Best is trial 20 with value: 30.926999448129536.
[I 2026-03-31 09:45:30,019] Trial 23 finished with value: 31.126361039447946 and parameters: {'learning_rate': 0.061211118988109166, 'max_depth': 4, 'subsample': 0.8234072175291721, 'colsample_bytree': 0.7098921498383199, 'min_child_weight': 17}. Best is trial 20 with value: 30.926999448129536.
[I 2026-03-31 09:45:35,128] Trial 24 finished with value: 30.89993040471215 and parameters: {'learning_rate': 0.060545790668976, 'max_depth': 6, 'subsample': 0.9915182263914608, 'colsample_bytree': 0.6239478826695686, 'min_child_weight': 14}. Best is trial 24 with value: 30.89993040471215.
[I 2026-03-31 09:45:37,793] Trial 25 finished with value: 31.13106283158222 and parameters: {'learning_rate': 0.05089798767365688, 'max_depth': 6, 'subsample': 0.06803497830397953, 'colsample_bytree': 0.6268332838135788, 'min_child_weight': 13}. Best is trial 24 with value: 30.89993040471215.
[I 2026-03-31 09:45:42,430] Trial 26 finished with value: 39.119396991878986 and parameters: {'learning_rate': 0.0033046872822721403, 'max_depth': 5, 'subsample': 0.864508106889909, 'colsample_bytree': 0.35496473824947383, 'min_child_weight': 13}. Best is trial 24 with value: 30.89993040471215.
[I 2026-03-31 09:45:47,142] Trial 27 finished with value: 32.27725436461342 and parameters: {'learning_rate': 0.026422388546104444, 'max_depth': 3, 'subsample': 0.7340185641694976, 'colsample_bytree': 0.6081216961882157, 'min_child_weight': 18}. Best is trial 24 with value: 30.89993040471215.
[I 2026-03-31 09:45:51,879] Trial 28 finished with value: 32.22267874347414 and parameters: {'learning_rate': 0.010098580130896508, 'max_depth': 7, 'subsample': 0.8680424754101748, 'colsample_bytree': 0.9994175643818508, 'min_child_weight': 12}. Best is trial 24 with value: 30.89993040471215.
[I 2026-03-31 09:45:56,635] Trial 29 finished with value: 31.598816995039076 and parameters: {'learning_rate': 0.050522278532705134, 'max_depth': 7, 'subsample': 0.6810433665361288, 'colsample_bytree': 0.24870603296132254, 'min_child_weight': 17}. Best is trial 24 with value: 30.89993040471215.

Best params for fold 5: {'learning_rate': 0.060545790668976, 'max_depth': 6, 'subsample': 0.9915182263914608, 'colsample_bytree': 0.6239478826695686, 'min_child_weight': 14}
Fold 5 MAE (log scale): 30.4861
Fold 5 MAE (original scale): 30.4861

==================================================
Cross-Validation Summary
==================================================
Mean MAE (log scale): 30.5799 (+/- 0.2693)
Mean MAE (original scale): 30.5799 (+/- 0.2693)

Overall OOF MAE: 30.5799

Sample of dataframe with OOF predictions:
     encoded_policy_number  is_churn  fold_number  oof_prediction  \
7                        5     False            5      193.966034
16                      85     False            4      162.414307
24                      93     False            1      168.083298
32                     119     False            5      175.712479
118                    395     False            5      210.380798
139                    470     False            3      210.291870
146                    478     False            2      178.864288
154                    527     False            4      215.742020
269                   1041     False            2      174.588638
294                   1196     False            1      179.336731

     oof_residual
7      -18.193534
16      18.454293
24      -2.442998
32      -4.377779
118    -40.282698
139    -53.178170
146    -27.295388
154     27.944480
269     98.377662
294    -22.243031

OOF Performance by Fold:
             count        mae
fold_number
1            38875  31.030247
2            38875  30.386986
3            38875  30.616137
4            38874  30.379952
5            38874  30.486116

## Section 8 — XGBoost Churn Classification (5-Fold OOF)

**Target variable:** `is_churn` (binary, 0 = retained, 1 = churned)  
**Features:** `model_features_class` — 11 features including `X_policy_premium` and `U`

`cross_validate_churn_with_oof_predictions` follows the same nested structure as the regression CV:
1. Outer 5-fold for OOF predictions  
2. Inner 80/20 split for Optuna tuning (maximise ROC-AUC)

**Outputs stored in `df_middle_class`:**
- `fold_number` — fold assignment  
- `oof_prediction` — OOF churn probability (output of `predict_proba[:, 1]`)
- `prob_acceptance = 1 − oof_prediction` — probability the client accepts (does not churn)
- `Z = 1 − is_churn` — binary acceptance indicator

The `prob_acceptance` column is the key output consumed by the pricing optimiser.

In [334]:
from sklearn.model_selection import KFold
import pandas as pd
import numpy as np

def cross_validate_churn_with_oof_predictions(X, y, n_splits=5, n_trials=30):
    """
    Perform cross-validation and generate out-of-fold predictions
    Returns: DataFrame with original data + fold number + OOF predictions
    """
    kfold = KFold(n_splits=n_splits, shuffle=True, random_state=123)
    
    # Initialize arrays to store fold numbers and OOF predictions
    fold_numbers = np.zeros(len(X))
    oof_predictions = np.zeros(len(X))
    
    fold_results = []
    best_params_per_fold = []
    
    for fold_idx, (train_idx, val_idx) in enumerate(kfold.split(X)):
        print(f"\n{'='*50}")
        print(f"Fold {fold_idx + 1}/{n_splits}")
        print(f"{'='*50}")
        
        # Assign fold number to validation indices
        fold_numbers[val_idx] = fold_idx + 1
        
        # Split data for this fold
        X_train_fold, X_val_fold = X.iloc[train_idx], X.iloc[val_idx]
        y_train_fold, y_val_fold = y.iloc[train_idx], y.iloc[val_idx]
        
        # Further split training data for Optuna tuning
        from sklearn.model_selection import train_test_split
        X_train_tune, X_val_tune, y_train_tune, y_val_tune = train_test_split(
            X_train_fold, y_train_fold, test_size=0.2, random_state=123
        )
        
        # Tune hyperparameters
        model_class = ModelClassifier()
        
        
        best_params = model_class.tuning(
            X_train_tune, y_train_tune, 
            X_val_tune, y_val_tune, 
            n_trials=n_trials
        )
        
        
        print(f"Best params for fold {fold_idx + 1}: {best_params}")
        best_params_per_fold.append(best_params)
        
        # Train final model on full training fold
        final_model = model_class.train(
            X_train_fold, y_train_fold,
            X_val_fold, y_val_fold,best_params)
        # Generate predictions for validation fold (log scale)
        y_pred = final_model.predict(X_val_fold)
        y_pred_proba = final_model.predict_proba(X_val_fold)[:,1]
        
        roc_auc = metrics.roc_auc_score(y_true=y_val_fold, y_score=y_pred_proba)
        # Store OOF predictions (in original scale)
        oof_predictions[val_idx] = y_pred_proba
        
        
        # Calculate metrics
        
        
        

        
        fold_results.append({
            'fold': fold_idx + 1,
            'roc_auc': roc_auc,
            'n_train': len(train_idx),
            'n_val': len(val_idx)
        })
        
        print(f"Fold {fold_idx + 1} AUC (log scale): {roc_auc:.4f}")
    
    # Create result dataframe
    results_df = pd.DataFrame(fold_results)
    
    # Summary
    print(f"\n{'='*50}")
    print("Cross-Validation Summary")


    
    return fold_numbers, oof_predictions, results_df, best_params_per_fold


# Usage example:
# Assuming df_filtered is your filtered dataframe
X = df_middle_class.loc[:,model_features_class]
y = df_middle_class['is_churn'].astype(int)

# Run cross-validation and get OOF predictions
fold_numbers, oof_predictions, results_df, best_params_list = cross_validate_churn_with_oof_predictions(
    X, y, n_splits=5, n_trials=30
)


df_middle_class['fold_number'] = fold_numbers.astype(int)
df_middle_class['oof_prediction'] = oof_predictions
# Add columns to the original filtered dataframe

[I 2026-03-31 09:46:04,443] A new study created in memory with name: Xgboost

==================================================
Fold 1/5
==================================================

[I 2026-03-31 09:46:05,900] Trial 0 finished with value: 0.6261414839152228 and parameters: {'learning_rate': 0.0012058415550974786, 'max_depth': 2, 'subsample': 0.37949398075941904, 'colsample_bytree': 0.9529677506880325, 'min_child_weight': 9}. Best is trial 0 with value: 0.6261414839152228.
[I 2026-03-31 09:46:07,057] Trial 1 finished with value: 0.6614852440284598 and parameters: {'learning_rate': 0.06263871684362121, 'max_depth': 5, 'subsample': 0.312680290738838, 'colsample_bytree': 0.3612661973111024, 'min_child_weight': 19}. Best is trial 1 with value: 0.6614852440284598.
[I 2026-03-31 09:46:08,156] Trial 2 finished with value: 0.6101319572112052 and parameters: {'learning_rate': 0.001109535213460959, 'max_depth': 1, 'subsample': 0.9944986867204899, 'colsample_bytree': 0.6734885896456438, 'min_child_weight': 20}. Best is trial 1 with value: 0.6614852440284598.
[I 2026-03-31 09:46:09,305] Trial 3 finished with value: 0.6233499766443613 and parameters: {'learning_rate': 0.005352997018978114, 'max_depth': 1, 'subsample': 0.20578021716286982, 'colsample_bytree': 0.8297164941544916, 'min_child_weight': 17}. Best is trial 1 with value: 0.6614852440284598.
[I 2026-03-31 09:46:10,511] Trial 4 finished with value: 0.6139716720902488 and parameters: {'learning_rate': 0.003998479069150611, 'max_depth': 1, 'subsample': 0.64204766207434, 'colsample_bytree': 0.8757210793274923, 'min_child_weight': 6}. Best is trial 1 with value: 0.6614852440284598.
[I 2026-03-31 09:46:11,973] Trial 5 finished with value: 0.6482493920072563 and parameters: {'learning_rate': 0.006144512081072734, 'max_depth': 3, 'subsample': 0.9126790761797261, 'colsample_bytree': 0.411093465908849, 'min_child_weight': 16}. Best is trial 1 with value: 0.6614852440284598.
[I 2026-03-31 09:46:13,085] Trial 6 finished with value: 0.6365538209381236 and parameters: {'learning_rate': 0.003718271356376721, 'max_depth': 1, 'subsample': 0.346710049700496, 'colsample_bytree': 0.1030248638916405, 'min_child_weight': 11}. Best is trial 1 with value: 0.6614852440284598.
[I 2026-03-31 09:46:14,047] Trial 7 finished with value: 0.6609021689165583 and parameters: {'learning_rate': 0.036803554833519644, 'max_depth': 8, 'subsample': 0.6687712328164427, 'colsample_bytree': 0.8808925448038889, 'min_child_weight': 5}. Best is trial 1 with value: 0.6614852440284598.
[I 2026-03-31 09:46:16,077] Trial 8 finished with value: 0.6575737239351087 and parameters: {'learning_rate': 0.003628094589497883, 'max_depth': 8, 'subsample': 0.053018978226305594, 'colsample_bytree': 0.5791710689013169, 'min_child_weight': 2}. Best is trial 1 with value: 0.6614852440284598.
[I 2026-03-31 09:46:18,538] Trial 9 finished with value: 0.659603183592839 and parameters: {'learning_rate': 0.013350609617017178, 'max_depth': 10, 'subsample': 0.5036290761809817, 'colsample_bytree': 0.355401652204308, 'min_child_weight': 5}. Best is trial 1 with value: 0.6614852440284598.
[I 2026-03-31 09:46:19,463] Trial 10 finished with value: 0.650444881647639 and parameters: {'learning_rate': 0.06879354283142342, 'max_depth': 5, 'subsample': 0.08798301502794836, 'colsample_bytree': 0.10704807852472348, 'min_child_weight': 13}. Best is trial 1 with value: 0.6614852440284598.
[I 2026-03-31 09:46:20,195] Trial 11 finished with value: 0.6624343367988266 and parameters: {'learning_rate': 0.07256103350105396, 'max_depth': 7, 'subsample': 0.7233680783149191, 'colsample_bytree': 0.3872670992175495, 'min_child_weight': 1}. Best is trial 11 with value: 0.6624343367988266.
[I 2026-03-31 09:46:20,870] Trial 12 finished with value: 0.6634616858358906 and parameters: {'learning_rate': 0.0842110852947997, 'max_depth': 5, 'subsample': 0.7709104652421385, 'colsample_bytree': 0.3176370878759842, 'min_child_weight': 2}. Best is trial 12 with value: 0.6634616858358906.
[I 2026-03-31 09:46:22,344] Trial 13 finished with value: 0.6591242346296149 and parameters: {'learning_rate': 0.02650689429998601, 'max_depth': 7, 'subsample': 0.8026909944081225, 'colsample_bytree': 0.2168574142329518, 'min_child_weight': 1}. Best is trial 12 with value: 0.6634616858358906.
[I 2026-03-31 09:46:22,865] Trial 14 finished with value: 0.6640122480478847 and parameters: {'learning_rate': 0.0997389082130575, 'max_depth': 6, 'subsample': 0.7618738430462966, 'colsample_bytree': 0.49675860026681473, 'min_child_weight': 3}. Best is trial 14 with value: 0.6640122480478847.
[I 2026-03-31 09:46:23,522] Trial 15 finished with value: 0.6641416176646849 and parameters: {'learning_rate': 0.09963725465177194, 'max_depth': 4, 'subsample': 0.8368017319814274, 'colsample_bytree': 0.6111426931192703, 'min_child_weight': 8}. Best is trial 15 with value: 0.6641416176646849.
[I 2026-03-31 09:46:24,594] Trial 16 finished with value: 0.6584248486091576 and parameters: {'learning_rate': 0.03000914444538623, 'max_depth': 3, 'subsample': 0.5573231291464615, 'colsample_bytree': 0.6829762583349538, 'min_child_weight': 8}. Best is trial 15 with value: 0.6641416176646849.
[I 2026-03-31 09:46:25,777] Trial 17 finished with value: 0.6585616190025837 and parameters: {'learning_rate': 0.016870972564882295, 'max_depth': 4, 'subsample': 0.8711089270024499, 'colsample_bytree': 0.5254102071706552, 'min_child_weight': 12}. Best is trial 15 with value: 0.6641416176646849.
[I 2026-03-31 09:46:26,963] Trial 18 finished with value: 0.6639020800365146 and parameters: {'learning_rate': 0.04010415975558472, 'max_depth': 6, 'subsample': 0.8847856580129682, 'colsample_bytree': 0.6652294272637297, 'min_child_weight': 7}. Best is trial 15 with value: 0.6641416176646849.
[I 2026-03-31 09:46:27,699] Trial 19 finished with value: 0.6652565737107905 and parameters: {'learning_rate': 0.09786135247299849, 'max_depth': 4, 'subsample': 0.5301003479615278, 'colsample_bytree': 0.565844903397824, 'min_child_weight': 3}. Best is trial 19 with value: 0.6652565737107905.
[I 2026-03-31 09:46:28,818] Trial 20 finished with value: 0.6620799128484545 and parameters: {'learning_rate': 0.047676590630588, 'max_depth': 3, 'subsample': 0.5274204924057242, 'colsample_bytree': 0.7168978074033285, 'min_child_weight': 4}. Best is trial 19 with value: 0.6652565737107905.
[I 2026-03-31 09:46:29,499] Trial 21 finished with value: 0.6641267756976358 and parameters: {'learning_rate': 0.09996071368082467, 'max_depth': 4, 'subsample': 0.5991068468877897, 'colsample_bytree': 0.5289089501012787, 'min_child_weight': 3}. Best is trial 19 with value: 0.6652565737107905.
[I 2026-03-31 09:46:30,701] Trial 22 finished with value: 0.6599897617706675 and parameters: {'learning_rate': 0.0210273702343048, 'max_depth': 4, 'subsample': 0.4308837237365468, 'colsample_bytree': 0.5818963000442073, 'min_child_weight': 9}. Best is trial 19 with value: 0.6652565737107905.
[I 2026-03-31 09:46:31,535] Trial 23 finished with value: 0.6637092203441963 and parameters: {'learning_rate': 0.052997681501114634, 'max_depth': 4, 'subsample': 0.5910073337922086, 'colsample_bytree': 0.7718243880816554, 'min_child_weight': 4}. Best is trial 19 with value: 0.6652565737107905.
[I 2026-03-31 09:46:32,485] Trial 24 finished with value: 0.6631702316333967 and parameters: {'learning_rate': 0.09483053353039926, 'max_depth': 4, 'subsample': 0.4678833469836118, 'colsample_bytree': 0.46699856326582684, 'min_child_weight': 7}. Best is trial 19 with value: 0.6652565737107905.
[I 2026-03-31 09:46:33,452] Trial 25 finished with value: 0.6409570152891154 and parameters: {'learning_rate': 0.009078824493279009, 'max_depth': 2, 'subsample': 0.6925042559733997, 'colsample_bytree': 0.6013082915039375, 'min_child_weight': 3}. Best is trial 19 with value: 0.6652565737107905.
[I 2026-03-31 09:46:34,506] Trial 26 finished with value: 0.6597287795713185 and parameters: {'learning_rate': 0.05271830413548553, 'max_depth': 3, 'subsample': 0.6144403494814358, 'colsample_bytree': 0.25565847409663806, 'min_child_weight': 10}. Best is trial 19 with value: 0.6652565737107905.
[I 2026-03-31 09:46:35,442] Trial 27 finished with value: 0.6376713584155302 and parameters: {'learning_rate': 0.0018862103872456788, 'max_depth': 2, 'subsample': 0.2214901579659142, 'colsample_bytree': 0.4563898651712675, 'min_child_weight': 14}. Best is trial 19 with value: 0.6652565737107905.
[I 2026-03-31 09:46:35,822] Trial 28 finished with value: 0.6596297809231702 and parameters: {'learning_rate': 0.0996727096755204, 'max_depth': 6, 'subsample': 0.2752304653412143, 'colsample_bytree': 0.5467221914768582, 'min_child_weight': 6}. Best is trial 19 with value: 0.6652565737107905.
[I 2026-03-31 09:46:36,813] Trial 29 finished with value: 0.6626614774946828 and parameters: {'learning_rate': 0.03370580427640452, 'max_depth': 5, 'subsample': 0.4075508865986345, 'colsample_bytree': 0.7490904583802016, 'min_child_weight': 9}. Best is trial 19 with value: 0.6652565737107905.

Best params for fold 1: {'learning_rate': 0.09786135247299849, 'max_depth': 4, 'subsample': 0.5301003479615278, 'colsample_bytree': 0.565844903397824, 'min_child_weight': 3}

[I 2026-03-31 09:46:37,816] A new study created in memory with name: Xgboost

Fold 1 AUC (log scale): 0.6704

==================================================
Fold 2/5
==================================================

[I 2026-03-31 09:46:38,933] Trial 0 finished with value: 0.653823890335859 and parameters: {'learning_rate': 0.014365893842485416, 'max_depth': 6, 'subsample': 0.40974969321370813, 'colsample_bytree': 0.09985773613270052, 'min_child_weight': 1}. Best is trial 0 with value: 0.653823890335859.
[I 2026-03-31 09:46:39,734] Trial 1 finished with value: 0.6711903170781663 and parameters: {'learning_rate': 0.08430870680750366, 'max_depth': 3, 'subsample': 0.963275252312179, 'colsample_bytree': 0.714277963486305, 'min_child_weight': 4}. Best is trial 1 with value: 0.6711903170781663.
[I 2026-03-31 09:46:41,019] Trial 2 finished with value: 0.6534841875516053 and parameters: {'learning_rate': 0.002475985479340072, 'max_depth': 5, 'subsample': 0.8443779229518359, 'colsample_bytree': 0.9474962722569205, 'min_child_weight': 10}. Best is trial 1 with value: 0.6711903170781663.
[I 2026-03-31 09:46:42,217] Trial 3 finished with value: 0.6525632269866255 and parameters: {'learning_rate': 0.018748099036651016, 'max_depth': 9, 'subsample': 0.22226652728313928, 'colsample_bytree': 0.05061727560489534, 'min_child_weight': 15}. Best is trial 1 with value: 0.6711903170781663.
[I 2026-03-31 09:46:43,822] Trial 4 finished with value: 0.6684610267107373 and parameters: {'learning_rate': 0.013096967504129512, 'max_depth': 6, 'subsample': 0.9850753515374415, 'colsample_bytree': 0.5170483174482905, 'min_child_weight': 19}. Best is trial 1 with value: 0.6711903170781663.
[I 2026-03-31 09:46:44,907] Trial 5 finished with value: 0.6405597395597675 and parameters: {'learning_rate': 0.009559323253267122, 'max_depth': 1, 'subsample': 0.37769547625012156, 'colsample_bytree': 0.5938517993788617, 'min_child_weight': 13}. Best is trial 1 with value: 0.6711903170781663.
[I 2026-03-31 09:46:46,527] Trial 6 finished with value: 0.6678255874368275 and parameters: {'learning_rate': 0.010334111884621938, 'max_depth': 8, 'subsample': 0.736089443488411, 'colsample_bytree': 0.43907188445482037, 'min_child_weight': 9}. Best is trial 1 with value: 0.6711903170781663.
[I 2026-03-31 09:46:47,252] Trial 7 finished with value: 0.6655116901813948 and parameters: {'learning_rate': 0.07600091308415856, 'max_depth': 8, 'subsample': 0.9500457523938088, 'colsample_bytree': 0.7727184821484839, 'min_child_weight': 9}. Best is trial 1 with value: 0.6711903170781663.
[I 2026-03-31 09:46:48,551] Trial 8 finished with value: 0.6503872049555077 and parameters: {'learning_rate': 0.004073057531820656, 'max_depth': 5, 'subsample': 0.6512105825375727, 'colsample_bytree': 0.05144809407272871, 'min_child_weight': 14}. Best is trial 1 with value: 0.6711903170781663.
[I 2026-03-31 09:46:48,982] Trial 9 finished with value: 0.6646309613222825 and parameters: {'learning_rate': 0.09013089219920856, 'max_depth': 4, 'subsample': 0.0889383118520276, 'colsample_bytree': 0.5409935792211432, 'min_child_weight': 4}. Best is trial 1 with value: 0.6711903170781663.
[I 2026-03-31 09:46:50,005] Trial 10 finished with value: 0.6540802438898135 and parameters: {'learning_rate': 0.03843495687786131, 'max_depth': 1, 'subsample': 0.4964592558679038, 'colsample_bytree': 0.30665678967699217, 'min_child_weight': 5}. Best is trial 1 with value: 0.6711903170781663.
[I 2026-03-31 09:46:51,613] Trial 11 finished with value: 0.6679000295731498 and parameters: {'learning_rate': 0.03250475169388616, 'max_depth': 3, 'subsample': 0.9989785484453882, 'colsample_bytree': 0.7373057083305282, 'min_child_weight': 20}. Best is trial 1 with value: 0.6711903170781663.
[I 2026-03-31 09:46:53,313] Trial 12 finished with value: 0.6617643599130604 and parameters: {'learning_rate': 0.00107216402021935, 'max_depth': 6, 'subsample': 0.7530172643505386, 'colsample_bytree': 0.7362490474346179, 'min_child_weight': 20}. Best is trial 1 with value: 0.6711903170781663.
[I 2026-03-31 09:46:54,674] Trial 13 finished with value: 0.655543703395528 and parameters: {'learning_rate': 0.005470477336710405, 'max_depth': 3, 'subsample': 0.8818110717661002, 'colsample_bytree': 0.3601073855017656, 'min_child_weight': 17}. Best is trial 1 with value: 0.6711903170781663.
[I 2026-03-31 09:46:56,411] Trial 14 finished with value: 0.6684388837949364 and parameters: {'learning_rate': 0.04021250297417224, 'max_depth': 3, 'subsample': 0.6956481364054792, 'colsample_bytree': 0.996250980990923, 'min_child_weight': 7}. Best is trial 1 with value: 0.6711903170781663.
[I 2026-03-31 09:46:58,235] Trial 15 finished with value: 0.6710632461987879 and parameters: {'learning_rate': 0.02560701949364882, 'max_depth': 7, 'subsample': 0.8477648997860459, 'colsample_bytree': 0.6341237316082057, 'min_child_weight': 1}. Best is trial 1 with value: 0.6711903170781663.
[I 2026-03-31 09:46:59,179] Trial 16 finished with value: 0.661890362340583 and parameters: {'learning_rate': 0.05868881588985056, 'max_depth': 10, 'subsample': 0.5626673005433526, 'colsample_bytree': 0.8400161422889969, 'min_child_weight': 1}. Best is trial 1 with value: 0.6711903170781663.
[I 2026-03-31 09:47:00,655] Trial 17 finished with value: 0.6715307687772726 and parameters: {'learning_rate': 0.022642577224718713, 'max_depth': 7, 'subsample': 0.8372807670215595, 'colsample_bytree': 0.6399568941153368, 'min_child_weight': 4}. Best is trial 17 with value: 0.6715307687772726.
[I 2026-03-31 09:47:01,564] Trial 18 finished with value: 0.6667763577287054 and parameters: {'learning_rate': 0.05249084960848065, 'max_depth': 2, 'subsample': 0.8194104370376263, 'colsample_bytree': 0.8772782018272524, 'min_child_weight': 4}. Best is trial 17 with value: 0.6715307687772726.
[I 2026-03-31 09:47:03,005] Trial 19 finished with value: 0.6680875928015342 and parameters: {'learning_rate': 0.022621716211241427, 'max_depth': 4, 'subsample': 0.5764444790666184, 'colsample_bytree': 0.6562170169158159, 'min_child_weight': 6}. Best is trial 17 with value: 0.6715307687772726.
[I 2026-03-31 09:47:03,976] Trial 20 finished with value: 0.6664325359127639 and parameters: {'learning_rate': 0.09121123910832739, 'max_depth': 7, 'subsample': 0.8917723972507231, 'colsample_bytree': 0.25231877192246394, 'min_child_weight': 3}. Best is trial 17 with value: 0.6715307687772726.
[I 2026-03-31 09:47:05,636] Trial 21 finished with value: 0.6716943817086795 and parameters: {'learning_rate': 0.02279791449880572, 'max_depth': 7, 'subsample': 0.8053349702441492, 'colsample_bytree': 0.6363262387928487, 'min_child_weight': 2}. Best is trial 21 with value: 0.6716943817086795.
[I 2026-03-31 09:47:07,957] Trial 22 finished with value: 0.6681962553538426 and parameters: {'learning_rate': 0.006207414026093802, 'max_depth': 8, 'subsample': 0.7787829079727627, 'colsample_bytree': 0.6648743813259783, 'min_child_weight': 7}. Best is trial 21 with value: 0.6716943817086795.
[I 2026-03-31 09:47:09,713] Trial 23 finished with value: 0.6705498550819805 and parameters: {'learning_rate': 0.018146175060544046, 'max_depth': 7, 'subsample': 0.9257467157114337, 'colsample_bytree': 0.47159812671031154, 'min_child_weight': 3}. Best is trial 21 with value: 0.6716943817086795.
[I 2026-03-31 09:47:10,655] Trial 24 finished with value: 0.6665361258151389 and parameters: {'learning_rate': 0.05593387477133152, 'max_depth': 9, 'subsample': 0.6631797724003318, 'colsample_bytree': 0.8198972840550907, 'min_child_weight': 3}. Best is trial 21 with value: 0.6716943817086795.
[I 2026-03-31 09:47:11,963] Trial 25 finished with value: 0.6690229375244445 and parameters: {'learning_rate': 0.029183790135271042, 'max_depth': 4, 'subsample': 0.7958011594845096, 'colsample_bytree': 0.6964977970581543, 'min_child_weight': 7}. Best is trial 21 with value: 0.6716943817086795.
[I 2026-03-31 09:47:13,727] Trial 26 finished with value: 0.6653888831239088 and parameters: {'learning_rate': 0.009139919905014485, 'max_depth': 5, 'subsample': 0.919104988177716, 'colsample_bytree': 0.5799660700691676, 'min_child_weight': 12}. Best is trial 21 with value: 0.6716943817086795.
[I 2026-03-31 09:47:15,022] Trial 27 finished with value: 0.6713240582924964 and parameters: {'learning_rate': 0.03939379023545107, 'max_depth': 7, 'subsample': 0.6112554199919499, 'colsample_bytree': 0.4280278836044061, 'min_child_weight': 5}. Best is trial 21 with value: 0.6716943817086795.
[I 2026-03-31 09:47:16,126] Trial 28 finished with value: 0.6693442819092847 and parameters: {'learning_rate': 0.04372501896644693, 'max_depth': 7, 'subsample': 0.6171443984797915, 'colsample_bytree': 0.3955663555787421, 'min_child_weight': 2}. Best is trial 21 with value: 0.6716943817086795.
[I 2026-03-31 09:47:18,160] Trial 29 finished with value: 0.6628003238427648 and parameters: {'learning_rate': 0.014901489943819618, 'max_depth': 6, 'subsample': 0.4468174885210705, 'colsample_bytree': 0.2497049461593076, 'min_child_weight': 6}. Best is trial 21 with value: 0.6716943817086795.

Best params for fold 2: {'learning_rate': 0.02279791449880572, 'max_depth': 7, 'subsample': 0.8053349702441492, 'colsample_bytree': 0.6363262387928487, 'min_child_weight': 2}

[I 2026-03-31 09:47:20,227] A new study created in memory with name: Xgboost

Fold 2 AUC (log scale): 0.6731

==================================================
Fold 3/5
==================================================

[I 2026-03-31 09:47:21,763] Trial 0 finished with value: 0.6638184075621778 and parameters: {'learning_rate': 0.029052547237550172, 'max_depth': 4, 'subsample': 0.5538957383346859, 'colsample_bytree': 0.5829947949835289, 'min_child_weight': 17}. Best is trial 0 with value: 0.6638184075621778.
[I 2026-03-31 09:47:22,496] Trial 1 finished with value: 0.6606927306175971 and parameters: {'learning_rate': 0.07884146720089524, 'max_depth': 2, 'subsample': 0.09727689469266892, 'colsample_bytree': 0.6040722138327468, 'min_child_weight': 1}. Best is trial 0 with value: 0.6638184075621778.
[I 2026-03-31 09:47:23,893] Trial 2 finished with value: 0.6462282214006988 and parameters: {'learning_rate': 0.018384441104779294, 'max_depth': 2, 'subsample': 0.9898817411475203, 'colsample_bytree': 0.13366047266835906, 'min_child_weight': 13}. Best is trial 0 with value: 0.6638184075621778.
[I 2026-03-31 09:47:24,871] Trial 3 finished with value: 0.6644365598207843 and parameters: {'learning_rate': 0.08096199872730425, 'max_depth': 5, 'subsample': 0.3217183231731379, 'colsample_bytree': 0.4168149817766727, 'min_child_weight': 20}. Best is trial 3 with value: 0.6644365598207843.
[I 2026-03-31 09:47:26,252] Trial 4 finished with value: 0.6595871859313365 and parameters: {'learning_rate': 0.02291696348454202, 'max_depth': 3, 'subsample': 0.1143701428686566, 'colsample_bytree': 0.48884989701074744, 'min_child_weight': 4}. Best is trial 3 with value: 0.6644365598207843.
[I 2026-03-31 09:47:27,573] Trial 5 finished with value: 0.6601276677401235 and parameters: {'learning_rate': 0.020264869711946187, 'max_depth': 4, 'subsample': 0.9220297827980279, 'colsample_bytree': 0.944848069350186, 'min_child_weight': 16}. Best is trial 3 with value: 0.6644365598207843.
[I 2026-03-31 09:47:29,282] Trial 6 finished with value: 0.6630151890550089 and parameters: {'learning_rate': 0.019153000348025147, 'max_depth': 6, 'subsample': 0.9589479124811268, 'colsample_bytree': 0.4814356369305992, 'min_child_weight': 2}. Best is trial 3 with value: 0.6644365598207843.
[I 2026-03-31 09:47:31,036] Trial 7 finished with value: 0.6302841128702538 and parameters: {'learning_rate': 0.005015570521817464, 'max_depth': 1, 'subsample': 0.6963054827935187, 'colsample_bytree': 0.4165344772400868, 'min_child_weight': 17}. Best is trial 3 with value: 0.6644365598207843.
[I 2026-03-31 09:47:33,756] Trial 8 finished with value: 0.6599602382932878 and parameters: {'learning_rate': 0.0018769135533234004, 'max_depth': 10, 'subsample': 0.3188348145208037, 'colsample_bytree': 0.5061718739251552, 'min_child_weight': 3}. Best is trial 3 with value: 0.6644365598207843.
[I 2026-03-31 09:47:35,087] Trial 9 finished with value: 0.6407259841450419 and parameters: {'learning_rate': 0.0012181728751030575, 'max_depth': 3, 'subsample': 0.39803439208050634, 'colsample_bytree': 0.7314805448563061, 'min_child_weight': 12}. Best is trial 3 with value: 0.6644365598207843.
[I 2026-03-31 09:47:36,126] Trial 10 finished with value: 0.6565171500536124 and parameters: {'learning_rate': 0.09904213349488235, 'max_depth': 7, 'subsample': 0.30710843439651647, 'colsample_bytree': 0.10393990240942991, 'min_child_weight': 20}. Best is trial 3 with value: 0.6644365598207843.
[I 2026-03-31 09:47:37,734] Trial 11 finished with value: 0.664947817413315 and parameters: {'learning_rate': 0.04808567625445943, 'max_depth': 5, 'subsample': 0.564874563148631, 'colsample_bytree': 0.2858941793552594, 'min_child_weight': 20}. Best is trial 11 with value: 0.664947817413315.
[I 2026-03-31 09:47:38,953] Trial 12 finished with value: 0.6620568699873375 and parameters: {'learning_rate': 0.051450047963929525, 'max_depth': 8, 'subsample': 0.6289482145093347, 'colsample_bytree': 0.3203378142915634, 'min_child_weight': 7}. Best is trial 11 with value: 0.664947817413315.
[I 2026-03-31 09:47:40,733] Trial 13 finished with value: 0.6533615432161626 and parameters: {'learning_rate': 0.007015141013755959, 'max_depth': 6, 'subsample': 0.7533417767429971, 'colsample_bytree': 0.2708086311720143, 'min_child_weight': 20}. Best is trial 11 with value: 0.664947817413315.
[I 2026-03-31 09:47:42,258] Trial 14 finished with value: 0.6649418498436962 and parameters: {'learning_rate': 0.04698408316091768, 'max_depth': 5, 'subsample': 0.4286949700896151, 'colsample_bytree': 0.27314630291431463, 'min_child_weight': 9}. Best is trial 11 with value: 0.664947817413315.
[I 2026-03-31 09:47:44,593] Trial 15 finished with value: 0.6603335463351714 and parameters: {'learning_rate': 0.04583099765387758, 'max_depth': 8, 'subsample': 0.4704736435542117, 'colsample_bytree': 0.23693830795906629, 'min_child_weight': 8}. Best is trial 11 with value: 0.664947817413315.
[I 2026-03-31 09:47:46,103] Trial 16 finished with value: 0.6540946951946972 and parameters: {'learning_rate': 0.03523935095958253, 'max_depth': 5, 'subsample': 0.7851071951388244, 'colsample_bytree': 0.17224665822566226, 'min_child_weight': 10}. Best is trial 11 with value: 0.664947817413315.
[I 2026-03-31 09:47:49,110] Trial 17 finished with value: 0.6587035816534677 and parameters: {'learning_rate': 0.009752891367462699, 'max_depth': 10, 'subsample': 0.5441243323397503, 'colsample_bytree': 0.3352301434140486, 'min_child_weight': 6}. Best is trial 11 with value: 0.664947817413315.
[I 2026-03-31 09:47:51,192] Trial 18 finished with value: 0.66329355291085 and parameters: {'learning_rate': 0.012025493932717221, 'max_depth': 7, 'subsample': 0.20452931187847184, 'colsample_bytree': 0.7374916415609974, 'min_child_weight': 14}. Best is trial 11 with value: 0.664947817413315.
[I 2026-03-31 09:47:52,561] Trial 19 finished with value: 0.6463228383164278 and parameters: {'learning_rate': 0.003450805586875656, 'max_depth': 4, 'subsample': 0.6136644884581748, 'colsample_bytree': 0.0801813146896535, 'min_child_weight': 10}. Best is trial 11 with value: 0.664947817413315.
[I 2026-03-31 09:47:54,482] Trial 20 finished with value: 0.6611972536007122 and parameters: {'learning_rate': 0.05372479577204341, 'max_depth': 7, 'subsample': 0.4170726937924971, 'colsample_bytree': 0.21396964921027495, 'min_child_weight': 15}. Best is trial 11 with value: 0.664947817413315.
[I 2026-03-31 09:47:55,603] Trial 21 finished with value: 0.6646415793312599 and parameters: {'learning_rate': 0.06914269763757556, 'max_depth': 5, 'subsample': 0.29746959756733826, 'colsample_bytree': 0.3951967254772588, 'min_child_weight': 19}. Best is trial 11 with value: 0.664947817413315.
[I 2026-03-31 09:47:57,038] Trial 22 finished with value: 0.663744904695254 and parameters: {'learning_rate': 0.06026475591248575, 'max_depth': 5, 'subsample': 0.22658851860996604, 'colsample_bytree': 0.3735022347806668, 'min_child_weight': 18}. Best is trial 11 with value: 0.664947817413315.
[I 2026-03-31 09:47:59,350] Trial 23 finished with value: 0.6636650609660105 and parameters: {'learning_rate': 0.03413811761335485, 'max_depth': 6, 'subsample': 0.4657097666495717, 'colsample_bytree': 0.28736676392938726, 'min_child_weight': 18}. Best is trial 11 with value: 0.664947817413315.
[I 2026-03-31 09:48:01,139] Trial 24 finished with value: 0.6578527862245052 and parameters: {'learning_rate': 0.013328325541391395, 'max_depth': 4, 'subsample': 0.21589604488232028, 'colsample_bytree': 0.39735529628734073, 'min_child_weight': 12}. Best is trial 11 with value: 0.664947817413315.
[I 2026-03-31 09:48:02,946] Trial 25 finished with value: 0.658829959130381 and parameters: {'learning_rate': 0.03878064504044002, 'max_depth': 3, 'subsample': 0.3840951946985587, 'colsample_bytree': 0.19831548360369572, 'min_child_weight': 9}. Best is trial 11 with value: 0.664947817413315.
[I 2026-03-31 09:48:04,082] Trial 26 finished with value: 0.6660285918277391 and parameters: {'learning_rate': 0.0695184698181166, 'max_depth': 5, 'subsample': 0.4957695562943118, 'colsample_bytree': 0.592708547414085, 'min_child_weight': 5}. Best is trial 26 with value: 0.6660285918277391.
[I 2026-03-31 09:48:06,786] Trial 27 finished with value: 0.663180394086434 and parameters: {'learning_rate': 0.098731754872055, 'max_depth': 6, 'subsample': 0.6038613602518412, 'colsample_bytree': 0.6616253833953705, 'min_child_weight': 5}. Best is trial 26 with value: 0.6660285918277391.
[I 2026-03-31 09:48:14,061] Trial 28 finished with value: 0.6640401280858279 and parameters: {'learning_rate': 0.02374443625841761, 'max_depth': 8, 'subsample': 0.8521764627498316, 'colsample_bytree': 0.9189555789058246, 'min_child_weight': 7}. Best is trial 26 with value: 0.6660285918277391.
[I 2026-03-31 09:48:18,238] Trial 29 finished with value: 0.6636523639005749 and parameters: {'learning_rate': 0.028713287421196478, 'max_depth': 4, 'subsample': 0.5005810940611822, 'colsample_bytree': 0.8237962389453253, 'min_child_weight': 5}. Best is trial 26 with value: 0.6660285918277391.

Best params for fold 3: {'learning_rate': 0.0695184698181166, 'max_depth': 5, 'subsample': 0.4957695562943118, 'colsample_bytree': 0.592708547414085, 'min_child_weight': 5}

[I 2026-03-31 09:48:20,780] A new study created in memory with name: Xgboost

Fold 3 AUC (log scale): 0.6667

==================================================
Fold 4/5
==================================================

[I 2026-03-31 09:48:24,392] Trial 0 finished with value: 0.6653625721112977 and parameters: {'learning_rate': 0.0025046182750578516, 'max_depth': 6, 'subsample': 0.6348526978195881, 'colsample_bytree': 0.733087601318229, 'min_child_weight': 8}. Best is trial 0 with value: 0.6653625721112977.
[I 2026-03-31 09:48:28,102] Trial 1 finished with value: 0.6714655268622733 and parameters: {'learning_rate': 0.011799306241729205, 'max_depth': 9, 'subsample': 0.508956528798332, 'colsample_bytree': 0.85540836155545, 'min_child_weight': 8}. Best is trial 1 with value: 0.6714655268622733.
[I 2026-03-31 09:48:29,814] Trial 2 finished with value: 0.6578300014289274 and parameters: {'learning_rate': 0.027290735086774112, 'max_depth': 7, 'subsample': 0.32740991239008876, 'colsample_bytree': 0.12517739443712747, 'min_child_weight': 7}. Best is trial 1 with value: 0.6714655268622733.
[I 2026-03-31 09:48:31,021] Trial 3 finished with value: 0.6724821931638855 and parameters: {'learning_rate': 0.07676646045776783, 'max_depth': 4, 'subsample': 0.38178966700974576, 'colsample_bytree': 0.7834593647193022, 'min_child_weight': 14}. Best is trial 3 with value: 0.6724821931638855.
[I 2026-03-31 09:48:32,297] Trial 4 finished with value: 0.6153181189055459 and parameters: {'learning_rate': 0.002613930190197231, 'max_depth': 1, 'subsample': 0.7669087238907595, 'colsample_bytree': 0.8558574162703526, 'min_child_weight': 13}. Best is trial 3 with value: 0.6724821931638855.
[I 2026-03-31 09:48:34,349] Trial 5 finished with value: 0.6520130251439097 and parameters: {'learning_rate': 0.002570913015190252, 'max_depth': 3, 'subsample': 0.9696098901109732, 'colsample_bytree': 0.17787643772402162, 'min_child_weight': 3}. Best is trial 3 with value: 0.6724821931638855.
[I 2026-03-31 09:48:36,171] Trial 6 finished with value: 0.6707547814314516 and parameters: {'learning_rate': 0.02437011799278251, 'max_depth': 4, 'subsample': 0.34141666171962787, 'colsample_bytree': 0.9880486777111692, 'min_child_weight': 5}. Best is trial 3 with value: 0.6724821931638855.
[I 2026-03-31 09:48:37,359] Trial 7 finished with value: 0.6502098958968919 and parameters: {'learning_rate': 0.00789964089503478, 'max_depth': 1, 'subsample': 0.05015803767335487, 'colsample_bytree': 0.09304628398418308, 'min_child_weight': 16}. Best is trial 3 with value: 0.6724821931638855.
[I 2026-03-31 09:48:39,513] Trial 8 finished with value: 0.6644961309439996 and parameters: {'learning_rate': 0.007151260727833505, 'max_depth': 5, 'subsample': 0.7256217238888447, 'colsample_bytree': 0.7401799183989144, 'min_child_weight': 13}. Best is trial 3 with value: 0.6724821931638855.
[I 2026-03-31 09:48:40,785] Trial 9 finished with value: 0.6676934397623598 and parameters: {'learning_rate': 0.07643385578549952, 'max_depth': 9, 'subsample': 0.6810208278619507, 'colsample_bytree': 0.6877772250729056, 'min_child_weight': 10}. Best is trial 3 with value: 0.6724821931638855.
[I 2026-03-31 09:48:41,824] Trial 10 finished with value: 0.6701613123604319 and parameters: {'learning_rate': 0.08437773830131955, 'max_depth': 3, 'subsample': 0.11252855793432404, 'colsample_bytree': 0.4514366871424006, 'min_child_weight': 20}. Best is trial 3 with value: 0.6724821931638855.
[I 2026-03-31 09:48:44,645] Trial 11 finished with value: 0.6703737427784402 and parameters: {'learning_rate': 0.025406899057457983, 'max_depth': 10, 'subsample': 0.42392372491039776, 'colsample_bytree': 0.5003807284711252, 'min_child_weight': 16}. Best is trial 3 with value: 0.6724821931638855.
[I 2026-03-31 09:48:45,717] Trial 12 finished with value: 0.669294104578722 and parameters: {'learning_rate': 0.045248329154944, 'max_depth': 8, 'subsample': 0.48917206433953364, 'colsample_bytree': 0.9580345943179054, 'min_child_weight': 1}. Best is trial 3 with value: 0.6724821931638855.
[I 2026-03-31 09:48:47,298] Trial 13 finished with value: 0.6707879335934608 and parameters: {'learning_rate': 0.01260089335935211, 'max_depth': 6, 'subsample': 0.21679326864881804, 'colsample_bytree': 0.6096924673300027, 'min_child_weight': 11}. Best is trial 3 with value: 0.6724821931638855.
[I 2026-03-31 09:48:49,867] Trial 14 finished with value: 0.6687693335461079 and parameters: {'learning_rate': 0.0047694672294304255, 'max_depth': 10, 'subsample': 0.5784200372311654, 'colsample_bytree': 0.8478225598390525, 'min_child_weight': 17}. Best is trial 3 with value: 0.6724821931638855.
[I 2026-03-31 09:48:51,682] Trial 15 finished with value: 0.6621392609837071 and parameters: {'learning_rate': 0.0011472331403355762, 'max_depth': 8, 'subsample': 0.25284262660949397, 'colsample_bytree': 0.34789981194831965, 'min_child_weight': 9}. Best is trial 3 with value: 0.6724821931638855.
[I 2026-03-31 09:48:53,036] Trial 16 finished with value: 0.6672804797024492 and parameters: {'learning_rate': 0.015341160452573622, 'max_depth': 4, 'subsample': 0.47141184045186785, 'colsample_bytree': 0.8532822445102685, 'min_child_weight': 13}. Best is trial 3 with value: 0.6724821931638855.
[I 2026-03-31 09:48:54,238] Trial 17 finished with value: 0.6720558043141096 and parameters: {'learning_rate': 0.040063957203289174, 'max_depth': 7, 'subsample': 0.8090356618740292, 'colsample_bytree': 0.6001201153616869, 'min_child_weight': 6}. Best is trial 3 with value: 0.6724821931638855.
[I 2026-03-31 09:48:55,573] Trial 18 finished with value: 0.6744059624870015 and parameters: {'learning_rate': 0.049391224441331975, 'max_depth': 5, 'subsample': 0.8704956989667747, 'colsample_bytree': 0.3722389124881974, 'min_child_weight': 5}. Best is trial 18 with value: 0.6744059624870015.
[I 2026-03-31 09:48:56,591] Trial 19 finished with value: 0.6667860134068866 and parameters: {'learning_rate': 0.05636188773204551, 'max_depth': 2, 'subsample': 0.99298196253465, 'colsample_bytree': 0.29738067656884415, 'min_child_weight': 4}. Best is trial 18 with value: 0.6744059624870015.
[I 2026-03-31 09:48:57,637] Trial 20 finished with value: 0.6727110093130614 and parameters: {'learning_rate': 0.09853066441054913, 'max_depth': 5, 'subsample': 0.8509298676906928, 'colsample_bytree': 0.3451958580139707, 'min_child_weight': 2}. Best is trial 18 with value: 0.6744059624870015.
[I 2026-03-31 09:48:58,509] Trial 21 finished with value: 0.673441509406411 and parameters: {'learning_rate': 0.09543631213061894, 'max_depth': 5, 'subsample': 0.8049272972942833, 'colsample_bytree': 0.36393955260618016, 'min_child_weight': 1}. Best is trial 18 with value: 0.6744059624870015.
[I 2026-03-31 09:48:59,625] Trial 22 finished with value: 0.6738157163255493 and parameters: {'learning_rate': 0.05571564809423663, 'max_depth': 5, 'subsample': 0.8652094007361826, 'colsample_bytree': 0.36477981689095085, 'min_child_weight': 1}. Best is trial 18 with value: 0.6744059624870015.
[I 2026-03-31 09:49:01,035] Trial 23 finished with value: 0.6699941747734837 and parameters: {'learning_rate': 0.04930639382400232, 'max_depth': 5, 'subsample': 0.8649122146230526, 'colsample_bytree': 0.218471669255147, 'min_child_weight': 1}. Best is trial 18 with value: 0.6744059624870015.
[I 2026-03-31 09:49:02,483] Trial 24 finished with value: 0.6733841071966841 and parameters: {'learning_rate': 0.03191974957850529, 'max_depth': 6, 'subsample': 0.9182467903321823, 'colsample_bytree': 0.427249666594371, 'min_child_weight': 3}. Best is trial 18 with value: 0.6744059624870015.
[I 2026-03-31 09:49:03,684] Trial 25 finished with value: 0.6644767100455692 and parameters: {'learning_rate': 0.017777875204199083, 'max_depth': 3, 'subsample': 0.9049577672703026, 'colsample_bytree': 0.27584976691866137, 'min_child_weight': 5}. Best is trial 18 with value: 0.6744059624870015.
[I 2026-03-31 09:49:05,250] Trial 26 finished with value: 0.6715940051796017 and parameters: {'learning_rate': 0.061320572792610294, 'max_depth': 7, 'subsample': 0.7761580526895899, 'colsample_bytree': 0.40361681602192556, 'min_child_weight': 1}. Best is trial 18 with value: 0.6744059624870015.
[I 2026-03-31 09:49:06,837] Trial 27 finished with value: 0.6723664135274589 and parameters: {'learning_rate': 0.03998294367129684, 'max_depth': 4, 'subsample': 0.6126924119144322, 'colsample_bytree': 0.5410781180491251, 'min_child_weight': 3}. Best is trial 18 with value: 0.6744059624870015.
[I 2026-03-31 09:49:08,653] Trial 28 finished with value: 0.6707769976041995 and parameters: {'learning_rate': 0.06072109192720842, 'max_depth': 5, 'subsample': 0.7053859795480053, 'colsample_bytree': 0.23222504742211045, 'min_child_weight': 5}. Best is trial 18 with value: 0.6744059624870015.
[I 2026-03-31 09:49:10,772] Trial 29 finished with value: 0.6729210251564259 and parameters: {'learning_rate': 0.0200691693841836, 'max_depth': 6, 'subsample': 0.9273565543719284, 'colsample_bytree': 0.3661822344182208, 'min_child_weight': 2}. Best is trial 18 with value: 0.6744059624870015.

Best params for fold 4: {'learning_rate': 0.049391224441331975, 'max_depth': 5, 'subsample': 0.8704956989667747, 'colsample_bytree': 0.3722389124881974, 'min_child_weight': 5}

[I 2026-03-31 09:49:12,708] A new study created in memory with name: Xgboost

Fold 4 AUC (log scale): 0.6671

==================================================
Fold 5/5
==================================================

[I 2026-03-31 09:49:14,259] Trial 0 finished with value: 0.6587502010749874 and parameters: {'learning_rate': 0.004077972478448117, 'max_depth': 6, 'subsample': 0.08184093471646892, 'colsample_bytree': 0.755733271148202, 'min_child_weight': 10}. Best is trial 0 with value: 0.6587502010749874.
[I 2026-03-31 09:49:15,443] Trial 1 finished with value: 0.6639298666882857 and parameters: {'learning_rate': 0.03771973017069119, 'max_depth': 4, 'subsample': 0.9120177794120664, 'colsample_bytree': 0.2872658921640067, 'min_child_weight': 20}. Best is trial 1 with value: 0.6639298666882857.
[I 2026-03-31 09:49:17,247] Trial 2 finished with value: 0.6565005969701869 and parameters: {'learning_rate': 0.002345109566115772, 'max_depth': 5, 'subsample': 0.12587084968749856, 'colsample_bytree': 0.7709705506850856, 'min_child_weight': 10}. Best is trial 1 with value: 0.6639298666882857.
[I 2026-03-31 09:49:18,631] Trial 3 finished with value: 0.6494174949833494 and parameters: {'learning_rate': 0.003730734568110959, 'max_depth': 2, 'subsample': 0.12966799865335843, 'colsample_bytree': 0.15919064077448522, 'min_child_weight': 15}. Best is trial 1 with value: 0.6639298666882857.
[I 2026-03-31 09:49:19,565] Trial 4 finished with value: 0.6652834642104966 and parameters: {'learning_rate': 0.04906909526777398, 'max_depth': 7, 'subsample': 0.6941379036067171, 'colsample_bytree': 0.6059394215669345, 'min_child_weight': 14}. Best is trial 4 with value: 0.6652834642104966.
[I 2026-03-31 09:49:20,850] Trial 5 finished with value: 0.6631040108185159 and parameters: {'learning_rate': 0.01690730181160383, 'max_depth': 5, 'subsample': 0.06359382997445262, 'colsample_bytree': 0.673173043553314, 'min_child_weight': 3}. Best is trial 4 with value: 0.6652834642104966.
[I 2026-03-31 09:49:21,966] Trial 6 finished with value: 0.6665792702152734 and parameters: {'learning_rate': 0.07161720971939052, 'max_depth': 3, 'subsample': 0.7596544211126036, 'colsample_bytree': 0.9549545566023544, 'min_child_weight': 8}. Best is trial 6 with value: 0.6665792702152734.
[I 2026-03-31 09:49:23,324] Trial 7 finished with value: 0.6501113590568184 and parameters: {'learning_rate': 0.0032005863809562636, 'max_depth': 9, 'subsample': 0.9213144807747529, 'colsample_bytree': 0.05476472844627606, 'min_child_weight': 5}. Best is trial 6 with value: 0.6665792702152734.
[I 2026-03-31 09:49:24,026] Trial 8 finished with value: 0.6652598985427336 and parameters: {'learning_rate': 0.06896918766713861, 'max_depth': 5, 'subsample': 0.48221976993514665, 'colsample_bytree': 0.48451107346816913, 'min_child_weight': 12}. Best is trial 6 with value: 0.6665792702152734.
[I 2026-03-31 09:49:24,987] Trial 9 finished with value: 0.6435781009331483 and parameters: {'learning_rate': 0.017798092208424102, 'max_depth': 1, 'subsample': 0.19264344037134834, 'colsample_bytree': 0.23312356060434736, 'min_child_weight': 10}. Best is trial 6 with value: 0.6665792702152734.
[I 2026-03-31 09:49:25,924] Trial 10 finished with value: 0.6657405940609145 and parameters: {'learning_rate': 0.0986251468759339, 'max_depth': 3, 'subsample': 0.6167335317752628, 'colsample_bytree': 0.9878305566503416, 'min_child_weight': 6}. Best is trial 6 with value: 0.6665792702152734.
[I 2026-03-31 09:49:27,012] Trial 11 finished with value: 0.666500880038863 and parameters: {'learning_rate': 0.0877820147051388, 'max_depth': 3, 'subsample': 0.615752590081497, 'colsample_bytree': 0.9591329153229188, 'min_child_weight': 6}. Best is trial 6 with value: 0.6665792702152734.
[I 2026-03-31 09:49:28,140] Trial 12 finished with value: 0.6614598569324401 and parameters: {'learning_rate': 0.027352719230733322, 'max_depth': 3, 'subsample': 0.46349576434958284, 'colsample_bytree': 0.9788263512021272, 'min_child_weight': 1}. Best is trial 6 with value: 0.6665792702152734.
[I 2026-03-31 09:49:29,063] Trial 13 finished with value: 0.6263329888395563 and parameters: {'learning_rate': 0.010608563876763613, 'max_depth': 1, 'subsample': 0.7408152548955638, 'colsample_bytree': 0.882378804647991, 'min_child_weight': 7}. Best is trial 6 with value: 0.6665792702152734.
[I 2026-03-31 09:49:29,741] Trial 14 finished with value: 0.6631843556122013 and parameters: {'learning_rate': 0.09556198118423152, 'max_depth': 3, 'subsample': 0.3131851131554495, 'colsample_bytree': 0.47303772569085734, 'min_child_weight': 7}. Best is trial 6 with value: 0.6665792702152734.
[I 2026-03-31 09:49:30,490] Trial 15 finished with value: 0.6635451428783128 and parameters: {'learning_rate': 0.045845867566137996, 'max_depth': 7, 'subsample': 0.7943082875635324, 'colsample_bytree': 0.8654121947363143, 'min_child_weight': 4}. Best is trial 6 with value: 0.6665792702152734.
[I 2026-03-31 09:49:32,786] Trial 16 finished with value: 0.6605423645953417 and parameters: {'learning_rate': 0.001456612266158449, 'max_depth': 10, 'subsample': 0.5960410582223487, 'colsample_bytree': 0.8796283727947402, 'min_child_weight': 8}. Best is trial 6 with value: 0.6665792702152734.
[I 2026-03-31 09:49:33,812] Trial 17 finished with value: 0.6448399417038906 and parameters: {'learning_rate': 0.007456092953583688, 'max_depth': 2, 'subsample': 0.3467809978063994, 'colsample_bytree': 0.38270506494440026, 'min_child_weight': 2}. Best is trial 6 with value: 0.6665792702152734.
[I 2026-03-31 09:49:35,001] Trial 18 finished with value: 0.6635790128874031 and parameters: {'learning_rate': 0.02585163572129457, 'max_depth': 4, 'subsample': 0.825226832348925, 'colsample_bytree': 0.7470912945938062, 'min_child_weight': 17}. Best is trial 6 with value: 0.6665792702152734.
[I 2026-03-31 09:49:36,048] Trial 19 finished with value: 0.6623669497032671 and parameters: {'learning_rate': 0.06451164831217837, 'max_depth': 2, 'subsample': 0.5881527227283447, 'colsample_bytree': 0.6348616096639494, 'min_child_weight': 12}. Best is trial 6 with value: 0.6665792702152734.
[I 2026-03-31 09:49:37,377] Trial 20 finished with value: 0.650266966639274 and parameters: {'learning_rate': 0.007471879866785113, 'max_depth': 4, 'subsample': 0.8289005354657089, 'colsample_bytree': 0.9221768241073753, 'min_child_weight': 8}. Best is trial 6 with value: 0.6665792702152734.
[I 2026-03-31 09:49:38,220] Trial 21 finished with value: 0.6655829416480787 and parameters: {'learning_rate': 0.09807245397474232, 'max_depth': 3, 'subsample': 0.6560540822441442, 'colsample_bytree': 0.9860532376537123, 'min_child_weight': 5}. Best is trial 6 with value: 0.6665792702152734.
[I 2026-03-31 09:49:39,265] Trial 22 finished with value: 0.6644961744431164 and parameters: {'learning_rate': 0.06552019394987033, 'max_depth': 3, 'subsample': 0.5611888125354791, 'colsample_bytree': 0.8237028656046085, 'min_child_weight': 6}. Best is trial 6 with value: 0.6665792702152734.
[I 2026-03-31 09:49:40,298] Trial 23 finished with value: 0.6546148624125855 and parameters: {'learning_rate': 0.09817653490321908, 'max_depth': 1, 'subsample': 0.39856263450698676, 'colsample_bytree': 0.9762578210028469, 'min_child_weight': 8}. Best is trial 6 with value: 0.6665792702152734.
[I 2026-03-31 09:49:41,638] Trial 24 finished with value: 0.6663250998037605 and parameters: {'learning_rate': 0.033534991464331844, 'max_depth': 4, 'subsample': 0.6482082225573322, 'colsample_bytree': 0.8024708739545807, 'min_child_weight': 4}. Best is trial 6 with value: 0.6665792702152734.
[I 2026-03-31 09:49:42,888] Trial 25 finished with value: 0.6662289526811817 and parameters: {'learning_rate': 0.03135377147344613, 'max_depth': 6, 'subsample': 0.7440234677078434, 'colsample_bytree': 0.7945227962703258, 'min_child_weight': 3}. Best is trial 6 with value: 0.6665792702152734.
[I 2026-03-31 09:49:44,608] Trial 26 finished with value: 0.6616847932860922 and parameters: {'learning_rate': 0.01877151784465066, 'max_depth': 4, 'subsample': 0.5173242422674327, 'colsample_bytree': 0.709404724561479, 'min_child_weight': 4}. Best is trial 6 with value: 0.6665792702152734.
[I 2026-03-31 09:49:45,591] Trial 27 finished with value: 0.6606305078107708 and parameters: {'learning_rate': 0.05452549374123295, 'max_depth': 2, 'subsample': 0.9711579022319973, 'colsample_bytree': 0.5628068375194204, 'min_child_weight': 9}. Best is trial 6 with value: 0.6665792702152734.
[I 2026-03-31 09:49:46,636] Trial 28 finished with value: 0.6641622205639048 and parameters: {'learning_rate': 0.03589832984035719, 'max_depth': 7, 'subsample': 0.6989823231575784, 'colsample_bytree': 0.9070601149309624, 'min_child_weight': 12}. Best is trial 6 with value: 0.6665792702152734.
[I 2026-03-31 09:49:47,913] Trial 29 finished with value: 0.6571414758799828 and parameters: {'learning_rate': 0.012568879910294378, 'max_depth': 4, 'subsample': 0.8783315483698612, 'colsample_bytree': 0.810253470949534, 'min_child_weight': 2}. Best is trial 6 with value: 0.6665792702152734.

Best params for fold 5: {'learning_rate': 0.07161720971939052, 'max_depth': 3, 'subsample': 0.7596544211126036, 'colsample_bytree': 0.9549545566023544, 'min_child_weight': 8}
Fold 5 AUC (log scale): 0.6736

==================================================
Cross-Validation Summary

## Section 9 — XGBoost Output: Acceptance Probability & Expected Financial Loss

Post-CV, the following export steps are performed:

### `df_acceptance_xgb_black_box.csv`
Selected columns from `df_middle_class`:  
`id, X_age, X_bonus_malus_rating, X_distr_channel, X_vehicle_type, X_ttm_claims, X_policy_count, X_risk_code, X_vehicle_age, X_policy_tenure, X_policy_premium, U, prob_acceptance, Z`

- `prob_acceptance` = acceptance probability predicted by the XGBoost classifier  
- `U` = premium uplift factor (`1 + relative_change`)  
- `Z` = binary acceptance outcome (ground truth)

### `df_exp_financial_loss_xgb_black_box.csv`
Selected columns from `df_middle`:  
`id, ..., Y (actual premium), U, Y_hat (predicted premium)`

- `Y_hat` = XGBoost regressor's OOF premium prediction  
- Used to compute expected financial loss = `Y_hat × (1 − prob_acceptance)`

In [335]:
df_middle_class['Z'] = 1- df_middle_class['is_churn'].astype(int)

In [336]:
model_features_class

['X_age',
 'X_bonus_malus_rating',
 'X_distr_channel',
 'X_vehicle_type',
 'X_ttm_claims',
 'X_policy_count',
 'X_risk_code',
 'X_vehicle_age',
 'X_policy_tenure',
 'X_policy_premium',
 'U']

In [337]:
['id', 'X_age','X_bonus_malus_rating','X_distr_channel','X_vehicle_type','X_ttm_claims','X_policy_count','X_risk_code','X_vehicle_age',
                           'X_policy_tenure','X_policy_premium', 'U','fold_number','churn_prediction','prob_acceptance','Z']

['id',
 'X_age',
 'X_bonus_malus_rating',
 'X_distr_channel',
 'X_vehicle_type',
 'X_ttm_claims',
 'X_policy_count',
 'X_risk_code',
 'X_vehicle_age',
 'X_policy_tenure',
 'X_policy_premium',
 'U',
 'fold_number',
 'churn_prediction',
 'prob_acceptance',
 'Z']

In [338]:
df_middle_class['prob_acceptance'] = 1 - df_middle_class['oof_prediction']

In [342]:
df_middle_class.columns

Index(['encoded_policy_number', 'X_age', 'X_bonus_malus_rating',
       'X_distr_channel', 'X_vehicle_type', 'X_ttm_claims', 'X_policy_count',
       'X_risk_code', 'X_vehicle_age', 'X_policy_tenure', 'X_policy_premium',
       'X_prev_renewal_perc', 'X_upcoming_premium', 'X_cur_renewal_perc',
       'year', 'is_churn', 'U', 'fold_number', 'oof_prediction', 'Z',
       'prob_acceptance'],
      dtype='object')

In [341]:
df_middle.columns = ['id', 'X_age','X_bonus_malus_rating','X_distr_channel','X_vehicle_type','X_ttm_claims','X_policy_count','X_risk_code','X_vehicle_age','X_policy_tenure',
                     'Y','X_prev_renewal_perc','X_upcoming_premium','X_cur_renewal_perc','X_year','1-Z','U','fold_number','Y_hat','Y_residual','Y_absolute_error']

In [343]:
df_middle_class.columns = ['id', 'X_age','X_bonus_malus_rating','X_distr_channel','X_vehicle_type','X_ttm_claims','X_policy_count','X_risk_code',"X_vehicle_age",
                           'X_policy_tenure','X_policy_premium','X_prev_renewal_perc','X_upcoming_premium','X_cur_renewal_perc','X_year','1-Z', 'U','fold_number','churn_prediction','Z','prob_acceptance']

In [344]:
df_middle_class['U'] = 1 + df_middle_class['U']

In [345]:
df_middle_class['U']

7          1.123099
16         1.107047
24         1.096895
32         1.097209
118        1.102011
             ...
3370174    1.062686
3370323    1.087288
3370329    1.087051
3370407    1.087493
3370452    1.087271
Name: U, Length: 194373, dtype: float64

In [346]:
['id', 'X_age','X_bonus_malus_rating','X_distr_channel','X_vehicle_type','X_ttm_claims','X_policy_count','X_risk_code',"X_vehicle_age",
                           'X_policy_tenure','X_policy_premium','X_prev_renewal_perc','X_upcoming_premium','X_cur_renewal_perc','X_year','1-Z', 'U','fold_number','churn_prediction','Z','prob_acceptance']

['id',
 'X_age',
 'X_bonus_malus_rating',
 'X_distr_channel',
 'X_vehicle_type',
 'X_ttm_claims',
 'X_policy_count',
 'X_risk_code',
 'X_vehicle_age',
 'X_policy_tenure',
 'X_policy_premium',
 'X_prev_renewal_perc',
 'X_upcoming_premium',
 'X_cur_renewal_perc',
 'X_year',
 '1-Z',
 'U',
 'fold_number',
 'churn_prediction',
 'Z',
 'prob_acceptance']

In [347]:
df_middle_class.loc[:, ['id', 'X_age','X_bonus_malus_rating','X_distr_channel','X_vehicle_type','X_ttm_claims','X_policy_count','X_risk_code','X_vehicle_age',
                           'X_policy_tenure','X_policy_premium', 'U','prob_acceptance','Z']].to_csv('df_acceptance_xgb_black_box.csv',sep=';')

In [348]:
df_middle.loc[:,['id', 'X_age','X_bonus_malus_rating','X_distr_channel','X_vehicle_type','X_ttm_claims','X_policy_count','X_risk_code','X_vehicle_age','X_policy_tenure',
                     'Y','U','Y_hat']]

,id,X_age,X_bonus_malus_rating,X_distr_channel,X_vehicle_type,X_ttm_claims,X_policy_count,X_risk_code,X_vehicle_age,X_policy_tenure,Y,U,Y_hat
7,5,93.0,45.0,5,7,0,1,0,24.0,24.0,175.7725,0.123099,193.966034
16,85,78.0,45.0,5,0,0,2,0,5.0,24.0,180.8686,0.107047,162.414307
24,93,78.0,45.0,5,1,0,1,0,21.0,24.0,165.6403,0.096895,168.083298
32,119,49.0,45.0,5,1,0,1,0,19.0,24.0,171.3347,0.097209,175.712479
118,395,49.0,45.0,2,2,0,4,0,16.0,24.0,170.0981,0.102011,210.380798
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3370174,5732129,68.0,45.0,4,2,0,1,2,9.0,9.0,345.4078,0.062686,267.912628
3370323,5732370,81.0,45.0,4,4,0,5,0,20.0,10.0,234.6113,0.087288,233.719376
3370329,5732373,58.0,45.0,4,7,0,3,0,30.0,8.0,174.1869,0.087051,193.689865
3370407,5732452,89.0,45.0,4,1,0,2,0,10.0,23.0,238.8796,0.087493,184.481094
3370452,5732508,54.0,45.0,7,0,1,1,1,22.0,21.0,220.5798,0.087271,213.106323

In [349]:
df_middle['U'] = 1 + df_middle['U']

In [352]:
df_middle.columns

Index(['id', 'X_age', 'X_bonus_malus_rating', 'X_distr_channel',
       'X_vehicle_type', 'X_ttm_claims', 'X_policy_count', 'X_risk_code',
       'X_vehicle_age', 'X_policy_tenure', 'Y', 'X_prev_renewal_perc',
       'X_upcoming_premium', 'X_cur_renewal_perc', 'X_year', '1-Z', 'U',
       'fold_number', 'Y_hat', 'Y_residual', 'Y_absolute_error'],
      dtype='object')

In [353]:
df_middle.loc[:,['id', 'X_age','X_bonus_malus_rating','X_distr_channel','X_vehicle_type','X_ttm_claims','X_policy_count','X_risk_code','X_vehicle_age','X_policy_tenure',
                     'Y','U','Y_hat']].to_csv('df_exp_financial_loss_xgb_black_box.csv',sep=';')

In [354]:
from pygam import LinearGAM, s
from pygam.datasets import toy_interaction

X, y = toy_interaction(return_X_y=True)

gam = LinearGAM(s(0, by=1)).fit(X, y)
gam.summary()

LinearGAM
=============================================== ==========================================================
Distribution:                        NormalDist Effective DoF:                                     20.8514
Link Function:                     IdentityLink Log Likelihood:                                 44131.6223
Number of Samples:                        50000 AIC:                                           -88219.5417
                                                AICc:                                          -88219.5218
                                                GCV:                                                  0.01
                                                Scale:                                              0.1001
                                                Pseudo R-Squared:                                   0.9976
==========================================================================================================
Feature Function                  Lambda               Rank         EDoF         P > x        Sig. Code
================================= ==================== ============ ============ ============ ============
s(0)                              [0.6]                20           19.9         1.11e-16     ***
intercept                                              1            1.0          5.44e-01
==========================================================================================================
Significance codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

WARNING: Fitting splines and a linear function to a feature introduces a model identifiability problem
         which can cause p-values to appear significant when they are not.

WARNING: p-values calculated in this manner behave correctly for un-penalized models or models with
         known smoothing parameters, but when smoothing parameters have been estimated, the p-values
         are typically lower than they should be, meaning that the tests reject the null too readily.

C:\Users\malosett\AppData\Local\Temp\ipykernel_22496\427681795.py:7: UserWarning: KNOWN BUG: p-values computed in this summary are likely much smaller than they should be.

Please do not make inferences based on these values!

Collaborate on a solution, and stay up to date at:
github.com/dswah/pyGAM/issues/163

  gam.summary()

In [355]:
!pip install pygam

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pygam in c:\users\malosett\appdata\roaming\python\python311\site-packages (0.12.0)
Requirement already satisfied: numpy>=1.5.0 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from pygam) (2.4.4)
Requirement already satisfied: progressbar2<5,>=4.2.0 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from pygam) (4.5.0)
Requirement already satisfied: scipy<1.17,>=1.11.1 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from pygam) (1.16.3)
Requirement already satisfied: python-utils>=3.8.1 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from progressbar2<5,>=4.2.0->pygam) (3.9.1)
Requirement already satisfied: typing_extensions>3.10.0.2 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from python-utils>=3.8.1->progressbar2<5,>=4.2.0->pygam) (4.15.0)

In [357]:
df_sub.columns

Index(['encoded_policy_number', 'X_age', 'X_bonus_malus_rating',
       'X_distr_channel', 'X_vehicle_type', 'X_ttm_claims', 'X_policy_count',
       'X_risk_code', 'X_vehicle_age', 'X_policy_tenure', 'X_policy_premium',
       'X_prev_renewal_perc', 'X_upcoming_premium', 'X_cur_renewal_perc',
       'year', 'is_churn'],
      dtype='object')

## Section 10 — GLM & GAM Dataset Preparation

Three additional datasets are created for the interpretable models, all using the same `filter_middle_advanced` thresholds:

| Dataset | Used by |
|---|---|
| `df_middle_glm` | GLM (Logistic Regression) churn classifier |
| `df_middle_gam` | GAM (LogisticGAM) churn classifier |
| `df_middle_reg` | (supporting dataset, currently superseded by `df_middle_reg_linear`) |

For GAM and GLM, categorical columns are **label-encoded** so that the preprocessors within each pipeline start from the same integer representation.  
`U` is computed and added to each dataset before training.

In [358]:
df_middle_glm = filter_middle_advanced(
    df_sub,
    numeric_filters={
        'X_age': {'multiplier': 1.5, 'method': 'iqr'},
        'X_policy_premium': {'multiplier': 2.0, 'method': 'iqr'},
        'X_upcoming_premium':{'multiplier':2.0,'method':'iqr'},
        'X_vehicle_age': {'method': 'percentile', 'lower_q': 0.05, 'upper_q': 0.95},
        'X_cur_renewal_perc':{'method': 'percentile', 'lower_q': 0.05, 'upper_q': 0.95}
    },
    categorical_filters={
        'X_distr_channel': {'max_categories':12},
        'X_risk_code': {'max_categories': 6},
        'X_vehicle_type': {'max_categories': 8}  # explicit list
    },
    keep_id_cols=['encoded_policy_number']
)

X_age: [8.50, 100.50]
X_policy_premium: [-14.06, 444.14]
X_upcoming_premium: [-15.07, 480.13]
X_vehicle_age: [4.00, 31.00]
X_cur_renewal_perc: [-0.02, 0.11]
X_distr_channel: Kept 12 categories
X_risk_code: Kept 6 categories
X_vehicle_type: Kept 8 categories

Total: 463400 → 194373 rows

In [359]:
df_middle_glm['U'] = (df_middle_glm['X_upcoming_premium'] - df_middle_glm['X_policy_premium']) / df_middle_glm['X_policy_premium']

In [360]:
df_middle_gam = filter_middle_advanced(
    df_sub,
    numeric_filters={
        'X_age': {'multiplier': 1.5, 'method': 'iqr'},
        'X_policy_premium': {'multiplier': 2.0, 'method': 'iqr'},
        'X_upcoming_premium':{'multiplier':2.0,'method':'iqr'},
        'X_vehicle_age': {'method': 'percentile', 'lower_q': 0.05, 'upper_q': 0.95},
        'X_cur_renewal_perc':{'method': 'percentile', 'lower_q': 0.05, 'upper_q': 0.95}
    },
    categorical_filters={
        'X_distr_channel': {'max_categories':12},
        'X_risk_code': {'max_categories': 6},
        'X_vehicle_type': {'max_categories': 8}  # explicit list
    },
    keep_id_cols=['encoded_policy_number']
)

X_age: [8.50, 100.50]
X_policy_premium: [-14.06, 444.14]
X_upcoming_premium: [-15.07, 480.13]
X_vehicle_age: [4.00, 31.00]
X_cur_renewal_perc: [-0.02, 0.11]
X_distr_channel: Kept 12 categories
X_risk_code: Kept 6 categories
X_vehicle_type: Kept 8 categories

Total: 463400 → 194373 rows

In [361]:
df_middle_gam.columns

Index(['encoded_policy_number', 'X_age', 'X_bonus_malus_rating',
       'X_distr_channel', 'X_vehicle_type', 'X_ttm_claims', 'X_policy_count',
       'X_risk_code', 'X_vehicle_age', 'X_policy_tenure', 'X_policy_premium',
       'X_prev_renewal_perc', 'X_upcoming_premium', 'X_cur_renewal_perc',
       'year', 'is_churn'],
      dtype='object')

In [362]:
df_middle_gam['U'] = (df_middle_gam['X_upcoming_premium'] - df_middle_gam['X_policy_premium']) / df_middle_gam['X_policy_premium']

In [363]:
df_middle_reg = filter_middle_advanced(
    df_sub,
    numeric_filters={
        'X_age': {'multiplier': 1.5, 'method': 'iqr'},
        'X_policy_premium': {'multiplier': 2.0, 'method': 'iqr'},
        'X_upcoming_premium':{'multiplier':2.0,'method':'iqr'},
        'X_vehicle_age': {'method': 'percentile', 'lower_q': 0.05, 'upper_q': 0.95},
        'X_cur_renewal_perc':{'method': 'percentile', 'lower_q': 0.05, 'upper_q': 0.95}
    },
    categorical_filters={
        'X_distr_channel': {'max_categories':12},
        'X_risk_code': {'max_categories': 6},
        'X_vehicle_type': {'max_categories': 8}  # explicit list
    },
    keep_id_cols=['encoded_policy_number']
)

X_age: [8.50, 100.50]
X_policy_premium: [-14.06, 444.14]
X_upcoming_premium: [-15.07, 480.13]
X_vehicle_age: [4.00, 31.00]
X_cur_renewal_perc: [-0.02, 0.11]
X_distr_channel: Kept 12 categories
X_risk_code: Kept 6 categories
X_vehicle_type: Kept 8 categories

Total: 463400 → 194373 rows

In [364]:
df_middle_reg['U'] = (df_middle_reg['X_upcoming_premium'] - df_middle_reg['X_policy_premium']) / df_middle_reg['X_policy_premium']

In [366]:
from sklearn.preprocessing import LabelEncoder
for cat in cat_cols:
    le = LabelEncoder()
    le.fit(df_middle_glm[cat])
    df_middle_glm[cat] = le.transform(df_middle_glm[cat])
    df_middle_gam[cat] = le.transform(df_middle_gam[cat])
    df_middle_reg[cat] = le.transform(df_middle_reg[cat])

## Section 11 — GLM Churn Cross-Validation (Logistic Regression)

### `ModelGLM`
A **sklearn `Pipeline`** wrapping:
1. `ColumnTransformer` — median imputation + standard scaling for numerics; mode imputation + one-hot encoding for categoricals
2. `LogisticRegression` (solver: `lbfgs`, max_iter: 1000)

**Tuning:** Optuna over the regularisation parameter `C` (log-uniform in `[0.001, 100]`), maximising ROC-AUC.

### `cross_validate_glm_with_oof`
- 5-fold outer CV with an inner 80/20 tuning split per fold  
- Outputs OOF churn probabilities (`oof_prediction_glm`) and the fold assignment

**Why GLM?**  
Provides an interpretable, linear-in-log-odds alternative to XGBoost.  
Suitable when a regulator requires explainability of acceptance probability estimates.

In [367]:
from sklearn import metrics
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold, train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
import optuna
from optuna.trial import Trial


class ModelGLM():
    """
    GLM-like classifier implemented with sklearn LogisticRegression.
    This avoids statsmodels exog shape mismatches across folds.
    """

    def __init__(self):
        self.categorical_cols = []
        self.numeric_cols = []

    def _build_model(self, C: float) -> Pipeline:
        numeric_transformer = Pipeline(steps=[
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler()),
        ])

        categorical_transformer = Pipeline(steps=[
            ("imputer", SimpleImputer(strategy="most_frequent")),
            ("onehot", OneHotEncoder(handle_unknown="ignore")),
        ])

        preprocessor = ColumnTransformer(
            transformers=[
                ("num", numeric_transformer, self.numeric_cols),
                ("cat", categorical_transformer, self.categorical_cols),
            ],
            remainder="drop",
        )

        clf = LogisticRegression(
            C=C,
            max_iter=1000,
            solver="lbfgs",
            random_state=123,
        )

        model = Pipeline(steps=[
            ("preprocessor", preprocessor),
            ("classifier", clf),
        ])
        return model

    def objective(self, trial: Trial, X_train: pd.DataFrame, y_train: pd.Series,
                  X_val: pd.DataFrame, y_val: pd.Series) -> float:
        """Optuna objective for logistic regression."""
        C = trial.suggest_float("C", 1e-3, 100.0, log=True)

        # Infer schema from training fold only.
        self.categorical_cols = X_train.select_dtypes(include=["object", "category"]).columns.tolist()
        self.numeric_cols = [c for c in X_train.columns if c not in self.categorical_cols]

        try:
            model = self._build_model(C=C)
            model.fit(X_train, y_train)
            y_score = model.predict_proba(X_val)[:, 1]
            y_score = np.clip(y_score, 1e-10, 1 - 1e-10)
            roc_auc = metrics.roc_auc_score(y_true=y_val, y_score=y_score)
            return roc_auc
        except Exception as e:
            print(f"Error in LogisticRegression fitting: {e}")
            return 0.5

    def tuning(self, X_train: pd.DataFrame, y_train: pd.Series,
               X_val: pd.DataFrame, y_val: pd.Series, n_trials: int) -> dict:
        """Hyperparameter tuning using Optuna."""
        study = optuna.create_study(study_name="LogisticRegression", direction="maximize")
        study.optimize(
            lambda trial: self.objective(trial, X_train, y_train, X_val, y_val),
            n_trials=n_trials,
            show_progress_bar=True,
        )
        return study.best_params

    def train(self, X_train: pd.DataFrame, y_train: pd.Series,
              X_val: pd.DataFrame, y_val: pd.Series, best_params: dict):
        """Train final logistic regression with best parameters."""
        C = best_params.get("C", 1.0)
        self.categorical_cols = X_train.select_dtypes(include=["object", "category"]).columns.tolist()
        self.numeric_cols = [c for c in X_train.columns if c not in self.categorical_cols]

        model = self._build_model(C=C)
        model.fit(X_train, y_train)
        return model


def cross_validate_glm_with_oof(X, y, n_splits=5, n_trials=20):
    """Cross-validation with OOF predictions for Logistic Regression GLM."""
    kfold = KFold(n_splits=n_splits, shuffle=True, random_state=123)

    fold_numbers = np.zeros(len(X))
    oof_predictions_proba = np.zeros(len(X))
    oof_predictions_class = np.zeros(len(X))

    fold_results = []
    best_params_per_fold = []

    for fold_idx, (train_idx, val_idx) in enumerate(kfold.split(X)):
        print(f"\n{'='*70}")
        print(f"Fold {fold_idx + 1}/{n_splits}")
        print(f"{'='*70}")

        fold_numbers[val_idx] = fold_idx + 1

        X_train_fold = X.iloc[train_idx].reset_index(drop=True)
        X_val_fold = X.iloc[val_idx].reset_index(drop=True)
        y_train_fold = y.iloc[train_idx].reset_index(drop=True)
        y_val_fold = y.iloc[val_idx].reset_index(drop=True)

        # Split for tuning
        X_train_tune, X_val_tune, y_train_tune, y_val_tune = train_test_split(
            X_train_fold, y_train_fold, test_size=0.2, random_state=123, stratify=y_train_fold
        )

        # Tune
        model_glm = ModelGLM()
        best_params = model_glm.tuning(
            X_train_tune, y_train_tune,
            X_val_tune, y_val_tune,
            n_trials=n_trials,
        )

        print(f"Best params: {best_params}")
        best_params_per_fold.append(best_params)

        # Train
        final_model = model_glm.train(
            X_train_fold, y_train_fold,
            X_val_fold, y_val_fold,
            best_params,
        )

        # Predict
        y_pred_proba = final_model.predict_proba(X_val_fold)[:, 1]
        y_pred_proba = np.clip(y_pred_proba, 0, 1)
        y_pred_class = (y_pred_proba > 0.5).astype(int)

        oof_predictions_proba[val_idx] = y_pred_proba
        oof_predictions_class[val_idx] = y_pred_class

        # Metrics
        roc_auc = metrics.roc_auc_score(y_val_fold, y_pred_proba)
        accuracy = metrics.accuracy_score(y_val_fold, y_pred_class)

        fold_results.append({
            "fold": fold_idx + 1,
            "roc_auc": roc_auc,
            "accuracy": accuracy,
            "n_train": len(train_idx),
            "n_val": len(val_idx),
        })

        print(f"Fold {fold_idx + 1} ROC-AUC: {roc_auc:.4f}")
        print(f"Fold {fold_idx + 1} Accuracy: {accuracy:.4f}")

    results_df = pd.DataFrame(fold_results)

    print(f"\n{'='*70}")
    print("Cross-Validation Summary")
    print(f"{'='*70}")
    print(f"Mean ROC-AUC: {results_df['roc_auc'].mean():.4f} (+/- {results_df['roc_auc'].std():.4f})")
    print(f"Mean Accuracy: {results_df['accuracy'].mean():.4f} (+/- {results_df['accuracy'].std():.4f})")

    overall_roc_auc = metrics.roc_auc_score(y, oof_predictions_proba)
    print(f"\nOverall OOF ROC-AUC: {overall_roc_auc:.4f}")

    return fold_numbers, oof_predictions_proba, results_df, best_params_per_fold


# Usage
X = df_middle_glm.loc[:, model_features_class]
y = df_middle_glm['is_churn']

fold_numbers_glm, oof_pred_glm, results_glm, params_glm = cross_validate_glm_with_oof(
    X, y, n_splits=5, n_trials=20
)

df_middle_glm['fold_number_glm'] = fold_numbers_glm.astype(int)
df_middle_glm['oof_prediction_glm'] = oof_pred_glm

[I 2026-03-31 10:08:17,780] A new study created in memory with name: LogisticRegression

======================================================================
Fold 1/5
======================================================================

  0%|          | 0/20 [00:00<?, ?it/s]

[I 2026-03-31 10:08:18,524] Trial 0 finished with value: 0.6511430838662619 and parameters: {'C': 1.2391445655399789}. Best is trial 0 with value: 0.6511430838662619.
[I 2026-03-31 10:08:19,145] Trial 1 finished with value: 0.6511532317480689 and parameters: {'C': 0.059422929543679635}. Best is trial 1 with value: 0.6511532317480689.
[I 2026-03-31 10:08:19,403] Trial 2 finished with value: 0.6511425567035705 and parameters: {'C': 94.5322401931766}. Best is trial 1 with value: 0.6511532317480689.
[I 2026-03-31 10:08:19,659] Trial 3 finished with value: 0.651498776754457 and parameters: {'C': 0.0013663406966000849}. Best is trial 3 with value: 0.651498776754457.
[I 2026-03-31 10:08:19,938] Trial 4 finished with value: 0.651207448403318 and parameters: {'C': 0.009142441029275604}. Best is trial 3 with value: 0.651498776754457.
[I 2026-03-31 10:08:20,182] Trial 5 finished with value: 0.6512052586506004 and parameters: {'C': 0.009573933926979491}. Best is trial 3 with value: 0.651498776754457.
[I 2026-03-31 10:08:20,402] Trial 6 finished with value: 0.6511464597350348 and parameters: {'C': 0.17672929134099088}. Best is trial 3 with value: 0.651498776754457.
[I 2026-03-31 10:08:20,625] Trial 7 finished with value: 0.6511477066775546 and parameters: {'C': 0.14136754245858457}. Best is trial 3 with value: 0.651498776754457.
[I 2026-03-31 10:08:20,833] Trial 8 finished with value: 0.651142789871684 and parameters: {'C': 7.76671285632966}. Best is trial 3 with value: 0.651498776754457.
[I 2026-03-31 10:08:21,039] Trial 9 finished with value: 0.6512814336594899 and parameters: {'C': 0.004135668467837485}. Best is trial 3 with value: 0.651498776754457.
[I 2026-03-31 10:08:21,244] Trial 10 finished with value: 0.6514120889049742 and parameters: {'C': 0.0019377712899255684}. Best is trial 3 with value: 0.651498776754457.
[I 2026-03-31 10:08:21,454] Trial 11 finished with value: 0.6514812790082042 and parameters: {'C': 0.0014540446002822818}. Best is trial 3 with value: 0.651498776754457.
[I 2026-03-31 10:08:21,662] Trial 12 finished with value: 0.651418668300871 and parameters: {'C': 0.0018854285215400123}. Best is trial 3 with value: 0.651498776754457.
[I 2026-03-31 10:08:21,863] Trial 13 finished with value: 0.6511716723045197 and parameters: {'C': 0.022034138165365424}. Best is trial 3 with value: 0.651498776754457.
[I 2026-03-31 10:08:22,068] Trial 14 finished with value: 0.6511430940040059 and parameters: {'C': 0.9976958715983634}. Best is trial 3 with value: 0.651498776754457.
[I 2026-03-31 10:08:22,273] Trial 15 finished with value: 0.6515462518099041 and parameters: {'C': 0.0011650434633761514}. Best is trial 15 with value: 0.6515462518099041.
[I 2026-03-31 10:08:22,490] Trial 16 finished with value: 0.6511591623283457 and parameters: {'C': 0.03791625111484127}. Best is trial 15 with value: 0.6515462518099041.
[I 2026-03-31 10:08:22,706] Trial 17 finished with value: 0.6515310756070417 and parameters: {'C': 0.001213227430725524}. Best is trial 15 with value: 0.6515462518099041.
[I 2026-03-31 10:08:22,926] Trial 18 finished with value: 0.6512183464781858 and parameters: {'C': 0.007708558406494009}. Best is trial 15 with value: 0.6515462518099041.
[I 2026-03-31 10:08:23,129] Trial 19 finished with value: 0.6511426783564994 and parameters: {'C': 15.941827539837536}. Best is trial 15 with value: 0.6515462518099041.
Best params: {'C': 0.0011650434633761514}

[I 2026-03-31 10:08:23,511] A new study created in memory with name: LogisticRegression

Fold 1 ROC-AUC: 0.6447
Fold 1 Accuracy: 0.8853

======================================================================
Fold 2/5
======================================================================

  0%|          | 0/20 [00:00<?, ?it/s]

[I 2026-03-31 10:08:23,751] Trial 0 finished with value: 0.641396605125871 and parameters: {'C': 1.5980060454508516}. Best is trial 0 with value: 0.641396605125871.
[I 2026-03-31 10:08:23,952] Trial 1 finished with value: 0.6413966051258712 and parameters: {'C': 1.5741570431562837}. Best is trial 1 with value: 0.6413966051258712.
[I 2026-03-31 10:08:24,256] Trial 2 finished with value: 0.6414044764250839 and parameters: {'C': 0.06061544346156023}. Best is trial 2 with value: 0.6414044764250839.
[I 2026-03-31 10:08:24,474] Trial 3 finished with value: 0.6413965747347544 and parameters: {'C': 90.8530735338292}. Best is trial 2 with value: 0.6414044764250839.
[I 2026-03-31 10:08:24,742] Trial 4 finished with value: 0.6413966355169877 and parameters: {'C': 4.015018452802382}. Best is trial 2 with value: 0.6414044764250839.
[I 2026-03-31 10:08:24,943] Trial 5 finished with value: 0.6414051551600225 and parameters: {'C': 0.0550382770750175}. Best is trial 5 with value: 0.6414051551600225.
[I 2026-03-31 10:08:25,137] Trial 6 finished with value: 0.641402845435157 and parameters: {'C': 0.07813341112997246}. Best is trial 5 with value: 0.6414051551600225.
[I 2026-03-31 10:08:25,336] Trial 7 finished with value: 0.6415014240872048 and parameters: {'C': 0.004332437655260105}. Best is trial 7 with value: 0.6415014240872048.
[I 2026-03-31 10:08:25,554] Trial 8 finished with value: 0.6414051855511392 and parameters: {'C': 0.05489887636213645}. Best is trial 7 with value: 0.6415014240872048.
[I 2026-03-31 10:08:25,747] Trial 9 finished with value: 0.6414034329967457 and parameters: {'C': 0.0709902511314833}. Best is trial 7 with value: 0.6415014240872048.
[I 2026-03-31 10:08:25,987] Trial 10 finished with value: 0.6416355907368525 and parameters: {'C': 0.0016388627010125092}. Best is trial 10 with value: 0.6416355907368525.
[I 2026-03-31 10:08:26,210] Trial 11 finished with value: 0.6416394402782951 and parameters: {'C': 0.001617087847004659}. Best is trial 11 with value: 0.6416394402782951.
[I 2026-03-31 10:08:26,426] Trial 12 finished with value: 0.6417041429656479 and parameters: {'C': 0.001201231840174079}. Best is trial 12 with value: 0.6417041429656479.
[I 2026-03-31 10:08:26,674] Trial 13 finished with value: 0.6414962981188628 and parameters: {'C': 0.0045871425240870435}. Best is trial 12 with value: 0.6417041429656479.
[I 2026-03-31 10:08:26,897] Trial 14 finished with value: 0.641454793983888 and parameters: {'C': 0.00841551753513416}. Best is trial 12 with value: 0.6417041429656479.
[I 2026-03-31 10:08:27,127] Trial 15 finished with value: 0.6416648776429332 and parameters: {'C': 0.001440868239014501}. Best is trial 12 with value: 0.6417041429656479.
[I 2026-03-31 10:08:27,332] Trial 16 finished with value: 0.6417483417796325 and parameters: {'C': 0.0010033732418018115}. Best is trial 16 with value: 0.6417483417796325.
[I 2026-03-31 10:08:27,558] Trial 17 finished with value: 0.6414555942832932 and parameters: {'C': 0.008100504425877078}. Best is trial 16 with value: 0.6417483417796325.
[I 2026-03-31 10:08:27,775] Trial 18 finished with value: 0.6414301366579107 and parameters: {'C': 0.014322797497136889}. Best is trial 16 with value: 0.6417483417796325.
[I 2026-03-31 10:08:27,972] Trial 19 finished with value: 0.6413983070284036 and parameters: {'C': 0.31177482568718423}. Best is trial 16 with value: 0.6417483417796325.
Best params: {'C': 0.0010033732418018115}

[I 2026-03-31 10:08:28,317] A new study created in memory with name: LogisticRegression

Fold 2 ROC-AUC: 0.6474
Fold 2 Accuracy: 0.8857

======================================================================
Fold 3/5
======================================================================

  0%|          | 0/20 [00:00<?, ?it/s]

[I 2026-03-31 10:08:28,580] Trial 0 finished with value: 0.6477350436972616 and parameters: {'C': 2.342703417064655}. Best is trial 0 with value: 0.6477350436972616.
[I 2026-03-31 10:08:28,777] Trial 1 finished with value: 0.6479265199935532 and parameters: {'C': 0.0033315418683598874}. Best is trial 1 with value: 0.6479265199935532.
[I 2026-03-31 10:08:29,068] Trial 2 finished with value: 0.6477347910500137 and parameters: {'C': 38.690984976044945}. Best is trial 1 with value: 0.6479265199935532.
[I 2026-03-31 10:08:29,271] Trial 3 finished with value: 0.6477412891372315 and parameters: {'C': 0.10289180399065131}. Best is trial 1 with value: 0.6479265199935532.
[I 2026-03-31 10:08:29,475] Trial 4 finished with value: 0.647737620699191 and parameters: {'C': 0.23315674535788955}. Best is trial 1 with value: 0.6479265199935532.
[I 2026-03-31 10:08:29,676] Trial 5 finished with value: 0.6477458064700252 and parameters: {'C': 0.0626996535620826}. Best is trial 1 with value: 0.6479265199935532.
[I 2026-03-31 10:08:29,927] Trial 6 finished with value: 0.647761258375711 and parameters: {'C': 0.02563296659251378}. Best is trial 1 with value: 0.6479265199935532.
[I 2026-03-31 10:08:30,207] Trial 7 finished with value: 0.647736003756804 and parameters: {'C': 0.4009468872832951}. Best is trial 1 with value: 0.6479265199935532.
[I 2026-03-31 10:08:30,448] Trial 8 finished with value: 0.6477598637629022 and parameters: {'C': 0.026758215124185185}. Best is trial 1 with value: 0.6479265199935532.
[I 2026-03-31 10:08:30,693] Trial 9 finished with value: 0.6477347809441237 and parameters: {'C': 28.252583942383296}. Best is trial 1 with value: 0.6479265199935532.
[I 2026-03-31 10:08:30,931] Trial 10 finished with value: 0.6481822697497284 and parameters: {'C': 0.0011863688857568582}. Best is trial 10 with value: 0.6481822697497284.
[I 2026-03-31 10:08:31,185] Trial 11 finished with value: 0.6480757132464245 and parameters: {'C': 0.0016911240691770846}. Best is trial 10 with value: 0.6481822697497284.
[I 2026-03-31 10:08:31,395] Trial 12 finished with value: 0.6480523282171525 and parameters: {'C': 0.0018166136586821309}. Best is trial 10 with value: 0.6481822697497284.
[I 2026-03-31 10:08:31,616] Trial 13 finished with value: 0.6481907182737006 and parameters: {'C': 0.001158804959076637}. Best is trial 13 with value: 0.6481907182737006.
[I 2026-03-31 10:08:31,819] Trial 14 finished with value: 0.6478235005517209 and parameters: {'C': 0.007465749911930382}. Best is trial 13 with value: 0.6481907182737006.
[I 2026-03-31 10:08:32,030] Trial 15 finished with value: 0.648222400238596 and parameters: {'C': 0.0010472434050874033}. Best is trial 15 with value: 0.648222400238596.
[I 2026-03-31 10:08:32,265] Trial 16 finished with value: 0.6478009947348718 and parameters: {'C': 0.01004894124492976}. Best is trial 15 with value: 0.648222400238596.
[I 2026-03-31 10:08:32,505] Trial 17 finished with value: 0.6477353165562894 and parameters: {'C': 1.2224549835048342}. Best is trial 15 with value: 0.648222400238596.
[I 2026-03-31 10:08:32,745] Trial 18 finished with value: 0.6478611449916685 and parameters: {'C': 0.005154865503081328}. Best is trial 15 with value: 0.648222400238596.
[I 2026-03-31 10:08:32,961] Trial 19 finished with value: 0.6477347506264539 and parameters: {'C': 8.035608193827523}. Best is trial 15 with value: 0.648222400238596.
Best params: {'C': 0.0010472434050874033}

[I 2026-03-31 10:08:33,330] A new study created in memory with name: LogisticRegression

Fold 3 ROC-AUC: 0.6363
Fold 3 Accuracy: 0.8869

======================================================================
Fold 4/5
======================================================================

  0%|          | 0/20 [00:00<?, ?it/s]

[I 2026-03-31 10:08:33,608] Trial 0 finished with value: 0.6437469872043566 and parameters: {'C': 20.529952161463886}. Best is trial 0 with value: 0.6437469872043566.
[I 2026-03-31 10:08:33,843] Trial 1 finished with value: 0.6437474165358815 and parameters: {'C': 2.4373876989871532}. Best is trial 1 with value: 0.6437474165358815.
[I 2026-03-31 10:08:34,152] Trial 2 finished with value: 0.6437469974265357 and parameters: {'C': 19.096089752404673}. Best is trial 1 with value: 0.6437474165358815.
[I 2026-03-31 10:08:34,378] Trial 3 finished with value: 0.6437469258712816 and parameters: {'C': 90.1469089833352}. Best is trial 1 with value: 0.6437474165358815.
[I 2026-03-31 10:08:34,619] Trial 4 finished with value: 0.6437475187576732 and parameters: {'C': 1.7963411087257362}. Best is trial 4 with value: 0.6437475187576732.
[I 2026-03-31 10:08:34,880] Trial 5 finished with value: 0.6438188491238964 and parameters: {'C': 0.0069960703018583075}. Best is trial 5 with value: 0.6438188491238964.
[I 2026-03-31 10:08:35,163] Trial 6 finished with value: 0.6437476005351065 and parameters: {'C': 1.2596356477209292}. Best is trial 5 with value: 0.6438188491238964.
[I 2026-03-31 10:08:35,386] Trial 7 finished with value: 0.6437491338619814 and parameters: {'C': 0.44332141951061393}. Best is trial 5 with value: 0.6438188491238964.
[I 2026-03-31 10:08:35,599] Trial 8 finished with value: 0.6437475187576732 and parameters: {'C': 1.7940019958962479}. Best is trial 5 with value: 0.6438188491238964.
[I 2026-03-31 10:08:35,801] Trial 9 finished with value: 0.6437469769821773 and parameters: {'C': 30.231670794329176}. Best is trial 5 with value: 0.6438188491238964.
[I 2026-03-31 10:08:36,048] Trial 10 finished with value: 0.6438874808348196 and parameters: {'C': 0.003342270834418449}. Best is trial 10 with value: 0.6438874808348196.
[I 2026-03-31 10:08:36,302] Trial 11 finished with value: 0.6439375592905558 and parameters: {'C': 0.0023636855703273287}. Best is trial 11 with value: 0.6439375592905558.
[I 2026-03-31 10:08:36,510] Trial 12 finished with value: 0.6440999386066142 and parameters: {'C': 0.0011091807098034475}. Best is trial 12 with value: 0.6440999386066142.
[I 2026-03-31 10:08:36,735] Trial 13 finished with value: 0.6437745257550308 and parameters: {'C': 0.01967328743903604}. Best is trial 12 with value: 0.6440999386066142.
[I 2026-03-31 10:08:36,990] Trial 14 finished with value: 0.6441188905267887 and parameters: {'C': 0.0010269546141557383}. Best is trial 14 with value: 0.6441188905267887.
[I 2026-03-31 10:08:37,184] Trial 15 finished with value: 0.6437625658054063 and parameters: {'C': 0.03620385465572609}. Best is trial 14 with value: 0.6441188905267887.
[I 2026-03-31 10:08:37,394] Trial 16 finished with value: 0.6437535191768439 and parameters: {'C': 0.09101541265001444}. Best is trial 14 with value: 0.6441188905267887.
[I 2026-03-31 10:08:37,614] Trial 17 finished with value: 0.6441031585930516 and parameters: {'C': 0.001082113721693321}. Best is trial 14 with value: 0.6441188905267887.
[I 2026-03-31 10:08:37,840] Trial 18 finished with value: 0.643808933610105 and parameters: {'C': 0.008134600091189739}. Best is trial 14 with value: 0.6441188905267887.
[I 2026-03-31 10:08:38,075] Trial 19 finished with value: 0.6437555125017813 and parameters: {'C': 0.06736907358348831}. Best is trial 14 with value: 0.6441188905267887.
Best params: {'C': 0.0010269546141557383}

[I 2026-03-31 10:08:38,482] A new study created in memory with name: LogisticRegression

Fold 4 ROC-AUC: 0.6393
Fold 4 Accuracy: 0.8809

======================================================================
Fold 5/5
======================================================================

  0%|          | 0/20 [00:00<?, ?it/s]

[I 2026-03-31 10:08:38,799] Trial 0 finished with value: 0.6459974896294033 and parameters: {'C': 0.12026725402462285}. Best is trial 0 with value: 0.6459974896294033.
[I 2026-03-31 10:08:39,061] Trial 1 finished with value: 0.6460013539850042 and parameters: {'C': 0.02217557195366564}. Best is trial 1 with value: 0.6460013539850042.
[I 2026-03-31 10:08:39,298] Trial 2 finished with value: 0.6460012424156824 and parameters: {'C': 0.029531814551313474}. Best is trial 1 with value: 0.6460013539850042.
[I 2026-03-31 10:08:39,634] Trial 3 finished with value: 0.6460004411450985 and parameters: {'C': 0.03728206570382278}. Best is trial 1 with value: 0.6460013539850042.
[I 2026-03-31 10:08:39,834] Trial 4 finished with value: 0.6460222783041759 and parameters: {'C': 0.005893368931531933}. Best is trial 4 with value: 0.6460222783041759.
[I 2026-03-31 10:08:40,037] Trial 5 finished with value: 0.6459967289294819 and parameters: {'C': 0.1524358559570441}. Best is trial 4 with value: 0.6460222783041759.
[I 2026-03-31 10:08:40,248] Trial 6 finished with value: 0.645994598969702 and parameters: {'C': 10.168249709736498}. Best is trial 4 with value: 0.6460222783041759.
[I 2026-03-31 10:08:40,536] Trial 7 finished with value: 0.6460080988576407 and parameters: {'C': 0.012642357765943529}. Best is trial 4 with value: 0.6460222783041759.
[I 2026-03-31 10:08:40,841] Trial 8 finished with value: 0.6459945076857113 and parameters: {'C': 34.53270576378565}. Best is trial 4 with value: 0.6460222783041759.
[I 2026-03-31 10:08:41,084] Trial 9 finished with value: 0.6459950655323203 and parameters: {'C': 1.4260451862210508}. Best is trial 4 with value: 0.6460222783041759.
[I 2026-03-31 10:08:41,353] Trial 10 finished with value: 0.6460650904957533 and parameters: {'C': 0.0013388224466969842}. Best is trial 10 with value: 0.6460650904957533.
[I 2026-03-31 10:08:41,691] Trial 11 finished with value: 0.6460637415212259 and parameters: {'C': 0.0012503328715786268}. Best is trial 10 with value: 0.6460650904957533.
[I 2026-03-31 10:08:41,921] Trial 12 finished with value: 0.6460609928588432 and parameters: {'C': 0.001063618568187244}. Best is trial 10 with value: 0.6460650904957533.
[I 2026-03-31 10:08:42,157] Trial 13 finished with value: 0.6460653136343969 and parameters: {'C': 0.0013799358800245807}. Best is trial 13 with value: 0.6460653136343969.
[I 2026-03-31 10:08:42,390] Trial 14 finished with value: 0.6460361737560739 and parameters: {'C': 0.003667075471480294}. Best is trial 13 with value: 0.6460653136343969.
[I 2026-03-31 10:08:42,632] Trial 15 finished with value: 0.646037127166642 and parameters: {'C': 0.003564824742211738}. Best is trial 13 with value: 0.6460653136343969.
[I 2026-03-31 10:08:42,977] Trial 16 finished with value: 0.6459954712389453 and parameters: {'C': 0.835232289599316}. Best is trial 13 with value: 0.6460653136343969.
[I 2026-03-31 10:08:43,208] Trial 17 finished with value: 0.6460636400945698 and parameters: {'C': 0.0010273888474269417}. Best is trial 13 with value: 0.6460653136343969.
[I 2026-03-31 10:08:43,421] Trial 18 finished with value: 0.6459948018230143 and parameters: {'C': 2.536942345563748}. Best is trial 13 with value: 0.6460653136343969.
[I 2026-03-31 10:08:43,643] Trial 19 finished with value: 0.6459984633253029 and parameters: {'C': 0.08824321503734608}. Best is trial 13 with value: 0.6460653136343969.
Best params: {'C': 0.0013799358800245807}
Fold 5 ROC-AUC: 0.6513
Fold 5 Accuracy: 0.8850

======================================================================
Cross-Validation Summary
======================================================================
Mean ROC-AUC: 0.6438 (+/- 0.0061)
Mean Accuracy: 0.8847 (+/- 0.0023)

Overall OOF ROC-AUC: 0.6437

In [369]:
df_middle_glm.head()

,encoded_policy_number,X_age,X_bonus_malus_rating,X_distr_channel,X_vehicle_type,X_ttm_claims,X_policy_count,X_risk_code,X_vehicle_age,X_policy_tenure,X_policy_premium,X_prev_renewal_perc,X_upcoming_premium,X_cur_renewal_perc,year,is_churn,U,fold_number_glm,oof_prediction_glm
7,5,93.0,45.0,5,7,0,1,0,24.0,24.0,175.7725,0.003637,197.41,0.098601,7,False,0.123099,5,0.133983
16,85,78.0,45.0,5,0,0,2,0,5.0,24.0,180.8686,0.003824,200.23,0.082852,7,False,0.107047,4,0.049107
24,93,78.0,45.0,5,1,0,1,0,21.0,24.0,165.6403,0.003731,181.69,0.072973,7,False,0.096895,1,0.088342
32,119,49.0,45.0,5,1,0,1,0,19.0,24.0,171.3347,-0.005503,187.99,0.073266,7,False,0.097209,5,0.100304
118,395,49.0,45.0,2,2,0,4,0,16.0,24.0,170.0981,-0.005223,187.45,0.077961,7,False,0.102011,5,0.067991

## Section 12 — GLM Output: Acceptance Probability

Post-CV steps for `df_middle_glm`:

1. Compute `Z = 1 − is_churn` (binary acceptance)  
2. Compute `prob_acceptance = 1 − oof_prediction_glm`  
3. Adjust `U = 1 + U` (uplift factor format)  
4. Rename columns to canonical business names  

**Exported to:** `df_acceptance_linear_model_black_box.csv`

This file mirrors the XGBoost acceptance output but with GLM-derived acceptance probabilities, allowing the optimisation module to compare model choices.

In [370]:
df_middle_glm['Z'] = 1 - df_middle_glm['is_churn'].astype(int)
df_middle_glm['prob_acceptance'] = 1 - df_middle_glm['oof_prediction_glm']

In [373]:
df_middle_glm['U'] = 1 + df_middle_glm['U']

In [371]:
df_middle_glm.columns = ['id','X_age','X_bonus_malus_rating','X_distr_channel','X_vehicle_type','X_ttm_claims','X_policy_count','X_risk_code','X_vehicle_age','X_policy_tenure',
                         'X_policy_premium','X_prev_renewal_perc','X_upcoming_premium','X_cur_renewal_perc','X_year','1-Z','U','fold_number_glm','churn_prediction','Z','prob_acceptance']

In [374]:
df_middle_glm.columns

Index(['id', 'X_age', 'X_bonus_malus_rating', 'X_distr_channel',
       'X_vehicle_type', 'X_ttm_claims', 'X_policy_count', 'X_risk_code',
       'X_vehicle_age', 'X_policy_tenure', 'X_policy_premium',
       'X_prev_renewal_perc', 'X_upcoming_premium', 'X_cur_renewal_perc',
       'X_year', '1-Z', 'U', 'fold_number_glm', 'churn_prediction', 'Z',
       'prob_acceptance'],
      dtype='object')

In [375]:
df_middle_glm.to_csv('df_acceptance_linear_model_black_box.csv',sep=';')

In [127]:
df_middle_gam.columns

Index(['encoded_policy_number', 'age', 'bonus_malus_rating', 'distr_channel',
       'vehicle_type', 'ttm_claims', 'policy_count', 'risk_code',
       'vehicle_age', 'policy_tenure', 'policy_premium', 'prev_renewal_perc',
       'upcoming_premium', 'cur_renewal_perc', 'year', 'is_churn', 'U'],
      dtype='object')

## Section 13 — GAM Churn Cross-Validation (LogisticGAM)

### `ModelGAM` (memory-safe version)
A **pyGAM `LogisticGAM`** that uses:
- **Spline terms** (`s()`) for continuous features — captures non-linear relationships
- **Factor terms** (`f()`) for categorical features — discrete category effects

Key design decisions:
- `_prepare_data` — category mappings are fitted on training data only (prevents leakage)
- Progressively tries `n_splines = [8, 6, 4]` if fitting fails due to memory pressure
- `max_train_samples = 35,000` — stratified subsampling is applied to avoid OOM on large folds

### `cross_validate_gam_with_oof`
- 5-fold outer CV (no inner Optuna tuning; `n_splines` and `lam` are fixed hyperparameters)
- `_stratified_sample` ensures class balance is preserved after subsampling

**Why GAM?**  
GAMs are semi-parametric: they capture non-linear covariate effects while remaining interpretable via partial dependence plots, making them a strong regulatory-friendly alternative.

In [128]:
from sklearn import metrics
import pandas as pd
import numpy as np
from pygam import LogisticGAM, s, f
from sklearn.model_selection import KFold


class ModelGAM:
    """Memory-safe GAM classifier for churn prediction."""

    def __init__(self):
        self.numeric_cols = []
        self.categorical_cols = []
        self.feature_order = []
        self.category_maps = {}
        self.category_default_code = {}

    def _prepare_data(self, X: pd.DataFrame, fit: bool = False) -> pd.DataFrame:
        """Prepare data for GAM using stable category mappings and fixed column order."""
        X_prep = X.copy()

        if fit:
            self.numeric_cols = X_prep.select_dtypes(include=[np.number]).columns.tolist()
            self.categorical_cols = X_prep.select_dtypes(include=["object", "category"]).columns.tolist()
            self.feature_order = self.numeric_cols + self.categorical_cols

            self.category_maps = {}
            self.category_default_code = {}
            for col in self.categorical_cols:
                cats = sorted(X_prep[col].astype(str).dropna().unique().tolist())
                mapping = {cat: idx for idx, cat in enumerate(cats)}
                self.category_maps[col] = mapping
                self.category_default_code[col] = len(mapping)

        for col in self.categorical_cols:
            mapping = self.category_maps[col]
            default_code = self.category_default_code[col]
            X_prep[col] = X_prep[col].astype(str).map(lambda x: mapping.get(x, default_code))

        if len(self.numeric_cols) > 0:
            X_prep[self.numeric_cols] = X_prep[self.numeric_cols].apply(
                lambda s_col: s_col.fillna(s_col.median())
            )

        X_prep = X_prep[self.feature_order]
        return X_prep

    def _build_formula(self, n_features: int, n_numeric: int, n_splines: int = 8, lam: float = 0.8):
        if n_features == 0:
            raise ValueError("No features found for GAM model.")

        terms = None

        for i in range(n_numeric):
            term = s(i, n_splines=n_splines, lam=lam)
            terms = term if terms is None else terms + term

        for i in range(n_numeric, n_features):
            term = f(i, lam=lam)
            terms = term if terms is None else terms + term

        return terms

    def train(
        self,
        X_train: pd.DataFrame,
        y_train: pd.Series,
        X_val: pd.DataFrame,
        y_val: pd.Series,
        n_splines: int = 8,
        lam: float = 0.8,
    ):
        X_train_prep = self._prepare_data(X_train, fit=True)
        _ = self._prepare_data(X_val, fit=False)

        n_features = X_train_prep.shape[1]
        n_numeric = len(self.numeric_cols)

        # Try progressively simpler models if memory pressure occurs.
        candidate_splines = [n_splines, min(6, n_splines), 4]

        last_error = None
        for spl in candidate_splines:
            try:
                terms = self._build_formula(n_features, n_numeric, n_splines=spl, lam=lam)
                gam = LogisticGAM(terms=terms, max_iter=100)
                gam.fit(X_train_prep.values.astype(np.float32), y_train.values)
                return gam
            except Exception as e:
                last_error = e
                print(f"GAM fit failed with n_splines={spl}: {e}")

        raise RuntimeError(f"All GAM fits failed. Last error: {last_error}")


def _stratified_sample(X: pd.DataFrame, y: pd.Series, max_samples: int, seed: int):
    """Return stratified sample indices for memory-safe GAM fitting."""
    if len(X) <= max_samples:
        return X.reset_index(drop=True), y.reset_index(drop=True)

    rng = np.random.default_rng(seed)
    y_arr = y.values

    pos_idx = np.where(y_arr == 1)[0]
    neg_idx = np.where(y_arr == 0)[0]

    pos_ratio = len(pos_idx) / len(y_arr)
    n_pos = int(max_samples * pos_ratio)
    n_neg = max_samples - n_pos

    n_pos = min(n_pos, len(pos_idx))
    n_neg = min(n_neg, len(neg_idx))

    sampled_pos = rng.choice(pos_idx, size=n_pos, replace=False) if n_pos > 0 else np.array([], dtype=int)
    sampled_neg = rng.choice(neg_idx, size=n_neg, replace=False) if n_neg > 0 else np.array([], dtype=int)

    sample_idx = np.concatenate([sampled_pos, sampled_neg])
    rng.shuffle(sample_idx)

    return X.iloc[sample_idx].reset_index(drop=True), y.iloc[sample_idx].reset_index(drop=True)


def cross_validate_gam_with_oof(
    X,
    y,
    n_splits=5,
    n_splines=8,
    lam=0.8,
    max_train_samples=35000,
):
    """Cross-validation for GAM with OOF predictions and RAM-safe training."""
    kfold = KFold(n_splits=n_splits, shuffle=True, random_state=123)

    fold_numbers = np.zeros(len(X))
    oof_predictions_proba = np.zeros(len(X))
    oof_predictions_class = np.zeros(len(X))

    fold_results = []

    for fold_idx, (train_idx, val_idx) in enumerate(kfold.split(X)):
        print(f"\n{'=' * 70}")
        print(f"Fold {fold_idx + 1}/{n_splits}")
        print(f"{'=' * 70}")

        fold_numbers[val_idx] = fold_idx + 1

        X_train_fold = X.iloc[train_idx].reset_index(drop=True)
        X_val_fold = X.iloc[val_idx].reset_index(drop=True)
        y_train_fold = y.iloc[train_idx].reset_index(drop=True)
        y_val_fold = y.iloc[val_idx].reset_index(drop=True)

        X_train_fit, y_train_fit = _stratified_sample(
            X_train_fold,
            y_train_fold,
            max_samples=max_train_samples,
            seed=123 + fold_idx,
        )

        print(f"Training rows used: {len(X_train_fit):,} / {len(X_train_fold):,}")

        model_gam = ModelGAM()
        try:
            gam_model = model_gam.train(
                X_train_fit,
                y_train_fit,
                X_val_fold,
                y_val_fold,
                n_splines=n_splines,
                lam=lam,
            )

            X_val_prep = model_gam._prepare_data(X_val_fold, fit=False)
            y_pred_proba = gam_model.predict_proba(X_val_prep.values.astype(np.float32))
            y_pred_class = (y_pred_proba > 0.5).astype(int)

            oof_predictions_proba[val_idx] = y_pred_proba
            oof_predictions_class[val_idx] = y_pred_class

            roc_auc = metrics.roc_auc_score(y_val_fold, y_pred_proba)
            accuracy = metrics.accuracy_score(y_val_fold, y_pred_class)

            fold_results.append(
                {
                    "fold": fold_idx + 1,
                    "roc_auc": roc_auc,
                    "accuracy": accuracy,
                    "n_train_used": len(X_train_fit),
                    "n_train_full": len(train_idx),
                    "n_val": len(val_idx),
                }
            )

            print(f"Fold {fold_idx + 1} ROC-AUC: {roc_auc:.4f}")
            print(f"Fold {fold_idx + 1} Accuracy: {accuracy:.4f}")

        except Exception as e:
            print(f"Error in fold {fold_idx + 1}: {e}")
            oof_predictions_proba[val_idx] = 0.5
            oof_predictions_class[val_idx] = 0

    results_df = pd.DataFrame(fold_results)

    print(f"\n{'=' * 70}")
    print("Cross-Validation Summary")
    print(f"{'=' * 70}")
    if len(results_df) > 0:
        print(
            f"Mean ROC-AUC: {results_df['roc_auc'].mean():.4f} "
            f"(+/- {results_df['roc_auc'].std():.4f})"
        )
        print(
            f"Mean Accuracy: {results_df['accuracy'].mean():.4f} "
            f"(+/- {results_df['accuracy'].std():.4f})"
        )

        overall_roc_auc = metrics.roc_auc_score(y, oof_predictions_proba)
        print(f"\nOverall OOF ROC-AUC: {overall_roc_auc:.4f}")

    return fold_numbers, oof_predictions_proba, results_df


# Usage with your data
X = df_middle_gam.loc[:, model_features_class]
y = df_middle_gam["is_churn"]

print("Running GAM Cross-Validation...")
fold_numbers_gam, oof_pred_gam, results_gam = cross_validate_gam_with_oof(
    X,
    y,
    n_splits=5,
    n_splines=8,
    lam=0.8,
    max_train_samples=35000,
)

df_middle_gam["fold_number_gam"] = fold_numbers_gam.astype(int)
df_middle_gam["oof_prediction_gam"] = oof_pred_gam

Running GAM Cross-Validation...

======================================================================
Fold 1/5
======================================================================
Training rows used: 35,000 / 155,498
Fold 1 ROC-AUC: 0.6622
Fold 1 Accuracy: 0.8854

======================================================================
Fold 2/5
======================================================================
Training rows used: 35,000 / 155,498
Fold 2 ROC-AUC: 0.6599
Fold 2 Accuracy: 0.8858

======================================================================
Fold 3/5
======================================================================
Training rows used: 35,000 / 155,498
Fold 3 ROC-AUC: 0.6520
Fold 3 Accuracy: 0.8870

======================================================================
Fold 4/5
======================================================================
Training rows used: 35,000 / 155,499
Fold 4 ROC-AUC: 0.6575
Fold 4 Accuracy: 0.8810

======================================================================
Fold 5/5
======================================================================
Training rows used: 35,000 / 155,499
Fold 5 ROC-AUC: 0.6640
Fold 5 Accuracy: 0.8851

======================================================================
Cross-Validation Summary
======================================================================
Mean ROC-AUC: 0.6591 (+/- 0.0047)
Mean Accuracy: 0.8849 (+/- 0.0023)

Overall OOF ROC-AUC: 0.6590

In [129]:
import pygam

In [68]:
# Update narwhals to the latest version
!pip install --upgrade narwhals

# Or if that doesn't work, try reinstalling both packages
!pip install --upgrade glum narwhals

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: narwhals in c:\users\malosett\appdata\roaming\python\python311\site-packages (2.18.1)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: glum in c:\users\malosett\appdata\roaming\python\python311\site-packages (3.2.3)
Requirement already satisfied: narwhals in c:\users\malosett\appdata\roaming\python\python311\site-packages (2.18.1)
Requirement already satisfied: formulaic>=1.2.0 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from glum) (1.2.1)
Requirement already satisfied: joblib in c:\users\malosett\appdata\roaming\python\python311\site-packages (from glum) (1.3.2)
Requirement already satisfied: numexpr in c:\programdata\anaconda3\lib\site-packages (from glum) (2.8.7)
Requirement already satisfied: numpy>=1.24 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from glum) (2.4.4)
Requirement already satisfied: packaging in c:\users\malosett\appdata\roaming\python\python311\site-packages (from glum) (25.0)
Requirement already satisfied: pandas>=1.4 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from glum) (2.3.3)
Requirement already satisfied: pyarrow in c:\users\malosett\appdata\roaming\python\python311\site-packages (from glum) (23.0.1)
Requirement already satisfied: scikit-learn>=1.1.0 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from glum) (1.8.0)
Requirement already satisfied: scipy>=1.8.0 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from glum) (1.16.3)
Requirement already satisfied: tabmat>=4.1.5 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from glum) (4.2.1)
Requirement already satisfied: tqdm in c:\programdata\anaconda3\lib\site-packages (from glum) (4.65.0)
Requirement already satisfied: interface-meta>=1.2.0 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from formulaic>=1.2.0->glum) (1.3.0)
Requirement already satisfied: typing-extensions>=4.2.0 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from formulaic>=1.2.0->glum) (4.15.0)
Requirement already satisfied: wrapt>=1.0 in c:\programdata\anaconda3\lib\site-packages (from formulaic>=1.2.0->glum) (1.14.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas>=1.4->glum) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas>=1.4->glum) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas>=1.4->glum) (2023.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from scikit-learn>=1.1.0->glum) (3.6.0)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from tqdm->glum) (0.4.6)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.4->glum) (1.16.0)

In [130]:
df_middle_gam.columns

Index(['encoded_policy_number', 'age', 'bonus_malus_rating', 'distr_channel',
       'vehicle_type', 'ttm_claims', 'policy_count', 'risk_code',
       'vehicle_age', 'policy_tenure', 'policy_premium', 'prev_renewal_perc',
       'upcoming_premium', 'cur_renewal_perc', 'year', 'is_churn', 'U',
       'fold_number_gam', 'oof_prediction_gam'],
      dtype='object')

In [132]:
df_middle_gam.columns = ['id','X_age','X_bonus_malus_rating','X_distr_channel','X_vehicle_type','X_ttm_claims',
                         'X_policy_count','X_risk_code','X_vehicle_age','X_policy_tenure','X_policy_premium',
                         'X_prev_renewal_perc','X_upcoming_premium','X_cur_renewal_perc','X_year','1-Z','U',
                         'fold_number_gam','churn_prediction']

## Section 14 — GAM Output: Acceptance Probability

Post-CV steps for `df_middle_gam`:

1. Compute `Z = 1 − churn_prediction` (binary acceptance, where `churn_prediction = oof_prediction_gam`)  
2. Compute `prob_acceptance = 1 − churn_prediction`  
3. Rename columns to canonical names  

**Exported to:** `df_acceptance_gam_model_black_box.csv`

Same schema as the XGBoost and GLM acceptance files — the optimiser can swap between models with no interface change.

In [133]:
df_middle_gam['Z'] = 1 - df_middle_gam['1-Z'].astype(int)
df_middle_gam['prob_acceptance'] = 1 - df_middle_gam['churn_prediction']

In [134]:
df_middle_gam.columns

Index(['id', 'X_age', 'X_bonus_malus_rating', 'X_distr_channel',
       'X_vehicle_type', 'X_ttm_claims', 'X_policy_count', 'X_risk_code',
       'X_vehicle_age', 'X_policy_tenure', 'X_policy_premium',
       'X_prev_renewal_perc', 'X_upcoming_premium', 'X_cur_renewal_perc',
       'X_year', '1-Z', 'U', 'fold_number_gam', 'churn_prediction', 'Z',
       'prob_acceptance'],
      dtype='object')

In [135]:
df_middle_gam.loc[:, ['id', 'X_age','X_bonus_malus_rating','X_distr_channel','X_vehicle_type','X_ttm_claims','X_policy_count','X_risk_code','X_vehicle_age',
                           'X_policy_tenure','X_policy_premium', 'U','prob_acceptance','Z']].to_csv('df_acceptance_gam_model_black_box.csv',sep=';')

In [136]:
df_middle_gam.columns

Index(['id', 'X_age', 'X_bonus_malus_rating', 'X_distr_channel',
       'X_vehicle_type', 'X_ttm_claims', 'X_policy_count', 'X_risk_code',
       'X_vehicle_age', 'X_policy_tenure', 'X_policy_premium',
       'X_prev_renewal_perc', 'X_upcoming_premium', 'X_cur_renewal_perc',
       'X_year', '1-Z', 'U', 'fold_number_gam', 'churn_prediction', 'Z',
       'prob_acceptance'],
      dtype='object')

In [137]:
from sklearn import metrics
import pandas as pd
import numpy as np
from pygam import LogisticGAM, s, f, te
from sklearn.model_selection import KFold, train_test_split
import optuna
from optuna.trial import Trial

class ModelGAM():
    """
    GAM Classifier for Churn Prediction
    GAMs are interpretable and can capture non-linear relationships
    """
    
    def objective(self, trial: Trial, X_train: pd.DataFrame, y_train: pd.Series, 
                  X_val: pd.DataFrame, y_val: pd.Series) -> float:
        """
        Optuna objective for hyperparameter tuning
        """
        # Suggest hyperparameters
        n_splines = trial.suggest_int("n_splines", 10, 50)
        lam = trial.suggest_float("lam", 0.01, 100, log=True)
        
        # Build GAM formula
        # Use splines for continuous features and factors for categorical
        numeric_cols = X_train.select_dtypes(include=[np.number]).columns
        categorical_cols = X_train.select_dtypes(include=['object', 'category']).columns
        
        # Create formula
        formula_terms = []
        for i, col in enumerate(numeric_cols):
            formula_terms.append(s(i, n_splines=n_splines, lam=lam))
        
        # For categorical, use factor terms
        cat_offset = len(numeric_cols)
        for i, col in enumerate(categorical_cols):
            formula_terms.append(f(cat_offset + i, lam=lam))
        
        # Combine numeric and categorical data
        X_train_prepared = self._prepare_data(X_train)
        X_val_prepared = self._prepare_data(X_val)
        
        # Fit model
        try:
            gam_terms = formula_terms[0]
            for term in formula_terms[1:]:
                gam_terms += term
            gam = LogisticGAM(terms=gam_terms, max_iter=100)
            gam.gridsearch(X_train_prepared.values, y_train.values, progress=False)
            
            # Predict
            y_score = gam.predict_proba(X_val_prepared.values)
            roc_auc = metrics.roc_auc_score(y_true=y_val, y_score=y_score)
            
            return roc_auc
        except Exception as e:
            print(f"Error in GAM fitting: {e}")
            return 0.5  # Return baseline score on error
    
    def _prepare_data(self, X: pd.DataFrame) -> pd.DataFrame:
        """
        Prepare data for GAM
        """
        X_prep = X.copy()
        
        # Encode categorical variables as numeric
        categorical_cols = X_prep.select_dtypes(include=['object', 'category']).columns
        if len(categorical_cols) > 0:
            from sklearn.preprocessing import LabelEncoder
            for col in categorical_cols:
                le = LabelEncoder()
                X_prep[col] = le.fit_transform(X_prep[col].astype(str))
        
        return X_prep
    
    def tuning(self, X_train: pd.DataFrame, y_train: pd.Series, 
               X_val: pd.DataFrame, y_val: pd.Series, n_trials: int) -> dict:
        """
        Hyperparameter tuning using Optuna
        """
        study = optuna.create_study(study_name='GAM', direction='maximize')
        study.optimize(lambda trial: self.objective(trial, X_train, y_train, X_val, y_val), 
                      n_trials=n_trials, show_progress_bar=True)
        best_params = study.best_params
        return best_params
    
    def train(self, X_train: pd.DataFrame, y_train: pd.Series, 
              X_val: pd.DataFrame, y_val: pd.Series, best_params: dict):
        """
        Train final GAM model with best parameters
        """
        n_splines = best_params.get('n_splines', 25)
        lam = best_params.get('lam', 0.6)
        
        # Prepare data
        X_train_prep = self._prepare_data(X_train)
        X_val_prep = self._prepare_data(X_val)
        
        # Build formula
        numeric_cols = X_train_prep.select_dtypes(include=[np.number]).columns
        formula_terms = [s(i, n_splines=n_splines, lam=lam) for i in range(len(numeric_cols))]
        gam_terms = formula_terms[0]
        for term in formula_terms[1:]:
            gam_terms += term
        
        # Fit model
        gam = LogisticGAM(terms=gam_terms, max_iter=100)
        gam.gridsearch(X_train_prep.values, y_train.values, progress=False)
        
        return gam


# Cross-validation function for GAM
def cross_validate_gam_with_oof(X, y, n_splits=5, n_trials=20):
    """
    Cross-validation with OOF predictions for GAM
    """
    kfold = KFold(n_splits=n_splits, shuffle=True, random_state=123)
    
    fold_numbers = np.zeros(len(X))
    oof_predictions_proba = np.zeros(len(X))
    oof_predictions_class = np.zeros(len(X))
    
    fold_results = []
    best_params_per_fold = []
    
    for fold_idx, (train_idx, val_idx) in enumerate(kfold.split(X)):
        print(f"\n{'='*70}")
        print(f"Fold {fold_idx + 1}/{n_splits}")
        print(f"{'='*70}")
        
        fold_numbers[val_idx] = fold_idx + 1
        
        X_train_fold = X.iloc[train_idx]
        X_val_fold = X.iloc[val_idx]
        y_train_fold = y.iloc[train_idx]
        y_val_fold = y.iloc[val_idx]
        
        # Split for tuning
        X_train_tune, X_val_tune, y_train_tune, y_val_tune = train_test_split(
            X_train_fold, y_train_fold, test_size=0.2, random_state=123, stratify=y_train_fold
        )
        
        # Tune
        model_gam = ModelGAM()
        best_params = model_gam.tuning(
            X_train_tune, y_train_tune,
            X_val_tune, y_val_tune,
            n_trials=n_trials
        )
        
        print(f"Best params: {best_params}")
        best_params_per_fold.append(best_params)
        
        # Train
        final_model = model_gam.train(
            X_train_fold, y_train_fold,
            X_val_fold, y_val_fold,
            best_params
        )
        
        # Predict
        X_val_prep = model_gam._prepare_data(X_val_fold)
        y_pred_proba = final_model.predict_proba(X_val_prep.values)
        y_pred_class = (y_pred_proba > 0.5).astype(int)
        
        oof_predictions_proba[val_idx] = y_pred_proba
        oof_predictions_class[val_idx] = y_pred_class
        
        # Metrics
        roc_auc = metrics.roc_auc_score(y_val_fold, y_pred_proba)
        accuracy = metrics.accuracy_score(y_val_fold, y_pred_class)
        
        fold_results.append({
            'fold': fold_idx + 1,
            'roc_auc': roc_auc,
            'accuracy': accuracy,
            'n_train': len(train_idx),
            'n_val': len(val_idx)
        })
        
        print(f"Fold {fold_idx + 1} ROC-AUC: {roc_auc:.4f}")
        print(f"Fold {fold_idx + 1} Accuracy: {accuracy:.4f}")
    
    results_df = pd.DataFrame(fold_results)
    
    print(f"\n{'='*70}")
    print("Cross-Validation Summary")
    print(f"{'='*70}")
    print(f"Mean ROC-AUC: {results_df['roc_auc'].mean():.4f} (+/- {results_df['roc_auc'].std():.4f})")
    print(f"Mean Accuracy: {results_df['accuracy'].mean():.4f} (+/- {results_df['accuracy'].std():.4f})")
    
    overall_roc_auc = metrics.roc_auc_score(y, oof_predictions_proba)
    print(f"\nOverall OOF ROC-AUC: {overall_roc_auc:.4f}")
    
    return fold_numbers, oof_predictions_proba, results_df, best_params_per_fold

In [142]:
df_middle_glm_gam = filter_middle_advanced(
    df_sub,
    numeric_filters={
        'age': {'multiplier': 1.5, 'method': 'iqr'},
        'policy_premium': {'multiplier': 2.0, 'method': 'iqr'},
        'upcoming_premium':{'multiplier':2.0,'method':'iqr'},
        'vehicle_age': {'method': 'percentile', 'lower_q': 0.05, 'upper_q': 0.95},
        'cur_renewal_perc':{'method': 'percentile', 'lower_q': 0.05, 'upper_q': 0.95}
    },
    categorical_filters={
        'distr_channel': {'max_categories':12},
        'risk_code': {'max_categories': 6},
        'vehicle_type': {'max_categories': 8}  # explicit list
    },
    keep_id_cols=['encoded_policy_number']
)

age: [8.50, 100.50]
policy_premium: [-14.06, 444.14]
upcoming_premium: [-15.07, 480.13]
vehicle_age: [4.00, 31.00]
cur_renewal_perc: [-0.02, 0.11]
distr_channel: Kept 12 categories
risk_code: Kept 6 categories
vehicle_type: Kept 8 categories

Total: 463400 → 194373 rows

In [143]:
from sklearn.preprocessing import LabelEncoder
for cat in cat_cols:
    le = LabelEncoder()
    le.fit(df_middle_glm_gam[cat])
    df_middle_glm_gam[cat] = le.transform(df_middle_glm_gam[cat])

In [144]:
df_middle_glm_gam['U'] = (df_middle_glm_gam['upcoming_premium'] - df_middle_glm_gam['policy_premium']) / df_middle_glm_gam['policy_premium']

In [145]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression


class ModelGLM():
    """GLM replacement using sklearn Logistic Regression."""

    def __init__(self):
        self.categorical_cols = []
        self.numeric_cols = []

    def _build_model(self, C: float) -> Pipeline:
        numeric_transformer = Pipeline(steps=[
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler()),
        ])

        categorical_transformer = Pipeline(steps=[
            ("imputer", SimpleImputer(strategy="most_frequent")),
            ("onehot", OneHotEncoder(handle_unknown="ignore")),
        ])

        preprocessor = ColumnTransformer(
            transformers=[
                ("num", numeric_transformer, self.numeric_cols),
                ("cat", categorical_transformer, self.categorical_cols),
            ],
            remainder="drop",
        )

        clf = LogisticRegression(
            C=C,
            max_iter=1000,
            solver="lbfgs",
            random_state=123,
        )

        return Pipeline(steps=[
            ("preprocessor", preprocessor),
            ("classifier", clf),
        ])

    def objective(self, trial, X_train, y_train, X_val, y_val):
        C = trial.suggest_float("C", 1e-3, 100.0, log=True)

        self.categorical_cols = X_train.select_dtypes(include=["object", "category"]).columns.tolist()
        self.numeric_cols = [c for c in X_train.columns if c not in self.categorical_cols]

        model = self._build_model(C=C)
        model.fit(X_train, y_train)
        y_score = model.predict_proba(X_val)[:, 1]
        return metrics.roc_auc_score(y_true=y_val, y_score=y_score)

    def tuning(self, X_train, y_train, X_val, y_val, n_trials):
        study = optuna.create_study(study_name="LogisticRegression", direction="maximize")
        study.optimize(
            lambda trial: self.objective(trial, X_train, y_train, X_val, y_val),
            n_trials=n_trials,
            show_progress_bar=True,
        )
        return study.best_params

    def train(self, X_train, y_train, X_val, y_val, best_params):
        C = best_params.get("C", 1.0)
        self.categorical_cols = X_train.select_dtypes(include=["object", "category"]).columns.tolist()
        self.numeric_cols = [c for c in X_train.columns if c not in self.categorical_cols]

        model = self._build_model(C=C)
        model.fit(X_train, y_train)
        return model

In [392]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import KFold
from sklearn import metrics
import pandas as pd
import numpy as np


class ModelLinearRegressor:
    """Baseline linear regression model."""

    def train(self, X_train: pd.DataFrame, y_train: pd.Series):
        model = LinearRegression()
        model.fit(X_train, y_train)
        return model


def cross_validate_linear_regression(X, y, n_splits=5):
    """Run Linear Regression with KFold cross-validation."""
    kfold = KFold(n_splits=n_splits, shuffle=True, random_state=123)

    lin_fold_numbers = np.zeros(len(X))
    lin_oof = np.zeros(len(X))
    lin_results = []

    for fold_idx, (train_idx, val_idx) in enumerate(kfold.split(X), 1):
        print(f"\n{'='*70}")
        print(f"Fold {fold_idx}/{n_splits}")
        print(f"{'='*70}")

        X_train_fold = X.iloc[train_idx].reset_index(drop=True)
        X_val_fold = X.iloc[val_idx].reset_index(drop=True)
        y_train_fold = y.iloc[train_idx].reset_index(drop=True)
        y_val_fold = y.iloc[val_idx].reset_index(drop=True)

        lin_fold_numbers[val_idx] = fold_idx

        # Linear regression
        linear_model = ModelLinearRegressor().train(X_train_fold, y_train_fold)
        lin_pred = linear_model.predict(X_val_fold)
        lin_oof[val_idx] = lin_pred

        lin_mae = metrics.mean_absolute_error(y_val_fold, lin_pred)
        lin_rmse = np.sqrt(metrics.mean_squared_error(y_val_fold, lin_pred))
        lin_r2 = metrics.r2_score(y_val_fold, lin_pred)

        lin_results.append({
            "fold": fold_idx,
            "model": "LinearRegression",
            "mae": lin_mae,
            "rmse": lin_rmse,
            "r2": lin_r2,
            "n_train": len(train_idx),
            "n_val": len(val_idx),
        })

        print(f"LinearRegression -> MAE: {lin_mae:.4f}, RMSE: {lin_rmse:.4f}, R2: {lin_r2:.4f}")

    lin_df = pd.DataFrame(lin_results)

    print(f"\n{'='*70}")
    print("Overall OOF Metrics")
    print(f"{'='*70}")

    lin_oof_mae = metrics.mean_absolute_error(y, lin_oof)
    lin_oof_rmse = np.sqrt(metrics.mean_squared_error(y, lin_oof))
    lin_oof_r2 = metrics.r2_score(y, lin_oof)

    print(f"LinearRegression OOF -> MAE: {lin_oof_mae:.4f}, RMSE: {lin_oof_rmse:.4f}, R2: {lin_oof_r2:.4f}")

    linear_results = {
        "fold_numbers": lin_fold_numbers,
        "oof_predictions": lin_oof,
        "results_df": lin_df,
        "oof_metrics": {"mae": lin_oof_mae, "rmse": lin_oof_rmse, "r2": lin_oof_r2},
    }

    return linear_results

In [395]:
df_middle_reg_linear

,encoded_policy_number,X_age,X_bonus_malus_rating,X_distr_channel,X_vehicle_type,X_ttm_claims,X_policy_count,X_risk_code,X_vehicle_age,X_policy_tenure,X_policy_premium,X_prev_renewal_perc,X_upcoming_premium,X_cur_renewal_perc,year,is_churn
7,5,93.0,45.0,5,7,0,1,0,24.0,24.0,175.7725,0.003637,197.41,0.098601,7,False
16,85,78.0,45.0,5,0,0,2,0,5.0,24.0,180.8686,0.003824,200.23,0.082852,7,False
24,93,78.0,45.0,5,1,0,1,0,21.0,24.0,165.6403,0.003731,181.69,0.072973,7,False
32,119,49.0,45.0,5,1,0,1,0,19.0,24.0,171.3347,-0.005503,187.99,0.073266,7,False
118,395,49.0,45.0,2,2,0,4,0,16.0,24.0,170.0981,-0.005223,187.45,0.077961,7,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3370174,5732129,68.0,45.0,4,2,0,1,2,9.0,9.0,345.4078,-0.023380,367.06,0.042169,7,False
3370323,5732370,81.0,45.0,4,4,0,5,0,20.0,10.0,234.6113,-0.040569,255.09,0.066399,7,False
3370329,5732373,58.0,45.0,4,7,0,3,0,30.0,8.0,174.1869,-0.074677,189.35,0.061103,7,True
3370407,5732452,89.0,45.0,4,1,0,2,0,10.0,23.0,238.8796,-0.060040,259.78,0.064402,7,True
3370452,5732508,54.0,45.0,7,0,1,1,1,22.0,21.0,220.5798,-0.014601,239.83,0.066294,7,False

## Section 15 — Linear Regression: Policy Premium (5-Fold OOF)

### `ModelLinearRegressor`
Plain **sklearn `LinearRegression`** with no hyperparameters — serves as the interpretable baseline for premium prediction.

### `cross_validate_linear_regression`
- 5-fold KFold with no tuning overhead
- Reports MAE, RMSE, R² per fold and overall OOF metrics
- Stores OOF predictions as `linear_reg_oof_prediction` → renamed to `Y_hat`

**Dataset:** `df_middle_reg_linear` — same filtering thresholds as other datasets, with label-encoded categoricals.  
`U = (upcoming_premium − Y) / Y` is computed after column renaming.

**Exported to:** `df_exp_financial_loss_linear_black_box.csv`  
Schema: `id, features, Y (premium), U, Y_hat (predicted premium)`

In [396]:
df_middle_reg_linear = filter_middle_advanced(
    df_sub,
    numeric_filters={
        'X_age': {'multiplier': 1.5, 'method': 'iqr'},
        'X_policy_premium': {'multiplier': 2.0, 'method': 'iqr'},
        'X_upcoming_premium':{'multiplier':2.0,'method':'iqr'},
        'X_vehicle_age': {'method': 'percentile', 'lower_q': 0.05, 'upper_q': 0.95},
        'X_cur_renewal_perc':{'method': 'percentile', 'lower_q': 0.05, 'upper_q': 0.95}
    },
    categorical_filters={
        'X_distr_channel': {'max_categories':12},
        'X_risk_code': {'max_categories': 6},
        'X_vehicle_type': {'max_categories': 8}  # explicit list
    },
    keep_id_cols=['encoded_policy_number']
)

X_age: [8.50, 100.50]
X_policy_premium: [-14.06, 444.14]
X_upcoming_premium: [-15.07, 480.13]
X_vehicle_age: [4.00, 31.00]
X_cur_renewal_perc: [-0.02, 0.11]
X_distr_channel: Kept 12 categories
X_risk_code: Kept 6 categories
X_vehicle_type: Kept 8 categories

Total: 463400 → 194373 rows

In [397]:
from sklearn.preprocessing import LabelEncoder
for cat in cat_cols:
    le = LabelEncoder()
    le.fit(df_middle_reg_linear[cat])
    df_middle_reg_linear[cat] = le.transform(df_middle_reg_linear[cat])

In [398]:
model_features_reg

['X_age',
 'X_bonus_malus_rating',
 'X_distr_channel',
 'X_vehicle_type',
 'X_ttm_claims',
 'X_policy_count',
 'X_risk_code',
 'X_vehicle_age',
 'X_policy_tenure']

In [400]:
# Regression setup (Linear Regression only)
X_reg = df_middle_reg_linear.loc[:,model_features_reg]
y_reg = df_middle_reg_linear['X_policy_premium']

linear_results = cross_validate_linear_regression(
    X_reg, y_reg, n_splits=5
)

# Save OOF outputs for downstream analysis
df_middle_reg_linear['linear_reg_oof_prediction'] = linear_results['oof_predictions']

======================================================================
Fold 1/5
======================================================================
LinearRegression -> MAE: 36.4032, RMSE: 51.5802, R2: 0.2525

======================================================================
Fold 2/5
======================================================================
LinearRegression -> MAE: 36.0190, RMSE: 50.7388, R2: 0.2541

======================================================================
Fold 3/5
======================================================================
LinearRegression -> MAE: 36.0655, RMSE: 50.9690, R2: 0.2527

======================================================================
Fold 4/5
======================================================================
LinearRegression -> MAE: 36.0176, RMSE: 50.6448, R2: 0.2541

======================================================================
Fold 5/5
======================================================================
LinearRegression -> MAE: 36.0272, RMSE: 50.6479, R2: 0.2555

======================================================================
Overall OOF Metrics
======================================================================
LinearRegression OOF -> MAE: 36.1065, RMSE: 50.9174, R2: 0.2538

In [406]:
df_middle_reg_linear.columns = ['id','X_age', 'X_bonus_malus_rating', 'X_distr_channel',
       'X_vehicle_type', 'X_ttm_claims', 'X_policy_count', 'X_risk_code',
       'X_vehicle_age', 'X_policy_tenure', 'Y', 'X_prev_renewal_perc',
       'X_upcoming_premium', 'X_cur_renewal_perc', 'X_year', '1-Z','Y_hat']

In [409]:
df_middle_reg_linear['U'] = (df_middle_reg_linear['X_upcoming_premium'] - df_middle_reg_linear['Y']) / df_middle_reg_linear['Y']

In [411]:
df_middle_reg_linear.loc[:,['id', 'X_age','X_bonus_malus_rating','X_distr_channel','X_vehicle_type','X_ttm_claims','X_policy_count','X_risk_code','X_vehicle_age','X_policy_tenure',
                     'Y','U','Y_hat']].to_csv('df_exp_financial_loss_linear_black_box.csv',sep=';')

In [412]:
df_middle.columns

Index(['id', 'X_age', 'X_bonus_malus_rating', 'X_distr_channel',
       'X_vehicle_type', 'X_ttm_claims', 'X_policy_count', 'X_risk_code',
       'X_vehicle_age', 'X_policy_tenure', 'Y', 'X_prev_renewal_perc',
       'X_upcoming_premium', 'X_cur_renewal_perc', 'X_year', '1-Z', 'U',
       'fold_number', 'Y_hat', 'Y_residual', 'Y_absolute_error'],
      dtype='object')

## Section 16 — Model Serialisation

Trained models are persisted as **pickle files** in the `artifacts/` directory for reuse without retraining.

### Saved models

| File | Model | Task |
|---|---|---|
| `artifacts/xgb_classifier_churn.pkl` | XGBoost classifier | Churn probability |
| `artifacts/xgb_regressor_policy_premium.pkl` | XGBoost regressor | Policy premium |
| `artifacts/glm_logistic_churn.pkl` | Logistic Regression (GLM) | Churn probability |
| `artifacts/linear_regression_policy_premium.pkl` | Linear Regression | Policy premium |

Models are loaded and retrained only if not already present in the kernel namespace (`globals()` check), enabling fast re-runs of downstream cells without full retraining.

> **Note:** Feature order must be preserved when loading models for inference.  
> Use `model.feature_names_in_` (available on sklearn estimators) to validate column alignment.

In [413]:
import pickle
from pathlib import Path

import numpy as np
import pandas as pd
import xgboost as xgb
from sklearn.model_selection import train_test_split


ARTIFACTS_DIR = Path("artifacts")
ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)

CLS_PICKLE_PATH = ARTIFACTS_DIR / "xgb_classifier.pkl"
REG_PICKLE_PATH = ARTIFACTS_DIR / "xgb_regressor.pkl"


def _is_xgb_fitted(model) -> bool:
    try:
        _ = model.get_booster()
        return True
    except Exception:
        return False


# ---------------------------
# 1) Build / retrieve classifier
# ---------------------------
if "xgb_classifier_model" in globals() and isinstance(globals()["xgb_classifier_model"], xgb.XGBClassifier):
    xgb_classifier_model = globals()["xgb_classifier_model"]
else:
    X_cls = df_middle_class.loc[:, model_features_class].copy()
    y_cls = df_middle_class["1-Z"].astype(int).copy()

    Xc_train, Xc_val, yc_train, yc_val = train_test_split(
        X_cls,
        y_cls,
        test_size=0.2,
        random_state=123,
        stratify=y_cls,
    )

    cls_params = {
        "random_state": 123,
        "n_estimators": 250,
        "max_depth": 4,
        "learning_rate": 0.05,
        "subsample": 0.9,
        "colsample_bytree": 0.9,
        "eval_metric": "logloss",
        "enable_categorical": True,
        "early_stopping_rounds": 20,
    }
    xgb_classifier_model = xgb.XGBClassifier(**cls_params)
    xgb_classifier_model.fit(Xc_train, yc_train, eval_set=[(Xc_val, yc_val)], verbose=0)


# ---------------------------
# 2) Build / retrieve regressor
# ---------------------------
if "xgb_model" in globals() and isinstance(globals()["xgb_model"], xgb.XGBRegressor):
    xgb_regressor_model = globals()["xgb_model"]
else:
    xgb_regressor_model = None

# If the existing regressor is not fitted, fit one now.
if xgb_regressor_model is None or not _is_xgb_fitted(xgb_regressor_model):
    X_reg = df_middle.loc[:, model_features_reg].copy()
    y_reg_local = df_middle["Y"].copy()

    Xr_train, Xr_val, yr_train, yr_val = train_test_split(
        X_reg,
        y_reg_local,
        test_size=0.2,
        random_state=123,
    )

    reg_params = {
        "random_state": 123,
        "n_estimators": 300,
        "max_depth": 4,
        "learning_rate": 0.05,
        "subsample": 0.9,
        "colsample_bytree": 0.9,
        "objective": "reg:squarederror",
        "enable_categorical": True,
        "early_stopping_rounds": 20,
    }
    xgb_regressor_model = xgb.XGBRegressor(**reg_params)
    xgb_regressor_model.fit(Xr_train, yr_train, eval_set=[(Xr_val, yr_val)], verbose=0)


# ---------------------------
# 3) Save to pickle
# ---------------------------
with open(CLS_PICKLE_PATH, "wb") as f:
    pickle.dump(xgb_classifier_model, f)

with open(REG_PICKLE_PATH, "wb") as f:
    pickle.dump(xgb_regressor_model, f)

print(f"Saved classifier to: {CLS_PICKLE_PATH.resolve()}")
print(f"Saved regressor to:  {REG_PICKLE_PATH.resolve()}")

Saved classifier to: C:\Users\malosett\OneDrive - Assicurazioni Generali S.p.A\coding\pricing_optim\artifacts\xgb_classifier.pkl
Saved regressor to:  C:\Users\malosett\OneDrive - Assicurazioni Generali S.p.A\coding\pricing_optim\artifacts\xgb_regressor.pkl

In [416]:
model_features_class

['X_age',
 'X_bonus_malus_rating',
 'X_distr_channel',
 'X_vehicle_type',
 'X_ttm_claims',
 'X_policy_count',
 'X_risk_code',
 'X_vehicle_age',
 'X_policy_tenure',
 'X_policy_premium',
 'U']

In [417]:
model_features_reg

['X_age',
 'X_bonus_malus_rating',
 'X_distr_channel',
 'X_vehicle_type',
 'X_ttm_claims',
 'X_policy_count',
 'X_risk_code',
 'X_vehicle_age',
 'X_policy_tenure']

## Section 17 — Single-Record Inference (Smoke Test)

Loads the serialised XGBoost classifier and regressor from `artifacts/` and runs a single-record prediction to verify the pickle round-trip is correct.

**Checks performed:**
- Classifier: outputs churn probability and hard class label
- Regressor: outputs predicted policy premium
- Both: column alignment against `feature_names_in_` to catch any schema mismatch

This cell is intended as a **quick sanity check** before handing off models to production or the optimisation module.

## Section 18 — Save All Four Models

Final cell: trains and serialises all four models in a single block:
1. **XGBClassifier** — churn (on `df_middle_class`)  
2. **XGBRegressor** — premium (on `df_middle`)  
3. **GLM logistic** — churn (on `df_middle_glm`); trained with `ModelGLM` at `C=1.0`  
4. **LinearRegression** — premium (on `df_middle_reg_linear`)  

Each model is written to `artifacts/` independently so individual files can be updated without replacing the full set.

In [414]:
import pickle
from pathlib import Path

import pandas as pd


ARTIFACTS_DIR = Path("artifacts")
CLS_PICKLE_PATH = ARTIFACTS_DIR / "xgb_classifier.pkl"
REG_PICKLE_PATH = ARTIFACTS_DIR / "xgb_regressor.pkl"


# 1) Load models from pickle
with open(CLS_PICKLE_PATH, "rb") as f:
    loaded_xgb_classifier = pickle.load(f)

with open(REG_PICKLE_PATH, "rb") as f:
    loaded_xgb_regressor = pickle.load(f)


# 2) Build a single-record input for each model
single_cls_record = df_middle_class.loc[:, model_features_class].iloc[[0]].copy()
single_reg_record = df_middle.loc[:, model_features_reg].iloc[[0]].copy()

# Align columns in case of any ordering mismatch
if hasattr(loaded_xgb_classifier, "feature_names_in_"):
    single_cls_record = single_cls_record.reindex(columns=list(loaded_xgb_classifier.feature_names_in_))
if hasattr(loaded_xgb_regressor, "feature_names_in_"):
    single_reg_record = single_reg_record.reindex(columns=list(loaded_xgb_regressor.feature_names_in_))


# 3) Inference on one record
cls_prob = float(loaded_xgb_classifier.predict_proba(single_cls_record)[:, 1][0])
cls_pred = int(loaded_xgb_classifier.predict(single_cls_record)[0])
reg_pred = float(loaded_xgb_regressor.predict(single_reg_record)[0])

print("Single-record classifier inference:")
print(f"  Predicted churn probability: {cls_prob:.6f}")
print(f"  Predicted churn class:       {cls_pred}")

print("\nSingle-record regressor inference:")
print(f"  Predicted premium:           {reg_pred:.6f}")

print("\nInput record used for classifier:")
print(single_cls_record)

print("\nInput record used for regressor:")
print(single_reg_record)

Single-record classifier inference:
  Predicted churn probability: 0.157302
  Predicted churn class:       0

Single-record regressor inference:
  Predicted premium:           201.582108

Input record used for classifier:
   X_age  X_bonus_malus_rating  X_distr_channel  X_vehicle_type  X_ttm_claims  \
7   93.0                  45.0                5               7             0

   X_policy_count  X_risk_code  X_vehicle_age  X_policy_tenure  \
7               1            0           24.0             24.0

   X_policy_premium         U
7          175.7725  1.123099

Input record used for regressor:
   X_age  X_bonus_malus_rating  X_distr_channel  X_vehicle_type  X_ttm_claims  \
7   93.0                  45.0                5               7             0

   X_policy_count  X_risk_code  X_vehicle_age  X_policy_tenure
7               1            0           24.0             24.0

In [424]:
df_middle_reg.columns

Index(['encoded_policy_number', 'X_age', 'X_bonus_malus_rating',
       'X_distr_channel', 'X_vehicle_type', 'X_ttm_claims', 'X_policy_count',
       'X_risk_code', 'X_vehicle_age', 'X_policy_tenure', 'X_policy_premium',
       'X_prev_renewal_perc', 'X_upcoming_premium', 'X_cur_renewal_perc',
       'year', 'is_churn', 'U'],
      dtype='object')

In [425]:
# Save all requested models as pickle:
# 1) XGBClassifier (churn)
# 2) XGBRegressor (policy_premium)
# 3) GLM logistic model (churn)
# 4) Linear model (policy_premium)

import pickle
from pathlib import Path

import numpy as np
import pandas as pd
import xgboost as xgb
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split


ARTIFACTS_DIR = Path("artifacts")
ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)

PATH_XGB_CLASSIFIER = ARTIFACTS_DIR / "xgb_classifier_churn.pkl"
PATH_XGB_REGRESSOR = ARTIFACTS_DIR / "xgb_regressor_policy_premium.pkl"
PATH_GLM_LOGISTIC = ARTIFACTS_DIR / "glm_logistic_churn.pkl"
PATH_LINEAR_MODEL = ARTIFACTS_DIR / "linear_regression_policy_premium.pkl"


def _to_xgb_compatible(df: pd.DataFrame) -> pd.DataFrame:
    df2 = df.copy()
    obj_cols = df2.select_dtypes(include=["object"]).columns
    for col in obj_cols:
        df2[col] = df2[col].astype("category")
    return df2


def _is_fitted_xgb(model) -> bool:
    try:
        _ = model.get_booster()
        return True
    except Exception:
        return False


# ----------------------------
# XGB Classifier (churn)
# ----------------------------
X_cls = df_middle_class.loc[:, model_features_class].copy()
y_cls = df_middle_class["1-Z"].astype(int).copy()
X_cls = _to_xgb_compatible(X_cls)

if "xgb_classifier_model" in globals() and isinstance(globals()["xgb_classifier_model"], xgb.XGBClassifier) and _is_fitted_xgb(globals()["xgb_classifier_model"]):
    xgb_classifier_model = globals()["xgb_classifier_model"]
else:
    Xc_train, Xc_val, yc_train, yc_val = train_test_split(
        X_cls, y_cls, test_size=0.2, random_state=123, stratify=y_cls
    )
    xgb_classifier_model = xgb.XGBClassifier(
        n_estimators=300,
        learning_rate=0.05,
        max_depth=4,
        subsample=0.9,
        colsample_bytree=0.9,
        eval_metric="logloss",
        random_state=123,
        enable_categorical=True,
        early_stopping_rounds=20,
    )
    xgb_classifier_model.fit(Xc_train, yc_train, eval_set=[(Xc_val, yc_val)], verbose=0)


# ----------------------------
# XGB Regressor (policy_premium)
# ----------------------------
X_reg = df_middle.loc[:, model_features_reg].copy()
y_reg_local = df_middle["Y"].copy()
X_reg = _to_xgb_compatible(X_reg)

if "xgb_model" in globals() and isinstance(globals()["xgb_model"], xgb.XGBRegressor) and _is_fitted_xgb(globals()["xgb_model"]):
    xgb_regressor_model = globals()["xgb_model"]
else:
    Xr_train, Xr_val, yr_train, yr_val = train_test_split(
        X_reg, y_reg_local, test_size=0.2, random_state=123
    )
    xgb_regressor_model = xgb.XGBRegressor(
        n_estimators=300,
        learning_rate=0.05,
        max_depth=4,
        subsample=0.9,
        colsample_bytree=0.9,
        objective="reg:squarederror",
        random_state=123,
        enable_categorical=True,
        early_stopping_rounds=20,
    )
    xgb_regressor_model.fit(Xr_train, yr_train, eval_set=[(Xr_val, yr_val)], verbose=0)


# ----------------------------
# GLM logistic model (churn)
# ----------------------------
X_glm = df_middle_glm.loc[:, model_features_class].copy()
y_glm = df_middle_glm["1-Z"].astype(int).copy()

Xg_train, Xg_val, yg_train, yg_val = train_test_split(
    X_glm, y_glm, test_size=0.2, random_state=123, stratify=y_glm
)

glm_model_obj = ModelGLM()
glm_logistic_model = glm_model_obj.train(
    Xg_train,
    yg_train,
    Xg_val,
    yg_val,
    {"C": 1.0},
)


# ----------------------------
# Linear model (policy_premium)
# ----------------------------
if "df_middle_reg" in globals():
    X_lin = df_middle_reg_linear.loc[:, model_features_reg].copy()
    y_lin = df_middle_reg_linear["Y"].copy()
else:
    X_lin = df_middle.loc[:, model_features_reg].copy()
    y_lin = df_middle["Y"].copy()

linear_model = LinearRegression()
linear_model.fit(X_lin, y_lin)


# ----------------------------
# Save all models
# ----------------------------
with open(PATH_XGB_CLASSIFIER, "wb") as f:
    pickle.dump(xgb_classifier_model, f)

with open(PATH_XGB_REGRESSOR, "wb") as f:
    pickle.dump(xgb_regressor_model, f)

with open(PATH_GLM_LOGISTIC, "wb") as f:
    pickle.dump(glm_logistic_model, f)

with open(PATH_LINEAR_MODEL, "wb") as f:
    pickle.dump(linear_model, f)

print(f"Saved: {PATH_XGB_CLASSIFIER.resolve()}")
print(f"Saved: {PATH_XGB_REGRESSOR.resolve()}")
print(f"Saved: {PATH_GLM_LOGISTIC.resolve()}")
print(f"Saved: {PATH_LINEAR_MODEL.resolve()}")

Saved: C:\Users\malosett\OneDrive - Assicurazioni Generali S.p.A\coding\pricing_optim\artifacts\xgb_classifier_churn.pkl
Saved: C:\Users\malosett\OneDrive - Assicurazioni Generali S.p.A\coding\pricing_optim\artifacts\xgb_regressor_policy_premium.pkl
Saved: C:\Users\malosett\OneDrive - Assicurazioni Generali S.p.A\coding\pricing_optim\artifacts\glm_logistic_churn.pkl
Saved: C:\Users\malosett\OneDrive - Assicurazioni Generali S.p.A\coding\pricing_optim\artifacts\linear_regression_policy_premium.pkl