# Pricing Optimisation — Acceptance Probability & Expected Financial Loss

## Purpose
This notebook implements the **black-box model generation pipeline** used downstream by the pricing optimisation module.  
It produces four output CSV files consumed by the optimiser:

| Output file | Content | Model source |
|---|---|---|
| `df_acceptance_xgb_black_box.csv` | Acceptance probability per policy | XGBoost classifier |
| `df_exp_financial_loss_xgb_black_box.csv` | Expected financial loss per policy | XGBoost regressor |
| `df_acceptance_linear_model_black_box.csv` | Acceptance probability per policy | GLM (Logistic Regression) |
| `df_acceptance_gam_model_black_box.csv` | Acceptance probability per policy | GAM (LogisticGAM) |
| `df_exp_financial_loss_linear_black_box.csv` | Expected financial loss per policy | Linear  |
| 

Additionally, it serialises all trained models to `artifacts/` as pickle files for reuse (see Section 17).

## Workflow Overview
1. **Setup** — install dependencies  
2. **Data ingestion** — load and clean the 3m-1006 parquet dataset  
3. **Feature engineering** — rename columns, compute premium change ratio `U`  
4. **In sample population  filtering **
5. **Model training (cross-validation with OOF predictions)**  
   - XGBoost regressor: predicts current policy premium `Y`  
   - XGBoost classifier: predicts churn probability  
   - GLM (logistic regression): interpretable churn alternative  
   - GAM (LogisticGAM): semi-parametric churn alternative  
   - Linear regression: interpretable premium baseline  
6. **Output generation** — derive acceptance probability and save CSVs  
7. **Model serialisation** — save all four models to `artifacts/`

## Section 2 — Data Ingestion & Preprocessing

Loads the anonymised 3-month policy dataset (`full_dataset_anonimized_processed_3m_1006.parquet`) and applies the following quality filters:

- **Missing upcoming renewal data** — rows with sentinel values for premium (`9999`), premium % change (`9`) or driver age (`100`) are dropped.
- **Duplicate churn rows** — only the first churn event per policy is retained; subsequent rows after churn are removed.
- **Mismatch policies** — policies where the *supposed* next-year premium differs from the *actual* premium by more than €40 (or the % change differs by more than 0.2) are excluded entirely to avoid noisy training signal.

The analysis is restricted to `year == 7` through the `df_sub` filter below.

In [341]:
import pandas as pd

def preprocess_3m_1006(parquet_path: str):
    """"
    #### Args
    - parquet_path: path to parquet file containing the 3m_1006 dataset

    #### Returns
    - df: preprocessed dataframe
    """
    df = pd.read_parquet(parquet_path)
    # make sure df is sorted by policy number first then year
    df = df.sort_values(['encoded_policy_number', 'year']).reset_index(drop=True)
    print(f"Original rows {len(df)}, Unique policies: {df['encoded_policy_number'].nunique()}")

    # get rid of rows with missing upcoming renewal data
    df = df[
        (df['premio_total_continuado_x_impute_GTE100_LTE1500_missing_9999'] != 9999) & # upcoming renewal premium
        (df['tx_pt_continuado_x_impute_inflation_this_renewal_6m_GTEminus1_LTE1_missing_9'] != 9) & # cur renewal % change
        (df['idade_condutor_x_impute_GTE18_LTE100_map_missing_100'] != 100) # age
    ]

    # remove churned rows that are not the first churned row of each policy
    is_first_policy_row = df["encoded_policy_number"] != df["encoded_policy_number"].shift(1)
    mask = (
        (df["is_churn"] == False) |
        (
            (df["is_churn"] == True) &
            (
                is_first_policy_row |
                (df["is_churn"].shift(1) == False)
            )
        )
    )
    df = df[mask]

    # ----- remove entire policies with mismatches (supposed increase vs actual increase) 
    # ----- over the thresholds
    # premium mismatch
    supposed = "premio_total_continuado_x_impute_GTE100_LTE1500_missing_9999"
    actual = "valor_vigor_pt_apol"

    temp = df[['encoded_policy_number', actual, supposed]].copy()
    temp['diff'] = (temp[actual] - temp[supposed].shift(1)).fillna(0).abs()

    same_policy_mask = temp['encoded_policy_number'] == temp['encoded_policy_number'].shift(1)
    temp = temp[same_policy_mask]
    mismatches = temp.groupby('encoded_policy_number')['diff'].max() > 40 # threshold

    bad_policies = set(mismatches.index[mismatches])
    
    # premium % change mismatch
    actual = "tx_pt_continuado_ant_x_impute_inflation_last_renewal_6m_GTEminus1_LTE1_missing_9"
    supposed = "tx_pt_continuado_x_impute_inflation_this_renewal_6m_GTEminus1_LTE1_missing_9"

    temp = df[['encoded_policy_number', actual, supposed]].copy()
    temp = temp[temp[actual] != 9.0]
    temp['diff'] = (temp[actual] - temp[supposed].shift(1)).fillna(0).abs()

    same_policy_mask = temp['encoded_policy_number'] == temp['encoded_policy_number'].shift(1)
    temp = temp[same_policy_mask]
    mismatches = temp.groupby('encoded_policy_number')['diff'].max() > 0.2 # threshold

    bad_policies |= set(mismatches.index[mismatches])

    # remove bad policies from df
    df = df[~df['encoded_policy_number'].isin(bad_policies)]
    print(f"Remaining rows {len(df)}, Remaining unique policies: {df['encoded_policy_number'].nunique()}")

    return df

## Section 1 — Setup & Dependencies

In [250]:
from preprocessing import *
import numpy as np
import pprint as pp
from matplotlib import pyplot as plt

In [251]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

%matplotlib inline


from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder

In [252]:
import sklearn

In [253]:
file_path = r"full_dataset_anonimized_processed_3m_1006.parquet"
df = preprocess_3m_1006(file_path)

Original rows 3370487, Unique policies: 1103634
Remaining rows 3075795, Remaining unique policies: 1034510

In [254]:
df.head()

,encoded_policy_number,idade_condutor_x_impute_GTE18_LTE100_map_missing_100,indice_bonus_malus,canal_distribuicao_h4_x_grouping_all_products,cod_estatistico_classe_risco,num_sin_tot,num_apolices_tot,ind_cliente_b_x_grouping_all_products,idade_construcao_veiculo_x_impute_GTE0_LTE50_missing_0,antiguidade_apolice_x_impute_GTE0_LTE30_missing_0,valor_vigor_pt_apol,tx_pt_continuado_ant_x_impute_inflation_last_renewal_6m_GTEminus1_LTE1_missing_9,premio_total_continuado_x_impute_GTE100_LTE1500_missing_9999,tx_pt_continuado_x_impute_inflation_this_renewal_6m_GTEminus1_LTE1_missing_9,year,is_churn
0,5,86.0,50.000,19,T4005040,0,1,0,17.0,17.0,174.4700,-0.108391,157.14,-0.111998,0,False
1,5,87.0,47.500,19,T4005040,0,1,0,18.0,18.0,157.1400,-0.111998,156.74,-0.011103,1,False
2,5,88.0,45.125,19,T4005040,0,1,0,19.0,19.0,156.7400,-0.011103,156.36,-0.009236,2,False
3,5,89.0,45.000,19,T4005040,0,1,0,20.0,20.0,155.9369,-0.011918,164.11,0.051139,3,False
4,5,90.0,45.000,19,T4005040,0,1,0,21.0,21.0,164.1100,0.048342,163.72,-0.007067,4,False

In [255]:
!pip install -U glum

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: glum in c:\users\malosett\appdata\roaming\python\python311\site-packages (3.2.3)
Requirement already satisfied: formulaic>=1.2.0 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from glum) (1.2.1)
Requirement already satisfied: joblib in c:\users\malosett\appdata\roaming\python\python311\site-packages (from glum) (1.3.2)
Requirement already satisfied: narwhals>=2.0.0 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from glum) (2.19.0)
Requirement already satisfied: numexpr in c:\programdata\anaconda3\lib\site-packages (from glum) (2.8.7)
Requirement already satisfied: numpy>=1.24 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from glum) (2.4.4)
Requirement already satisfied: packaging in c:\users\malosett\appdata\roaming\python\python311\site-packages (from glum) (25.0)
Requirement already satisfied: pandas>=1.4 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from glum) (3.0.2)
Requirement already satisfied: pyarrow in c:\users\malosett\appdata\roaming\python\python311\site-packages (from glum) (23.0.1)
Requirement already satisfied: scikit-learn>=1.1.0 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from glum) (1.8.0)
Requirement already satisfied: scipy>=1.8.0 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from glum) (1.16.3)
Requirement already satisfied: tabmat>=4.1.5 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from glum) (4.2.1)
Requirement already satisfied: tqdm in c:\programdata\anaconda3\lib\site-packages (from glum) (4.65.0)
Requirement already satisfied: interface-meta>=1.2.0 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from formulaic>=1.2.0->glum) (1.3.0)
Requirement already satisfied: typing-extensions>=4.2.0 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from formulaic>=1.2.0->glum) (4.15.0)
Requirement already satisfied: wrapt>=1.0 in c:\programdata\anaconda3\lib\site-packages (from formulaic>=1.2.0->glum) (1.14.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas>=1.4->glum) (2.8.2)
Requirement already satisfied: tzdata in c:\programdata\anaconda3\lib\site-packages (from pandas>=1.4->glum) (2023.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from scikit-learn>=1.1.0->glum) (3.6.0)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from tqdm->glum) (0.4.6)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.4->glum) (1.16.0)

In [256]:
df_sub = df.loc[df.year==7]

## Section 3 — Feature Name Mapping

Raw column names in the parquet file use verbose Portuguese/encoded names.  
This section defines a mapping to clean `X_` prefixed names used throughout the modelling pipeline.

| Clean name | Meaning |
|---|---|
| `X_age` | Driver age (clamped 18–100) |
| `X_vehicle_age` | Vehicle age in years |
| `X_policy_tenure` | Policy seniority in years |
| `X_policy_count` | Number of policies held by this client |
| `X_risk_code` | Risk segment code (higher = lower risk) |
| `X_distr_channel` | Distribution channel group |
| `X_ttm_claims` | Total claims in trailing 12 months |
| `X_bonus_malus_rating` | Bonus-malus coefficient |
| `X_vehicle_type` | Vehicle statistical risk class |
| `X_policy_premium` | Current active premium (`Y` in regression) |
| `X_upcoming_premium` | Proposed renewal premium |
| `X_cur_renewal_perc` | % premium change at this renewal |
| `U` | Relative premium increase: `(upcoming - current) / current` |

In [257]:

age = 'idade_condutor_x_impute_GTE18_LTE100_map_missing_100'
vehicle_age = 'idade_construcao_veiculo_x_impute_GTE0_LTE50_missing_0' # 0 = new car
policy_tenure = 'antiguidade_apolice_x_impute_GTE0_LTE30_missing_0'
policy_count = 'num_apolices_tot'
risk_code = 'ind_cliente_b_x_grouping_all_products' # integers, larger = higher survival chance
distr_channel = 'canal_distribuicao_h4_x_grouping_all_products' # larger = higher obs survival in training
ttm_claims = 'num_sin_tot'
bonus_malus_rating = 'indice_bonus_malus'
vehicle_type = 'cod_estatistico_classe_risco'
policy_premium = 'valor_vigor_pt_apol'
upcoming_premium = 'premio_total_continuado_x_impute_GTE100_LTE1500_missing_9999'
prev_renewal_perc = "tx_pt_continuado_ant_x_impute_inflation_last_renewal_6m_GTEminus1_LTE1_missing_9"
cur_renewal_perc = 'tx_pt_continuado_x_impute_inflation_this_renewal_6m_GTEminus1_LTE1_missing_9' # % change of total premium
id_number = 'encoded_policy_number'

# for selecting the features to build the model
covariate_cols = [age, vehicle_age, policy_count, risk_code, distr_channel, ttm_claims,bonus_malus_rating, vehicle_type,
                  policy_premium, upcoming_premium, cur_renewal_perc]
col_name_map = {
    id_number: 'id',
    age: 'X_age',
    vehicle_age: 'X_vehicle_age',
    policy_tenure: 'X_policy_tenure',
    policy_count: 'X_policy_count',
    risk_code: 'X_risk_code',
    distr_channel: 'X_distr_channel',
    ttm_claims: 'X_ttm_claims',
    bonus_malus_rating: 'X_bonus_malus_rating',
    vehicle_type: 'X_vehicle_type',
    policy_premium: 'X_policy_premium',
    upcoming_premium: 'X_upcoming_premium',
    prev_renewal_perc:"X_prev_renewal_perc",
    cur_renewal_perc: 'X_cur_renewal_perc'
}

In [258]:
df_sub = df_sub.rename(columns=col_name_map)

In [259]:
df_sub.columns

Index(['id', 'X_age', 'X_bonus_malus_rating', 'X_distr_channel',
       'X_vehicle_type', 'X_ttm_claims', 'X_policy_count', 'X_risk_code',
       'X_vehicle_age', 'X_policy_tenure', 'X_policy_premium',
       'X_prev_renewal_perc', 'X_upcoming_premium', 'X_cur_renewal_perc',
       'year', 'is_churn'],
      dtype='str')

In [260]:
# common function to filter out rows fro xgb regression and classification

## Section 4 — Outlier Filtering: `filter_middle_advanced`

`filter_middle_advanced` applies **per-column** outlier filtering before model training.  
Three methods are supported:

- **`iqr`** — keeps rows within `[Q1 − k·IQR, Q3 + k·IQR]` (default `k = 1.5`)
- **`percentile`** — keeps rows between specified quantiles (e.g., 5th–95th)
- **`zscore`** — keeps rows within `mean ± threshold·std`

Categorical filtering reduces cardinality by keeping the top-N most frequent values.

**Why filter?**  
Extreme premium values and very rare distribution channels create poor generalisation.  
The filtered datasets vary per model (XGBoost, GLM, GAM, Linear) to allow independent tuning of cleaning thresholds.

In [261]:
def filter_middle_advanced(df, 
                          numeric_filters=None, 
                          categorical_filters=None,
                          keep_id_cols=None):
    """
    Advanced filtering with per-column configuration
    
    Parameters:
    -----------
    numeric_filters : dict
        {column_name: {'multiplier': 1.5, 'method': 'iqr'}}
    categorical_filters : dict
        {column_name: {'min_freq': 0.01, 'max_categories': 10, 'keep_values': [...]}}
    keep_id_cols : list
        Columns to preserve in output (like 'encoded_policy_number')
    """
    df_filtered = df.copy()
    
    if keep_id_cols is None:
        keep_id_cols = ['encoded_policy_number']
    
    # Numeric filtering
    if numeric_filters:
        for col, config in numeric_filters.items():
            multiplier = config.get('multiplier', 1.5)
            method = config.get('method', 'iqr')
            
            if method == 'iqr':
                Q1 = df[col].quantile(0.25)
                Q3 = df[col].quantile(0.75)
                IQR = Q3 - Q1
                lower = Q1 - multiplier * IQR
                upper = Q3 + multiplier * IQR
            elif method == 'percentile':
                lower = df[col].quantile(config.get('lower_q', 0.05))
                upper = df[col].quantile(config.get('upper_q', 0.95))
            elif method == 'zscore':
                mean = df[col].mean()
                std = df[col].std()
                threshold = config.get('threshold', 3)
                lower = mean - threshold * std
                upper = mean + threshold * std
            
            df_filtered = df_filtered[(df_filtered[col] >= lower) & (df_filtered[col] <= upper)]
            print(f"{col}: [{lower:.2f}, {upper:.2f}]")
    
    # Categorical filtering
    if categorical_filters:
        for col, config in categorical_filters.items():
            # Option 1: Explicit list of values to keep
            if 'keep_values' in config:
                valid_values = config['keep_values']
            # Option 2: By frequency or top N
            else:
                value_counts = df[col].value_counts()
                
                if 'max_categories' in config:
                    valid_values = value_counts.nlargest(config['max_categories']).index.tolist()
                elif 'min_freq' in config:
                    min_count = int(len(df) * config['min_freq'])
                    valid_values = value_counts[value_counts >= min_count].index.tolist()
                else:
                    valid_values = value_counts.index.tolist()
            
            df_filtered = df_filtered[df_filtered[col].isin(valid_values)]
            print(f"{col}: Kept {len(valid_values)} categories")
    
    print(f"\nTotal: {len(df)} → {len(df_filtered)} rows")
    
    return df_filtered


# Usage
df_middle = filter_middle_advanced(
    df_sub,
    numeric_filters={
        'X_age': {'multiplier': 1.5, 'method': 'iqr'},
        'X_policy_premium': {'multiplier': 2.0, 'method': 'iqr'},
        'X_upcoming_premium':{'multiplier':2.0,'method':'iqr'},
        'X_vehicle_age': {'method': 'percentile', 'lower_q': 0.05, 'upper_q': 0.95},
        'X_cur_renewal_perc':{'method': 'percentile', 'lower_q': 0.05, 'upper_q': 0.95}
    },
    categorical_filters={
        'X_distr_channel': {'max_categories':12},
        'X_risk_code': {'max_categories': 6},
        'X_vehicle_type': {'max_categories': 8}  # explicit list
    },
    keep_id_cols=['encoded_policy_number']
)

X_age: [8.50, 100.50]
X_policy_premium: [-14.06, 444.14]
X_upcoming_premium: [-15.07, 480.13]
X_vehicle_age: [4.00, 31.00]
X_cur_renewal_perc: [-0.02, 0.11]
X_distr_channel: Kept 12 categories
X_risk_code: Kept 6 categories
X_vehicle_type: Kept 8 categories

Total: 463400 → 194373 rows

## Section 5 — Model Architecture Definitions

Three model classes are defined here and reused across datasets:

### `ModelRegressor`
XGBoost regressor with **Optuna hyperparameter tuning**.  
- Objective: `reg:absoluteerror` (MAE-optimised)
- Tuned parameters: `learning_rate`, `max_depth`, `subsample`, `colsample_bytree`, `min_child_weight`
- Used to predict `X_policy_premium` (target `Y`)

### `ModelClassifier`
XGBoost binary classifier with **Optuna hyperparameter tuning**.  
- Metric: ROC-AUC
- Used to predict churn (`is_churn`), which is then converted to acceptance probability: `Z = 1 − is_churn`, `prob_acceptance = 1 − churn_proba`

### `ModelRegressorCV`  
Extended version of `ModelRegressor` that runs **fully nested Optuna + KFold CV** in a single call. Used for the policy premium regression CV experiment.

In [262]:

from sklearn import metrics
import pandas as pd
import numpy as np
import xgboost as xgb
import optuna
from optuna.trial import Trial
N_ESTIMATORS = 200
OBJECTIVE = 'reg:absoluteerror'
class ModelRegressor():
    
    def objective(self,trial : Trial, X_train : pd.DataFrame, y_train : pd.Series,X_val : pd.DataFrame, y_val : pd.Series)-> float:
        params = {
            "learning_rate": trial.suggest_float("learning_rate", 1e-3, 0.1, log=True),
            "max_depth": trial.suggest_int("max_depth", 1, 10),
            "subsample": trial.suggest_float("subsample", 0.05, 1.0),
            "colsample_bytree": trial.suggest_float("colsample_bytree", 0.05, 1.0),
            "min_child_weight": trial.suggest_int("min_child_weight", 1, 20),
        }
        model = xgb.XGBRegressor(**params,random_state=123,n_estimators=N_ESTIMATORS,early_stopping_rounds=5,objective = OBJECTIVE)
        model.fit(X_train, y_train,verbose=0,eval_set=[(X_val, y_val)])
        y_pred = model.predict(X_val)
        loss = metrics.mean_absolute_error(y_true=y_val,y_pred=y_pred)
        return loss
    
    def tuning(self,X_train:pd.DataFrame,y_train:pd.Series,X_val:pd.DataFrame, y_val:pd.Series,n_trials:int)->dict:
        y_train = y_train
        y_val = y_val
        study = optuna.create_study(study_name='Xgboost', direction='minimize')
        study.optimize(lambda trial: self.objective(trial, X_train, y_train, X_val, y_val), n_trials=n_trials)
        best_params = study.best_params
        return best_params
    
    def train(self,X_train:pd.DataFrame,y_train:pd.Series,X_val:pd.DataFrame, y_val:pd.Series,best_params:dict)->xgb.XGBRegressor:
        y_train = y_train
        y_val = y_val
        model = xgb.XGBRegressor(**best_params,random_state=123,n_estimators=N_ESTIMATORS,early_stopping_rounds=5,objective = OBJECTIVE)
        model.fit(X_train, y_train,verbose=0,eval_set=[(X_val, y_val)])
        return model

In [263]:
from sklearn import metrics
import pandas as pd
import xgboost as xgb
import optuna
from optuna.trial import Trial

N_ESTIMATORS = 200

class ModelClassifier():
    
    def objective(self,trial : Trial, X_train : pd.DataFrame, y_train : pd.Series,X_val : pd.DataFrame, y_val : pd.Series)-> float:
        params = {
            "learning_rate": trial.suggest_float("learning_rate", 1e-3, 0.1, log=True),
            "max_depth": trial.suggest_int("max_depth", 1, 10),
            "subsample": trial.suggest_float("subsample", 0.05, 1.0),
            "colsample_bytree": trial.suggest_float("colsample_bytree", 0.05, 1.0),
            "min_child_weight": trial.suggest_int("min_child_weight", 1, 20),
        }

        model = xgb.XGBClassifier(**params,random_state=123,n_estimators=N_ESTIMATORS,early_stopping_rounds=5)
        model.fit(X_train, y_train,verbose=0,eval_set=[(X_val, y_val)])
        y_score = model.predict_proba(X_val)[:,1]
        roc_auc = metrics.roc_auc_score(y_true=y_val,y_score=y_score)
        return roc_auc
    
    def tuning(self,X_train:pd.DataFrame,y_train:pd.Series,X_val:pd.DataFrame, y_val:pd.Series,n_trials:int)->dict:
        study = optuna.create_study(study_name='Xgboost', direction='maximize')
        study.optimize(lambda trial: self.objective(trial, X_train, y_train, X_val, y_val), n_trials=n_trials)
        best_params = study.best_params
        return best_params
    
    def train(self,X_train:pd.DataFrame,y_train:pd.Series,X_val:pd.DataFrame, y_val:pd.Series,best_params:dict)->xgb.XGBClassifier:
        model = xgb.XGBClassifier(**best_params,random_state= 123,n_estimators= N_ESTIMATORS,
                                  early_stopping_rounds= 5)
        model.fit(X_train, y_train,verbose=0,eval_set=[(X_val, y_val)])
        return model

In [264]:
import numpy as np
import pandas as pd


class FeatureProcessor:
    """
    Center+sphere numeric features and label-encode categorical features as continuous values.
    Supports PCA with whitening for multivariate Mahalanobis distance.
    """

    def __init__(
        self,
        numeric_cols=None,
        categorical_cols=None,
        regularization=1e-6,
        missing_category="__MISSING__",
        use_pca=False,
        n_components=None,
        explained_variance_threshold=None,
    ):
        """
        Parameters
        ----------
        numeric_cols : list, optional
            Columns to treat as numeric. If None, inferred from data.
        categorical_cols : list, optional
            Columns to treat as categorical. If None, inferred from data.
        regularization : float, default=1e-6
            Regularization added to eigenvalues for numerical stability.
        missing_category : str, default="__MISSING__"
            Value to use for missing categorical values.
        use_pca : bool, default=False
            If True, apply PCA with whitening to numeric features.
            Whitening transforms data so Euclidean distance = Mahalanobis distance.
        n_components : int or float, optional
            Number of PCA components to keep:
            - If int: keep exactly n_components
            - If float (0.0, 1.0): keep components explaining this fraction of variance
            - If None: keep all components (full rank with whitening)
        explained_variance_threshold : float, optional
            Alternative to n_components: keep components until cumulative
            explained variance reaches this threshold (e.g., 0.95 for 95%).
        """
        self.numeric_cols = numeric_cols
        self.categorical_cols = categorical_cols
        self.regularization = regularization
        self.missing_category = missing_category
        self.use_pca = use_pca
        self.n_components = n_components
        self.explained_variance_threshold = explained_variance_threshold

    def fit(self, X: pd.DataFrame):
        X = X.copy()

        if self.numeric_cols is None:
            self.numeric_cols_ = X.select_dtypes(include=[np.number]).columns.tolist()
        else:
            self.numeric_cols_ = list(self.numeric_cols)

        if self.categorical_cols is None:
            self.categorical_cols_ = [c for c in X.columns if c not in self.numeric_cols_]
        else:
            self.categorical_cols_ = list(self.categorical_cols)

        # Numeric centering + sphering/PCA
        if self.numeric_cols_:
            X_num = X[self.numeric_cols_].astype(float)
            self.numeric_means_ = X_num.mean(axis=0)
            X_num_centered = X_num - self.numeric_means_

            # Compute covariance matrix
            cov = np.cov(X_num_centered.values, rowvar=False)
            if np.ndim(cov) == 0:
                cov = np.array([[float(cov)]])

            # Eigendecomposition
            eigvals, eigvecs = np.linalg.eigh(cov)
            
            # Sort eigenvalues and eigenvectors in descending order
            idx = np.argsort(eigvals)[::-1]
            eigvals = eigvals[idx]
            eigvecs = eigvecs[:, idx]
            
            # Regularize eigenvalues
            eigvals = np.maximum(eigvals, self.regularization)
            
            # Store full eigenvalues for explained variance
            self.eigenvalues_ = eigvals
            total_var = eigvals.sum()
            self.explained_variance_ratio_ = eigvals / total_var if total_var > 0 else eigvals
            self.cumulative_variance_ratio_ = np.cumsum(self.explained_variance_ratio_)

            if self.use_pca:
                # Determine number of components to keep
                n_features = len(eigvals)
                if self.explained_variance_threshold is not None:
                    # Keep components until threshold is reached
                    n_keep = np.searchsorted(self.cumulative_variance_ratio_, 
                                            self.explained_variance_threshold) + 1
                    n_keep = min(n_keep, n_features)
                elif self.n_components is not None:
                    if isinstance(self.n_components, float) and 0 < self.n_components < 1:
                        # n_components as fraction of variance
                        n_keep = np.searchsorted(self.cumulative_variance_ratio_, 
                                                self.n_components) + 1
                        n_keep = min(n_keep, n_features)
                    else:
                        # n_components as integer
                        n_keep = min(int(self.n_components), n_features)
                else:
                    # Keep all components
                    n_keep = n_features
                
                self.n_components_ = n_keep
                
                # Select top components
                eigvals_keep = eigvals[:n_keep]
                eigvecs_keep = eigvecs[:, :n_keep]
                
                # PCA with whitening: transform = X_centered @ eigvecs @ diag(1/sqrt(eigvals))
                # This makes covariance matrix of transformed data = Identity
                self.pca_components_ = eigvecs_keep
                self.whitening_scale_ = 1.0 / np.sqrt(eigvals_keep)
                
                # Combined transformation matrix for efficiency
                self.sphering_matrix_ = eigvecs_keep @ np.diag(self.whitening_scale_)
                
                # Feature names for PCA components
                self.numeric_feature_names_ = [f"PC{i+1}" for i in range(n_keep)]
            else:
                # Original sphering (full rank)
                self.n_components_ = len(eigvals)
                self.sphering_matrix_ = eigvecs @ np.diag(1.0 / np.sqrt(eigvals)) @ eigvecs.T
                self.numeric_feature_names_ = [f"sphered__{col}" for col in self.numeric_cols_]
        else:
            self.numeric_means_ = pd.Series(dtype=float)
            self.sphering_matrix_ = np.empty((0, 0))
            self.n_components_ = 0
            self.numeric_feature_names_ = []

        # Categorical label encoding -> continuous [0, 1]
        self.cat_mapping_ = {}
        self.cat_denominator_ = {}
        self.encoded_cat_feature_names_ = []

        for col in self.categorical_cols_:
            col_values = X[col].fillna(self.missing_category).astype(str)
            categories = pd.Index(col_values.unique())
            mapping = {cat: idx for idx, cat in enumerate(categories)}
            self.cat_mapping_[col] = mapping
            # Keep one extra bucket for unseen categories at transform time.
            self.cat_denominator_[col] = max(len(mapping), 1)
            self.encoded_cat_feature_names_.append(f"label_cont__{col}")

        self.output_feature_names_ = [
            *self.numeric_feature_names_,
            *self.encoded_cat_feature_names_,
        ]
        return self

    def transform(self, X: pd.DataFrame) -> pd.DataFrame:
        X = X.copy()

        # Transform numeric features
        if self.numeric_cols_:
            X_num = X[self.numeric_cols_].astype(float)
            X_num_centered = X_num - self.numeric_means_
            X_num_transformed = X_num_centered.values @ self.sphering_matrix_
        else:
            X_num_transformed = np.empty((len(X), 0))

        # Transform categorical features using fitted mappings
        cat_arrays = []
        for col in self.categorical_cols_:
            values = X[col].fillna(self.missing_category).astype(str)
            mapping = self.cat_mapping_[col]
            unknown_code = len(mapping)
            denom = self.cat_denominator_[col]

            label_codes = values.map(mapping).fillna(unknown_code).astype(float)
            continuous_codes = (label_codes / denom).to_numpy().reshape(-1, 1)
            cat_arrays.append(continuous_codes)

        if cat_arrays:
            X_cat_encoded = np.hstack(cat_arrays)
        else:
            X_cat_encoded = np.empty((len(X), 0))

        X_out = np.hstack([X_num_transformed, X_cat_encoded])
        return pd.DataFrame(X_out, index=X.index, columns=self.output_feature_names_)

    def fit_transform(self, X: pd.DataFrame) -> pd.DataFrame:
        return self.fit(X).transform(X)
    
    def get_explained_variance_info(self):
        """
        Get information about explained variance (useful when use_pca=True).
        
        Returns
        -------
        dict with keys:
            - 'eigenvalues': array of eigenvalues
            - 'explained_variance_ratio': variance explained by each component
            - 'cumulative_variance_ratio': cumulative variance explained
            - 'n_components_kept': number of components retained
        """
        if not hasattr(self, 'eigenvalues_'):
            raise ValueError("Model not fitted yet. Call fit() first.")
        
        return {
            'eigenvalues': self.eigenvalues_,
            'explained_variance_ratio': self.explained_variance_ratio_,
            'cumulative_variance_ratio': self.cumulative_variance_ratio_,
            'n_components_kept': self.n_components_,
        }
    
    def inverse_transform_numeric(self, X_transformed: np.ndarray) -> np.ndarray:
        """
        Inverse transform for numeric features only (approximate if PCA was used with n_components < n_features).
        
        Parameters
        ----------
        X_transformed : ndarray of shape (n_samples, n_components)
            Transformed numeric features only (not including categorical).
            
        Returns
        -------
        X_original : ndarray of shape (n_samples, n_numeric_features)
            Approximate reconstruction of original numeric features.
        """
        if not self.use_pca:
            # For full-rank sphering, inverse is more complex
            # X_sphered = X_centered @ sphering_matrix
            # X_centered = X_sphered @ sphering_matrix^-1
            raise NotImplementedError("Inverse transform only supported when use_pca=True")
        
        if not self.numeric_cols_:
            return np.empty((len(X_transformed), 0))
        
        # Inverse: X_centered = PC_scores @ components.T
        X_centered = X_transformed @ self.pca_components_.T
        
        # Add back the mean
        X_original = X_centered + self.numeric_means_.values
        
        return X_original

In [265]:
# Demo: FeatureProcessor with PCA and whitening

# Example 1: Standard sphering (original behavior)
fp_standard = FeatureProcessor()
X_sphered = fp_standard.fit_transform(X_raw)
print(f"Standard sphering - Output shape: {X_sphered.shape}")

# Example 2: PCA with whitening, keeping top 5 components
fp_pca = FeatureProcessor(use_pca=True, n_components=5)
X_pca = fp_pca.fit_transform(X_raw)
print(f"\nPCA (5 components) - Output shape: {X_pca.shape}")
var_info = fp_pca.get_explained_variance_info()
print(f"Explained variance by top 5: {var_info['cumulative_variance_ratio'][:5][-1]:.3f}")

# Example 3: PCA keeping 95% of variance
fp_pca_var = FeatureProcessor(use_pca=True, explained_variance_threshold=0.95)
X_pca_var = fp_pca_var.fit_transform(X_raw)
print(f"\nPCA (95% variance) - Output shape: {X_pca_var.shape}")
print(f"Components kept: {fp_pca_var.n_components_}")

# Example 4: PCA with all components (whitening only, no dimensionality reduction)
fp_pca_full = FeatureProcessor(use_pca=True)
X_pca_full = fp_pca_full.fit_transform(X_raw)
print(f"\nPCA (all components) - Output shape: {X_pca_full.shape}")

# Note: With whitening, Euclidean distance in transformed space = Mahalanobis distance in original space
# This is useful for distance-based algorithms like k-NN, k-means, etc.

Standard sphering - Output shape: (194373, 10)

PCA (5 components) - Output shape: (194373, 5)
Explained variance by top 5: 0.996

PCA (95% variance) - Output shape: (194373, 2)
Components kept: 2

PCA (all components) - Output shape: (194373, 10)

In [266]:
df_middle_class = filter_middle_advanced(
    df_sub,
    numeric_filters={
        'X_age': {'multiplier': 1.5, 'method': 'iqr'},
        'X_policy_premium': {'multiplier': 2.0, 'method': 'iqr'},
        'X_upcoming_premium':{'multiplier':2.0,'method':'iqr'},
        'X_vehicle_age': {'method': 'percentile', 'lower_q': 0.05, 'upper_q': 0.95},
        'X_cur_renewal_perc':{'method': 'percentile', 'lower_q': 0.05, 'upper_q': 0.95}
    },
    categorical_filters={
        'X_distr_channel': {'max_categories':12},
        'X_risk_code': {'max_categories': 6},
        'X_vehicle_type': {'max_categories': 8}  # explicit list
    },
    keep_id_cols=['encode_policy_number']
)

X_age: [8.50, 100.50]
X_policy_premium: [-14.06, 444.14]
X_upcoming_premium: [-15.07, 480.13]
X_vehicle_age: [4.00, 31.00]
X_cur_renewal_perc: [-0.02, 0.11]
X_distr_channel: Kept 12 categories
X_risk_code: Kept 6 categories
X_vehicle_type: Kept 8 categories

Total: 463400 → 194373 rows

In [267]:
def filter_middle_iqr(df, columns=None, multiplier=1.5):
    """Keep observations within Q1 - multiplier*IQR to Q3 + multiplier*IQR"""
    df_filtered = df.copy()
    
    # Use numeric columns only if not specified
    if columns is None:
        columns = df.select_dtypes(include=['number']).columns
        columns = [col for col in columns if col not in ['encoded_policy_number', 'is_churn']]
    
    for col in columns:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1
        lower = Q1 - multiplier * IQR
        upper = Q3 + multiplier * IQR
        df_filtered = df_filtered[(df_filtered[col] >= lower) & (df_filtered[col] <= upper)]
    
    return df_filtered

In [268]:
df_middle_class.columns

Index(['id', 'X_age', 'X_bonus_malus_rating', 'X_distr_channel',
       'X_vehicle_type', 'X_ttm_claims', 'X_policy_count', 'X_risk_code',
       'X_vehicle_age', 'X_policy_tenure', 'X_policy_premium',
       'X_prev_renewal_perc', 'X_upcoming_premium', 'X_cur_renewal_perc',
       'year', 'is_churn'],
      dtype='str')

In [269]:
from sklearn import metrics
from sklearn.model_selection import KFold, cross_val_score
import pandas as pd
import numpy as np
import xgboost as xgb
import optuna
from optuna.trial import Trial

N_ESTIMATORS = 200
OBJECTIVE = 'reg:absoluteerror'
N_FOLDS = 5
RANDOM_STATE = 123

class ModelRegressorCV():
    
    def __init__(self, n_folds=N_FOLDS, random_state=RANDOM_STATE):
        self.n_folds = n_folds
        self.random_state = random_state
        self.best_params = None
        self.cv_scores = None
        self.final_model = None
        
    def objective(self, trial: Trial, X: pd.DataFrame, y: pd.Series) -> float:
        """Optuna objective with cross-validation"""
        params = {
            "learning_rate": trial.suggest_float("learning_rate", 1e-3, 0.1, log=True),
            "max_depth": trial.suggest_int("max_depth", 1, 10),
            "subsample": trial.suggest_float("subsample", 0.05, 1.0),
            "colsample_bytree": trial.suggest_float("colsample_bytree", 0.05, 1.0),
            "min_child_weight": trial.suggest_int("min_child_weight", 1, 20),
        }
        
        # Cross-validation with the suggested parameters
        kfold = KFold(n_splits=self.n_folds, shuffle=True, random_state=self.random_state)
        cv_scores = []
        
        for train_idx, val_idx in kfold.split(X):
            X_train_fold, X_val_fold = X.iloc[train_idx], X.iloc[val_idx]
            y_train_fold, y_val_fold = y.iloc[train_idx], y.iloc[val_idx]
            
            # Apply log transformation
            y_train_transformed = np.log(y_train_fold) + 1
            y_val_transformed = np.log(y_val_fold) + 1
            
            model = xgb.XGBRegressor(
                **params,
                random_state=self.random_state,
                n_estimators=N_ESTIMATORS,
                early_stopping_rounds=5,
                objective=OBJECTIVE
            )
            
            model.fit(
                X_train_fold, 
                y_train_transformed,
                verbose=0,
                eval_set=[(X_val_fold, y_val_transformed)]
            )
            
            y_pred = model.predict(X_val_fold)
            fold_mae = metrics.mean_absolute_error(y_val_transformed, y_pred)
            cv_scores.append(fold_mae)
        
        # Return mean CV score
        return np.mean(cv_scores)
    
    def tuning(self, X: pd.DataFrame, y: pd.Series, n_trials: int) -> dict:
        """Hyperparameter tuning with cross-validation"""
        print(f"Starting hyperparameter tuning with {n_trials} trials and {self.n_folds}-fold CV...")
        
        study = optuna.create_study(study_name='XGBoost_CV', direction='minimize')
        study.optimize(
            lambda trial: self.objective(trial, X, y), 
            n_trials=n_trials,
            show_progress_bar=True
        )
        
        self.best_params = study.best_params
        print(f"\nBest CV MAE: {study.best_value:.6f}")
        print(f"Best parameters: {self.best_params}")
        
        return self.best_params
    
    def train_with_cv(self, X: pd.DataFrame, y: pd.Series, params: dict = None) -> tuple:
        """Train model with cross-validation and return CV scores"""
        if params is None:
            if self.best_params is None:
                raise ValueError("No parameters provided. Run tuning() first or provide params.")
            params = self.best_params
        
        print(f"\nTraining with {self.n_folds}-fold cross-validation...")
        kfold = KFold(n_splits=self.n_folds, shuffle=True, random_state=self.random_state)
        
        cv_scores = []
        fold_models = []
        
        for fold_num, (train_idx, val_idx) in enumerate(kfold.split(X), 1):
            X_train_fold, X_val_fold = X.iloc[train_idx], X.iloc[val_idx]
            y_train_fold, y_val_fold = y.iloc[train_idx], y.iloc[val_idx]
            
            # Apply log transformation
            y_train_transformed = y_train_fold 
            y_val_transformed = y_val_fold 
            
            model = xgb.XGBRegressor(
                **params,
                random_state=self.random_state,
                n_estimators=N_ESTIMATORS,
                early_stopping_rounds=5,
                objective=OBJECTIVE
            )
            
            model.fit(
                X_train_fold, 
                y_train_transformed,
                verbose=0,
                eval_set=[(X_val_fold, y_val_transformed)]
            )
            
            y_pred = model.predict(X_val_fold)
            fold_mae = metrics.mean_absolute_error(y_val_transformed, y_pred)
            cv_scores.append(fold_mae)
            fold_models.append(model)
            
            print(f"Fold {fold_num}: MAE = {fold_mae:.6f}")
        
        self.cv_scores = cv_scores
        print(f"\nMean CV MAE: {np.mean(cv_scores):.6f} (+/- {np.std(cv_scores):.6f})")
        
        return fold_models, cv_scores
    
    def train_final(self, X: pd.DataFrame, y: pd.Series, params: dict = None) -> xgb.XGBRegressor:
        """Train final model on full dataset"""
        if params is None:
            if self.best_params is None:
                raise ValueError("No parameters provided. Run tuning() first or provide params.")
            params = self.best_params
        
        print("\nTraining final model on full dataset...")
        y_transformed = np.log(y) + 1
        
        # Use a portion for validation (20%)
        split_idx = int(len(X) * 0.8)
        X_train, X_val = X.iloc[:split_idx], X.iloc[split_idx:]
        y_train, y_val = y_transformed.iloc[:split_idx], y_transformed.iloc[split_idx:]
        
        model = xgb.XGBRegressor(
            **params,
            random_state=self.random_state,
            n_estimators=N_ESTIMATORS,
            early_stopping_rounds=5,
            objective=OBJECTIVE
        )
        
        model.fit(
            X_train, 
            y_train,
            verbose=0,
            eval_set=[(X_val, y_val)]
        )
        
        self.final_model = model
        print("Final model training complete!")
        
        return model
    
    def predict(self, X: pd.DataFrame, inverse_transform: bool = True) -> np.ndarray:
        """Make predictions using the final model"""
        if self.final_model is None:
            raise ValueError("No model trained. Run train_final() first.")
        
        predictions = self.final_model.predict(X)
        
        if inverse_transform:
            # Inverse log transformation
            predictions = predictions
        
        return predictions

In [270]:
from sklearn.model_selection import KFold, cross_val_score
import pandas as pd
import numpy as np
import xgboost as xgb
import optuna
from optuna.trial import Trial

N_ESTIMATORS = 200
OBJECTIVE = 'reg:absoluteerror'
N_FOLDS = 5
RANDOM_STATE = 123

class ModelRegressorCV():
    
    def __init__(self, n_folds=N_FOLDS, random_state=RANDOM_STATE):
        self.n_folds = n_folds
        self.random_state = random_state
        self.best_params = None
        self.cv_scores = None
        self.final_model = None
        
    def objective(self, trial: Trial, X: pd.DataFrame, y: pd.Series) -> float:
        """Optuna objective with cross-validation"""
        params = {
            "learning_rate": trial.suggest_float("learning_rate", 1e-3, 0.1, log=True),
            "max_depth": trial.suggest_int("max_depth", 1, 10),
            "subsample": trial.suggest_float("subsample", 0.05, 1.0),
            "colsample_bytree": trial.suggest_float("colsample_bytree", 0.05, 1.0),
            "min_child_weight": trial.suggest_int("min_child_weight", 1, 20),
        }
        
        # Cross-validation with the suggested parameters
        kfold = KFold(n_splits=self.n_folds, shuffle=True, random_state=self.random_state)
        cv_scores = []
        
        for train_idx, val_idx in kfold.split(X):
            X_train_fold, X_val_fold = X.iloc[train_idx], X.iloc[val_idx]
            y_train_fold, y_val_fold = y.iloc[train_idx], y.iloc[val_idx]
            
            # Apply log transformation
            y_train_transformed = np.log(y_train_fold) + 1
            y_val_transformed = np.log(y_val_fold) + 1
            
            model = xgb.XGBRegressor(
                **params,
                random_state=self.random_state,
                n_estimators=N_ESTIMATORS,
                early_stopping_rounds=5,
                objective=OBJECTIVE
            )
            
            model.fit(
                X_train_fold, 
                y_train_transformed,
                verbose=0,
                eval_set=[(X_val_fold, y_val_transformed)]
            )
            
            y_pred = model.predict(X_val_fold)
            fold_mae = metrics.mean_absolute_error(y_val_transformed, y_pred)
            cv_scores.append(fold_mae)
        
        # Return mean CV score
        return np.mean(cv_scores)
    
    def tuning(self, X: pd.DataFrame, y: pd.Series, n_trials: int) -> dict:
        """Hyperparameter tuning with cross-validation"""
        print(f"Starting hyperparameter tuning with {n_trials} trials and {self.n_folds}-fold CV...")
        
        study = optuna.create_study(study_name='XGBoost_CV', direction='minimize')
        study.optimize(
            lambda trial: self.objective(trial, X, y), 
            n_trials=n_trials,
            show_progress_bar=True
        )
        
        self.best_params = study.best_params
        print(f"\nBest CV MAE: {study.best_value:.6f}")
        print(f"Best parameters: {self.best_params}")
        
        return self.best_params
    
    def train_with_cv(self, X: pd.DataFrame, y: pd.Series, params: dict = None) -> tuple:
        """Train model with cross-validation and return CV scores"""
        if params is None:
            if self.best_params is None:
                raise ValueError("No parameters provided. Run tuning() first or provide params.")
            params = self.best_params
        
        print(f"\nTraining with {self.n_folds}-fold cross-validation...")
        kfold = KFold(n_splits=self.n_folds, shuffle=True, random_state=self.random_state)
        
        cv_scores = []
        fold_models = []
        
        for fold_num, (train_idx, val_idx) in enumerate(kfold.split(X), 1):
            X_train_fold, X_val_fold = X.iloc[train_idx], X.iloc[val_idx]
            y_train_fold, y_val_fold = y.iloc[train_idx], y.iloc[val_idx]
            
            # Apply log transformation
            y_train_transformed = np.log(y_train_fold) + 1
            y_val_transformed = np.log(y_val_fold) + 1
            
            model = xgb.XGBRegressor(
                **params,
                random_state=self.random_state,
                n_estimators=N_ESTIMATORS,
                early_stopping_rounds=5,
                objective=OBJECTIVE
            )
            
            model.fit(
                X_train_fold, 
                y_train_transformed,
                verbose=0,
                eval_set=[(X_val_fold, y_val_transformed)]
            )
            
            y_pred = model.predict(X_val_fold)
            fold_mae = metrics.mean_absolute_error(y_val_transformed, y_pred)
            cv_scores.append(fold_mae)
            fold_models.append(model)
            
            print(f"Fold {fold_num}: MAE = {fold_mae:.6f}")
        
        self.cv_scores = cv_scores
        print(f"\nMean CV MAE: {np.mean(cv_scores):.6f} (+/- {np.std(cv_scores):.6f})")
        
        return fold_models, cv_scores
    
    def train_final(self, X: pd.DataFrame, y: pd.Series, params: dict = None) -> xgb.XGBRegressor:
        """Train final model on full dataset"""
        if params is None:
            if self.best_params is None:
                raise ValueError("No parameters provided. Run tuning() first or provide params.")
            params = self.best_params
        
        print("\nTraining final model on full dataset...")
        y_transformed = np.log(y) + 1
        
        # Use a portion for validation (20%)
        split_idx = int(len(X) * 0.8)
        X_train, X_val = X.iloc[:split_idx], X.iloc[split_idx:]
        y_train, y_val = y_transformed.iloc[:split_idx], y_transformed.iloc[split_idx:]
        
        model = xgb.XGBRegressor(
            **params,
            random_state=self.random_state,
            n_estimators=N_ESTIMATORS,
            early_stopping_rounds=5,
            objective=OBJECTIVE
        )
        
        model.fit(
            X_train, 
            y_train,
            verbose=0,
            eval_set=[(X_val, y_val)]
        )
        
        self.final_model = model
        print("Final model training complete!")
        
        return model
    
    def predict(self, X: pd.DataFrame, inverse_transform: bool = True) -> np.ndarray:
        """Make predictions using the final model"""
        if self.final_model is None:
            raise ValueError("No model trained. Run train_final() first.")
        
        predictions = self.final_model.predict(X)
        
        if inverse_transform:
            # Inverse log transformation
            predictions = np.exp(predictions - 1)
        
        return predictions

In [271]:
# encode category feats

In [272]:
model_features_class = ['X_age','X_bonus_malus_rating','X_distr_channel','X_vehicle_type','X_ttm_claims','X_policy_count','X_risk_code','X_vehicle_age','X_policy_tenure','X_policy_premium','U']

model_features_reg = ['X_age','X_bonus_malus_rating','X_distr_channel','X_vehicle_type','X_ttm_claims','X_policy_count','X_risk_code','X_vehicle_age','X_policy_tenure']

In [273]:
cat_cols = list(df_middle.select_dtypes('object').columns)

from sklearn.preprocessing import LabelEncoder
for cat in cat_cols:
    le = LabelEncoder()
    le.fit(df_middle[cat])
    df_middle[cat] = le.transform(df_middle[cat])
    df_middle_class[cat] = le.transform(df_middle_class[cat])

C:\Users\malosett\AppData\Local\Temp\ipykernel_13900\2776194888.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = list(df_middle.select_dtypes('object').columns)

## Section 6 — Dataset Preparation for XGBoost

Two filtered datasets are created from `df_sub`:

- **`df_middle`** — used for the **premium regressor** (target: `X_policy_premium`)  
- **`df_middle_class`** — used for the **churn classifier** (target: `is_churn`)

Both use identical `filter_middle_advanced` thresholds.  
Categorical columns (`X_distr_channel`, `X_risk_code`, `X_vehicle_type`) are **label-encoded** here so XGBoost can consume them directly.

The premium change ratio `U` is computed as:  
$$U = \frac{\text{upcoming\_premium} - \text{policy\_premium}}{\text{policy\_premium}}$$  
This is a core feature driving churn behaviour: larger premium increases lead to higher churn probability.  
`U` is later adjusted to `1 + U` (i.e., the *uplift factor*) for the optimisation module.

In [274]:
df_middle.columns

Index(['id', 'X_age', 'X_bonus_malus_rating', 'X_distr_channel',
       'X_vehicle_type', 'X_ttm_claims', 'X_policy_count', 'X_risk_code',
       'X_vehicle_age', 'X_policy_tenure', 'X_policy_premium',
       'X_prev_renewal_perc', 'X_upcoming_premium', 'X_cur_renewal_perc',
       'year', 'is_churn'],
      dtype='str')

In [275]:
df_middle['U'] = (df_middle['X_upcoming_premium'] - df_middle['X_policy_premium']) / df_middle['X_policy_premium']
df_middle_class['U'] = (df_middle_class['X_upcoming_premium'] - df_middle_class['X_policy_premium']) / df_middle_class['X_policy_premium']

In [276]:
# Split X and U so U stays untouched (policy-space representation)
u_cols = [
    col
    for col in ["id","U"]
    if col in df_middle_class.columns
]
U_raw = df_middle_class[u_cols].copy()

x_feature_cols = [col for col in model_features_class if col not in u_cols]
X_raw = df_middle_class[x_feature_cols].copy()

feature_processor = FeatureProcessor()
X_processed = feature_processor.fit_transform(X_raw)

print("U columns kept untouched:", u_cols)
print("U shape (untouched):", U_raw.shape)
print("X raw shape:", X_raw.shape)
print("X processed shape:", X_processed.shape)

# If needed downstream, concatenate untouched U with processed X
UX_processed = pd.concat([U_raw, X_processed], axis=1)
UX_processed.head()

U columns kept untouched: ['id', 'U']
U shape (untouched): (194373, 2)
X raw shape: (194373, 10)
X processed shape: (194373, 10)

,id,U,sphered__X_age,sphered__X_bonus_malus_rating,sphered__X_distr_channel,sphered__X_vehicle_type,sphered__X_ttm_claims,sphered__X_policy_count,sphered__X_risk_code,sphered__X_vehicle_age,sphered__X_policy_tenure,sphered__X_policy_premium
7,5,0.123099,2.298428,0.264406,-0.058562,2.621382,-0.185054,-1.160296,-0.066957,0.331389,5.691633,-0.384604
16,85,0.107047,1.401397,0.093772,-0.030788,-0.634504,-0.074525,-0.231868,-0.361906,-2.243026,5.951082,-0.377904
24,93,0.096895,1.283066,0.140256,-0.045808,-0.465812,-0.184750,-0.873439,-0.260413,0.094712,5.828775,-0.576589
32,119,0.097209,-0.679815,-0.108967,-0.019604,-0.393850,-0.271498,-0.805693,-0.255897,-0.007691,6.124242,-0.527929
118,395,0.102011,-0.667820,-0.063739,-1.088519,0.107791,-0.259477,0.729975,-0.156885,-0.507888,6.123292,-0.564618

In [277]:
model_features_class = ['X_age','X_bonus_malus_rating','X_distr_channel','X_vehicle_type','X_ttm_claims','X_policy_count','X_risk_code','X_vehicle_age','X_policy_tenure','X_policy_premium','U']

model_features_reg = ['X_age','X_bonus_malus_rating','X_distr_channel','X_vehicle_type','X_ttm_claims','X_policy_count','X_risk_code','X_vehicle_age','X_policy_tenure']

In [278]:
from sklearn.model_selection import KFold, cross_val_score
from sklearn import metrics
import pandas as pd
import numpy as np
import xgboost as xgb

# Assuming 'df' is your dataframe with the columns you mentioned
# First, filter to middle of distribution (using IQR method)
def filter_middle_distribution(df, multiplier=1.5):
    """Remove outliers using IQR method"""
    df_filtered = df.copy()
    
    # Select numeric columns, exclude ID and target
    numeric_cols = df.select_dtypes(include=['number']).columns
    numeric_cols = [col for col in numeric_cols if col not in ['encoded_policy_number', 'is_churn']]
    
    for col in numeric_cols:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1
        lower = Q1 - multiplier * IQR
        upper = Q3 + multiplier * IQR
        df_filtered = df_filtered[(df_filtered[col] >= lower) & (df_filtered[col] <= upper)]
    
    print(f"Original rows: {len(df)}, Filtered rows: {len(df_filtered)}")
    return df_filtered

# Apply filtering


# Separate features and target
X = df_middle.loc[:, model_features_reg]
y = df_middle['X_upcoming_premium']

# Initialize the model
model_regressor = ModelRegressor()

# Cross-validation approach 1: Using sklearn's cross_val_score
kfold = KFold(n_splits=5, shuffle=True, random_state=123)

# Simple CV without hyperparameter tuning
default_params = {
    'learning_rate': 0.01,
    'max_depth': 5,
    'subsample': 0.8,
    'colsample_bytree': 0.8,
    'min_child_weight': 1,
    'random_state': 123,
    'n_estimators': 200,
    'objective': 'reg:absoluteerror'
}

xgb_model = xgb.XGBRegressor(**default_params, enable_categorical=True)

# Perform cross-validation
# n_jobs=1: avoids joblib spawning worker processes that may pick up a
# different numpy version than the kernel, causing BrokenProcessPool.
cv_scores = cross_val_score(
    xgb_model, 
    X, 
    y,
    cv=kfold, 
    scoring='neg_mean_absolute_error',
    n_jobs=1
)

print(f"CV MAE Scores: {-cv_scores}")
print(f"Mean CV MAE: {-cv_scores.mean():.4f} (+/- {cv_scores.std():.4f})")

CV MAE Scores: [35.92597784 35.24692809 35.43542505 35.24695861 35.34396943]
Mean CV MAE: 35.4399 (+/- 0.2530)

In [279]:
df_middle.columns

Index(['id', 'X_age', 'X_bonus_malus_rating', 'X_distr_channel',
       'X_vehicle_type', 'X_ttm_claims', 'X_policy_count', 'X_risk_code',
       'X_vehicle_age', 'X_policy_tenure', 'X_policy_premium',
       'X_prev_renewal_perc', 'X_upcoming_premium', 'X_cur_renewal_perc',
       'year', 'is_churn', 'U'],
      dtype='str')

## Section 7 — XGBoost Policy Premium Regression (5-Fold OOF)

**Target variable:** `X_policy_premium` (current active premium, `Y`)  
**Features:** `model_features_reg` — 9 policy/client covariates (excluding premium-related features)

`cross_validate_with_oof_predictions` runs a **nested cross-validation**:
1. Outer KFold (5 splits) — for generating honest out-of-fold (OOF) predictions  
2. Inner 80/20 split — for Optuna hyperparameter tuning within each fold  

**Outputs stored in `df_middle`:**
- `fold_number` — which fold each row was validated in
- `oof_prediction` (`Y_hat`) — predicted policy premium  
- `oof_residual` / `oof_absolute_error` — residual diagnostics  

These OOF predictions are used as the regressor output in `df_exp_financial_loss_xgb_black_box.csv`.

In [280]:
df_middle['U'].describe()

count    194373.000000
mean          0.083095
std           0.029994
min          -0.001829
25%           0.061570
50%           0.094024
75%           0.103913
max           0.418037
Name: U, dtype: float64

In [281]:
from sklearn.model_selection import KFold
import pandas as pd
import numpy as np

def cross_validate_with_oof_predictions(X, y, n_splits=5, n_trials=30):
    """
    Perform cross-validation and generate out-of-fold predictions.
    FeatureProcessor is fit on each training fold and applied to both train and val
    to prevent data leakage.
    """
    kfold = KFold(n_splits=n_splits, shuffle=True, random_state=123)

    fold_numbers   = np.zeros(len(X))
    oof_predictions = np.zeros(len(X))

    fold_results        = []
    best_params_per_fold = []

    for fold_idx, (train_idx, val_idx) in enumerate(kfold.split(X)):
        print(f"\n{'='*50}")
        print(f"Fold {fold_idx + 1}/{n_splits}")
        print(f"{'='*50}")

        fold_numbers[val_idx] = fold_idx + 1

        X_train_fold, X_val_fold = X.iloc[train_idx], X.iloc[val_idx]
        y_train_fold, y_val_fold = y.iloc[train_idx], y.iloc[val_idx]

        # --- fit preprocessor on train fold only (no leakage) ---
        fp = FeatureProcessor()
        X_train_proc = fp.fit_transform(X_train_fold)
        X_val_proc   = fp.transform(X_val_fold)

        from sklearn.model_selection import train_test_split
        X_train_tune, X_val_tune, y_train_tune, y_val_tune = train_test_split(
            X_train_proc, y_train_fold, test_size=0.2, random_state=123
        )

        model_reg   = ModelRegressor()
        best_params = model_reg.tuning(
            X_train_tune, y_train_tune,
            X_val_tune,   y_val_tune,
            n_trials=n_trials
        )

        print(f"Best params for fold {fold_idx + 1}: {best_params}")
        best_params_per_fold.append(best_params)

        final_model = model_reg.train(
            X_train_proc, y_train_fold,
            X_val_proc,   y_val_fold,
            best_params
        )

        y_pred_log = final_model.predict(X_val_proc)
        oof_predictions[val_idx] = y_pred_log

        mae_log      = metrics.mean_absolute_error(y_val_fold, y_pred_log)
        mae_original = metrics.mean_absolute_error(y_val_fold, oof_predictions[val_idx])

        fold_results.append({
            'fold':               fold_idx + 1,
            'mae_log_scale':      mae_log,
            'mae_original_scale': mae_original,
            'n_train':            len(train_idx),
            'n_val':              len(val_idx)
        })

        print(f"Fold {fold_idx + 1} MAE (log scale):      {mae_log:.4f}")
        print(f"Fold {fold_idx + 1} MAE (original scale): {mae_original:.4f}")

    results_df = pd.DataFrame(fold_results)

    print(f"\n{'='*50}")
    print("Cross-Validation Summary")
    print(f"{'='*50}")
    print(f"Mean MAE (log scale):      {results_df['mae_log_scale'].mean():.4f} (+/- {results_df['mae_log_scale'].std():.4f})")
    print(f"Mean MAE (original scale): {results_df['mae_original_scale'].mean():.4f} (+/- {results_df['mae_original_scale'].std():.4f})")

    overall_oof_mae = metrics.mean_absolute_error(y, oof_predictions)
    print(f"\nOverall OOF MAE: {overall_oof_mae:.4f}")

    return fold_numbers, oof_predictions, results_df, best_params_per_fold


X = df_middle.loc[:, model_features_reg]
y = df_middle['X_policy_premium']

fold_numbers, oof_predictions, results_df, best_params_list = cross_validate_with_oof_predictions(
    X, y, n_splits=5, n_trials=30
)

df_middle['fold_number']    = fold_numbers.astype(int)
df_middle['oof_prediction'] = oof_predictions
df_middle['oof_residual']       = df_middle['X_policy_premium'] - df_middle['oof_prediction']
df_middle['oof_absolute_error'] = np.abs(df_middle['oof_residual'])

print("\nSample of dataframe with OOF predictions:")
print(df_middle[['id', 'is_churn', 'fold_number', 'oof_prediction', 'oof_residual']].head(10))

print("\nOOF Performance by Fold:")
fold_summary = df_middle.groupby('fold_number').agg({
    'is_churn':            'count',
    'oof_absolute_error':  'mean'
}).rename(columns={'is_churn': 'count', 'oof_absolute_error': 'mae'})
print(fold_summary)

==================================================
Fold 1/5
==================================================

[I 2026-04-07 20:17:09,956] A new study created in memory with name: Xgboost
[I 2026-04-07 20:17:15,657] Trial 0 finished with value: 31.45591211562806 and parameters: {'learning_rate': 0.06192300299095742, 'max_depth': 2, 'subsample': 0.3575471836396081, 'colsample_bytree': 0.8858131915291948, 'min_child_weight': 19}. Best is trial 0 with value: 31.45591211562806.
[I 2026-04-07 20:17:18,512] Trial 1 finished with value: 39.04611370320586 and parameters: {'learning_rate': 0.004209220818771749, 'max_depth': 1, 'subsample': 0.07038683062668837, 'colsample_bytree': 0.8164818836543422, 'min_child_weight': 19}. Best is trial 0 with value: 31.45591211562806.
[I 2026-04-07 20:17:22,983] Trial 2 finished with value: 40.284401545971434 and parameters: {'learning_rate': 0.002522159700290059, 'max_depth': 4, 'subsample': 0.40454116178946314, 'colsample_bytree': 0.2027090819939552, 'min_child_weight': 4}. Best is trial 0 with value: 31.45591211562806.
[I 2026-04-07 20:17:27,188] Trial 3 finished with value: 37.053993723365124 and parameters: {'learning_rate': 0.009922252953940154, 'max_depth': 7, 'subsample': 0.349059009672956, 'colsample_bytree': 0.15088186820135674, 'min_child_weight': 7}. Best is trial 0 with value: 31.45591211562806.
[I 2026-04-07 20:17:35,800] Trial 4 finished with value: 32.22574552502638 and parameters: {'learning_rate': 0.09648949579119609, 'max_depth': 1, 'subsample': 0.6195582334043347, 'colsample_bytree': 0.6847823550385381, 'min_child_weight': 5}. Best is trial 0 with value: 31.45591211562806.
[I 2026-04-07 20:17:39,884] Trial 5 finished with value: 36.06700519520887 and parameters: {'learning_rate': 0.008961544505175374, 'max_depth': 3, 'subsample': 0.37034725712674044, 'colsample_bytree': 0.25754145567605713, 'min_child_weight': 13}. Best is trial 0 with value: 31.45591211562806.
[I 2026-04-07 20:17:44,759] Trial 6 finished with value: 40.61115207544652 and parameters: {'learning_rate': 0.0020458676980528454, 'max_depth': 3, 'subsample': 0.524284004196471, 'colsample_bytree': 0.13445795254923884, 'min_child_weight': 19}. Best is trial 0 with value: 31.45591211562806.
[I 2026-04-07 20:17:50,278] Trial 7 finished with value: 30.82830939199643 and parameters: {'learning_rate': 0.09152835015076606, 'max_depth': 4, 'subsample': 0.5086237124888544, 'colsample_bytree': 0.5150991355625234, 'min_child_weight': 10}. Best is trial 7 with value: 30.82830939199643.
[I 2026-04-07 20:17:57,021] Trial 8 finished with value: 34.12821534495186 and parameters: {'learning_rate': 0.026070223771201485, 'max_depth': 1, 'subsample': 0.4718579065445458, 'colsample_bytree': 0.9025126341800442, 'min_child_weight': 13}. Best is trial 7 with value: 30.82830939199643.
[I 2026-04-07 20:18:03,237] Trial 9 finished with value: 40.02124714238737 and parameters: {'learning_rate': 0.0013157354167732088, 'max_depth': 3, 'subsample': 0.9200179727063591, 'colsample_bytree': 0.5115892256370131, 'min_child_weight': 16}. Best is trial 7 with value: 30.82830939199643.
[I 2026-04-07 20:18:10,365] Trial 10 finished with value: 31.13725515466976 and parameters: {'learning_rate': 0.03333385895462644, 'max_depth': 10, 'subsample': 0.8307530393759384, 'colsample_bytree': 0.44017680345066784, 'min_child_weight': 1}. Best is trial 7 with value: 30.82830939199643.
[I 2026-04-07 20:18:17,242] Trial 11 finished with value: 31.06266375647247 and parameters: {'learning_rate': 0.03675334012792752, 'max_depth': 10, 'subsample': 0.7971948811178822, 'colsample_bytree': 0.37660712543141406, 'min_child_weight': 9}. Best is trial 7 with value: 30.82830939199643.
[I 2026-04-07 20:18:22,694] Trial 12 finished with value: 31.00861729516876 and parameters: {'learning_rate': 0.03460559794109988, 'max_depth': 7, 'subsample': 0.7071202141271661, 'colsample_bytree': 0.3407686593375192, 'min_child_weight': 10}. Best is trial 7 with value: 30.82830939199643.
[I 2026-04-07 20:18:27,799] Trial 13 finished with value: 31.24941589156859 and parameters: {'learning_rate': 0.01913987441364331, 'max_depth': 6, 'subsample': 0.6830468233391701, 'colsample_bytree': 0.6197279394229718, 'min_child_weight': 10}. Best is trial 7 with value: 30.82830939199643.
[I 2026-04-07 20:18:30,085] Trial 14 finished with value: 31.1462070874883 and parameters: {'learning_rate': 0.09526056937602441, 'max_depth': 8, 'subsample': 0.19627239090822662, 'colsample_bytree': 0.3397369492453906, 'min_child_weight': 13}. Best is trial 7 with value: 30.82830939199643.
[I 2026-04-07 20:18:35,148] Trial 15 finished with value: 32.43548851576512 and parameters: {'learning_rate': 0.05179233425324325, 'max_depth': 5, 'subsample': 0.6402053156495728, 'colsample_bytree': 0.051817309615022844, 'min_child_weight': 8}. Best is trial 7 with value: 30.82830939199643.
[I 2026-04-07 20:18:41,316] Trial 16 finished with value: 31.32354608331319 and parameters: {'learning_rate': 0.015337006811365062, 'max_depth': 8, 'subsample': 0.9889325404046033, 'colsample_bytree': 0.607968974155017, 'min_child_weight': 12}. Best is trial 7 with value: 30.82830939199643.
[I 2026-04-07 20:18:48,942] Trial 17 finished with value: 30.74119182527617 and parameters: {'learning_rate': 0.05790410286268522, 'max_depth': 5, 'subsample': 0.7493487988283295, 'colsample_bytree': 0.7567989788312635, 'min_child_weight': 16}. Best is trial 17 with value: 30.74119182527617.
[I 2026-04-07 20:18:54,257] Trial 18 finished with value: 34.196756390158704 and parameters: {'learning_rate': 0.006089437608765388, 'max_depth': 5, 'subsample': 0.5795763329704693, 'colsample_bytree': 0.6685111526128318, 'min_child_weight': 16}. Best is trial 17 with value: 30.74119182527617.
[I 2026-04-07 20:19:01,667] Trial 19 finished with value: 30.87188384100479 and parameters: {'learning_rate': 0.05600077093504676, 'max_depth': 4, 'subsample': 0.7872457669961404, 'colsample_bytree': 0.7887348680691838, 'min_child_weight': 16}. Best is trial 17 with value: 30.74119182527617.
[I 2026-04-07 20:19:06,606] Trial 20 finished with value: 31.560550804688287 and parameters: {'learning_rate': 0.018622649273632382, 'max_depth': 6, 'subsample': 0.2138609131190744, 'colsample_bytree': 0.5282274935745762, 'min_child_weight': 15}. Best is trial 17 with value: 30.74119182527617.
[I 2026-04-07 20:19:14,161] Trial 21 finished with value: 30.83398901814491 and parameters: {'learning_rate': 0.06202230880859705, 'max_depth': 4, 'subsample': 0.7954756418082161, 'colsample_bytree': 0.7848281352877006, 'min_child_weight': 17}. Best is trial 17 with value: 30.74119182527617.
[I 2026-04-07 20:19:21,205] Trial 22 finished with value: 30.823267561619208 and parameters: {'learning_rate': 0.06569005607726576, 'max_depth': 4, 'subsample': 0.7303623081138153, 'colsample_bytree': 0.9911794627714066, 'min_child_weight': 18}. Best is trial 17 with value: 30.74119182527617.
[I 2026-04-07 20:19:26,798] Trial 23 finished with value: 30.7195486130273 and parameters: {'learning_rate': 0.08197147110029573, 'max_depth': 5, 'subsample': 0.5361485113765887, 'colsample_bytree': 0.9625949348682726, 'min_child_weight': 20}. Best is trial 23 with value: 30.7195486130273.
[I 2026-04-07 20:19:33,199] Trial 24 finished with value: 30.772643198946348 and parameters: {'learning_rate': 0.052263431658514145, 'max_depth': 5, 'subsample': 0.7268736688677122, 'colsample_bytree': 0.976467675184408, 'min_child_weight': 20}. Best is trial 23 with value: 30.7195486130273.
[I 2026-04-07 20:19:39,706] Trial 25 finished with value: 30.753053029348294 and parameters: {'learning_rate': 0.038091007870621474, 'max_depth': 6, 'subsample': 0.8882978281047276, 'colsample_bytree': 0.9899709149722193, 'min_child_weight': 20}. Best is trial 23 with value: 30.7195486130273.
[I 2026-04-07 20:19:45,942] Trial 26 finished with value: 30.872945629508752 and parameters: {'learning_rate': 0.026428091860165624, 'max_depth': 6, 'subsample': 0.8942829800120486, 'colsample_bytree': 0.8968552395978001, 'min_child_weight': 18}. Best is trial 23 with value: 30.7195486130273.
[I 2026-04-07 20:19:51,851] Trial 27 finished with value: 31.20826586826219 and parameters: {'learning_rate': 0.014588936999091598, 'max_depth': 7, 'subsample': 0.9081920676698806, 'colsample_bytree': 0.9996503303234725, 'min_child_weight': 20}. Best is trial 23 with value: 30.7195486130273.
[I 2026-04-07 20:19:59,151] Trial 28 finished with value: 30.69341272204237 and parameters: {'learning_rate': 0.038751445826578565, 'max_depth': 8, 'subsample': 0.9976837478996017, 'colsample_bytree': 0.7319195288717291, 'min_child_weight': 15}. Best is trial 28 with value: 30.69341272204237.
[I 2026-04-07 20:20:02,522] Trial 29 finished with value: 30.86848893575726 and parameters: {'learning_rate': 0.08070754556345712, 'max_depth': 9, 'subsample': 0.43516516924212856, 'colsample_bytree': 0.7196374012788415, 'min_child_weight': 14}. Best is trial 28 with value: 30.69341272204237.

Best params for fold 1: {'learning_rate': 0.038751445826578565, 'max_depth': 8, 'subsample': 0.9976837478996017, 'colsample_bytree': 0.7319195288717291, 'min_child_weight': 15}

[I 2026-04-07 20:20:11,838] A new study created in memory with name: Xgboost

Fold 1 MAE (log scale):      31.2250
Fold 1 MAE (original scale): 31.2250

==================================================
Fold 2/5
==================================================

[I 2026-04-07 20:20:19,296] Trial 0 finished with value: 37.7880958898706 and parameters: {'learning_rate': 0.004095798367687468, 'max_depth': 10, 'subsample': 0.6263145507989707, 'colsample_bytree': 0.23235708089597895, 'min_child_weight': 5}. Best is trial 0 with value: 37.7880958898706.
[I 2026-04-07 20:20:24,302] Trial 1 finished with value: 33.552606499189864 and parameters: {'learning_rate': 0.015968591152034417, 'max_depth': 2, 'subsample': 0.3436146764069821, 'colsample_bytree': 0.5551573579839936, 'min_child_weight': 16}. Best is trial 1 with value: 33.552606499189864.
[I 2026-04-07 20:20:30,841] Trial 2 finished with value: 40.48811565874714 and parameters: {'learning_rate': 0.0012277367209131112, 'max_depth': 6, 'subsample': 0.9295995193085286, 'colsample_bytree': 0.2990012922266816, 'min_child_weight': 20}. Best is trial 1 with value: 33.552606499189864.
[I 2026-04-07 20:20:35,613] Trial 3 finished with value: 32.080777290834284 and parameters: {'learning_rate': 0.03239763231867062, 'max_depth': 2, 'subsample': 0.28949886069361475, 'colsample_bytree': 0.6478244447957658, 'min_child_weight': 2}. Best is trial 3 with value: 32.080777290834284.
[I 2026-04-07 20:20:43,422] Trial 4 finished with value: 39.39003170733976 and parameters: {'learning_rate': 0.002316866404851496, 'max_depth': 2, 'subsample': 0.751982347673423, 'colsample_bytree': 0.5434102582301338, 'min_child_weight': 16}. Best is trial 3 with value: 32.080777290834284.
[I 2026-04-07 20:20:50,443] Trial 5 finished with value: 36.567578400670875 and parameters: {'learning_rate': 0.011756596503641551, 'max_depth': 7, 'subsample': 0.9590134612218415, 'colsample_bytree': 0.22010998345389465, 'min_child_weight': 11}. Best is trial 3 with value: 32.080777290834284.
[I 2026-04-07 20:20:55,602] Trial 6 finished with value: 36.9441446867927 and parameters: {'learning_rate': 0.0026252845410956027, 'max_depth': 7, 'subsample': 0.3433741281740207, 'colsample_bytree': 0.7201885067644599, 'min_child_weight': 6}. Best is trial 3 with value: 32.080777290834284.
[I 2026-04-07 20:21:02,054] Trial 7 finished with value: 40.93503666605722 and parameters: {'learning_rate': 0.0011558517958332138, 'max_depth': 1, 'subsample': 0.42478537075980694, 'colsample_bytree': 0.6666186579234162, 'min_child_weight': 4}. Best is trial 3 with value: 32.080777290834284.
[I 2026-04-07 20:21:05,916] Trial 8 finished with value: 39.02593560117784 and parameters: {'learning_rate': 0.002719317746924578, 'max_depth': 9, 'subsample': 0.07048907925629139, 'colsample_bytree': 0.23610406045362647, 'min_child_weight': 20}. Best is trial 3 with value: 32.080777290834284.
[I 2026-04-07 20:21:10,034] Trial 9 finished with value: 30.92409164820749 and parameters: {'learning_rate': 0.07007518413380008, 'max_depth': 5, 'subsample': 0.2897040583122053, 'colsample_bytree': 0.47223867820311755, 'min_child_weight': 1}. Best is trial 9 with value: 30.92409164820749.
[I 2026-04-07 20:21:12,510] Trial 10 finished with value: 31.18664163355277 and parameters: {'learning_rate': 0.07436571236996843, 'max_depth': 4, 'subsample': 0.05301872621779563, 'colsample_bytree': 0.952533620061131, 'min_child_weight': 9}. Best is trial 9 with value: 30.92409164820749.
[I 2026-04-07 20:21:14,644] Trial 11 finished with value: 31.09438628622662 and parameters: {'learning_rate': 0.09066583425344103, 'max_depth': 4, 'subsample': 0.09769575031669087, 'colsample_bytree': 0.9848630346004557, 'min_child_weight': 9}. Best is trial 9 with value: 30.92409164820749.
[I 2026-04-07 20:21:17,152] Trial 12 finished with value: 31.012902104805015 and parameters: {'learning_rate': 0.09994877256010126, 'max_depth': 4, 'subsample': 0.181541035435618, 'colsample_bytree': 0.8630738233660269, 'min_child_weight': 1}. Best is trial 9 with value: 30.92409164820749.
[I 2026-04-07 20:21:20,902] Trial 13 finished with value: 31.327708482065475 and parameters: {'learning_rate': 0.03962015914304566, 'max_depth': 4, 'subsample': 0.20962182993068362, 'colsample_bytree': 0.3748667313405824, 'min_child_weight': 1}. Best is trial 9 with value: 30.92409164820749.
[I 2026-04-07 20:21:25,538] Trial 14 finished with value: 32.8326744013923 and parameters: {'learning_rate': 0.042203160483084395, 'max_depth': 5, 'subsample': 0.5107576241322398, 'colsample_bytree': 0.0584542263498678, 'min_child_weight': 1}. Best is trial 9 with value: 30.92409164820749.
[I 2026-04-07 20:21:29,183] Trial 15 finished with value: 31.10090677598056 and parameters: {'learning_rate': 0.022120063150716303, 'max_depth': 6, 'subsample': 0.21193082904577398, 'colsample_bytree': 0.8177508667786786, 'min_child_weight': 7}. Best is trial 9 with value: 30.92409164820749.
[I 2026-04-07 20:21:33,282] Trial 16 finished with value: 35.14783308003574 and parameters: {'learning_rate': 0.006645036270035686, 'max_depth': 8, 'subsample': 0.2144673794436487, 'colsample_bytree': 0.42591763821088946, 'min_child_weight': 3}. Best is trial 9 with value: 30.92409164820749.
[I 2026-04-07 20:21:39,049] Trial 17 finished with value: 31.125766925988888 and parameters: {'learning_rate': 0.06140077309633503, 'max_depth': 3, 'subsample': 0.5070778825632646, 'colsample_bytree': 0.8298215044735305, 'min_child_weight': 12}. Best is trial 9 with value: 30.92409164820749.
[I 2026-04-07 20:21:44,398] Trial 18 finished with value: 31.56746423870084 and parameters: {'learning_rate': 0.02570203554195462, 'max_depth': 5, 'subsample': 0.6446534656556264, 'colsample_bytree': 0.439656464465511, 'min_child_weight': 7}. Best is trial 9 with value: 30.92409164820749.
[I 2026-04-07 20:21:49,942] Trial 19 finished with value: 31.001335770285653 and parameters: {'learning_rate': 0.095934551728261, 'max_depth': 3, 'subsample': 0.42483585125479517, 'colsample_bytree': 0.8361312649468109, 'min_child_weight': 4}. Best is trial 9 with value: 30.92409164820749.
[I 2026-04-07 20:21:56,584] Trial 20 finished with value: 32.97819679191212 and parameters: {'learning_rate': 0.04733802511790777, 'max_depth': 1, 'subsample': 0.42188195999150463, 'colsample_bytree': 0.6112391003638252, 'min_child_weight': 4}. Best is trial 9 with value: 30.92409164820749.
[I 2026-04-07 20:22:00,019] Trial 21 finished with value: 31.06726024503162 and parameters: {'learning_rate': 0.09976340354487233, 'max_depth': 3, 'subsample': 0.15713807907949054, 'colsample_bytree': 0.8138842687113141, 'min_child_weight': 1}. Best is trial 9 with value: 30.92409164820749.
[I 2026-04-07 20:22:04,885] Trial 22 finished with value: 31.10262257688899 and parameters: {'learning_rate': 0.06045494524270583, 'max_depth': 3, 'subsample': 0.29672857712705236, 'colsample_bytree': 0.9116390409546891, 'min_child_weight': 3}. Best is trial 9 with value: 30.92409164820749.
[I 2026-04-07 20:22:09,513] Trial 23 finished with value: 30.87200905722625 and parameters: {'learning_rate': 0.06223216910265167, 'max_depth': 5, 'subsample': 0.4326149287951272, 'colsample_bytree': 0.7234438693878082, 'min_child_weight': 3}. Best is trial 23 with value: 30.87200905722625.
[I 2026-04-07 20:22:14,881] Trial 24 finished with value: 30.881722944277843 and parameters: {'learning_rate': 0.05732945686269924, 'max_depth': 5, 'subsample': 0.42206240192735944, 'colsample_bytree': 0.7417704434321621, 'min_child_weight': 5}. Best is trial 23 with value: 30.87200905722625.
[I 2026-04-07 20:22:20,255] Trial 25 finished with value: 31.005046317130034 and parameters: {'learning_rate': 0.021139966009159242, 'max_depth': 7, 'subsample': 0.6272179314154935, 'colsample_bytree': 0.7385659920112675, 'min_child_weight': 6}. Best is trial 23 with value: 30.87200905722625.
[I 2026-04-07 20:22:25,875] Trial 26 finished with value: 30.869230319397168 and parameters: {'learning_rate': 0.054955641765266315, 'max_depth': 5, 'subsample': 0.5624589736683036, 'colsample_bytree': 0.735265333534257, 'min_child_weight': 8}. Best is trial 26 with value: 30.869230319397168.
[I 2026-04-07 20:22:31,472] Trial 27 finished with value: 32.1575369835209 and parameters: {'learning_rate': 0.010656916242333479, 'max_depth': 6, 'subsample': 0.7632174875055329, 'colsample_bytree': 0.7456910797852253, 'min_child_weight': 8}. Best is trial 26 with value: 30.869230319397168.
[I 2026-04-07 20:22:36,538] Trial 28 finished with value: 31.026283160577023 and parameters: {'learning_rate': 0.03243585349815199, 'max_depth': 5, 'subsample': 0.5644135370855163, 'colsample_bytree': 0.597720248278703, 'min_child_weight': 13}. Best is trial 26 with value: 30.869230319397168.
[I 2026-04-07 20:22:43,627] Trial 29 finished with value: 33.48720885479128 and parameters: {'learning_rate': 0.005878128478668964, 'max_depth': 10, 'subsample': 0.7108625180799324, 'colsample_bytree': 0.6964786714361297, 'min_child_weight': 5}. Best is trial 26 with value: 30.869230319397168.

Best params for fold 2: {'learning_rate': 0.054955641765266315, 'max_depth': 5, 'subsample': 0.5624589736683036, 'colsample_bytree': 0.735265333534257, 'min_child_weight': 8}

[I 2026-04-07 20:22:51,066] A new study created in memory with name: Xgboost

Fold 2 MAE (log scale):      30.6780
Fold 2 MAE (original scale): 30.6780

==================================================
Fold 3/5
==================================================

[I 2026-04-07 20:22:56,745] Trial 0 finished with value: 30.881124166836358 and parameters: {'learning_rate': 0.04857461850809395, 'max_depth': 7, 'subsample': 0.7731751210944946, 'colsample_bytree': 0.6605622350236693, 'min_child_weight': 5}. Best is trial 0 with value: 30.881124166836358.
[I 2026-04-07 20:23:01,057] Trial 1 finished with value: 40.07425603363802 and parameters: {'learning_rate': 0.0011314657628139998, 'max_depth': 9, 'subsample': 0.07950981897917916, 'colsample_bytree': 0.3715681121477664, 'min_child_weight': 8}. Best is trial 0 with value: 30.881124166836358.
[I 2026-04-07 20:23:11,956] Trial 2 finished with value: 35.93284045175672 and parameters: {'learning_rate': 0.014584139900039178, 'max_depth': 1, 'subsample': 0.9324254325822792, 'colsample_bytree': 0.402601053033832, 'min_child_weight': 15}. Best is trial 0 with value: 30.881124166836358.
[I 2026-04-07 20:23:17,527] Trial 3 finished with value: 37.116978273014375 and parameters: {'learning_rate': 0.009666705162712995, 'max_depth': 9, 'subsample': 0.8935850570936629, 'colsample_bytree': 0.18351490724383251, 'min_child_weight': 1}. Best is trial 0 with value: 30.881124166836358.
[I 2026-04-07 20:23:21,499] Trial 4 finished with value: 37.99544013781307 and parameters: {'learning_rate': 0.007276471415034126, 'max_depth': 6, 'subsample': 0.2965967022086984, 'colsample_bytree': 0.16701102627900577, 'min_child_weight': 2}. Best is trial 0 with value: 30.881124166836358.
[I 2026-04-07 20:23:25,775] Trial 5 finished with value: 34.67979533196766 and parameters: {'learning_rate': 0.003974338317237199, 'max_depth': 8, 'subsample': 0.16277059438175007, 'colsample_bytree': 0.9017253812701221, 'min_child_weight': 12}. Best is trial 0 with value: 30.881124166836358.
[I 2026-04-07 20:23:28,893] Trial 6 finished with value: 30.90431379394767 and parameters: {'learning_rate': 0.06966566723189904, 'max_depth': 9, 'subsample': 0.8934663130064026, 'colsample_bytree': 0.8953278570948564, 'min_child_weight': 10}. Best is trial 0 with value: 30.881124166836358.
[I 2026-04-07 20:23:33,037] Trial 7 finished with value: 33.56495887404385 and parameters: {'learning_rate': 0.014404155957697189, 'max_depth': 9, 'subsample': 0.1856819896140246, 'colsample_bytree': 0.24194858313388673, 'min_child_weight': 17}. Best is trial 0 with value: 30.881124166836358.
[I 2026-04-07 20:23:36,579] Trial 8 finished with value: 35.334515938901255 and parameters: {'learning_rate': 0.007587404482212443, 'max_depth': 4, 'subsample': 0.22505418230701374, 'colsample_bytree': 0.40503627786947577, 'min_child_weight': 5}. Best is trial 0 with value: 30.881124166836358.
[I 2026-04-07 20:23:42,775] Trial 9 finished with value: 37.97431871937644 and parameters: {'learning_rate': 0.0022398394288311338, 'max_depth': 10, 'subsample': 0.45170510322426566, 'colsample_bytree': 0.46328693780406355, 'min_child_weight': 8}. Best is trial 0 with value: 30.881124166836358.
[I 2026-04-07 20:23:48,043] Trial 10 finished with value: 30.934886471547408 and parameters: {'learning_rate': 0.08439794636729676, 'max_depth': 5, 'subsample': 0.6681912836460756, 'colsample_bytree': 0.7001036846043877, 'min_child_weight': 5}. Best is trial 0 with value: 30.881124166836358.
[I 2026-04-07 20:23:51,377] Trial 11 finished with value: 30.874699401110096 and parameters: {'learning_rate': 0.084866834587964, 'max_depth': 7, 'subsample': 0.7258069321640874, 'colsample_bytree': 0.9643156618666694, 'min_child_weight': 12}. Best is trial 11 with value: 30.874699401110096.
[I 2026-04-07 20:23:56,518] Trial 12 finished with value: 30.870109435415777 and parameters: {'learning_rate': 0.03689177210813512, 'max_depth': 7, 'subsample': 0.6808817871963602, 'colsample_bytree': 0.6679806932367334, 'min_child_weight': 13}. Best is trial 12 with value: 30.870109435415777.
[I 2026-04-07 20:24:02,581] Trial 13 finished with value: 31.48302877633029 and parameters: {'learning_rate': 0.03667691731924111, 'max_depth': 3, 'subsample': 0.5748325301299467, 'colsample_bytree': 0.9790784522062239, 'min_child_weight': 14}. Best is trial 12 with value: 30.870109435415777.
[I 2026-04-07 20:24:08,697] Trial 14 finished with value: 30.919764306493438 and parameters: {'learning_rate': 0.028094099144552017, 'max_depth': 7, 'subsample': 0.7145661823190705, 'colsample_bytree': 0.6802956129269448, 'min_child_weight': 20}. Best is trial 12 with value: 30.870109435415777.
[I 2026-04-07 20:24:13,902] Trial 15 finished with value: 31.12192518623259 and parameters: {'learning_rate': 0.023165291689208348, 'max_depth': 6, 'subsample': 0.4378763049402946, 'colsample_bytree': 0.8154532666446633, 'min_child_weight': 12}. Best is trial 12 with value: 30.870109435415777.
[I 2026-04-07 20:24:20,131] Trial 16 finished with value: 30.85724969786145 and parameters: {'learning_rate': 0.05513225854611371, 'max_depth': 7, 'subsample': 0.5927005129906887, 'colsample_bytree': 0.5879703055303891, 'min_child_weight': 17}. Best is trial 16 with value: 30.85724969786145.
[I 2026-04-07 20:24:26,539] Trial 17 finished with value: 31.1297632861124 and parameters: {'learning_rate': 0.04493970178904295, 'max_depth': 4, 'subsample': 0.6037075684790649, 'colsample_bytree': 0.5713955668162847, 'min_child_weight': 19}. Best is trial 16 with value: 30.85724969786145.
[I 2026-04-07 20:24:31,988] Trial 18 finished with value: 31.57028505578888 and parameters: {'learning_rate': 0.019030260868786376, 'max_depth': 5, 'subsample': 0.454718612796778, 'colsample_bytree': 0.5585936856445213, 'min_child_weight': 17}. Best is trial 16 with value: 30.85724969786145.
[I 2026-04-07 20:24:36,375] Trial 19 finished with value: 30.85383391269892 and parameters: {'learning_rate': 0.05414866673973233, 'max_depth': 8, 'subsample': 0.823049193976364, 'colsample_bytree': 0.7699943657287786, 'min_child_weight': 15}. Best is trial 19 with value: 30.85383391269892.
[I 2026-04-07 20:24:40,338] Trial 20 finished with value: 30.93568410430143 and parameters: {'learning_rate': 0.05876556561266329, 'max_depth': 10, 'subsample': 0.9994735232778282, 'colsample_bytree': 0.7903983737194148, 'min_child_weight': 16}. Best is trial 19 with value: 30.85383391269892.
[I 2026-04-07 20:24:47,770] Trial 21 finished with value: 30.871000165514786 and parameters: {'learning_rate': 0.03581833358459558, 'max_depth': 8, 'subsample': 0.7921999428871422, 'colsample_bytree': 0.7779510671395053, 'min_child_weight': 14}. Best is trial 19 with value: 30.85383391269892.
[I 2026-04-07 20:24:51,371] Trial 22 finished with value: 30.92188525805703 and parameters: {'learning_rate': 0.09913095673673135, 'max_depth': 8, 'subsample': 0.6383858320796283, 'colsample_bytree': 0.6153506483437637, 'min_child_weight': 18}. Best is trial 19 with value: 30.85383391269892.
[I 2026-04-07 20:24:58,146] Trial 23 finished with value: 30.932537724389178 and parameters: {'learning_rate': 0.0284722138897643, 'max_depth': 7, 'subsample': 0.8154934664673488, 'colsample_bytree': 0.7671592833998715, 'min_child_weight': 14}. Best is trial 19 with value: 30.85383391269892.
[I 2026-04-07 20:25:04,423] Trial 24 finished with value: 30.900049737206558 and parameters: {'learning_rate': 0.056853198906326306, 'max_depth': 6, 'subsample': 0.53298924494465, 'colsample_bytree': 0.49326873402456733, 'min_child_weight': 10}. Best is trial 19 with value: 30.85383391269892.
[I 2026-04-07 20:25:10,103] Trial 25 finished with value: 35.11373810037477 and parameters: {'learning_rate': 0.01824356439058971, 'max_depth': 8, 'subsample': 0.33699710859508725, 'colsample_bytree': 0.05602579754271214, 'min_child_weight': 16}. Best is trial 19 with value: 30.85383391269892.
[I 2026-04-07 20:25:16,675] Trial 26 finished with value: 30.84630594400623 and parameters: {'learning_rate': 0.04017394781240316, 'max_depth': 7, 'subsample': 0.8399884751182012, 'colsample_bytree': 0.7232625340392187, 'min_child_weight': 20}. Best is trial 26 with value: 30.84630594400623.
[I 2026-04-07 20:25:28,235] Trial 27 finished with value: 32.73380311878815 and parameters: {'learning_rate': 0.06493656650420526, 'max_depth': 1, 'subsample': 0.8533660018457458, 'colsample_bytree': 0.8290513067012781, 'min_child_weight': 19}. Best is trial 26 with value: 30.84630594400623.
[I 2026-04-07 20:25:34,463] Trial 28 finished with value: 31.171775344721066 and parameters: {'learning_rate': 0.02685762318451149, 'max_depth': 5, 'subsample': 0.9875384513130971, 'colsample_bytree': 0.7328852175671848, 'min_child_weight': 20}. Best is trial 26 with value: 30.84630594400623.
[I 2026-04-07 20:25:40,161] Trial 29 finished with value: 30.89871811904211 and parameters: {'learning_rate': 0.04580450730752124, 'max_depth': 6, 'subsample': 0.7323522538922073, 'colsample_bytree': 0.622026994686416, 'min_child_weight': 18}. Best is trial 26 with value: 30.84630594400623.

Best params for fold 3: {'learning_rate': 0.04017394781240316, 'max_depth': 7, 'subsample': 0.8399884751182012, 'colsample_bytree': 0.7232625340392187, 'min_child_weight': 20}

[I 2026-04-07 20:25:47,976] A new study created in memory with name: Xgboost

Fold 3 MAE (log scale):      30.8123
Fold 3 MAE (original scale): 30.8123

==================================================
Fold 4/5
==================================================

[I 2026-04-07 20:25:54,181] Trial 0 finished with value: 32.42759219248212 and parameters: {'learning_rate': 0.08692567877151777, 'max_depth': 10, 'subsample': 0.83201710576586, 'colsample_bytree': 0.156555177078099, 'min_child_weight': 14}. Best is trial 0 with value: 32.42759219248212.
[I 2026-04-07 20:26:03,174] Trial 1 finished with value: 34.060598726951866 and parameters: {'learning_rate': 0.03187334162983267, 'max_depth': 1, 'subsample': 0.6896685777019385, 'colsample_bytree': 0.48965309829397413, 'min_child_weight': 12}. Best is trial 0 with value: 32.42759219248212.
[I 2026-04-07 20:26:07,626] Trial 2 finished with value: 40.005061348828285 and parameters: {'learning_rate': 0.0012240480182017178, 'max_depth': 3, 'subsample': 0.49851837325059845, 'colsample_bytree': 0.8849872449317784, 'min_child_weight': 15}. Best is trial 0 with value: 32.42759219248212.
[I 2026-04-07 20:26:11,592] Trial 3 finished with value: 36.34586789981835 and parameters: {'learning_rate': 0.005246576827589239, 'max_depth': 8, 'subsample': 0.16406379400929755, 'colsample_bytree': 0.3925256687324429, 'min_child_weight': 1}. Best is trial 0 with value: 32.42759219248212.
[I 2026-04-07 20:26:20,552] Trial 4 finished with value: 32.83956410073274 and parameters: {'learning_rate': 0.02957383662029734, 'max_depth': 2, 'subsample': 0.9906858780974375, 'colsample_bytree': 0.39252664942529786, 'min_child_weight': 3}. Best is trial 0 with value: 32.42759219248212.
[I 2026-04-07 20:26:25,202] Trial 5 finished with value: 33.866140998207015 and parameters: {'learning_rate': 0.03159511946999252, 'max_depth': 4, 'subsample': 0.49178055263794435, 'colsample_bytree': 0.11558608638970472, 'min_child_weight': 14}. Best is trial 0 with value: 32.42759219248212.
[I 2026-04-07 20:26:29,097] Trial 6 finished with value: 31.177063043575572 and parameters: {'learning_rate': 0.046579030278034686, 'max_depth': 8, 'subsample': 0.24083424459267289, 'colsample_bytree': 0.4495209545603515, 'min_child_weight': 4}. Best is trial 6 with value: 31.177063043575572.
[I 2026-04-07 20:26:33,939] Trial 7 finished with value: 39.329629876438155 and parameters: {'learning_rate': 0.001520749673063324, 'max_depth': 6, 'subsample': 0.6658678876168457, 'colsample_bytree': 0.6260552347231527, 'min_child_weight': 7}. Best is trial 6 with value: 31.177063043575572.
[I 2026-04-07 20:26:37,804] Trial 8 finished with value: 31.17285456597017 and parameters: {'learning_rate': 0.030709720605592804, 'max_depth': 8, 'subsample': 0.1787720604436676, 'colsample_bytree': 0.631842876601197, 'min_child_weight': 20}. Best is trial 8 with value: 31.17285456597017.
[I 2026-04-07 20:26:43,365] Trial 9 finished with value: 37.16492213707122 and parameters: {'learning_rate': 0.006062380418281201, 'max_depth': 5, 'subsample': 0.8286615288555349, 'colsample_bytree': 0.31112310881639654, 'min_child_weight': 6}. Best is trial 8 with value: 31.17285456597017.
[I 2026-04-07 20:26:47,437] Trial 10 finished with value: 31.897463100699767 and parameters: {'learning_rate': 0.012689857625713242, 'max_depth': 10, 'subsample': 0.05752507471668397, 'colsample_bytree': 0.8238803309838928, 'min_child_weight': 19}. Best is trial 8 with value: 31.17285456597017.
[I 2026-04-07 20:26:49,588] Trial 11 finished with value: 31.170056629080133 and parameters: {'learning_rate': 0.09595158020051593, 'max_depth': 7, 'subsample': 0.26969591775071855, 'colsample_bytree': 0.6795231372737245, 'min_child_weight': 19}. Best is trial 11 with value: 31.170056629080133.
[I 2026-04-07 20:26:52,098] Trial 12 finished with value: 31.12420559075751 and parameters: {'learning_rate': 0.09959321745340131, 'max_depth': 7, 'subsample': 0.3186099366324464, 'colsample_bytree': 0.6618307965532042, 'min_child_weight': 20}. Best is trial 12 with value: 31.12420559075751.
[I 2026-04-07 20:26:54,450] Trial 13 finished with value: 31.14615725947046 and parameters: {'learning_rate': 0.09764869708702281, 'max_depth': 7, 'subsample': 0.3533606280775127, 'colsample_bytree': 0.7317405670338178, 'min_child_weight': 17}. Best is trial 12 with value: 31.12420559075751.
[I 2026-04-07 20:26:58,654] Trial 14 finished with value: 31.84631558475919 and parameters: {'learning_rate': 0.013480788425818582, 'max_depth': 6, 'subsample': 0.3996162717951647, 'colsample_bytree': 0.991096617799069, 'min_child_weight': 17}. Best is trial 12 with value: 31.12420559075751.
[I 2026-04-07 20:27:02,122] Trial 15 finished with value: 31.111506428441285 and parameters: {'learning_rate': 0.06145114113465001, 'max_depth': 7, 'subsample': 0.36614234481699476, 'colsample_bytree': 0.7409992714645739, 'min_child_weight': 10}. Best is trial 15 with value: 31.111506428441285.
[I 2026-04-07 20:27:06,508] Trial 16 finished with value: 31.097079281739067 and parameters: {'learning_rate': 0.058662283363383375, 'max_depth': 5, 'subsample': 0.3805928158298449, 'colsample_bytree': 0.8066588273552352, 'min_child_weight': 9}. Best is trial 16 with value: 31.097079281739067.
[I 2026-04-07 20:27:12,378] Trial 17 finished with value: 31.241226185909166 and parameters: {'learning_rate': 0.050714313505108875, 'max_depth': 4, 'subsample': 0.6041430679144237, 'colsample_bytree': 0.798724467978354, 'min_child_weight': 9}. Best is trial 16 with value: 31.097079281739067.
[I 2026-04-07 20:27:17,005] Trial 18 finished with value: 31.852943723499354 and parameters: {'learning_rate': 0.015872675022447425, 'max_depth': 5, 'subsample': 0.42818855829411373, 'colsample_bytree': 0.9381674344109985, 'min_child_weight': 10}. Best is trial 16 with value: 31.097079281739067.
[I 2026-04-07 20:27:22,577] Trial 19 finished with value: 38.252262221215744 and parameters: {'learning_rate': 0.0023336925946003, 'max_depth': 9, 'subsample': 0.5823941428593549, 'colsample_bytree': 0.5543437762493786, 'min_child_weight': 8}. Best is trial 16 with value: 31.097079281739067.
[I 2026-04-07 20:27:25,725] Trial 20 finished with value: 31.29902857005462 and parameters: {'learning_rate': 0.0532356279991092, 'max_depth': 4, 'subsample': 0.07116456856328346, 'colsample_bytree': 0.7909124144965443, 'min_child_weight': 12}. Best is trial 16 with value: 31.097079281739067.
[I 2026-04-07 20:27:29,478] Trial 21 finished with value: 31.07729586823746 and parameters: {'learning_rate': 0.06495579081935007, 'max_depth': 7, 'subsample': 0.3443320305211701, 'colsample_bytree': 0.7056473304907893, 'min_child_weight': 11}. Best is trial 21 with value: 31.07729586823746.
[I 2026-04-07 20:27:33,868] Trial 22 finished with value: 31.403383974137576 and parameters: {'learning_rate': 0.020255373612637958, 'max_depth': 6, 'subsample': 0.4325457945185365, 'colsample_bytree': 0.8934607660871817, 'min_child_weight': 11}. Best is trial 21 with value: 31.07729586823746.
[I 2026-04-07 20:27:38,233] Trial 23 finished with value: 31.108902599169763 and parameters: {'learning_rate': 0.06345050006398135, 'max_depth': 5, 'subsample': 0.32903677748803556, 'colsample_bytree': 0.7416226816947968, 'min_child_weight': 6}. Best is trial 21 with value: 31.07729586823746.
[I 2026-04-07 20:27:41,885] Trial 24 finished with value: 34.15379605802304 and parameters: {'learning_rate': 0.007547793080977131, 'max_depth': 5, 'subsample': 0.23275318486385194, 'colsample_bytree': 0.5671919313417799, 'min_child_weight': 5}. Best is trial 21 with value: 31.07729586823746.
[I 2026-04-07 20:27:45,251] Trial 25 finished with value: 31.384460229465105 and parameters: {'learning_rate': 0.06372810172646261, 'max_depth': 3, 'subsample': 0.17171333551557136, 'colsample_bytree': 0.7381848129774791, 'min_child_weight': 8}. Best is trial 21 with value: 31.07729586823746.
[I 2026-04-07 20:27:50,233] Trial 26 finished with value: 32.20641959518815 and parameters: {'learning_rate': 0.021566968512810394, 'max_depth': 3, 'subsample': 0.46612684815049377, 'colsample_bytree': 0.8757406100446002, 'min_child_weight': 2}. Best is trial 21 with value: 31.07729586823746.
[I 2026-04-07 20:27:54,285] Trial 27 finished with value: 31.186415045519272 and parameters: {'learning_rate': 0.04341475117592639, 'max_depth': 5, 'subsample': 0.2990430277984426, 'colsample_bytree': 0.8350579412103648, 'min_child_weight': 6}. Best is trial 21 with value: 31.07729586823746.
[I 2026-04-07 20:27:58,784] Trial 28 finished with value: 35.78857154877317 and parameters: {'learning_rate': 0.0034689641270977496, 'max_depth': 6, 'subsample': 0.5471346522230481, 'colsample_bytree': 0.990118400788102, 'min_child_weight': 12}. Best is trial 21 with value: 31.07729586823746.
[I 2026-04-07 20:28:03,350] Trial 29 finished with value: 31.20406034442433 and parameters: {'learning_rate': 0.07057613576118112, 'max_depth': 4, 'subsample': 0.36362851476919417, 'colsample_bytree': 0.5918812374733528, 'min_child_weight': 8}. Best is trial 21 with value: 31.07729586823746.

Best params for fold 4: {'learning_rate': 0.06495579081935007, 'max_depth': 7, 'subsample': 0.3443320305211701, 'colsample_bytree': 0.7056473304907893, 'min_child_weight': 11}

[I 2026-04-07 20:28:08,567] A new study created in memory with name: Xgboost

Fold 4 MAE (log scale):      30.6681
Fold 4 MAE (original scale): 30.6681

==================================================
Fold 5/5
==================================================

[I 2026-04-07 20:28:11,754] Trial 0 finished with value: 35.059181158977154 and parameters: {'learning_rate': 0.010648547753918039, 'max_depth': 2, 'subsample': 0.16010201852602707, 'colsample_bytree': 0.568168702096513, 'min_child_weight': 6}. Best is trial 0 with value: 35.059181158977154.
[I 2026-04-07 20:28:17,166] Trial 1 finished with value: 31.57692655905534 and parameters: {'learning_rate': 0.018518052631618584, 'max_depth': 7, 'subsample': 0.7133778748611332, 'colsample_bytree': 0.5583320988911838, 'min_child_weight': 11}. Best is trial 1 with value: 31.57692655905534.
[I 2026-04-07 20:28:25,035] Trial 2 finished with value: 32.491519062650724 and parameters: {'learning_rate': 0.030559546038999193, 'max_depth': 2, 'subsample': 0.7763443071602072, 'colsample_bytree': 0.9644217654118817, 'min_child_weight': 1}. Best is trial 1 with value: 31.57692655905534.
[I 2026-04-07 20:28:30,660] Trial 3 finished with value: 36.00467676554572 and parameters: {'learning_rate': 0.003975007678398037, 'max_depth': 9, 'subsample': 0.6338323405656033, 'colsample_bytree': 0.6583447624284705, 'min_child_weight': 13}. Best is trial 1 with value: 31.57692655905534.
[I 2026-04-07 20:28:36,091] Trial 4 finished with value: 31.088547254917742 and parameters: {'learning_rate': 0.08149047538627709, 'max_depth': 6, 'subsample': 0.7972466608993599, 'colsample_bytree': 0.5709564306355499, 'min_child_weight': 3}. Best is trial 4 with value: 31.088547254917742.
[I 2026-04-07 20:28:41,659] Trial 5 finished with value: 36.83486482593872 and parameters: {'learning_rate': 0.0027036021400418182, 'max_depth': 10, 'subsample': 0.13648489914986772, 'colsample_bytree': 0.855163322012868, 'min_child_weight': 7}. Best is trial 4 with value: 31.088547254917742.
[I 2026-04-07 20:28:46,017] Trial 6 finished with value: 31.239428228529754 and parameters: {'learning_rate': 0.06169464477458625, 'max_depth': 8, 'subsample': 0.2977946477456169, 'colsample_bytree': 0.5501955894819699, 'min_child_weight': 4}. Best is trial 4 with value: 31.088547254917742.
[I 2026-04-07 20:28:50,305] Trial 7 finished with value: 31.172404747393344 and parameters: {'learning_rate': 0.05125544869173275, 'max_depth': 8, 'subsample': 0.4768326802403469, 'colsample_bytree': 0.8448873884855196, 'min_child_weight': 7}. Best is trial 4 with value: 31.088547254917742.
[I 2026-04-07 20:28:56,885] Trial 8 finished with value: 31.953197486035315 and parameters: {'learning_rate': 0.021662091494039342, 'max_depth': 9, 'subsample': 0.8152304533439657, 'colsample_bytree': 0.42699013603131714, 'min_child_weight': 3}. Best is trial 4 with value: 31.088547254917742.
[I 2026-04-07 20:29:02,202] Trial 9 finished with value: 39.46926232568123 and parameters: {'learning_rate': 0.002637216753066686, 'max_depth': 9, 'subsample': 0.4973236065613388, 'colsample_bytree': 0.3318007332684898, 'min_child_weight': 9}. Best is trial 4 with value: 31.088547254917742.
[I 2026-04-07 20:29:08,224] Trial 10 finished with value: 32.252037128678204 and parameters: {'learning_rate': 0.0912057797630087, 'max_depth': 5, 'subsample': 0.9425702434078727, 'colsample_bytree': 0.09641044151360634, 'min_child_weight': 20}. Best is trial 4 with value: 31.088547254917742.
[I 2026-04-07 20:29:12,873] Trial 11 finished with value: 31.19628227509389 and parameters: {'learning_rate': 0.044756466022247435, 'max_depth': 5, 'subsample': 0.4477290372063848, 'colsample_bytree': 0.7973607509182892, 'min_child_weight': 15}. Best is trial 4 with value: 31.088547254917742.
[I 2026-04-07 20:29:19,290] Trial 12 finished with value: 31.083153161228974 and parameters: {'learning_rate': 0.09677760815263309, 'max_depth': 6, 'subsample': 0.9980176265605039, 'colsample_bytree': 0.735683271341637, 'min_child_weight': 1}. Best is trial 12 with value: 31.083153161228974.
[I 2026-04-07 20:29:25,818] Trial 13 finished with value: 40.34116360939854 and parameters: {'learning_rate': 0.001026526762557903, 'max_depth': 4, 'subsample': 0.9855474512263378, 'colsample_bytree': 0.7131076667945535, 'min_child_weight': 1}. Best is trial 12 with value: 31.083153161228974.
[I 2026-04-07 20:29:32,131] Trial 14 finished with value: 31.28291850582876 and parameters: {'learning_rate': 0.09346541941629051, 'max_depth': 6, 'subsample': 0.891882290664505, 'colsample_bytree': 0.2887629602947593, 'min_child_weight': 4}. Best is trial 12 with value: 31.083153161228974.
[I 2026-04-07 20:29:37,297] Trial 15 finished with value: 33.21252586038375 and parameters: {'learning_rate': 0.010872213000694408, 'max_depth': 4, 'subsample': 0.648534503705873, 'colsample_bytree': 0.6845638473281016, 'min_child_weight': 1}. Best is trial 12 with value: 31.083153161228974.
[I 2026-04-07 20:29:43,053] Trial 16 finished with value: 31.55515822169303 and parameters: {'learning_rate': 0.03173735133026779, 'max_depth': 6, 'subsample': 0.8287340627600321, 'colsample_bytree': 0.437031389296199, 'min_child_weight': 4}. Best is trial 12 with value: 31.083153161228974.
[I 2026-04-07 20:29:52,216] Trial 17 finished with value: 31.279085131754293 and parameters: {'learning_rate': 0.09855784913904694, 'max_depth': 3, 'subsample': 0.9915502301559669, 'colsample_bytree': 0.9960881161213802, 'min_child_weight': 18}. Best is trial 12 with value: 31.083153161228974.
[I 2026-04-07 20:29:57,139] Trial 18 finished with value: 39.447076127504204 and parameters: {'learning_rate': 0.005024301672101161, 'max_depth': 7, 'subsample': 0.6071302103631562, 'colsample_bytree': 0.11395115939945366, 'min_child_weight': 9}. Best is trial 12 with value: 31.083153161228974.
[I 2026-04-07 20:30:03,494] Trial 19 finished with value: 33.01202204174962 and parameters: {'learning_rate': 0.01762291144876983, 'max_depth': 4, 'subsample': 0.8835833433220875, 'colsample_bytree': 0.4346401120367351, 'min_child_weight': 6}. Best is trial 12 with value: 31.083153161228974.
[I 2026-04-07 20:30:13,971] Trial 20 finished with value: 33.09036604738605 and parameters: {'learning_rate': 0.060865918112775225, 'max_depth': 1, 'subsample': 0.7221367341450825, 'colsample_bytree': 0.7792241053557079, 'min_child_weight': 3}. Best is trial 12 with value: 31.083153161228974.
[I 2026-04-07 20:30:18,410] Trial 21 finished with value: 31.149030583673113 and parameters: {'learning_rate': 0.051869214380522985, 'max_depth': 7, 'subsample': 0.37557088367229063, 'colsample_bytree': 0.8834207751289098, 'min_child_weight': 8}. Best is trial 12 with value: 31.083153161228974.
[I 2026-04-07 20:30:22,545] Trial 22 finished with value: 31.183327707717748 and parameters: {'learning_rate': 0.03650005312927875, 'max_depth': 7, 'subsample': 0.24393272066630772, 'colsample_bytree': 0.8884065326657913, 'min_child_weight': 11}. Best is trial 12 with value: 31.083153161228974.
[I 2026-04-07 20:30:27,529] Trial 23 finished with value: 31.12859789731218 and parameters: {'learning_rate': 0.0645010726355176, 'max_depth': 6, 'subsample': 0.3761599349786784, 'colsample_bytree': 0.6399045424141595, 'min_child_weight': 9}. Best is trial 12 with value: 31.083153161228974.
[I 2026-04-07 20:30:29,766] Trial 24 finished with value: 31.455825928641854 and parameters: {'learning_rate': 0.06708166515344142, 'max_depth': 6, 'subsample': 0.05741609606766335, 'colsample_bytree': 0.6381189758543501, 'min_child_weight': 15}. Best is trial 12 with value: 31.083153161228974.
[I 2026-04-07 20:30:33,957] Trial 25 finished with value: 31.466148936057134 and parameters: {'learning_rate': 0.02579181610416544, 'max_depth': 5, 'subsample': 0.38741801855442637, 'colsample_bytree': 0.7366705801474106, 'min_child_weight': 2}. Best is trial 12 with value: 31.083153161228974.
[I 2026-04-07 20:30:38,853] Trial 26 finished with value: 31.079066176689516 and parameters: {'learning_rate': 0.07855875143099925, 'max_depth': 6, 'subsample': 0.8966692662805076, 'colsample_bytree': 0.6399679371719589, 'min_child_weight': 6}. Best is trial 26 with value: 31.079066176689516.
[I 2026-04-07 20:30:44,688] Trial 27 finished with value: 31.13196930155253 and parameters: {'learning_rate': 0.040464877954544065, 'max_depth': 8, 'subsample': 0.8812181474172825, 'colsample_bytree': 0.4916245191557037, 'min_child_weight': 5}. Best is trial 26 with value: 31.079066176689516.
[I 2026-04-07 20:30:50,673] Trial 28 finished with value: 31.378736488766783 and parameters: {'learning_rate': 0.07897730559189392, 'max_depth': 5, 'subsample': 0.9198359170082988, 'colsample_bytree': 0.31732845010689714, 'min_child_weight': 3}. Best is trial 26 with value: 31.079066176689516.
[I 2026-04-07 20:30:56,349] Trial 29 finished with value: 33.53955170139011 and parameters: {'learning_rate': 0.012722366371195495, 'max_depth': 3, 'subsample': 0.745023959686032, 'colsample_bytree': 0.6191707043284341, 'min_child_weight': 6}. Best is trial 26 with value: 31.079066176689516.

Best params for fold 5: {'learning_rate': 0.07855875143099925, 'max_depth': 6, 'subsample': 0.8966692662805076, 'colsample_bytree': 0.6399679371719589, 'min_child_weight': 6}
Fold 5 MAE (log scale):      30.6989
Fold 5 MAE (original scale): 30.6989

==================================================
Cross-Validation Summary
==================================================
Mean MAE (log scale):      30.8165 (+/- 0.2356)
Mean MAE (original scale): 30.8165 (+/- 0.2356)

Overall OOF MAE: 30.8165

Sample of dataframe with OOF predictions:
       id  is_churn  fold_number  oof_prediction  oof_residual
7       5     False            5      208.090927    -32.318427
16     85     False            4      157.774734     23.093866
24     93     False            1      170.593414     -4.953114
32    119     False            5      173.659164     -2.324464
118   395     False            5      213.783005    -43.684905
139   470     False            3      211.152405    -54.038705
146   478     False            2      179.256470    -27.687570
154   527     False            4      224.995499     18.691001
269  1041     False            2      174.479401     98.486899
294  1196     False            1      175.973267    -18.879567

OOF Performance by Fold:
             count        mae
fold_number
1            38875  31.225025
2            38875  30.678020
3            38875  30.812296
4            38874  30.668069
5            38874  30.698948

## Section 8 — XGBoost Churn Classification (5-Fold OOF)

**Target variable:** `is_churn` (binary, 0 = retained, 1 = churned)  
**Features:** `model_features_class` — 11 features including `X_policy_premium` and `U`

`cross_validate_churn_with_oof_predictions` follows the same nested structure as the regression CV:
1. Outer 5-fold for OOF predictions  
2. Inner 80/20 split for Optuna tuning (maximise ROC-AUC)

**Outputs stored in `df_middle_class`:**
- `fold_number` — fold assignment  
- `oof_prediction` — OOF churn probability (output of `predict_proba[:, 1]`)
- `prob_acceptance = 1 − oof_prediction` — probability the client accepts (does not churn)
- `Z = 1 − is_churn` — binary acceptance indicator

The `prob_acceptance` column is the key output consumed by the pricing optimiser.

In [ ]:
from sklearn.model_selection import KFold
import pandas as pd
import numpy as np

def cross_validate_churn_with_oof_predictions(X, y, n_splits=5, n_trials=30):
    """
    Perform cross-validation and generate out-of-fold predictions.
    FeatureProcessor is fit on each training fold and applied to both train and val
    to prevent data leakage.
    """
    kfold = KFold(n_splits=n_splits, shuffle=True, random_state=123)

    fold_numbers    = np.zeros(len(X))
    oof_predictions = np.zeros(len(X))

    fold_results         = []
    best_params_per_fold = []

    for fold_idx, (train_idx, val_idx) in enumerate(kfold.split(X)):
        print(f"\n{'='*50}")
        print(f"Fold {fold_idx + 1}/{n_splits}")
        print(f"{'='*50}")

        fold_numbers[val_idx] = fold_idx + 1

        X_train_fold, X_val_fold = X.iloc[train_idx], X.iloc[val_idx]
        y_train_fold, y_val_fold = y.iloc[train_idx], y.iloc[val_idx]

        # --- fit preprocessor on train fold only (no leakage) ---
        fp = FeatureProcessor()
        X_train_proc = fp.fit_transform(X_train_fold)
        X_val_proc   = fp.transform(X_val_fold)

        from sklearn.model_selection import train_test_split
        X_train_tune, X_val_tune, y_train_tune, y_val_tune = train_test_split(
            X_train_proc, y_train_fold, test_size=0.2, random_state=123
        )

        model_class = ModelClassifier()
        best_params = model_class.tuning(
            X_train_tune, y_train_tune,
            X_val_tune,   y_val_tune,
            n_trials=n_trials
        )

        print(f"Best params for fold {fold_idx + 1}: {best_params}")
        best_params_per_fold.append(best_params)

        final_model = model_class.train(
            X_train_proc, y_train_fold,
            X_val_proc,   y_val_fold,
            best_params
        )

        y_pred_proba = final_model.predict_proba(X_val_proc)[:, 1]
        roc_auc      = metrics.roc_auc_score(y_true=y_val_fold, y_score=y_pred_proba)

        oof_predictions[val_idx] = y_pred_proba

        fold_results.append({
            'fold':    fold_idx + 1,
            'roc_auc': roc_auc,
            'n_train': len(train_idx),
            'n_val':   len(val_idx)
        })

        print(f"Fold {fold_idx + 1} AUC: {roc_auc:.4f}")

    results_df = pd.DataFrame(fold_results)

    print(f"\n{'='*50}")
    print("Cross-Validation Summary")
    print(f"{'='*50}")
    print(f"Mean AUC: {results_df['roc_auc'].mean():.4f} (+/- {results_df['roc_auc'].std():.4f})")

    return fold_numbers, oof_predictions, results_df, best_params_per_fold


X = df_middle_class.loc[:, model_features_class]
y = df_middle_class['is_churn'].astype(int)

fold_numbers, oof_predictions, results_df, best_params_list = cross_validate_churn_with_oof_predictions(
    X, y, n_splits=5, n_trials=30
)

df_middle_class['fold_number']    = fold_numbers.astype(int)
df_middle_class['oof_prediction'] = oof_predictions

==================================================
Fold 1/5
==================================================

[I 2026-04-07 20:31:03,193] A new study created in memory with name: Xgboost
[I 2026-04-07 20:31:04,778] Trial 0 finished with value: 0.6542729977668649 and parameters: {'learning_rate': 0.05195535262891233, 'max_depth': 2, 'subsample': 0.8519703364881129, 'colsample_bytree': 0.29814907290915027, 'min_child_weight': 12}. Best is trial 0 with value: 0.6542729977668649.
[I 2026-04-07 20:31:06,452] Trial 1 finished with value: 0.6443876869707705 and parameters: {'learning_rate': 0.005275566158735326, 'max_depth': 8, 'subsample': 0.05480191038633371, 'colsample_bytree': 0.1882059183412142, 'min_child_weight': 11}. Best is trial 0 with value: 0.6542729977668649.
[I 2026-04-07 20:31:08,326] Trial 2 finished with value: 0.6337223191631345 and parameters: {'learning_rate': 0.0030966705491492115, 'max_depth': 10, 'subsample': 0.5324095732245242, 'colsample_bytree': 0.07194226196334333, 'min_child_weight': 5}. Best is trial 0 with value: 0.6542729977668649.
[I 2026-04-07 20:31:09,516] Trial 3 finished with value: 0.6411060664251881 and parameters: {'learning_rate': 0.040957155018574956, 'max_depth': 9, 'subsample': 0.12348126755391176, 'colsample_bytree': 0.1904833484775293, 'min_child_weight': 3}. Best is trial 0 with value: 0.6542729977668649.
[I 2026-04-07 20:31:10,639] Trial 4 finished with value: 0.653098451576678 and parameters: {'learning_rate': 0.03221564151137247, 'max_depth': 2, 'subsample': 0.3163510148867503, 'colsample_bytree': 0.7029526902578662, 'min_child_weight': 11}. Best is trial 0 with value: 0.6542729977668649.
[I 2026-04-07 20:31:12,920] Trial 5 finished with value: 0.6593789476386618 and parameters: {'learning_rate': 0.0121926153013523, 'max_depth': 9, 'subsample': 0.6059996878002523, 'colsample_bytree': 0.6762615529701897, 'min_child_weight': 20}. Best is trial 5 with value: 0.6593789476386618.
[I 2026-04-07 20:31:14,703] Trial 6 finished with value: 0.6562764764046722 and parameters: {'learning_rate': 0.006568488388963419, 'max_depth': 7, 'subsample': 0.14583838587075368, 'colsample_bytree': 0.7547538163443677, 'min_child_weight': 13}. Best is trial 5 with value: 0.6593789476386618.
[I 2026-04-07 20:31:16,376] Trial 7 finished with value: 0.6587502251427387 and parameters: {'learning_rate': 0.030106220787082694, 'max_depth': 5, 'subsample': 0.5180489540779322, 'colsample_bytree': 0.973744023290446, 'min_child_weight': 6}. Best is trial 5 with value: 0.6593789476386618.
[I 2026-04-07 20:31:17,917] Trial 8 finished with value: 0.6494146682826931 and parameters: {'learning_rate': 0.009836652026236894, 'max_depth': 4, 'subsample': 0.6662649335014929, 'colsample_bytree': 0.7747509228573426, 'min_child_weight': 4}. Best is trial 5 with value: 0.6593789476386618.
[I 2026-04-07 20:31:19,232] Trial 9 finished with value: 0.632570692647727 and parameters: {'learning_rate': 0.0013656616977398622, 'max_depth': 3, 'subsample': 0.49995641553986375, 'colsample_bytree': 0.8698548860322487, 'min_child_weight': 8}. Best is trial 5 with value: 0.6593789476386618.
[I 2026-04-07 20:31:21,002] Trial 10 finished with value: 0.658857291395168 and parameters: {'learning_rate': 0.016766338044901904, 'max_depth': 7, 'subsample': 0.9957030188674907, 'colsample_bytree': 0.48467729924571096, 'min_child_weight': 20}. Best is trial 5 with value: 0.6593789476386618.
[I 2026-04-07 20:31:23,756] Trial 11 finished with value: 0.6588435001868481 and parameters: {'learning_rate': 0.017686419144775423, 'max_depth': 7, 'subsample': 0.9849945180135391, 'colsample_bytree': 0.503354313663425, 'min_child_weight': 20}. Best is trial 5 with value: 0.6593789476386618.
[I 2026-04-07 20:31:25,673] Trial 12 finished with value: 0.6578646376030642 and parameters: {'learning_rate': 0.01569782383818083, 'max_depth': 6, 'subsample': 0.7673194726652839, 'colsample_bytree': 0.5452939166850733, 'min_child_weight': 20}. Best is trial 5 with value: 0.6593789476386618.
[I 2026-04-07 20:31:26,527] Trial 13 finished with value: 0.6554116666085213 and parameters: {'learning_rate': 0.07929114739233939, 'max_depth': 10, 'subsample': 0.9955292209251723, 'colsample_bytree': 0.48916884845939346, 'min_child_weight': 16}. Best is trial 5 with value: 0.6593789476386618.
[I 2026-04-07 20:31:28,496] Trial 14 finished with value: 0.6591465885112324 and parameters: {'learning_rate': 0.019281291768018627, 'max_depth': 8, 'subsample': 0.31377940295614937, 'colsample_bytree': 0.6183502468235477, 'min_child_weight': 16}. Best is trial 5 with value: 0.6593789476386618.
[I 2026-04-07 20:31:30,705] Trial 15 finished with value: 0.6571572900645438 and parameters: {'learning_rate': 0.002677441143553252, 'max_depth': 9, 'subsample': 0.33296328177841533, 'colsample_bytree': 0.6370202323574408, 'min_child_weight': 16}. Best is trial 5 with value: 0.6593789476386618.
[I 2026-04-07 20:31:32,747] Trial 16 finished with value: 0.6552681066971533 and parameters: {'learning_rate': 0.00815454082477954, 'max_depth': 8, 'subsample': 0.3198057578466584, 'colsample_bytree': 0.3490597596721573, 'min_child_weight': 16}. Best is trial 5 with value: 0.6593789476386618.
[I 2026-04-07 20:31:34,825] Trial 17 finished with value: 0.6593262783573638 and parameters: {'learning_rate': 0.017777870257487394, 'max_depth': 9, 'subsample': 0.4264222950945302, 'colsample_bytree': 0.6111718530416242, 'min_child_weight': 17}. Best is trial 5 with value: 0.6593789476386618.
[I 2026-04-07 20:31:37,965] Trial 18 finished with value: 0.6552316180899391 and parameters: {'learning_rate': 0.0034276407261872614, 'max_depth': 10, 'subsample': 0.652685864038861, 'colsample_bytree': 0.8497968585566913, 'min_child_weight': 18}. Best is trial 5 with value: 0.6593789476386618.
[I 2026-04-07 20:31:38,568] Trial 19 finished with value: 0.6570112447046433 and parameters: {'learning_rate': 0.07931146365158205, 'max_depth': 5, 'subsample': 0.4244803809077142, 'colsample_bytree': 0.397799009440586, 'min_child_weight': 14}. Best is trial 5 with value: 0.6593789476386618.
[I 2026-04-07 20:31:41,063] Trial 20 finished with value: 0.6583476835149867 and parameters: {'learning_rate': 0.01176401609358174, 'max_depth': 9, 'subsample': 0.6072145714008241, 'colsample_bytree': 0.5950144086774711, 'min_child_weight': 8}. Best is trial 5 with value: 0.6593789476386618.
[I 2026-04-07 20:31:42,730] Trial 21 finished with value: 0.660543122638123 and parameters: {'learning_rate': 0.023157784977968086, 'max_depth': 8, 'subsample': 0.2512235270480896, 'colsample_bytree': 0.6653041312493568, 'min_child_weight': 18}. Best is trial 21 with value: 0.660543122638123.
[I 2026-04-07 20:31:44,323] Trial 22 finished with value: 0.6608770719484509 and parameters: {'learning_rate': 0.026426507992683073, 'max_depth': 9, 'subsample': 0.410927310861262, 'colsample_bytree': 0.6950215678596119, 'min_child_weight': 18}. Best is trial 22 with value: 0.6608770719484509.
[I 2026-04-07 20:31:45,875] Trial 23 finished with value: 0.6611396555445168 and parameters: {'learning_rate': 0.02457868191658342, 'max_depth': 6, 'subsample': 0.1995982026239695, 'colsample_bytree': 0.7517232076681153, 'min_child_weight': 18}. Best is trial 23 with value: 0.6611396555445168.
[I 2026-04-07 20:31:46,982] Trial 24 finished with value: 0.6587047596208051 and parameters: {'learning_rate': 0.028339819010020556, 'max_depth': 6, 'subsample': 0.22092863553254122, 'colsample_bytree': 0.8478869670730889, 'min_child_weight': 1}. Best is trial 23 with value: 0.6611396555445168.
[I 2026-04-07 20:31:47,838] Trial 25 finished with value: 0.6597693247134341 and parameters: {'learning_rate': 0.04665221386731344, 'max_depth': 7, 'subsample': 0.22103179391602576, 'colsample_bytree': 0.9637031783692365, 'min_child_weight': 18}. Best is trial 23 with value: 0.6611396555445168.
[I 2026-04-07 20:31:48,619] Trial 26 finished with value: 0.658926641471291 and parameters: {'learning_rate': 0.05925839950496304, 'max_depth': 6, 'subsample': 0.22274507305955493, 'colsample_bytree': 0.7745709395750268, 'min_child_weight': 14}. Best is trial 23 with value: 0.6611396555445168.
[I 2026-04-07 20:31:50,069] Trial 27 finished with value: 0.6603612100331414 and parameters: {'learning_rate': 0.026738063733002956, 'max_depth': 8, 'subsample': 0.41365681933923576, 'colsample_bytree': 0.7270422756671657, 'min_child_weight': 18}. Best is trial 23 with value: 0.6611396555445168.
[I 2026-04-07 20:31:50,535] Trial 28 finished with value: 0.6548480305331088 and parameters: {'learning_rate': 0.09744613129664004, 'max_depth': 4, 'subsample': 0.134941868938749, 'colsample_bytree': 0.8792256512971688, 'min_child_weight': 14}. Best is trial 23 with value: 0.6611396555445168.
[I 2026-04-07 20:31:52,098] Trial 29 finished with value: 0.6589628320267502 and parameters: {'learning_rate': 0.023286469751585347, 'max_depth': 5, 'subsample': 0.25921728685280854, 'colsample_bytree': 0.4263555648063169, 'min_child_weight': 18}. Best is trial 23 with value: 0.6611396555445168.

Best params for fold 1: {'learning_rate': 0.02457868191658342, 'max_depth': 6, 'subsample': 0.1995982026239695, 'colsample_bytree': 0.7517232076681153, 'min_child_weight': 18}

[I 2026-04-07 20:31:54,325] A new study created in memory with name: Xgboost

Fold 1 AUC: 0.6670

==================================================
Fold 2/5
==================================================

[I 2026-04-07 20:31:55,422] Trial 0 finished with value: 0.66741571133091 and parameters: {'learning_rate': 0.06366663709962736, 'max_depth': 5, 'subsample': 0.6667198788438659, 'colsample_bytree': 0.3979277710356616, 'min_child_weight': 9}. Best is trial 0 with value: 0.66741571133091.
[I 2026-04-07 20:31:57,725] Trial 1 finished with value: 0.6454536984091531 and parameters: {'learning_rate': 0.00245130590632162, 'max_depth': 9, 'subsample': 0.45938068620022154, 'colsample_bytree': 0.22174762279647514, 'min_child_weight': 1}. Best is trial 0 with value: 0.66741571133091.
[I 2026-04-07 20:31:59,122] Trial 2 finished with value: 0.6588540917751815 and parameters: {'learning_rate': 0.0020704039434618713, 'max_depth': 5, 'subsample': 0.06275158322947254, 'colsample_bytree': 0.893076689825583, 'min_child_weight': 4}. Best is trial 0 with value: 0.66741571133091.
[I 2026-04-07 20:32:01,822] Trial 3 finished with value: 0.6639278600878471 and parameters: {'learning_rate': 0.006241943980723664, 'max_depth': 10, 'subsample': 0.28432096217764874, 'colsample_bytree': 0.6958871738164041, 'min_child_weight': 4}. Best is trial 0 with value: 0.66741571133091.
[I 2026-04-07 20:32:03,361] Trial 4 finished with value: 0.6374071525322668 and parameters: {'learning_rate': 0.0016220490863953288, 'max_depth': 7, 'subsample': 0.30375191252115885, 'colsample_bytree': 0.08066511988585469, 'min_child_weight': 19}. Best is trial 0 with value: 0.66741571133091.
[I 2026-04-07 20:32:04,449] Trial 5 finished with value: 0.6628337653873044 and parameters: {'learning_rate': 0.05015832260716439, 'max_depth': 2, 'subsample': 0.9413342737026467, 'colsample_bytree': 0.6228525829119439, 'min_child_weight': 19}. Best is trial 0 with value: 0.66741571133091.
[I 2026-04-07 20:32:05,758] Trial 6 finished with value: 0.6592112542610259 and parameters: {'learning_rate': 0.07464794599475864, 'max_depth': 10, 'subsample': 0.9384029278171744, 'colsample_bytree': 0.29956928428993707, 'min_child_weight': 20}. Best is trial 0 with value: 0.66741571133091.
[I 2026-04-07 20:32:07,160] Trial 7 finished with value: 0.6581757995934211 and parameters: {'learning_rate': 0.0014901512499465002, 'max_depth': 5, 'subsample': 0.7038732586460098, 'colsample_bytree': 0.6308485552624385, 'min_child_weight': 5}. Best is trial 0 with value: 0.66741571133091.
[I 2026-04-07 20:32:08,245] Trial 8 finished with value: 0.6348954568788008 and parameters: {'learning_rate': 0.0019122195742033272, 'max_depth': 2, 'subsample': 0.1885860830553962, 'colsample_bytree': 0.892461781519613, 'min_child_weight': 17}. Best is trial 0 with value: 0.66741571133091.
[I 2026-04-07 20:32:09,742] Trial 9 finished with value: 0.6530707915458818 and parameters: {'learning_rate': 0.0012686913398537174, 'max_depth': 6, 'subsample': 0.22677371216587172, 'colsample_bytree': 0.3395401490521785, 'min_child_weight': 5}. Best is trial 0 with value: 0.66741571133091.
[I 2026-04-07 20:32:11,061] Trial 10 finished with value: 0.6652787876478498 and parameters: {'learning_rate': 0.023701822353247082, 'max_depth': 4, 'subsample': 0.634238529603313, 'colsample_bytree': 0.4299128627143799, 'min_child_weight': 12}. Best is trial 0 with value: 0.66741571133091.
[I 2026-04-07 20:32:12,461] Trial 11 finished with value: 0.6662773407842973 and parameters: {'learning_rate': 0.02887824353585155, 'max_depth': 4, 'subsample': 0.6936734659817746, 'colsample_bytree': 0.42671976723366883, 'min_child_weight': 12}. Best is trial 0 with value: 0.66741571133091.
[I 2026-04-07 20:32:13,684] Trial 12 finished with value: 0.6629026555681878 and parameters: {'learning_rate': 0.025074907639260895, 'max_depth': 3, 'subsample': 0.7331260105070297, 'colsample_bytree': 0.4735120598170663, 'min_child_weight': 11}. Best is trial 0 with value: 0.66741571133091.
[I 2026-04-07 20:32:15,286] Trial 13 finished with value: 0.6451097018464125 and parameters: {'learning_rate': 0.024153215595041105, 'max_depth': 7, 'subsample': 0.5269151300534664, 'colsample_bytree': 0.1637741947943478, 'min_child_weight': 14}. Best is trial 0 with value: 0.66741571133091.
[I 2026-04-07 20:32:16,546] Trial 14 finished with value: 0.6591578116971634 and parameters: {'learning_rate': 0.09982754630706737, 'max_depth': 1, 'subsample': 0.8163449905276458, 'colsample_bytree': 0.3861475658559084, 'min_child_weight': 8}. Best is trial 0 with value: 0.66741571133091.
[I 2026-04-07 20:32:18,253] Trial 15 finished with value: 0.6610473088913088 and parameters: {'learning_rate': 0.010860557150972193, 'max_depth': 4, 'subsample': 0.5465336917374862, 'colsample_bytree': 0.5472314073323009, 'min_child_weight': 8}. Best is trial 0 with value: 0.66741571133091.
[I 2026-04-07 20:32:19,353] Trial 16 finished with value: 0.6661841458200726 and parameters: {'learning_rate': 0.04383708692242314, 'max_depth': 7, 'subsample': 0.8181312676776703, 'colsample_bytree': 0.7198003932550989, 'min_child_weight': 14}. Best is trial 0 with value: 0.66741571133091.
[I 2026-04-07 20:32:20,717] Trial 17 finished with value: 0.6552879339951584 and parameters: {'learning_rate': 0.012183314786223512, 'max_depth': 4, 'subsample': 0.41806127699439727, 'colsample_bytree': 0.2606725404785396, 'min_child_weight': 8}. Best is trial 0 with value: 0.66741571133091.
[I 2026-04-07 20:32:21,930] Trial 18 finished with value: 0.6673549893146826 and parameters: {'learning_rate': 0.04755854156276207, 'max_depth': 6, 'subsample': 0.5958411802018995, 'colsample_bytree': 0.5256871018411604, 'min_child_weight': 14}. Best is trial 0 with value: 0.66741571133091.
[I 2026-04-07 20:32:24,081] Trial 19 finished with value: 0.6647044698114221 and parameters: {'learning_rate': 0.00489817142719663, 'max_depth': 8, 'subsample': 0.5992605163624696, 'colsample_bytree': 0.7660840840052495, 'min_child_weight': 15}. Best is trial 0 with value: 0.66741571133091.
[I 2026-04-07 20:32:24,977] Trial 20 finished with value: 0.6653573088737342 and parameters: {'learning_rate': 0.051992202443398014, 'max_depth': 6, 'subsample': 0.4402084152413036, 'colsample_bytree': 0.5801701467345968, 'min_child_weight': 9}. Best is trial 0 with value: 0.66741571133091.
[I 2026-04-07 20:32:26,576] Trial 21 finished with value: 0.6673028099205376 and parameters: {'learning_rate': 0.035375275802099336, 'max_depth': 5, 'subsample': 0.6994728594906174, 'colsample_bytree': 0.487036246124128, 'min_child_weight': 12}. Best is trial 0 with value: 0.66741571133091.
[I 2026-04-07 20:32:28,176] Trial 22 finished with value: 0.6664201438683406 and parameters: {'learning_rate': 0.01617530403373909, 'max_depth': 6, 'subsample': 0.815818758000216, 'colsample_bytree': 0.5040386897951852, 'min_child_weight': 16}. Best is trial 0 with value: 0.66741571133091.
[I 2026-04-07 20:32:29,719] Trial 23 finished with value: 0.6678757297825741 and parameters: {'learning_rate': 0.038509548435815014, 'max_depth': 5, 'subsample': 0.6283697632865697, 'colsample_bytree': 0.37345596781984713, 'min_child_weight': 10}. Best is trial 23 with value: 0.6678757297825741.
[I 2026-04-07 20:32:31,090] Trial 24 finished with value: 0.6672019410754593 and parameters: {'learning_rate': 0.07004986925894281, 'max_depth': 3, 'subsample': 0.6294625031448344, 'colsample_bytree': 0.3705434292498938, 'min_child_weight': 10}. Best is trial 23 with value: 0.6678757297825741.
[I 2026-04-07 20:32:31,995] Trial 25 finished with value: 0.6467832519392702 and parameters: {'learning_rate': 0.09952725858806849, 'max_depth': 8, 'subsample': 0.3870736139264715, 'colsample_bytree': 0.17415200936459568, 'min_child_weight': 6}. Best is trial 23 with value: 0.6678757297825741.
[I 2026-04-07 20:32:33,033] Trial 26 finished with value: 0.6642611571537306 and parameters: {'learning_rate': 0.06534362717774062, 'max_depth': 5, 'subsample': 0.5702463003130758, 'colsample_bytree': 0.31558653302425366, 'min_child_weight': 13}. Best is trial 23 with value: 0.6678757297825741.
[I 2026-04-07 20:32:34,682] Trial 27 finished with value: 0.6666860985107018 and parameters: {'learning_rate': 0.015579112952544022, 'max_depth': 6, 'subsample': 0.49724585919606606, 'colsample_bytree': 0.807139171350674, 'min_child_weight': 10}. Best is trial 23 with value: 0.6678757297825741.
[I 2026-04-07 20:32:35,925] Trial 28 finished with value: 0.6678956159682865 and parameters: {'learning_rate': 0.03565271484026513, 'max_depth': 8, 'subsample': 0.767356433023253, 'colsample_bytree': 0.9716792434114486, 'min_child_weight': 17}. Best is trial 28 with value: 0.6678956159682865.
[I 2026-04-07 20:32:38,470] Trial 29 finished with value: 0.6467851292191666 and parameters: {'learning_rate': 0.006302550908178985, 'max_depth': 9, 'subsample': 0.9860140767553861, 'colsample_bytree': 0.20868593117449516, 'min_child_weight': 1}. Best is trial 28 with value: 0.6678956159682865.

Best params for fold 2: {'learning_rate': 0.03565271484026513, 'max_depth': 8, 'subsample': 0.767356433023253, 'colsample_bytree': 0.9716792434114486, 'min_child_weight': 17}

[I 2026-04-07 20:32:40,610] A new study created in memory with name: Xgboost

Fold 2 AUC: 0.6688

==================================================
Fold 3/5
==================================================

[I 2026-04-07 20:32:42,151] Trial 0 finished with value: 0.6512641086871256 and parameters: {'learning_rate': 0.0025309944301633515, 'max_depth': 5, 'subsample': 0.575038489123357, 'colsample_bytree': 0.5344918324669137, 'min_child_weight': 12}. Best is trial 0 with value: 0.6512641086871256.
[I 2026-04-07 20:32:43,999] Trial 1 finished with value: 0.6425406724641989 and parameters: {'learning_rate': 0.0032644132358548724, 'max_depth': 7, 'subsample': 0.860944823058239, 'colsample_bytree': 0.21222797811613714, 'min_child_weight': 6}. Best is trial 0 with value: 0.6512641086871256.
[I 2026-04-07 20:32:45,806] Trial 2 finished with value: 0.6588961955736302 and parameters: {'learning_rate': 0.008707860928874628, 'max_depth': 7, 'subsample': 0.24829895342377833, 'colsample_bytree': 0.8263080540585217, 'min_child_weight': 18}. Best is trial 2 with value: 0.6588961955736302.
[I 2026-04-07 20:32:46,545] Trial 3 finished with value: 0.6535144142476559 and parameters: {'learning_rate': 0.09590108583997968, 'max_depth': 9, 'subsample': 0.9239403742681971, 'colsample_bytree': 0.6547308955377367, 'min_child_weight': 1}. Best is trial 2 with value: 0.6588961955736302.
[I 2026-04-07 20:32:47,787] Trial 4 finished with value: 0.648342290466128 and parameters: {'learning_rate': 0.008877652574334486, 'max_depth': 3, 'subsample': 0.10317205359989218, 'colsample_bytree': 0.2737747965787035, 'min_child_weight': 2}. Best is trial 2 with value: 0.6588961955736302.
[I 2026-04-07 20:32:49,356] Trial 5 finished with value: 0.6392520558123929 and parameters: {'learning_rate': 0.002076657268183072, 'max_depth': 5, 'subsample': 0.17099071407659922, 'colsample_bytree': 0.1841178262693482, 'min_child_weight': 15}. Best is trial 2 with value: 0.6588961955736302.
[I 2026-04-07 20:32:51,196] Trial 6 finished with value: 0.6581568510271363 and parameters: {'learning_rate': 0.007321489080899725, 'max_depth': 7, 'subsample': 0.2286448922670974, 'colsample_bytree': 0.718200156082462, 'min_child_weight': 11}. Best is trial 2 with value: 0.6588961955736302.
[I 2026-04-07 20:32:52,388] Trial 7 finished with value: 0.6304683149206453 and parameters: {'learning_rate': 0.0025563373122135264, 'max_depth': 2, 'subsample': 0.7708702139573538, 'colsample_bytree': 0.8790429291220082, 'min_child_weight': 8}. Best is trial 2 with value: 0.6588961955736302.
[I 2026-04-07 20:32:55,948] Trial 8 finished with value: 0.6576463962695929 and parameters: {'learning_rate': 0.0044711818687930005, 'max_depth': 10, 'subsample': 0.9480470084191386, 'colsample_bytree': 0.5790579024682445, 'min_child_weight': 7}. Best is trial 2 with value: 0.6588961955736302.
[I 2026-04-07 20:32:57,061] Trial 9 finished with value: 0.6123182766387117 and parameters: {'learning_rate': 0.0011505574738245976, 'max_depth': 1, 'subsample': 0.8639651994575758, 'colsample_bytree': 0.7404547842817992, 'min_child_weight': 7}. Best is trial 2 with value: 0.6588961955736302.
[I 2026-04-07 20:32:58,492] Trial 10 finished with value: 0.6620271957744002 and parameters: {'learning_rate': 0.029337009756684882, 'max_depth': 7, 'subsample': 0.38424669291239777, 'colsample_bytree': 0.9893823759726534, 'min_child_weight': 20}. Best is trial 10 with value: 0.6620271957744002.
[I 2026-04-07 20:32:59,999] Trial 11 finished with value: 0.6629940238702172 and parameters: {'learning_rate': 0.02996665855664246, 'max_depth': 7, 'subsample': 0.3835205190775656, 'colsample_bytree': 0.9987239689941956, 'min_child_weight': 20}. Best is trial 11 with value: 0.6629940238702172.
[I 2026-04-07 20:33:01,517] Trial 12 finished with value: 0.6613912328517131 and parameters: {'learning_rate': 0.03460183956018656, 'max_depth': 8, 'subsample': 0.428777655134808, 'colsample_bytree': 0.9870420078706559, 'min_child_weight': 20}. Best is trial 11 with value: 0.6629940238702172.
[I 2026-04-07 20:33:02,868] Trial 13 finished with value: 0.6607219190386631 and parameters: {'learning_rate': 0.027000002620682164, 'max_depth': 4, 'subsample': 0.4127738440160702, 'colsample_bytree': 0.9920786945979501, 'min_child_weight': 17}. Best is trial 11 with value: 0.6629940238702172.
[I 2026-04-07 20:33:04,373] Trial 14 finished with value: 0.6587418825073189 and parameters: {'learning_rate': 0.022041020982815695, 'max_depth': 6, 'subsample': 0.5908478697817674, 'colsample_bytree': 0.3356132277670213, 'min_child_weight': 20}. Best is trial 11 with value: 0.6629940238702172.
[I 2026-04-07 20:33:05,567] Trial 15 finished with value: 0.6563671682053537 and parameters: {'learning_rate': 0.060093063896238495, 'max_depth': 9, 'subsample': 0.35295717853533226, 'colsample_bytree': 0.8619043821256017, 'min_child_weight': 14}. Best is trial 11 with value: 0.6629940238702172.
[I 2026-04-07 20:33:07,282] Trial 16 finished with value: 0.6588695895198801 and parameters: {'learning_rate': 0.017209599513632958, 'max_depth': 6, 'subsample': 0.675155011223003, 'colsample_bytree': 0.39074503628794544, 'min_child_weight': 17}. Best is trial 11 with value: 0.6629940238702172.
[I 2026-04-07 20:33:08,378] Trial 17 finished with value: 0.660869436132375 and parameters: {'learning_rate': 0.045985921006930115, 'max_depth': 8, 'subsample': 0.3505776933816912, 'colsample_bytree': 0.9306804659258724, 'min_child_weight': 14}. Best is trial 11 with value: 0.6629940238702172.
[I 2026-04-07 20:33:09,700] Trial 18 finished with value: 0.6573701085348016 and parameters: {'learning_rate': 0.014708195092308777, 'max_depth': 4, 'subsample': 0.5127500094071337, 'colsample_bytree': 0.7868653231255072, 'min_child_weight': 20}. Best is trial 11 with value: 0.6629940238702172.
[I 2026-04-07 20:33:10,850] Trial 19 finished with value: 0.6432539120896097 and parameters: {'learning_rate': 0.07701710232494761, 'max_depth': 8, 'subsample': 0.4766684468233034, 'colsample_bytree': 0.059389578956372924, 'min_child_weight': 18}. Best is trial 11 with value: 0.6629940238702172.
[I 2026-04-07 20:33:12,445] Trial 20 finished with value: 0.6567676345696408 and parameters: {'learning_rate': 0.04089750425458301, 'max_depth': 10, 'subsample': 0.31156271802312985, 'colsample_bytree': 0.44897479728868483, 'min_child_weight': 16}. Best is trial 11 with value: 0.6629940238702172.
[I 2026-04-07 20:33:13,827] Trial 21 finished with value: 0.6625311255800728 and parameters: {'learning_rate': 0.03315070358637467, 'max_depth': 8, 'subsample': 0.4198716201626051, 'colsample_bytree': 0.9977740416530261, 'min_child_weight': 20}. Best is trial 11 with value: 0.6629940238702172.
[I 2026-04-07 20:33:15,602] Trial 22 finished with value: 0.6607418620733787 and parameters: {'learning_rate': 0.01468341692501309, 'max_depth': 7, 'subsample': 0.662984684942534, 'colsample_bytree': 0.9257905047539369, 'min_child_weight': 19}. Best is trial 11 with value: 0.6629940238702172.
[I 2026-04-07 20:33:17,403] Trial 23 finished with value: 0.6614846838669513 and parameters: {'learning_rate': 0.026263395893562788, 'max_depth': 9, 'subsample': 0.41982019915705115, 'colsample_bytree': 0.9944563838680323, 'min_child_weight': 18}. Best is trial 11 with value: 0.6629940238702172.
[I 2026-04-07 20:33:18,366] Trial 24 finished with value: 0.6593543433306335 and parameters: {'learning_rate': 0.05499926810852064, 'max_depth': 6, 'subsample': 0.27864456953989425, 'colsample_bytree': 0.8954813241686225, 'min_child_weight': 13}. Best is trial 11 with value: 0.6629940238702172.
[I 2026-04-07 20:33:19,138] Trial 25 finished with value: 0.6552972499608528 and parameters: {'learning_rate': 0.034800563305216976, 'max_depth': 8, 'subsample': 0.06697003327938589, 'colsample_bytree': 0.6574847286356889, 'min_child_weight': 16}. Best is trial 11 with value: 0.6629940238702172.
[I 2026-04-07 20:33:20,794] Trial 26 finished with value: 0.6619343481638023 and parameters: {'learning_rate': 0.022132065853408794, 'max_depth': 7, 'subsample': 0.1919597670526818, 'colsample_bytree': 0.7993885734071012, 'min_child_weight': 20}. Best is trial 11 with value: 0.6629940238702172.
[I 2026-04-07 20:33:22,387] Trial 27 finished with value: 0.6581139888432936 and parameters: {'learning_rate': 0.012788000591543495, 'max_depth': 5, 'subsample': 0.5566188809343178, 'colsample_bytree': 0.9298794002534594, 'min_child_weight': 9}. Best is trial 11 with value: 0.6629940238702172.
[I 2026-04-07 20:33:23,008] Trial 28 finished with value: 0.6558832274567848 and parameters: {'learning_rate': 0.07162243360124607, 'max_depth': 9, 'subsample': 0.3740005175310712, 'colsample_bytree': 0.675200407515975, 'min_child_weight': 18}. Best is trial 11 with value: 0.6629940238702172.
[I 2026-04-07 20:33:24,627] Trial 29 finished with value: 0.65512237511439 and parameters: {'learning_rate': 0.005721131831902421, 'max_depth': 6, 'subsample': 0.47054273413999287, 'colsample_bytree': 0.49111531519321455, 'min_child_weight': 4}. Best is trial 11 with value: 0.6629940238702172.

Best params for fold 3: {'learning_rate': 0.02996665855664246, 'max_depth': 7, 'subsample': 0.3835205190775656, 'colsample_bytree': 0.9987239689941956, 'min_child_weight': 20}

[I 2026-04-07 20:33:26,618] A new study created in memory with name: Xgboost

Fold 3 AUC: 0.6629

==================================================
Fold 4/5
==================================================

[I 2026-04-07 20:33:28,486] Trial 0 finished with value: 0.6623523015642062 and parameters: {'learning_rate': 0.0035674408563110705, 'max_depth': 7, 'subsample': 0.1419909006656476, 'colsample_bytree': 0.6762658677777235, 'min_child_weight': 17}. Best is trial 0 with value: 0.6623523015642062.
[I 2026-04-07 20:33:31,511] Trial 1 finished with value: 0.6633097560288747 and parameters: {'learning_rate': 0.007559588682129681, 'max_depth': 9, 'subsample': 0.9471497787911717, 'colsample_bytree': 0.7711381734148368, 'min_child_weight': 2}. Best is trial 1 with value: 0.6633097560288747.
[I 2026-04-07 20:33:33,430] Trial 2 finished with value: 0.6615759819183301 and parameters: {'learning_rate': 0.002047663106638644, 'max_depth': 7, 'subsample': 0.5632377343087152, 'colsample_bytree': 0.9013894403562951, 'min_child_weight': 12}. Best is trial 1 with value: 0.6633097560288747.
[I 2026-04-07 20:33:34,489] Trial 3 finished with value: 0.6436873788149498 and parameters: {'learning_rate': 0.01963731387991994, 'max_depth': 1, 'subsample': 0.5912065258580042, 'colsample_bytree': 0.6872293317213589, 'min_child_weight': 12}. Best is trial 1 with value: 0.6633097560288747.
[I 2026-04-07 20:33:35,669] Trial 4 finished with value: 0.6414684055776152 and parameters: {'learning_rate': 0.0028111706724849605, 'max_depth': 2, 'subsample': 0.5218110605248475, 'colsample_bytree': 0.46009774856486746, 'min_child_weight': 15}. Best is trial 1 with value: 0.6633097560288747.
[I 2026-04-07 20:33:37,341] Trial 5 finished with value: 0.6591544555942513 and parameters: {'learning_rate': 0.01063380457664703, 'max_depth': 5, 'subsample': 0.9701970091036257, 'colsample_bytree': 0.9472846920774193, 'min_child_weight': 13}. Best is trial 1 with value: 0.6633097560288747.
[I 2026-04-07 20:33:37,906] Trial 6 finished with value: 0.6631504462530287 and parameters: {'learning_rate': 0.07929300732564085, 'max_depth': 6, 'subsample': 0.1995662775403873, 'colsample_bytree': 0.9501586341637348, 'min_child_weight': 5}. Best is trial 1 with value: 0.6633097560288747.
[I 2026-04-07 20:33:38,841] Trial 7 finished with value: 0.6569370520911885 and parameters: {'learning_rate': 0.048472889491209134, 'max_depth': 10, 'subsample': 0.21860840096971373, 'colsample_bytree': 0.5143926635072312, 'min_child_weight': 5}. Best is trial 1 with value: 0.6633097560288747.
[I 2026-04-07 20:33:40,633] Trial 8 finished with value: 0.6682737720870999 and parameters: {'learning_rate': 0.026928981284994304, 'max_depth': 7, 'subsample': 0.8652764891360125, 'colsample_bytree': 0.4749036242464349, 'min_child_weight': 13}. Best is trial 8 with value: 0.6682737720870999.
[I 2026-04-07 20:33:42,670] Trial 9 finished with value: 0.6641887133498338 and parameters: {'learning_rate': 0.005301293763044012, 'max_depth': 9, 'subsample': 0.14327424345683792, 'colsample_bytree': 0.7173092013522507, 'min_child_weight': 15}. Best is trial 8 with value: 0.6682737720870999.
[I 2026-04-07 20:33:43,990] Trial 10 finished with value: 0.6484810760971713 and parameters: {'learning_rate': 0.0010599019650493712, 'max_depth': 4, 'subsample': 0.7815757307959499, 'colsample_bytree': 0.21830746989995925, 'min_child_weight': 20}. Best is trial 8 with value: 0.6682737720870999.
[I 2026-04-07 20:33:45,834] Trial 11 finished with value: 0.6652545420600129 and parameters: {'learning_rate': 0.026280457308083083, 'max_depth': 8, 'subsample': 0.38952915183127607, 'colsample_bytree': 0.31698279505830035, 'min_child_weight': 8}. Best is trial 8 with value: 0.6682737720870999.
[I 2026-04-07 20:33:47,694] Trial 12 finished with value: 0.6643677204225036 and parameters: {'learning_rate': 0.025267990251088196, 'max_depth': 8, 'subsample': 0.39758299667141206, 'colsample_bytree': 0.2819338881580251, 'min_child_weight': 8}. Best is trial 8 with value: 0.6682737720870999.
[I 2026-04-07 20:33:49,106] Trial 13 finished with value: 0.6543004148061925 and parameters: {'learning_rate': 0.02660003281109373, 'max_depth': 4, 'subsample': 0.7352607165561416, 'colsample_bytree': 0.06814354066127898, 'min_child_weight': 8}. Best is trial 8 with value: 0.6682737720870999.
[I 2026-04-07 20:33:50,221] Trial 14 finished with value: 0.6628568225032099 and parameters: {'learning_rate': 0.04872516358909061, 'max_depth': 7, 'subsample': 0.3613687688937963, 'colsample_bytree': 0.37371985880424075, 'min_child_weight': 9}. Best is trial 8 with value: 0.6682737720870999.
[I 2026-04-07 20:33:52,267] Trial 15 finished with value: 0.644463463782945 and parameters: {'learning_rate': 0.014604735097210863, 'max_depth': 10, 'subsample': 0.7795751861834421, 'colsample_bytree': 0.15628768083314465, 'min_child_weight': 5}. Best is trial 8 with value: 0.6682737720870999.
[I 2026-04-07 20:33:54,013] Trial 16 finished with value: 0.6644500714985276 and parameters: {'learning_rate': 0.03955479350532096, 'max_depth': 8, 'subsample': 0.3705500106793126, 'colsample_bytree': 0.3759163747981353, 'min_child_weight': 10}. Best is trial 8 with value: 0.6682737720870999.
[I 2026-04-07 20:33:55,014] Trial 17 finished with value: 0.6690498309797749 and parameters: {'learning_rate': 0.08343191665440626, 'max_depth': 5, 'subsample': 0.6780323801566223, 'colsample_bytree': 0.5506632599408162, 'min_child_weight': 2}. Best is trial 17 with value: 0.6690498309797749.
[I 2026-04-07 20:33:56,283] Trial 18 finished with value: 0.6696481552754023 and parameters: {'learning_rate': 0.08944683263635181, 'max_depth': 3, 'subsample': 0.8690661849246916, 'colsample_bytree': 0.5941534281187826, 'min_child_weight': 1}. Best is trial 18 with value: 0.6696481552754023.
[I 2026-04-07 20:33:57,408] Trial 19 finished with value: 0.6693446229039354 and parameters: {'learning_rate': 0.08122272515675462, 'max_depth': 3, 'subsample': 0.6787825907435666, 'colsample_bytree': 0.5877027775952236, 'min_child_weight': 1}. Best is trial 18 with value: 0.6696481552754023.
[I 2026-04-07 20:33:58,646] Trial 20 finished with value: 0.6702124199878802 and parameters: {'learning_rate': 0.0933749763002824, 'max_depth': 3, 'subsample': 0.8854701079544368, 'colsample_bytree': 0.6098335329937612, 'min_child_weight': 1}. Best is trial 20 with value: 0.6702124199878802.
[I 2026-04-07 20:33:59,773] Trial 21 finished with value: 0.6700188420263237 and parameters: {'learning_rate': 0.09959137951805577, 'max_depth': 3, 'subsample': 0.8966296016618909, 'colsample_bytree': 0.6017583822253324, 'min_child_weight': 1}. Best is trial 20 with value: 0.6702124199878802.
[I 2026-04-07 20:34:01,149] Trial 22 finished with value: 0.6649545924375313 and parameters: {'learning_rate': 0.05990313678986038, 'max_depth': 2, 'subsample': 0.8665885523438056, 'colsample_bytree': 0.8007469458193174, 'min_child_weight': 3}. Best is trial 20 with value: 0.6702124199878802.
[I 2026-04-07 20:34:02,192] Trial 23 finished with value: 0.670079441070298 and parameters: {'learning_rate': 0.09402437683914627, 'max_depth': 3, 'subsample': 0.895930208934493, 'colsample_bytree': 0.6234537580712395, 'min_child_weight': 4}. Best is trial 20 with value: 0.6702124199878802.
[I 2026-04-07 20:34:03,393] Trial 24 finished with value: 0.6501528430964547 and parameters: {'learning_rate': 0.0377602842471441, 'max_depth': 1, 'subsample': 0.99613221402435, 'colsample_bytree': 0.6187285251222063, 'min_child_weight': 4}. Best is trial 20 with value: 0.6702124199878802.
[I 2026-04-07 20:34:04,595] Trial 25 finished with value: 0.668491308052789 and parameters: {'learning_rate': 0.06043598518315819, 'max_depth': 3, 'subsample': 0.8847281987516336, 'colsample_bytree': 0.8408657144475444, 'min_child_weight': 6}. Best is trial 20 with value: 0.6702124199878802.
[I 2026-04-07 20:34:05,759] Trial 26 finished with value: 0.6692057144585564 and parameters: {'learning_rate': 0.09942185685355047, 'max_depth': 4, 'subsample': 0.7970813224638067, 'colsample_bytree': 0.43977358638089303, 'min_child_weight': 3}. Best is trial 20 with value: 0.6702124199878802.
[I 2026-04-07 20:34:07,002] Trial 27 finished with value: 0.6647337657664423 and parameters: {'learning_rate': 0.056317656504326845, 'max_depth': 2, 'subsample': 0.937009994844529, 'colsample_bytree': 0.6381623539800275, 'min_child_weight': 1}. Best is trial 20 with value: 0.6702124199878802.
[I 2026-04-07 20:34:08,228] Trial 28 finished with value: 0.6661935351980316 and parameters: {'learning_rate': 0.036880846318859434, 'max_depth': 3, 'subsample': 0.6955374177686733, 'colsample_bytree': 0.7174953514930176, 'min_child_weight': 6}. Best is trial 20 with value: 0.6702124199878802.
[I 2026-04-07 20:34:09,064] Trial 29 finished with value: 0.6686578511224383 and parameters: {'learning_rate': 0.0667914173176882, 'max_depth': 5, 'subsample': 0.6170141546518646, 'colsample_bytree': 0.530151220725627, 'min_child_weight': 3}. Best is trial 20 with value: 0.6702124199878802.

Best params for fold 4: {'learning_rate': 0.0933749763002824, 'max_depth': 3, 'subsample': 0.8854701079544368, 'colsample_bytree': 0.6098335329937612, 'min_child_weight': 1}

[I 2026-04-07 20:34:10,233] A new study created in memory with name: Xgboost

Fold 4 AUC: 0.6611

==================================================
Fold 5/5
==================================================

[I 2026-04-07 20:34:11,782] Trial 0 finished with value: 0.6558014053116834 and parameters: {'learning_rate': 0.002078741016752897, 'max_depth': 6, 'subsample': 0.2634200058287854, 'colsample_bytree': 0.2844756709561361, 'min_child_weight': 20}. Best is trial 0 with value: 0.6558014053116834.
[I 2026-04-07 20:34:13,606] Trial 1 finished with value: 0.6404457716195506 and parameters: {'learning_rate': 0.0037275590320679846, 'max_depth': 8, 'subsample': 0.3200342058698116, 'colsample_bytree': 0.06805206506901729, 'min_child_weight': 13}. Best is trial 0 with value: 0.6558014053116834.
[I 2026-04-07 20:34:14,755] Trial 2 finished with value: 0.641653253982688 and parameters: {'learning_rate': 0.0023717557835721535, 'max_depth': 2, 'subsample': 0.06713136189665113, 'colsample_bytree': 0.4446655840994831, 'min_child_weight': 7}. Best is trial 0 with value: 0.6558014053116834.
[I 2026-04-07 20:34:15,781] Trial 3 finished with value: 0.604892756865979 and parameters: {'learning_rate': 0.001122201338251858, 'max_depth': 1, 'subsample': 0.4115182082582251, 'colsample_bytree': 0.9558338636543526, 'min_child_weight': 17}. Best is trial 0 with value: 0.6558014053116834.
[I 2026-04-07 20:34:17,256] Trial 4 finished with value: 0.6451660269956101 and parameters: {'learning_rate': 0.008384046609561435, 'max_depth': 5, 'subsample': 0.10231054234439796, 'colsample_bytree': 0.07265500832629704, 'min_child_weight': 13}. Best is trial 0 with value: 0.6558014053116834.
[I 2026-04-07 20:34:18,630] Trial 5 finished with value: 0.6498391660716611 and parameters: {'learning_rate': 0.08303815633518581, 'max_depth': 1, 'subsample': 0.8142064540112571, 'colsample_bytree': 0.9638405642729164, 'min_child_weight': 20}. Best is trial 0 with value: 0.6558014053116834.
[I 2026-04-07 20:34:20,303] Trial 6 finished with value: 0.6575431497300183 and parameters: {'learning_rate': 0.0015260245537432261, 'max_depth': 6, 'subsample': 0.34677615440152715, 'colsample_bytree': 0.6902752716751367, 'min_child_weight': 4}. Best is trial 6 with value: 0.6575431497300183.
[I 2026-04-07 20:34:21,659] Trial 7 finished with value: 0.6610745617728022 and parameters: {'learning_rate': 0.029623992381409326, 'max_depth': 9, 'subsample': 0.9137820260573963, 'colsample_bytree': 0.5591257470792923, 'min_child_weight': 16}. Best is trial 7 with value: 0.6610745617728022.
[I 2026-04-07 20:34:22,685] Trial 8 finished with value: 0.6166554281185187 and parameters: {'learning_rate': 0.0016512420112956506, 'max_depth': 1, 'subsample': 0.6885886282931031, 'colsample_bytree': 0.46120006113192535, 'min_child_weight': 9}. Best is trial 7 with value: 0.6610745617728022.
[I 2026-04-07 20:34:23,228] Trial 9 finished with value: 0.6568750214506717 and parameters: {'learning_rate': 0.06361303538051513, 'max_depth': 7, 'subsample': 0.09469849031093894, 'colsample_bytree': 0.7130534528149074, 'min_child_weight': 19}. Best is trial 7 with value: 0.6610745617728022.
[I 2026-04-07 20:34:25,229] Trial 10 finished with value: 0.6604866028727702 and parameters: {'learning_rate': 0.02654897949232022, 'max_depth': 10, 'subsample': 0.9784495091132803, 'colsample_bytree': 0.7042123464331329, 'min_child_weight': 14}. Best is trial 7 with value: 0.6610745617728022.
[I 2026-04-07 20:34:27,047] Trial 11 finished with value: 0.6609662308692085 and parameters: {'learning_rate': 0.02690118552983357, 'max_depth': 10, 'subsample': 0.9887573684946088, 'colsample_bytree': 0.6876507853797235, 'min_child_weight': 15}. Best is trial 7 with value: 0.6610745617728022.
[I 2026-04-07 20:34:29,457] Trial 12 finished with value: 0.6611633715628406 and parameters: {'learning_rate': 0.020930799743833346, 'max_depth': 10, 'subsample': 0.9929477106026328, 'colsample_bytree': 0.5992696215605866, 'min_child_weight': 16}. Best is trial 12 with value: 0.6611633715628406.
[I 2026-04-07 20:34:31,700] Trial 13 finished with value: 0.6622284575515667 and parameters: {'learning_rate': 0.018650015800872197, 'max_depth': 9, 'subsample': 0.7734023334637996, 'colsample_bytree': 0.5617458523310771, 'min_child_weight': 16}. Best is trial 13 with value: 0.6622284575515667.
[I 2026-04-07 20:34:33,043] Trial 14 finished with value: 0.6570653460430367 and parameters: {'learning_rate': 0.010563235291024754, 'max_depth': 4, 'subsample': 0.6550658483266489, 'colsample_bytree': 0.3254660357402326, 'min_child_weight': 11}. Best is trial 13 with value: 0.6622284575515667.
[I 2026-04-07 20:34:35,198] Trial 15 finished with value: 0.6611610611049846 and parameters: {'learning_rate': 0.012177346762999867, 'max_depth': 8, 'subsample': 0.7832696363592568, 'colsample_bytree': 0.8381846473958408, 'min_child_weight': 17}. Best is trial 13 with value: 0.6622284575515667.
[I 2026-04-07 20:34:37,812] Trial 16 finished with value: 0.6619726783396811 and parameters: {'learning_rate': 0.01692165143397957, 'max_depth': 9, 'subsample': 0.5682186650090927, 'colsample_bytree': 0.5575275885441766, 'min_child_weight': 2}. Best is trial 13 with value: 0.6622284575515667.
[I 2026-04-07 20:34:40,091] Trial 17 finished with value: 0.6576395975629471 and parameters: {'learning_rate': 0.005504246797797792, 'max_depth': 8, 'subsample': 0.5520071527032324, 'colsample_bytree': 0.3259197574116788, 'min_child_weight': 1}. Best is trial 13 with value: 0.6622284575515667.
[I 2026-04-07 20:34:41,173] Trial 18 finished with value: 0.6624041626090816 and parameters: {'learning_rate': 0.05247072304397114, 'max_depth': 4, 'subsample': 0.5002773350472217, 'colsample_bytree': 0.43161948264645267, 'min_child_weight': 1}. Best is trial 18 with value: 0.6624041626090816.
[I 2026-04-07 20:34:42,636] Trial 19 finished with value: 0.6595197489317164 and parameters: {'learning_rate': 0.0490723859744689, 'max_depth': 3, 'subsample': 0.47441825460279335, 'colsample_bytree': 0.20036066643575007, 'min_child_weight': 6}. Best is trial 18 with value: 0.6624041626090816.
[I 2026-04-07 20:34:44,068] Trial 20 finished with value: 0.6627051686576098 and parameters: {'learning_rate': 0.04137394627685702, 'max_depth': 4, 'subsample': 0.6630152406824767, 'colsample_bytree': 0.431002377864811, 'min_child_weight': 10}. Best is trial 20 with value: 0.6627051686576098.
[I 2026-04-07 20:34:45,388] Trial 21 finished with value: 0.6627339265907497 and parameters: {'learning_rate': 0.045566954769341986, 'max_depth': 4, 'subsample': 0.686842322102692, 'colsample_bytree': 0.43302271548121746, 'min_child_weight': 11}. Best is trial 21 with value: 0.6627339265907497.
[I 2026-04-07 20:34:46,817] Trial 22 finished with value: 0.6629634788482746 and parameters: {'learning_rate': 0.0465224197056908, 'max_depth': 4, 'subsample': 0.6347786069409747, 'colsample_bytree': 0.4197238163655338, 'min_child_weight': 10}. Best is trial 22 with value: 0.6629634788482746.
[I 2026-04-07 20:34:48,142] Trial 23 finished with value: 0.662019052887493 and parameters: {'learning_rate': 0.037687040660772234, 'max_depth': 4, 'subsample': 0.6867432601158117, 'colsample_bytree': 0.38920980261177585, 'min_child_weight': 11}. Best is trial 22 with value: 0.6629634788482746.
[I 2026-04-07 20:34:49,098] Trial 24 finished with value: 0.6607061565111569 and parameters: {'learning_rate': 0.09381111991303104, 'max_depth': 3, 'subsample': 0.6211632343876816, 'colsample_bytree': 0.2133496450199901, 'min_child_weight': 9}. Best is trial 22 with value: 0.6629634788482746.
[I 2026-04-07 20:34:50,458] Trial 25 finished with value: 0.6640287252158539 and parameters: {'learning_rate': 0.04237893606534701, 'max_depth': 5, 'subsample': 0.745076604162433, 'colsample_bytree': 0.498014838276501, 'min_child_weight': 8}. Best is trial 25 with value: 0.6640287252158539.
[I 2026-04-07 20:34:51,528] Trial 26 finished with value: 0.6594831975886719 and parameters: {'learning_rate': 0.073194654890049, 'max_depth': 5, 'subsample': 0.869827237366574, 'colsample_bytree': 0.2288763471979618, 'min_child_weight': 7}. Best is trial 25 with value: 0.6640287252158539.
[I 2026-04-07 20:34:52,916] Trial 27 finished with value: 0.6588910187200613 and parameters: {'learning_rate': 0.03547050615912673, 'max_depth': 3, 'subsample': 0.7369275567726954, 'colsample_bytree': 0.49668463135019336, 'min_child_weight': 5}. Best is trial 25 with value: 0.6640287252158539.
[I 2026-04-07 20:34:53,724] Trial 28 finished with value: 0.6622183737311628 and parameters: {'learning_rate': 0.05299832686143199, 'max_depth': 5, 'subsample': 0.5842537037258015, 'colsample_bytree': 0.6234253276244356, 'min_child_weight': 8}. Best is trial 25 with value: 0.6640287252158539.
[I 2026-04-07 20:34:54,334] Trial 29 finished with value: 0.6598940180451871 and parameters: {'learning_rate': 0.09974034359152532, 'max_depth': 6, 'subsample': 0.8587457526736875, 'colsample_bytree': 0.35533201872682574, 'min_child_weight': 11}. Best is trial 25 with value: 0.6640287252158539.

Best params for fold 5: {'learning_rate': 0.04237893606534701, 'max_depth': 5, 'subsample': 0.745076604162433, 'colsample_bytree': 0.498014838276501, 'min_child_weight': 8}
Fold 5 AUC: 0.6706

==================================================
Cross-Validation Summary
==================================================
Mean AUC: 0.6661 (+/- 0.0040)

In [283]:
df_middle_class.U.describe()

count    194373.000000
mean          0.083095
std           0.029994
min          -0.001829
25%           0.061570
50%           0.094024
75%           0.103913
max           0.418037
Name: U, dtype: float64

## Section 9 — XGBoost Output: Acceptance Probability & Expected Financial Loss

Post-CV, the following export steps are performed:

### `df_acceptance_xgb_black_box.csv`
Selected columns from `df_middle_class`:  
`id, X_age, X_bonus_malus_rating, X_distr_channel, X_vehicle_type, X_ttm_claims, X_policy_count, X_risk_code, X_vehicle_age, X_policy_tenure, X_policy_premium, U, prob_acceptance, Z`

- `prob_acceptance` = acceptance probability predicted by the XGBoost classifier  
- `U` = premium uplift factor (`1 + relative_change`)  
- `Z` = binary acceptance outcome (ground truth)

### `df_exp_financial_loss_xgb_black_box.csv`
Selected columns from `df_middle`:  
`id, ..., Y (actual premium), U, Y_hat (predicted premium)`

- `Y_hat` = XGBoost regressor's OOF premium prediction  
- Used to compute expected financial loss = `Y_hat × (1 − prob_acceptance)`

In [284]:
df_middle_class['Z'] = 1- df_middle_class['is_churn'].astype(int)

In [285]:
model_features_class

['X_age',
 'X_bonus_malus_rating',
 'X_distr_channel',
 'X_vehicle_type',
 'X_ttm_claims',
 'X_policy_count',
 'X_risk_code',
 'X_vehicle_age',
 'X_policy_tenure',
 'X_policy_premium',
 'U']

In [286]:
df_middle_class['prob_acceptance'] = 1 - df_middle_class['oof_prediction']

In [287]:
df_middle_class.columns

Index(['id', 'X_age', 'X_bonus_malus_rating', 'X_distr_channel',
       'X_vehicle_type', 'X_ttm_claims', 'X_policy_count', 'X_risk_code',
       'X_vehicle_age', 'X_policy_tenure', 'X_policy_premium',
       'X_prev_renewal_perc', 'X_upcoming_premium', 'X_cur_renewal_perc',
       'year', 'is_churn', 'U', 'fold_number', 'oof_prediction', 'Z',
       'prob_acceptance'],
      dtype='str')

In [288]:
df_middle.columns = ['id', 'X_age','X_bonus_malus_rating','X_distr_channel','X_vehicle_type','X_ttm_claims','X_policy_count','X_risk_code','X_vehicle_age','X_policy_tenure',
                     'Y','X_prev_renewal_perc','X_upcoming_premium','X_cur_renewal_perc','X_year','1-Z','U','fold_number','Y_hat','Y_residual','Y_absolute_error']

In [289]:
df_middle_class.columns = ['id', 'X_age','X_bonus_malus_rating','X_distr_channel','X_vehicle_type','X_ttm_claims','X_policy_count','X_risk_code',"X_vehicle_age",
                           'X_policy_tenure','X_policy_premium','X_prev_renewal_perc','X_upcoming_premium','X_cur_renewal_perc','X_year','1-Z', 'U','fold_number','churn_prediction','Z','prob_acceptance']

In [290]:
df_middle_class['U+1'] = 1 + df_middle_class['U']

In [291]:
df_middle_class.loc[:, ['id', 'X_age','X_bonus_malus_rating','X_distr_channel','X_vehicle_type','X_ttm_claims','X_policy_count','X_risk_code','X_vehicle_age',
                           'X_policy_tenure','X_policy_premium', 'U','prob_acceptance','Z']]

,id,X_age,X_bonus_malus_rating,X_distr_channel,X_vehicle_type,X_ttm_claims,X_policy_count,X_risk_code,X_vehicle_age,X_policy_tenure,X_policy_premium,U,prob_acceptance,Z
7,5,93.0,45.0,5,7,0,1,0,24.0,24.0,175.7725,0.123099,0.848508,1
16,85,78.0,45.0,5,0,0,2,0,5.0,24.0,180.8686,0.107047,0.946727,1
24,93,78.0,45.0,5,1,0,1,0,21.0,24.0,165.6403,0.096895,0.920173,1
32,119,49.0,45.0,5,1,0,1,0,19.0,24.0,171.3347,0.097209,0.931579,1
118,395,49.0,45.0,2,2,0,4,0,16.0,24.0,170.0981,0.102011,0.941084,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3370174,5732129,68.0,45.0,4,2,0,1,2,9.0,9.0,345.4078,0.062686,0.930541,1
3370323,5732370,81.0,45.0,4,4,0,5,0,20.0,10.0,234.6113,0.087288,0.949478,1
3370329,5732373,58.0,45.0,4,7,0,3,0,30.0,8.0,174.1869,0.087051,0.918007,0
3370407,5732452,89.0,45.0,4,1,0,2,0,10.0,23.0,238.8796,0.087493,0.927157,0
3370452,5732508,54.0,45.0,7,0,1,1,1,22.0,21.0,220.5798,0.087271,0.854156,1

In [292]:
df_middle_class.loc[:, ['id', 'X_age','X_bonus_malus_rating','X_distr_channel','X_vehicle_type','X_ttm_claims','X_policy_count','X_risk_code','X_vehicle_age',
                           'X_policy_tenure','X_policy_premium', 'U', 'U+1','prob_acceptance','Z']].to_csv('df_acceptance_xgb_black_box_feat_processor.csv',sep=';')

In [293]:
df_middle.loc[:,['id', 'X_age','X_bonus_malus_rating','X_distr_channel','X_vehicle_type','X_ttm_claims','X_policy_count','X_risk_code','X_vehicle_age','X_policy_tenure',
                     'Y','U','Y_hat']]

,id,X_age,X_bonus_malus_rating,X_distr_channel,X_vehicle_type,X_ttm_claims,X_policy_count,X_risk_code,X_vehicle_age,X_policy_tenure,Y,U,Y_hat
7,5,93.0,45.0,5,7,0,1,0,24.0,24.0,175.7725,0.123099,208.090927
16,85,78.0,45.0,5,0,0,2,0,5.0,24.0,180.8686,0.107047,157.774734
24,93,78.0,45.0,5,1,0,1,0,21.0,24.0,165.6403,0.096895,170.593414
32,119,49.0,45.0,5,1,0,1,0,19.0,24.0,171.3347,0.097209,173.659164
118,395,49.0,45.0,2,2,0,4,0,16.0,24.0,170.0981,0.102011,213.783005
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3370174,5732129,68.0,45.0,4,2,0,1,2,9.0,9.0,345.4078,0.062686,261.505676
3370323,5732370,81.0,45.0,4,4,0,5,0,20.0,10.0,234.6113,0.087288,231.815430
3370329,5732373,58.0,45.0,4,7,0,3,0,30.0,8.0,174.1869,0.087051,191.933762
3370407,5732452,89.0,45.0,4,1,0,2,0,10.0,23.0,238.8796,0.087493,184.055298
3370452,5732508,54.0,45.0,7,0,1,1,1,22.0,21.0,220.5798,0.087271,208.673264

In [294]:
df_middle['U+1'] = 1 + df_middle['U']

In [295]:
df_middle.columns

Index(['id', 'X_age', 'X_bonus_malus_rating', 'X_distr_channel',
       'X_vehicle_type', 'X_ttm_claims', 'X_policy_count', 'X_risk_code',
       'X_vehicle_age', 'X_policy_tenure', 'Y', 'X_prev_renewal_perc',
       'X_upcoming_premium', 'X_cur_renewal_perc', 'X_year', '1-Z', 'U',
       'fold_number', 'Y_hat', 'Y_residual', 'Y_absolute_error', 'U+1'],
      dtype='str')

In [296]:
df_middle.loc[:,['id', 'X_age','X_bonus_malus_rating','X_distr_channel','X_vehicle_type','X_ttm_claims','X_policy_count','X_risk_code','X_vehicle_age','X_policy_tenure',
                     'Y','U','U+1','Y_hat']].to_csv('df_exp_financial_loss_xgb_black_box_feat_processor.csv',sep=';')

In [297]:
from pygam import LinearGAM, s
from pygam.datasets import toy_interaction

X, y = toy_interaction(return_X_y=True)

gam = LinearGAM(s(0, by=1)).fit(X, y)
gam.summary()

LinearGAM
=============================================== ==========================================================
Distribution:                        NormalDist Effective DoF:                                     20.8506
Link Function:                     IdentityLink Log Likelihood:                                 44202.0909
Number of Samples:                        50000 AIC:                                           -88360.4805
                                                AICc:                                          -88360.4605
                                                GCV:                                                  0.01
                                                Scale:                                                 0.1
                                                Pseudo R-Squared:                                   0.9976
==========================================================================================================
Feature Function                  Lambda               Rank         EDoF         P > x        Sig. Code
================================= ==================== ============ ============ ============ ============
s(0)                              [0.6]                20           19.9         1.11e-16     ***
intercept                                              1            1.0          7.95e-01
==========================================================================================================
Significance codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

WARNING: Fitting splines and a linear function to a feature introduces a model identifiability problem
         which can cause p-values to appear significant when they are not.

WARNING: p-values calculated in this manner behave correctly for un-penalized models or models with
         known smoothing parameters, but when smoothing parameters have been estimated, the p-values
         are typically lower than they should be, meaning that the tests reject the null too readily.

C:\Users\malosett\AppData\Local\Temp\ipykernel_13900\427681795.py:7: UserWarning: KNOWN BUG: p-values computed in this summary are likely much smaller than they should be.

Please do not make inferences based on these values!

Collaborate on a solution, and stay up to date at:
github.com/dswah/pyGAM/issues/163

  gam.summary()

In [298]:
!pip install pygam

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pygam in c:\users\malosett\appdata\roaming\python\python311\site-packages (0.12.0)
Requirement already satisfied: numpy>=1.5.0 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from pygam) (2.4.4)
Requirement already satisfied: progressbar2<5,>=4.2.0 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from pygam) (4.5.0)
Requirement already satisfied: scipy<1.17,>=1.11.1 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from pygam) (1.16.3)
Requirement already satisfied: python-utils>=3.8.1 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from progressbar2<5,>=4.2.0->pygam) (3.9.1)
Requirement already satisfied: typing_extensions>3.10.0.2 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from python-utils>=3.8.1->progressbar2<5,>=4.2.0->pygam) (4.15.0)

## Section 10 — GLM & GAM Dataset Preparation

Three additional datasets are created for the interpretable models, all using the same `filter_middle_advanced` thresholds:

| Dataset | Used by |
|---|---|
| `df_middle_glm` | GLM (Logistic Regression) churn classifier |
| `df_middle_gam` | GAM (LogisticGAM) churn classifier |
| `df_middle_reg` | (supporting dataset, currently superseded by `df_middle_reg_linear`) |

For GAM and GLM, categorical columns are **label-encoded** so that the preprocessors within each pipeline start from the same integer representation.  
`U` is computed and added to each dataset before training.

In [299]:
df_middle_glm = filter_middle_advanced(
    df_sub,
    numeric_filters={
        'X_age': {'multiplier': 1.5, 'method': 'iqr'},
        'X_policy_premium': {'multiplier': 2.0, 'method': 'iqr'},
        'X_upcoming_premium':{'multiplier':2.0,'method':'iqr'},
        'X_vehicle_age': {'method': 'percentile', 'lower_q': 0.05, 'upper_q': 0.95},
        'X_cur_renewal_perc':{'method': 'percentile', 'lower_q': 0.05, 'upper_q': 0.95}
    },
    categorical_filters={
        'X_distr_channel': {'max_categories':12},
        'X_risk_code': {'max_categories': 6},
        'X_vehicle_type': {'max_categories': 8}  # explicit list
    },
    keep_id_cols=['encoded_policy_number']
)

X_age: [8.50, 100.50]
X_policy_premium: [-14.06, 444.14]
X_upcoming_premium: [-15.07, 480.13]
X_vehicle_age: [4.00, 31.00]
X_cur_renewal_perc: [-0.02, 0.11]
X_distr_channel: Kept 12 categories
X_risk_code: Kept 6 categories
X_vehicle_type: Kept 8 categories

Total: 463400 → 194373 rows

In [300]:
df_middle_glm['U'] = (df_middle_glm['X_upcoming_premium'] - df_middle_glm['X_policy_premium']) / df_middle_glm['X_policy_premium']

In [301]:
df_middle_gam = filter_middle_advanced(
    df_sub,
    numeric_filters={
        'X_age': {'multiplier': 1.5, 'method': 'iqr'},
        'X_policy_premium': {'multiplier': 2.0, 'method': 'iqr'},
        'X_upcoming_premium':{'multiplier':2.0,'method':'iqr'},
        'X_vehicle_age': {'method': 'percentile', 'lower_q': 0.05, 'upper_q': 0.95},
        'X_cur_renewal_perc':{'method': 'percentile', 'lower_q': 0.05, 'upper_q': 0.95}
    },
    categorical_filters={
        'X_distr_channel': {'max_categories':12},
        'X_risk_code': {'max_categories': 6},
        'X_vehicle_type': {'max_categories': 8}  # explicit list
    },
    keep_id_cols=['encoded_policy_number']
)

X_age: [8.50, 100.50]
X_policy_premium: [-14.06, 444.14]
X_upcoming_premium: [-15.07, 480.13]
X_vehicle_age: [4.00, 31.00]
X_cur_renewal_perc: [-0.02, 0.11]
X_distr_channel: Kept 12 categories
X_risk_code: Kept 6 categories
X_vehicle_type: Kept 8 categories

Total: 463400 → 194373 rows

In [302]:
df_middle_gam.columns

Index(['id', 'X_age', 'X_bonus_malus_rating', 'X_distr_channel',
       'X_vehicle_type', 'X_ttm_claims', 'X_policy_count', 'X_risk_code',
       'X_vehicle_age', 'X_policy_tenure', 'X_policy_premium',
       'X_prev_renewal_perc', 'X_upcoming_premium', 'X_cur_renewal_perc',
       'year', 'is_churn'],
      dtype='str')

In [303]:
df_middle_gam['U'] = (df_middle_gam['X_upcoming_premium'] - df_middle_gam['X_policy_premium']) / df_middle_gam['X_policy_premium']

In [304]:
df_middle_reg = filter_middle_advanced(
    df_sub,
    numeric_filters={
        'X_age': {'multiplier': 1.5, 'method': 'iqr'},
        'X_policy_premium': {'multiplier': 2.0, 'method': 'iqr'},
        'X_upcoming_premium':{'multiplier':2.0,'method':'iqr'},
        'X_vehicle_age': {'method': 'percentile', 'lower_q': 0.05, 'upper_q': 0.95},
        'X_cur_renewal_perc':{'method': 'percentile', 'lower_q': 0.05, 'upper_q': 0.95}
    },
    categorical_filters={
        'X_distr_channel': {'max_categories':12},
        'X_risk_code': {'max_categories': 6},
        'X_vehicle_type': {'max_categories': 8}  # explicit list
    },
    keep_id_cols=['encoded_policy_number']
)

X_age: [8.50, 100.50]
X_policy_premium: [-14.06, 444.14]
X_upcoming_premium: [-15.07, 480.13]
X_vehicle_age: [4.00, 31.00]
X_cur_renewal_perc: [-0.02, 0.11]
X_distr_channel: Kept 12 categories
X_risk_code: Kept 6 categories
X_vehicle_type: Kept 8 categories

Total: 463400 → 194373 rows

In [305]:
df_middle_glm

,id,X_age,X_bonus_malus_rating,X_distr_channel,X_vehicle_type,X_ttm_claims,X_policy_count,X_risk_code,X_vehicle_age,X_policy_tenure,X_policy_premium,X_prev_renewal_perc,X_upcoming_premium,X_cur_renewal_perc,year,is_churn,U
7,5,93.0,45.0,19,T4005040,0,1,0,24.0,24.0,175.7725,0.003637,197.41,0.098601,7,False,0.123099
16,85,78.0,45.0,19,T4003010,0,2,0,5.0,24.0,180.8686,0.003824,200.23,0.082852,7,False,0.107047
24,93,78.0,45.0,19,T4003020,0,1,0,21.0,24.0,165.6403,0.003731,181.69,0.072973,7,False,0.096895
32,119,49.0,45.0,19,T4003020,0,1,0,19.0,24.0,171.3347,-0.005503,187.99,0.073266,7,False,0.097209
118,395,49.0,45.0,11,T4003030,0,4,0,16.0,24.0,170.0981,-0.005223,187.45,0.077961,7,False,0.102011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3370174,5732129,68.0,45.0,16,T4003030,0,1,11,9.0,9.0,345.4078,-0.023380,367.06,0.042169,7,False,0.062686
3370323,5732370,81.0,45.0,16,T4003050,0,5,0,20.0,10.0,234.6113,-0.040569,255.09,0.066399,7,False,0.087288
3370329,5732373,58.0,45.0,16,T4005040,0,3,0,30.0,8.0,174.1869,-0.074677,189.35,0.061103,7,True,0.087051
3370407,5732452,89.0,45.0,16,T4003020,0,2,0,10.0,23.0,238.8796,-0.060040,259.78,0.064402,7,True,0.087493
3370452,5732508,54.0,45.0,4,T4003010,1,1,10,22.0,21.0,220.5798,-0.014601,239.83,0.066294,7,False,0.087271

In [306]:
df_middle_reg['U'] = (df_middle_reg['X_upcoming_premium'] - df_middle_reg['X_policy_premium']) / df_middle_reg['X_policy_premium']

In [307]:
from sklearn.preprocessing import LabelEncoder
for cat in cat_cols:
    le = LabelEncoder()
    le.fit(df_middle_glm[cat])
    df_middle_glm[cat] = le.transform(df_middle_glm[cat])
    df_middle_gam[cat] = le.transform(df_middle_gam[cat])
    df_middle_reg[cat] = le.transform(df_middle_reg[cat])

## Section 11 — GLM Churn Cross-Validation (Logistic Regression)

### `ModelGLM`
A **sklearn `Pipeline`** wrapping:
1. `ColumnTransformer` — median imputation + standard scaling for numerics; mode imputation + one-hot encoding for categoricals
2. `LogisticRegression` (solver: `lbfgs`, max_iter: 1000)

**Tuning:** Optuna over the regularisation parameter `C` (log-uniform in `[0.001, 100]`), maximising ROC-AUC.

### `cross_validate_glm_with_oof`
- 5-fold outer CV with an inner 80/20 tuning split per fold  
- Outputs OOF churn probabilities (`oof_prediction_glm`) and the fold assignment

**Why GLM?**  
Provides an interpretable, linear-in-log-odds alternative to XGBoost.  
Suitable when a regulator requires explainability of acceptance probability estimates.

In [308]:
from sklearn import metrics
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold, train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
import optuna
from optuna.trial import Trial


class ModelGLM():
    """
    GLM-like classifier implemented with sklearn LogisticRegression.
    This avoids statsmodels exog shape mismatches across folds.
    """

    def __init__(self):
        self.categorical_cols = []
        self.numeric_cols = []

    def _build_model(self, C: float) -> Pipeline:
        numeric_transformer = Pipeline(steps=[
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler()),
        ])

        categorical_transformer = Pipeline(steps=[
            ("imputer", SimpleImputer(strategy="most_frequent")),
            ("onehot", OneHotEncoder(handle_unknown="ignore")),
        ])

        preprocessor = ColumnTransformer(
            transformers=[
                ("num", numeric_transformer, self.numeric_cols),
                ("cat", categorical_transformer, self.categorical_cols),
            ],
            remainder="drop",
        )

        clf = LogisticRegression(
            C=C,
            max_iter=1000,
            solver="lbfgs",
            random_state=123,
        )

        model = Pipeline(steps=[
            ("preprocessor", preprocessor),
            ("classifier", clf),
        ])
        return model

    def objective(self, trial: Trial, X_train: pd.DataFrame, y_train: pd.Series,
                  X_val: pd.DataFrame, y_val: pd.Series) -> float:
        """Optuna objective for logistic regression."""
        C = trial.suggest_float("C", 1e-3, 100.0, log=True)

        # Infer schema from training fold only.
        self.categorical_cols = X_train.select_dtypes(include=["object", "category"]).columns.tolist()
        self.numeric_cols = [c for c in X_train.columns if c not in self.categorical_cols]

        try:
            model = self._build_model(C=C)
            model.fit(X_train, y_train)
            y_score = model.predict_proba(X_val)[:, 1]
            y_score = np.clip(y_score, 1e-10, 1 - 1e-10)
            roc_auc = metrics.roc_auc_score(y_true=y_val, y_score=y_score)
            return roc_auc
        except Exception as e:
            print(f"Error in LogisticRegression fitting: {e}")
            return 0.5

    def tuning(self, X_train: pd.DataFrame, y_train: pd.Series,
               X_val: pd.DataFrame, y_val: pd.Series, n_trials: int) -> dict:
        """Hyperparameter tuning using Optuna."""
        study = optuna.create_study(study_name="LogisticRegression", direction="maximize")
        study.optimize(
            lambda trial: self.objective(trial, X_train, y_train, X_val, y_val),
            n_trials=n_trials,
            show_progress_bar=True,
        )
        return study.best_params

    def train(self, X_train: pd.DataFrame, y_train: pd.Series,
              X_val: pd.DataFrame, y_val: pd.Series, best_params: dict):
        """Train final logistic regression with best parameters."""
        C = best_params.get("C", 1.0)
        self.categorical_cols = X_train.select_dtypes(include=["object", "category"]).columns.tolist()
        self.numeric_cols = [c for c in X_train.columns if c not in self.categorical_cols]

        model = self._build_model(C=C)
        model.fit(X_train, y_train)
        return model


def cross_validate_glm_with_oof(X, y, n_splits=5, n_trials=20):
    """
    Cross-validation with OOF predictions for Logistic Regression GLM.
    FeatureProcessor is fit on each training fold and applied to both train and val
    to prevent data leakage. U is kept untouched (not processed).
    """
    kfold = KFold(n_splits=n_splits, shuffle=True, random_state=123)

    fold_numbers = np.zeros(len(X))
    oof_predictions_proba = np.zeros(len(X))
    oof_predictions_class = np.zeros(len(X))

    fold_results = []
    best_params_per_fold = []

    # Identify columns to keep untouched (U)
    u_cols = [col for col in ["U"] if col in X.columns]
    x_feature_cols = [col for col in X.columns if col not in u_cols]

    for fold_idx, (train_idx, val_idx) in enumerate(kfold.split(X)):
        print(f"\n{'='*70}")
        print(f"Fold {fold_idx + 1}/{n_splits}")
        print(f"{'='*70}")

        fold_numbers[val_idx] = fold_idx + 1

        X_train_fold = X.iloc[train_idx].reset_index(drop=True)
        X_val_fold = X.iloc[val_idx].reset_index(drop=True)
        y_train_fold = y.iloc[train_idx].reset_index(drop=True)
        y_val_fold = y.iloc[val_idx].reset_index(drop=True)

        # --- Separate U from other features ---
        if u_cols:
            U_train = X_train_fold[u_cols].copy()
            U_val = X_val_fold[u_cols].copy()
            X_train_raw = X_train_fold[x_feature_cols].copy()
            X_val_raw = X_val_fold[x_feature_cols].copy()
        else:
            X_train_raw = X_train_fold.copy()
            X_val_raw = X_val_fold.copy()

        # --- Fit preprocessor on train fold only (no leakage) ---
        fp = FeatureProcessor()
        X_train_proc = fp.fit_transform(X_train_raw)
        X_val_proc = fp.transform(X_val_raw)

        # --- Concatenate U back with processed features ---
        if u_cols:
            X_train_proc = pd.concat([U_train.reset_index(drop=True), X_train_proc.reset_index(drop=True)], axis=1)
            X_val_proc = pd.concat([U_val.reset_index(drop=True), X_val_proc.reset_index(drop=True)], axis=1)

        # Split for tuning
        X_train_tune, X_val_tune, y_train_tune, y_val_tune = train_test_split(
            X_train_proc, y_train_fold, test_size=0.2, random_state=123, stratify=y_train_fold
        )

        # Tune
        model_glm = ModelGLM()
        best_params = model_glm.tuning(
            X_train_tune, y_train_tune,
            X_val_tune, y_val_tune,
            n_trials=n_trials,
        )

        print(f"Best params: {best_params}")
        best_params_per_fold.append(best_params)

        # Train
        final_model = model_glm.train(
            X_train_proc, y_train_fold,
            X_val_proc, y_val_fold,
            best_params,
        )

        # Predict
        y_pred_proba = final_model.predict_proba(X_val_proc)[:, 1]
        y_pred_proba = np.clip(y_pred_proba, 0, 1)
        y_pred_class = (y_pred_proba > 0.5).astype(int)

        oof_predictions_proba[val_idx] = y_pred_proba
        oof_predictions_class[val_idx] = y_pred_class

        # Metrics
        roc_auc = metrics.roc_auc_score(y_val_fold, y_pred_proba)
        accuracy = metrics.accuracy_score(y_val_fold, y_pred_class)

        fold_results.append({
            "fold": fold_idx + 1,
            "roc_auc": roc_auc,
            "accuracy": accuracy,
            "n_train": len(train_idx),
            "n_val": len(val_idx),
        })

        print(f"Fold {fold_idx + 1} ROC-AUC: {roc_auc:.4f}")
        print(f"Fold {fold_idx + 1} Accuracy: {accuracy:.4f}")

    results_df = pd.DataFrame(fold_results)

    print(f"\n{'='*70}")
    print("Cross-Validation Summary")
    print(f"{'='*70}")
    print(f"Mean ROC-AUC: {results_df['roc_auc'].mean():.4f} (+/- {results_df['roc_auc'].std():.4f})")
    print(f"Mean Accuracy: {results_df['accuracy'].mean():.4f} (+/- {results_df['accuracy'].std():.4f})")

    overall_roc_auc = metrics.roc_auc_score(y, oof_predictions_proba)
    print(f"\nOverall OOF ROC-AUC: {overall_roc_auc:.4f}")

    return fold_numbers, oof_predictions_proba, results_df, best_params_per_fold


# Usage
X = df_middle_glm.loc[:, model_features_class]
y = df_middle_glm['is_churn']

fold_numbers_glm, oof_pred_glm, results_glm, params_glm = cross_validate_glm_with_oof(
    X, y, n_splits=5, n_trials=20
)

df_middle_glm['fold_number_glm'] = fold_numbers_glm.astype(int)
df_middle_glm['oof_prediction_glm'] = oof_pred_glm

======================================================================
Fold 1/5
======================================================================

[I 2026-04-07 20:35:11,630] A new study created in memory with name: LogisticRegression

  0%|          | 0/20 [00:00<?, ?it/s]

[I 2026-04-07 20:35:12,100] Trial 0 finished with value: 0.651126863475761 and parameters: {'C': 2.0215005819761416}. Best is trial 0 with value: 0.651126863475761.
[I 2026-04-07 20:35:12,463] Trial 1 finished with value: 0.6511312227057081 and parameters: {'C': 0.060295279198897773}. Best is trial 1 with value: 0.6511312227057081.
[I 2026-04-07 20:35:12,836] Trial 2 finished with value: 0.6511304218239272 and parameters: {'C': 0.0796522825530112}. Best is trial 1 with value: 0.6511312227057081.
[I 2026-04-07 20:35:13,219] Trial 3 finished with value: 0.6511912989770255 and parameters: {'C': 0.003636189860693768}. Best is trial 3 with value: 0.6511912989770255.
[I 2026-04-07 20:35:13,668] Trial 4 finished with value: 0.651130411686183 and parameters: {'C': 0.08001387052396138}. Best is trial 3 with value: 0.6511912989770255.
[I 2026-04-07 20:35:14,043] Trial 5 finished with value: 0.6511268736135051 and parameters: {'C': 3.293768263682318}. Best is trial 3 with value: 0.6511912989770255.
[I 2026-04-07 20:35:14,394] Trial 6 finished with value: 0.6511281205560248 and parameters: {'C': 0.16534049089167774}. Best is trial 3 with value: 0.6511912989770255.
[I 2026-04-07 20:35:14,778] Trial 7 finished with value: 0.6511332603922647 and parameters: {'C': 0.04028157786445827}. Best is trial 3 with value: 0.6511912989770255.
[I 2026-04-07 20:35:15,108] Trial 8 finished with value: 0.6511267114096001 and parameters: {'C': 4.4718503269693555}. Best is trial 3 with value: 0.6511912989770255.
[I 2026-04-07 20:35:15,441] Trial 9 finished with value: 0.6511269344399695 and parameters: {'C': 2.229432941511532}. Best is trial 3 with value: 0.6511912989770255.
[I 2026-04-07 20:35:15,773] Trial 10 finished with value: 0.6512983636920752 and parameters: {'C': 0.0012408563649002474}. Best is trial 10 with value: 0.6512983636920752.
[I 2026-04-07 20:35:16,120] Trial 11 finished with value: 0.6512282916051115 and parameters: {'C': 0.002475679669705629}. Best is trial 10 with value: 0.6512983636920752.
[I 2026-04-07 20:35:16,486] Trial 12 finished with value: 0.6513306422691718 and parameters: {'C': 0.0010247326224620665}. Best is trial 12 with value: 0.6513306422691718.
[I 2026-04-07 20:35:16,849] Trial 13 finished with value: 0.6511266201699034 and parameters: {'C': 77.29324747714794}. Best is trial 12 with value: 0.6513306422691718.
[I 2026-04-07 20:35:17,167] Trial 14 finished with value: 0.6512890673807694 and parameters: {'C': 0.001322095589795079}. Best is trial 12 with value: 0.6513306422691718.
[I 2026-04-07 20:35:17,574] Trial 15 finished with value: 0.6511562629335438 and parameters: {'C': 0.00839136699659204}. Best is trial 12 with value: 0.6513306422691718.
[I 2026-04-07 20:35:17,924] Trial 16 finished with value: 0.6511614129075278 and parameters: {'C': 0.007507998210860132}. Best is trial 12 with value: 0.6513306422691718.
[I 2026-04-07 20:35:18,356] Trial 17 finished with value: 0.6513292939492115 and parameters: {'C': 0.0010301746230176408}. Best is trial 12 with value: 0.6513306422691718.
[I 2026-04-07 20:35:18,687] Trial 18 finished with value: 0.6511415226536762 and parameters: {'C': 0.017403135835452124}. Best is trial 12 with value: 0.6513306422691718.
[I 2026-04-07 20:35:18,999] Trial 19 finished with value: 0.6511278265614471 and parameters: {'C': 0.6801973592710847}. Best is trial 12 with value: 0.6513306422691718.
Best params: {'C': 0.0010247326224620665}

[I 2026-04-07 20:35:19,539] A new study created in memory with name: LogisticRegression

Fold 1 ROC-AUC: 0.6447
Fold 1 Accuracy: 0.8853

======================================================================
Fold 2/5
======================================================================

  0%|          | 0/20 [00:00<?, ?it/s]

[I 2026-04-07 20:35:19,866] Trial 0 finished with value: 0.6413997961931195 and parameters: {'C': 0.013137071796130075}. Best is trial 0 with value: 0.6413997961931195.
[I 2026-04-07 20:35:20,171] Trial 1 finished with value: 0.6413844588095824 and parameters: {'C': 0.04708933981353743}. Best is trial 0 with value: 0.6413997961931195.
[I 2026-04-07 20:35:20,491] Trial 2 finished with value: 0.6415253115048934 and parameters: {'C': 0.0015810775558902394}. Best is trial 2 with value: 0.6415253115048934.
[I 2026-04-07 20:35:20,798] Trial 3 finished with value: 0.6413814804801505 and parameters: {'C': 0.09113457476433041}. Best is trial 2 with value: 0.6415253115048934.
[I 2026-04-07 20:35:21,101] Trial 4 finished with value: 0.6414905541978155 and parameters: {'C': 0.0022439267323539824}. Best is trial 2 with value: 0.6415253115048934.
[I 2026-04-07 20:35:21,418] Trial 5 finished with value: 0.6415192636726796 and parameters: {'C': 0.001701648362047079}. Best is trial 2 with value: 0.6415253115048934.
[I 2026-04-07 20:35:21,740] Trial 6 finished with value: 0.6413785426722074 and parameters: {'C': 12.356134151783365}. Best is trial 2 with value: 0.6415253115048934.
[I 2026-04-07 20:35:22,051] Trial 7 finished with value: 0.6414594438247359 and parameters: {'C': 0.0032211716198391814}. Best is trial 2 with value: 0.6415253115048934.
[I 2026-04-07 20:35:22,349] Trial 8 finished with value: 0.6413785426722074 and parameters: {'C': 9.541178797695789}. Best is trial 2 with value: 0.6415253115048934.
[I 2026-04-07 20:35:22,676] Trial 9 finished with value: 0.6414786915319489 and parameters: {'C': 0.0025614731175498035}. Best is trial 2 with value: 0.6415253115048934.
[I 2026-04-07 20:35:23,011] Trial 10 finished with value: 0.641379079581935 and parameters: {'C': 1.06253309085869}. Best is trial 2 with value: 0.6415253115048934.
[I 2026-04-07 20:35:23,302] Trial 11 finished with value: 0.6415589747317719 and parameters: {'C': 0.0011660669686442762}. Best is trial 11 with value: 0.6415589747317719.
[I 2026-04-07 20:35:23,627] Trial 12 finished with value: 0.6413794442753348 and parameters: {'C': 0.5520475671074466}. Best is trial 11 with value: 0.6415589747317719.
[I 2026-04-07 20:35:23,940] Trial 13 finished with value: 0.6413967368207099 and parameters: {'C': 0.016114251823968802}. Best is trial 11 with value: 0.6415589747317719.
[I 2026-04-07 20:35:24,252] Trial 14 finished with value: 0.6413979423350038 and parameters: {'C': 0.01403506325309301}. Best is trial 11 with value: 0.6415589747317719.
[I 2026-04-07 20:35:24,558] Trial 15 finished with value: 0.6413807713540952 and parameters: {'C': 0.1332092873968519}. Best is trial 11 with value: 0.6415589747317719.
[I 2026-04-07 20:35:24,894] Trial 16 finished with value: 0.6413784818899742 and parameters: {'C': 66.52693967536294}. Best is trial 11 with value: 0.6415589747317719.
[I 2026-04-07 20:35:25,216] Trial 17 finished with value: 0.6414177573430611 and parameters: {'C': 0.007108182211319817}. Best is trial 11 with value: 0.6415589747317719.
[I 2026-04-07 20:35:25,517] Trial 18 finished with value: 0.6413845702436767 and parameters: {'C': 0.03965520272072232}. Best is trial 11 with value: 0.6415589747317719.
[I 2026-04-07 20:35:25,799] Trial 19 finished with value: 0.6415673525495958 and parameters: {'C': 0.001115087929092591}. Best is trial 19 with value: 0.6415673525495958.
Best params: {'C': 0.001115087929092591}

[I 2026-04-07 20:35:26,304] A new study created in memory with name: LogisticRegression

Fold 2 ROC-AUC: 0.6474
Fold 2 Accuracy: 0.8856

======================================================================
Fold 3/5
======================================================================

  0%|          | 0/20 [00:00<?, ?it/s]

[I 2026-04-07 20:35:26,707] Trial 0 finished with value: 0.6477599749276913 and parameters: {'C': 0.00936968582116389}. Best is trial 0 with value: 0.6477599749276913.
[I 2026-04-07 20:35:27,081] Trial 1 finished with value: 0.6477233410767357 and parameters: {'C': 0.23345336824360366}. Best is trial 0 with value: 0.6477599749276913.
[I 2026-04-07 20:35:27,430] Trial 2 finished with value: 0.647721804981468 and parameters: {'C': 1.0164114331379326}. Best is trial 0 with value: 0.6477599749276913.
[I 2026-04-07 20:35:27,740] Trial 3 finished with value: 0.64772156244011 and parameters: {'C': 93.78111091059205}. Best is trial 0 with value: 0.6477599749276913.
[I 2026-04-07 20:35:28,040] Trial 4 finished with value: 0.6477215826518897 and parameters: {'C': 4.977545436746212}. Best is trial 0 with value: 0.6477599749276913.
[I 2026-04-07 20:35:28,332] Trial 5 finished with value: 0.6480493368737364 and parameters: {'C': 0.0010219075516589083}. Best is trial 5 with value: 0.6480493368737364.
[I 2026-04-07 20:35:28,649] Trial 6 finished with value: 0.6479448318660861 and parameters: {'C': 0.0016372900355910423}. Best is trial 5 with value: 0.6480493368737364.
[I 2026-04-07 20:35:29,015] Trial 7 finished with value: 0.6477215826518898 and parameters: {'C': 99.495584674998}. Best is trial 5 with value: 0.6480493368737364.
[I 2026-04-07 20:35:29,300] Trial 8 finished with value: 0.6477218959344773 and parameters: {'C': 1.2419844404047584}. Best is trial 5 with value: 0.6480493368737364.
[I 2026-04-07 20:35:29,605] Trial 9 finished with value: 0.6477215826518898 and parameters: {'C': 7.186048289629159}. Best is trial 5 with value: 0.6480493368737364.
[I 2026-04-07 20:35:29,876] Trial 10 finished with value: 0.6477358016390056 and parameters: {'C': 0.02368262394793302}. Best is trial 5 with value: 0.6480493368737364.
[I 2026-04-07 20:35:30,151] Trial 11 finished with value: 0.6480175235322722 and parameters: {'C': 0.001139294674320268}. Best is trial 5 with value: 0.6480493368737364.
[I 2026-04-07 20:35:30,420] Trial 12 finished with value: 0.6480335413677933 and parameters: {'C': 0.0010749217138605984}. Best is trial 5 with value: 0.6480493368737364.
[I 2026-04-07 20:35:30,701] Trial 13 finished with value: 0.6477405716190472 and parameters: {'C': 0.017814998136580842}. Best is trial 5 with value: 0.6480493368737364.
[I 2026-04-07 20:35:30,965] Trial 14 finished with value: 0.6477735168201826 and parameters: {'C': 0.0070867400861698}. Best is trial 5 with value: 0.6480493368737364.
[I 2026-04-07 20:35:31,224] Trial 15 finished with value: 0.6477285759277136 and parameters: {'C': 0.05073358782450314}. Best is trial 5 with value: 0.6480493368737364.
[I 2026-04-07 20:35:31,499] Trial 16 finished with value: 0.6478761118146382 and parameters: {'C': 0.0024417597834092085}. Best is trial 5 with value: 0.6480493368737364.
[I 2026-04-07 20:35:31,771] Trial 17 finished with value: 0.6477233208649558 and parameters: {'C': 0.1995114702509123}. Best is trial 5 with value: 0.6480493368737364.
[I 2026-04-07 20:35:32,036] Trial 18 finished with value: 0.6477257159608667 and parameters: {'C': 0.08597268518008268}. Best is trial 5 with value: 0.6480493368737364.
[I 2026-04-07 20:35:32,313] Trial 19 finished with value: 0.6478035009955716 and parameters: {'C': 0.004549238730199178}. Best is trial 5 with value: 0.6480493368737364.
Best params: {'C': 0.0010219075516589083}

[I 2026-04-07 20:35:32,807] A new study created in memory with name: LogisticRegression

Fold 3 ROC-AUC: 0.6359
Fold 3 Accuracy: 0.8869

======================================================================
Fold 4/5
======================================================================

  0%|          | 0/20 [00:00<?, ?it/s]

[I 2026-04-07 20:35:33,084] Trial 0 finished with value: 0.6437396783462526 and parameters: {'C': 71.16287606669546}. Best is trial 0 with value: 0.6437396783462526.
[I 2026-04-07 20:35:33,354] Trial 1 finished with value: 0.6438024425263343 and parameters: {'C': 0.0036813378496365684}. Best is trial 1 with value: 0.6438024425263343.
[I 2026-04-07 20:35:33,617] Trial 2 finished with value: 0.6437397499015067 and parameters: {'C': 3.3075357188290586}. Best is trial 1 with value: 0.6438024425263343.
[I 2026-04-07 20:35:33,874] Trial 3 finished with value: 0.6437419578922067 and parameters: {'C': 0.10232580719289011}. Best is trial 1 with value: 0.6438024425263343.
[I 2026-04-07 20:35:34,137] Trial 4 finished with value: 0.6437654177933936 and parameters: {'C': 0.009685360750226385}. Best is trial 1 with value: 0.6438024425263343.
[I 2026-04-07 20:35:34,406] Trial 5 finished with value: 0.6437506365223189 and parameters: {'C': 0.02585223288638243}. Best is trial 1 with value: 0.6438024425263343.
[I 2026-04-07 20:35:34,675] Trial 6 finished with value: 0.6437396681240733 and parameters: {'C': 11.9457100566156}. Best is trial 1 with value: 0.6438024425263343.
[I 2026-04-07 20:35:35,011] Trial 7 finished with value: 0.6437397090127901 and parameters: {'C': 18.591792970511438}. Best is trial 1 with value: 0.6438024425263343.
[I 2026-04-07 20:35:35,345] Trial 8 finished with value: 0.6437396885684318 and parameters: {'C': 94.53658903629018}. Best is trial 1 with value: 0.6438024425263343.
[I 2026-04-07 20:35:35,612] Trial 9 finished with value: 0.6437397499015067 and parameters: {'C': 23.612287133135258}. Best is trial 1 with value: 0.6438024425263343.
[I 2026-04-07 20:35:35,879] Trial 10 finished with value: 0.643907649194315 and parameters: {'C': 0.0011794892293735411}. Best is trial 10 with value: 0.643907649194315.
[I 2026-04-07 20:35:36,167] Trial 11 finished with value: 0.6439059012016773 and parameters: {'C': 0.0013387633521462286}. Best is trial 10 with value: 0.643907649194315.
[I 2026-04-07 20:35:36,489] Trial 12 finished with value: 0.6439162460469939 and parameters: {'C': 0.0011238859087438883}. Best is trial 12 with value: 0.6439162460469939.
[I 2026-04-07 20:35:36,782] Trial 13 finished with value: 0.6439294531024768 and parameters: {'C': 0.0010269279418107771}. Best is trial 13 with value: 0.6439294531024768.
[I 2026-04-07 20:35:37,074] Trial 14 finished with value: 0.6437399645672692 and parameters: {'C': 0.6784962715258057}. Best is trial 13 with value: 0.6439294531024768.
[I 2026-04-07 20:35:37,364] Trial 15 finished with value: 0.6437509329655148 and parameters: {'C': 0.025398582554766628}. Best is trial 13 with value: 0.6439294531024768.
[I 2026-04-07 20:35:37,644] Trial 16 finished with value: 0.6437405778980193 and parameters: {'C': 0.1701046274622151}. Best is trial 13 with value: 0.6439294531024768.
[I 2026-04-07 20:35:37,960] Trial 17 finished with value: 0.6437834497174431 and parameters: {'C': 0.005635371632288408}. Best is trial 13 with value: 0.6439294531024768.
[I 2026-04-07 20:35:38,269] Trial 18 finished with value: 0.6437468543160274 and parameters: {'C': 0.03695903617656658}. Best is trial 13 with value: 0.6439294531024768.
[I 2026-04-07 20:35:38,541] Trial 19 finished with value: 0.6437399032341942 and parameters: {'C': 0.8668963341148945}. Best is trial 13 with value: 0.6439294531024768.
Best params: {'C': 0.0010269279418107771}

[I 2026-04-07 20:35:39,014] A new study created in memory with name: LogisticRegression

Fold 4 ROC-AUC: 0.6394
Fold 4 Accuracy: 0.8809

======================================================================
Fold 5/5
======================================================================

  0%|          | 0/20 [00:00<?, ?it/s]

[I 2026-04-07 20:35:39,286] Trial 0 finished with value: 0.6459718692560501 and parameters: {'C': 3.7216439749167174}. Best is trial 0 with value: 0.6459718692560501.
[I 2026-04-07 20:35:39,551] Trial 1 finished with value: 0.645971362122769 and parameters: {'C': 0.5541071355718894}. Best is trial 0 with value: 0.6459718692560501.
[I 2026-04-07 20:35:39,815] Trial 2 finished with value: 0.645971788114725 and parameters: {'C': 1.7645874222233446}. Best is trial 0 with value: 0.6459718692560501.
[I 2026-04-07 20:35:40,096] Trial 3 finished with value: 0.6459718591133843 and parameters: {'C': 0.050907844907920115}. Best is trial 0 with value: 0.6459718692560501.
[I 2026-04-07 20:35:40,362] Trial 4 finished with value: 0.6459718286853875 and parameters: {'C': 11.304211013820058}. Best is trial 0 with value: 0.6459718692560501.
[I 2026-04-07 20:35:40,624] Trial 5 finished with value: 0.6459732486585741 and parameters: {'C': 0.0010025121848850898}. Best is trial 5 with value: 0.6459732486585741.
[I 2026-04-07 20:35:40,940] Trial 6 finished with value: 0.6459714229787628 and parameters: {'C': 0.3900070889741104}. Best is trial 5 with value: 0.6459732486585741.
[I 2026-04-07 20:35:41,204] Trial 7 finished with value: 0.6459713418374378 and parameters: {'C': 0.08442334999833002}. Best is trial 5 with value: 0.6459732486585741.
[I 2026-04-07 20:35:41,504] Trial 8 finished with value: 0.6459716156894095 and parameters: {'C': 0.6590801571199988}. Best is trial 5 with value: 0.6459732486585741.
[I 2026-04-07 20:35:41,771] Trial 9 finished with value: 0.6459762610302631 and parameters: {'C': 0.009326584561867404}. Best is trial 9 with value: 0.6459762610302631.
[I 2026-04-07 20:35:42,034] Trial 10 finished with value: 0.6459790908339706 and parameters: {'C': 0.0026531388290301264}. Best is trial 10 with value: 0.6459790908339706.
[I 2026-04-07 20:35:42,301] Trial 11 finished with value: 0.6459795472539235 and parameters: {'C': 0.0029085771580508457}. Best is trial 11 with value: 0.6459795472539235.
[I 2026-04-07 20:35:42,570] Trial 12 finished with value: 0.6459823364869688 and parameters: {'C': 0.001911905530998081}. Best is trial 12 with value: 0.6459823364869688.
[I 2026-04-07 20:35:42,846] Trial 13 finished with value: 0.6459718185427218 and parameters: {'C': 96.42754673419509}. Best is trial 12 with value: 0.6459823364869688.
[I 2026-04-07 20:35:43,114] Trial 14 finished with value: 0.6459734920825491 and parameters: {'C': 0.012918215758705383}. Best is trial 12 with value: 0.6459823364869688.
[I 2026-04-07 20:35:43,379] Trial 15 finished with value: 0.6459795573965892 and parameters: {'C': 0.0059126642203763385}. Best is trial 12 with value: 0.6459823364869688.
[I 2026-04-07 20:35:43,644] Trial 16 finished with value: 0.6459723256760028 and parameters: {'C': 0.04820874411389009}. Best is trial 12 with value: 0.6459823364869688.
[I 2026-04-07 20:35:43,909] Trial 17 finished with value: 0.6459760784622818 and parameters: {'C': 0.009033186838227836}. Best is trial 12 with value: 0.6459823364869688.
[I 2026-04-07 20:35:44,173] Trial 18 finished with value: 0.645975571329001 and parameters: {'C': 0.0011610614200419592}. Best is trial 12 with value: 0.6459823364869688.
[I 2026-04-07 20:35:44,442] Trial 19 finished with value: 0.645972670526634 and parameters: {'C': 0.019009189664687124}. Best is trial 12 with value: 0.6459823364869688.
Best params: {'C': 0.001911905530998081}
Fold 5 ROC-AUC: 0.6512
Fold 5 Accuracy: 0.8850

======================================================================
Cross-Validation Summary
======================================================================
Mean ROC-AUC: 0.6437 (+/- 0.0061)
Mean Accuracy: 0.8847 (+/- 0.0023)

Overall OOF ROC-AUC: 0.6437

In [309]:
df_middle_glm.head()

,id,X_age,X_bonus_malus_rating,X_distr_channel,X_vehicle_type,X_ttm_claims,X_policy_count,X_risk_code,X_vehicle_age,X_policy_tenure,X_policy_premium,X_prev_renewal_perc,X_upcoming_premium,X_cur_renewal_perc,year,is_churn,U,fold_number_glm,oof_prediction_glm
7,5,93.0,45.0,5,7,0,1,0,24.0,24.0,175.7725,0.003637,197.41,0.098601,7,False,0.123099,5,0.134916
16,85,78.0,45.0,5,0,0,2,0,5.0,24.0,180.8686,0.003824,200.23,0.082852,7,False,0.107047,4,0.049394
24,93,78.0,45.0,5,1,0,1,0,21.0,24.0,165.6403,0.003731,181.69,0.072973,7,False,0.096895,1,0.089371
32,119,49.0,45.0,5,1,0,1,0,19.0,24.0,171.3347,-0.005503,187.99,0.073266,7,False,0.097209,5,0.100781
118,395,49.0,45.0,2,2,0,4,0,16.0,24.0,170.0981,-0.005223,187.45,0.077961,7,False,0.102011,5,0.067738

## Section 12 — GLM Output: Acceptance Probability

Post-CV steps for `df_middle_glm`:

1. Compute `Z = 1 − is_churn` (binary acceptance)  
2. Compute `prob_acceptance = 1 − oof_prediction_glm`  
3. Adjust `U = 1 + U` (uplift factor format)  
4. Rename columns to canonical business names  

**Exported to:** `df_acceptance_linear_model_black_box.csv`

This file mirrors the XGBoost acceptance output but with GLM-derived acceptance probabilities, allowing the optimisation module to compare model choices.

In [310]:
df_middle_glm['Z'] = 1 - df_middle_glm['is_churn'].astype(int)
df_middle_glm['prob_acceptance'] = 1 - df_middle_glm['oof_prediction_glm']

In [311]:
df_middle_glm['U+1'] = 1 + df_middle_glm['U']

In [312]:
df_middle_glm.columns = ['id','X_age','X_bonus_malus_rating','X_distr_channel','X_vehicle_type','X_ttm_claims','X_policy_count','X_risk_code','X_vehicle_age','X_policy_tenure',
                         'X_policy_premium','X_prev_renewal_perc','X_upcoming_premium','X_cur_renewal_perc','X_year','1-Z','U','fold_number_glm','churn_prediction','Z','prob_acceptance','U+1']

In [313]:
df_middle_glm.columns

Index(['id', 'X_age', 'X_bonus_malus_rating', 'X_distr_channel',
       'X_vehicle_type', 'X_ttm_claims', 'X_policy_count', 'X_risk_code',
       'X_vehicle_age', 'X_policy_tenure', 'X_policy_premium',
       'X_prev_renewal_perc', 'X_upcoming_premium', 'X_cur_renewal_perc',
       'X_year', '1-Z', 'U', 'fold_number_glm', 'churn_prediction', 'Z',
       'prob_acceptance', 'U+1'],
      dtype='str')

In [314]:
df_middle_glm.to_csv('df_acceptance_linear_model_black_box_feat_processor.csv',sep=';')

In [315]:
df_middle_gam.columns

Index(['id', 'X_age', 'X_bonus_malus_rating', 'X_distr_channel',
       'X_vehicle_type', 'X_ttm_claims', 'X_policy_count', 'X_risk_code',
       'X_vehicle_age', 'X_policy_tenure', 'X_policy_premium',
       'X_prev_renewal_perc', 'X_upcoming_premium', 'X_cur_renewal_perc',
       'year', 'is_churn', 'U'],
      dtype='str')

## Section 13 — GAM Churn Cross-Validation (LogisticGAM)

### `ModelGAM` (memory-safe version)
A **pyGAM `LogisticGAM`** that uses:
- **Spline terms** (`s()`) for continuous features — captures non-linear relationships
- **Factor terms** (`f()`) for categorical features — discrete category effects

Key design decisions:
- `_prepare_data` — category mappings are fitted on training data only (prevents leakage)
- Progressively tries `n_splines = [8, 6, 4]` if fitting fails due to memory pressure
- `max_train_samples = 35,000` — stratified subsampling is applied to avoid OOM on large folds

### `cross_validate_gam_with_oof`
- 5-fold outer CV (no inner Optuna tuning; `n_splines` and `lam` are fixed hyperparameters)
- `_stratified_sample` ensures class balance is preserved after subsampling

**Why GAM?**  
GAMs are semi-parametric: they capture non-linear covariate effects while remaining interpretable via partial dependence plots, making them a strong regulatory-friendly alternative.

In [316]:
from sklearn import metrics
import pandas as pd
import numpy as np
from pygam import LogisticGAM, s, f
from sklearn.model_selection import KFold


class ModelGAM:
    """Memory-safe GAM classifier for churn prediction."""

    def __init__(self):
        self.numeric_cols = []
        self.categorical_cols = []
        self.feature_order = []
        self.category_maps = {}
        self.category_default_code = {}

    def _prepare_data(self, X: pd.DataFrame, fit: bool = False) -> pd.DataFrame:
        """Prepare data for GAM using stable category mappings and fixed column order."""
        X_prep = X.copy()

        if fit:
            self.numeric_cols = X_prep.select_dtypes(include=[np.number]).columns.tolist()
            self.categorical_cols = X_prep.select_dtypes(include=["object", "category"]).columns.tolist()
            self.feature_order = self.numeric_cols + self.categorical_cols

            self.category_maps = {}
            self.category_default_code = {}
            for col in self.categorical_cols:
                cats = sorted(X_prep[col].astype(str).dropna().unique().tolist())
                mapping = {cat: idx for idx, cat in enumerate(cats)}
                self.category_maps[col] = mapping
                self.category_default_code[col] = len(mapping)

        for col in self.categorical_cols:
            mapping = self.category_maps[col]
            default_code = self.category_default_code[col]
            X_prep[col] = X_prep[col].astype(str).map(lambda x: mapping.get(x, default_code))

        if len(self.numeric_cols) > 0:
            X_prep[self.numeric_cols] = X_prep[self.numeric_cols].apply(
                lambda s_col: s_col.fillna(s_col.median())
            )

        X_prep = X_prep[self.feature_order]
        return X_prep

    def _build_formula(self, n_features: int, n_numeric: int, n_splines: int = 8, lam: float = 0.8):
        if n_features == 0:
            raise ValueError("No features found for GAM model.")

        terms = None

        for i in range(n_numeric):
            term = s(i, n_splines=n_splines, lam=lam)
            terms = term if terms is None else terms + term

        for i in range(n_numeric, n_features):
            term = f(i, lam=lam)
            terms = term if terms is None else terms + term

        return terms

    def train(
        self,
        X_train: pd.DataFrame,
        y_train: pd.Series,
        X_val: pd.DataFrame,
        y_val: pd.Series,
        n_splines: int = 8,
        lam: float = 0.8,
    ):
        X_train_prep = self._prepare_data(X_train, fit=True)
        _ = self._prepare_data(X_val, fit=False)

        n_features = X_train_prep.shape[1]
        n_numeric = len(self.numeric_cols)

        # Try progressively simpler models if memory pressure occurs.
        candidate_splines = [n_splines, min(6, n_splines), 4]

        last_error = None
        for spl in candidate_splines:
            try:
                terms = self._build_formula(n_features, n_numeric, n_splines=spl, lam=lam)
                gam = LogisticGAM(terms=terms, max_iter=100)
                gam.fit(X_train_prep.values.astype(np.float32), y_train.values)
                return gam
            except Exception as e:
                last_error = e
                print(f"GAM fit failed with n_splines={spl}: {e}")

        raise RuntimeError(f"All GAM fits failed. Last error: {last_error}")


def _stratified_sample(X: pd.DataFrame, y: pd.Series, max_samples: int, seed: int):
    """Return stratified sample indices for memory-safe GAM fitting."""
    if len(X) <= max_samples:
        return X.reset_index(drop=True), y.reset_index(drop=True)

    rng = np.random.default_rng(seed)
    y_arr = y.values

    pos_idx = np.where(y_arr == 1)[0]
    neg_idx = np.where(y_arr == 0)[0]

    pos_ratio = len(pos_idx) / len(y_arr)
    n_pos = int(max_samples * pos_ratio)
    n_neg = max_samples - n_pos

    n_pos = min(n_pos, len(pos_idx))
    n_neg = min(n_neg, len(neg_idx))

    sampled_pos = rng.choice(pos_idx, size=n_pos, replace=False) if n_pos > 0 else np.array([], dtype=int)
    sampled_neg = rng.choice(neg_idx, size=n_neg, replace=False) if n_neg > 0 else np.array([], dtype=int)

    sample_idx = np.concatenate([sampled_pos, sampled_neg])
    rng.shuffle(sample_idx)

    return X.iloc[sample_idx].reset_index(drop=True), y.iloc[sample_idx].reset_index(drop=True)


def cross_validate_gam_with_oof(
    X,
    y,
    n_splits=5,
    n_splines=8,
    lam=0.8,
    max_train_samples=35000,
):
    """Cross-validation for GAM with OOF predictions and RAM-safe training."""
    kfold = KFold(n_splits=n_splits, shuffle=True, random_state=123)

    fold_numbers = np.zeros(len(X))
    oof_predictions_proba = np.zeros(len(X))
    oof_predictions_class = np.zeros(len(X))

    fold_results = []

    for fold_idx, (train_idx, val_idx) in enumerate(kfold.split(X)):
        print(f"\n{'=' * 70}")
        print(f"Fold {fold_idx + 1}/{n_splits}")
        print(f"{'=' * 70}")

        fold_numbers[val_idx] = fold_idx + 1

        X_train_fold = X.iloc[train_idx].reset_index(drop=True)
        X_val_fold = X.iloc[val_idx].reset_index(drop=True)
        y_train_fold = y.iloc[train_idx].reset_index(drop=True)
        y_val_fold = y.iloc[val_idx].reset_index(drop=True)

        X_train_fit, y_train_fit = _stratified_sample(
            X_train_fold,
            y_train_fold,
            max_samples=max_train_samples,
            seed=123 + fold_idx,
        )

        print(f"Training rows used: {len(X_train_fit):,} / {len(X_train_fold):,}")

        model_gam = ModelGAM()
        try:
            gam_model = model_gam.train(
                X_train_fit,
                y_train_fit,
                X_val_fold,
                y_val_fold,
                n_splines=n_splines,
                lam=lam,
            )

            X_val_prep = model_gam._prepare_data(X_val_fold, fit=False)
            y_pred_proba = gam_model.predict_proba(X_val_prep.values.astype(np.float32))
            y_pred_class = (y_pred_proba > 0.5).astype(int)

            oof_predictions_proba[val_idx] = y_pred_proba
            oof_predictions_class[val_idx] = y_pred_class

            roc_auc = metrics.roc_auc_score(y_val_fold, y_pred_proba)
            accuracy = metrics.accuracy_score(y_val_fold, y_pred_class)

            fold_results.append(
                {
                    "fold": fold_idx + 1,
                    "roc_auc": roc_auc,
                    "accuracy": accuracy,
                    "n_train_used": len(X_train_fit),
                    "n_train_full": len(train_idx),
                    "n_val": len(val_idx),
                }
            )

            print(f"Fold {fold_idx + 1} ROC-AUC: {roc_auc:.4f}")
            print(f"Fold {fold_idx + 1} Accuracy: {accuracy:.4f}")

        except Exception as e:
            print(f"Error in fold {fold_idx + 1}: {e}")
            oof_predictions_proba[val_idx] = 0.5
            oof_predictions_class[val_idx] = 0

    results_df = pd.DataFrame(fold_results)

    print(f"\n{'=' * 70}")
    print("Cross-Validation Summary")
    print(f"{'=' * 70}")
    if len(results_df) > 0:
        print(
            f"Mean ROC-AUC: {results_df['roc_auc'].mean():.4f} "
            f"(+/- {results_df['roc_auc'].std():.4f})"
        )
        print(
            f"Mean Accuracy: {results_df['accuracy'].mean():.4f} "
            f"(+/- {results_df['accuracy'].std():.4f})"
        )

        overall_roc_auc = metrics.roc_auc_score(y, oof_predictions_proba)
        print(f"\nOverall OOF ROC-AUC: {overall_roc_auc:.4f}")

    return fold_numbers, oof_predictions_proba, results_df


# Usage with your data
X = df_middle_gam.loc[:, model_features_class]
y = df_middle_gam["is_churn"]

print("Running GAM Cross-Validation...")
fold_numbers_gam, oof_pred_gam, results_gam = cross_validate_gam_with_oof(
    X,
    y,
    n_splits=5,
    n_splines=8,
    lam=0.8,
    max_train_samples=35000,
)

df_middle_gam["fold_number_gam"] = fold_numbers_gam.astype(int)
df_middle_gam["oof_prediction_gam"] = oof_pred_gam

Running GAM Cross-Validation...

======================================================================
Fold 1/5
======================================================================
Training rows used: 35,000 / 155,498
Fold 1 ROC-AUC: 0.6622
Fold 1 Accuracy: 0.8854

======================================================================
Fold 2/5
======================================================================
Training rows used: 35,000 / 155,498
Fold 2 ROC-AUC: 0.6599
Fold 2 Accuracy: 0.8858

======================================================================
Fold 3/5
======================================================================
Training rows used: 35,000 / 155,498
Fold 3 ROC-AUC: 0.6520
Fold 3 Accuracy: 0.8870

======================================================================
Fold 4/5
======================================================================
Training rows used: 35,000 / 155,499
Fold 4 ROC-AUC: 0.6575
Fold 4 Accuracy: 0.8810

======================================================================
Fold 5/5
======================================================================
Training rows used: 35,000 / 155,499
Fold 5 ROC-AUC: 0.6640
Fold 5 Accuracy: 0.8851

======================================================================
Cross-Validation Summary
======================================================================
Mean ROC-AUC: 0.6591 (+/- 0.0047)
Mean Accuracy: 0.8849 (+/- 0.0023)

Overall OOF ROC-AUC: 0.6590

In [317]:
import pygam

In [318]:
# Update narwhals to the latest version
!pip install --upgrade narwhals

# Or if that doesn't work, try reinstalling both packages
!pip install --upgrade glum narwhals

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: narwhals in c:\users\malosett\appdata\roaming\python\python311\site-packages (2.19.0)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: glum in c:\users\malosett\appdata\roaming\python\python311\site-packages (3.2.3)
Requirement already satisfied: narwhals in c:\users\malosett\appdata\roaming\python\python311\site-packages (2.19.0)
Requirement already satisfied: formulaic>=1.2.0 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from glum) (1.2.1)
Requirement already satisfied: joblib in c:\users\malosett\appdata\roaming\python\python311\site-packages (from glum) (1.3.2)
Requirement already satisfied: numexpr in c:\programdata\anaconda3\lib\site-packages (from glum) (2.8.7)
Requirement already satisfied: numpy>=1.24 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from glum) (2.4.4)
Requirement already satisfied: packaging in c:\users\malosett\appdata\roaming\python\python311\site-packages (from glum) (25.0)
Requirement already satisfied: pandas>=1.4 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from glum) (3.0.2)
Requirement already satisfied: pyarrow in c:\users\malosett\appdata\roaming\python\python311\site-packages (from glum) (23.0.1)
Requirement already satisfied: scikit-learn>=1.1.0 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from glum) (1.8.0)
Requirement already satisfied: scipy>=1.8.0 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from glum) (1.16.3)
Requirement already satisfied: tabmat>=4.1.5 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from glum) (4.2.1)
Requirement already satisfied: tqdm in c:\programdata\anaconda3\lib\site-packages (from glum) (4.65.0)
Requirement already satisfied: interface-meta>=1.2.0 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from formulaic>=1.2.0->glum) (1.3.0)
Requirement already satisfied: typing-extensions>=4.2.0 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from formulaic>=1.2.0->glum) (4.15.0)
Requirement already satisfied: wrapt>=1.0 in c:\programdata\anaconda3\lib\site-packages (from formulaic>=1.2.0->glum) (1.14.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas>=1.4->glum) (2.8.2)
Requirement already satisfied: tzdata in c:\programdata\anaconda3\lib\site-packages (from pandas>=1.4->glum) (2023.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\malosett\appdata\roaming\python\python311\site-packages (from scikit-learn>=1.1.0->glum) (3.6.0)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from tqdm->glum) (0.4.6)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.4->glum) (1.16.0)

In [319]:
df_middle_gam.columns

Index(['id', 'X_age', 'X_bonus_malus_rating', 'X_distr_channel',
       'X_vehicle_type', 'X_ttm_claims', 'X_policy_count', 'X_risk_code',
       'X_vehicle_age', 'X_policy_tenure', 'X_policy_premium',
       'X_prev_renewal_perc', 'X_upcoming_premium', 'X_cur_renewal_perc',
       'year', 'is_churn', 'U', 'fold_number_gam', 'oof_prediction_gam'],
      dtype='str')

In [320]:
df_middle_gam.columns = ['id','X_age','X_bonus_malus_rating','X_distr_channel','X_vehicle_type','X_ttm_claims',
                         'X_policy_count','X_risk_code','X_vehicle_age','X_policy_tenure','X_policy_premium',
                         'X_prev_renewal_perc','X_upcoming_premium','X_cur_renewal_perc','X_year','1-Z','U',
                         'fold_number_gam','churn_prediction']

## Section 14 — GAM Output: Acceptance Probability

Post-CV steps for `df_middle_gam`:

1. Compute `Z = 1 − churn_prediction` (binary acceptance, where `churn_prediction = oof_prediction_gam`)  
2. Compute `prob_acceptance = 1 − churn_prediction`  
3. Rename columns to canonical names  

**Exported to:** `df_acceptance_gam_model_black_box.csv`

Same schema as the XGBoost and GLM acceptance files — the optimiser can swap between models with no interface change.

In [321]:
df_middle_gam['Z'] = 1 - df_middle_gam['1-Z'].astype(int)
df_middle_gam['prob_acceptance'] = 1 - df_middle_gam['churn_prediction']

In [322]:
df_middle_gam['U+1'] = 1 + df_middle_gam['U']

In [323]:
df_middle_gam.columns

Index(['id', 'X_age', 'X_bonus_malus_rating', 'X_distr_channel',
       'X_vehicle_type', 'X_ttm_claims', 'X_policy_count', 'X_risk_code',
       'X_vehicle_age', 'X_policy_tenure', 'X_policy_premium',
       'X_prev_renewal_perc', 'X_upcoming_premium', 'X_cur_renewal_perc',
       'X_year', '1-Z', 'U', 'fold_number_gam', 'churn_prediction', 'Z',
       'prob_acceptance', 'U+1'],
      dtype='str')

In [324]:
df_middle_gam.loc[:, ['id', 'X_age','X_bonus_malus_rating','X_distr_channel','X_vehicle_type','X_ttm_claims','X_policy_count','X_risk_code','X_vehicle_age',
                           'X_policy_tenure','X_policy_premium', 'U','prob_acceptance','Z','U+1']].to_csv('df_acceptance_gam_model_black_box_feat_processor.csv',sep=';')

In [325]:
df_middle_gam['U+1'] = 1 + df_middle_gam['U']

In [326]:
from sklearn import metrics
import pandas as pd
import numpy as np
from pygam import LogisticGAM, s, f, te
from sklearn.model_selection import KFold, train_test_split
import optuna
from optuna.trial import Trial

class ModelGAM():
    """
    GAM Classifier for Churn Prediction
    GAMs are interpretable and can capture non-linear relationships
    """
    
    def objective(self, trial: Trial, X_train: pd.DataFrame, y_train: pd.Series, 
                  X_val: pd.DataFrame, y_val: pd.Series) -> float:
        """
        Optuna objective for hyperparameter tuning
        """
        # Suggest hyperparameters
        n_splines = trial.suggest_int("n_splines", 10, 50)
        lam = trial.suggest_float("lam", 0.01, 100, log=True)
        
        # Build GAM formula
        # Use splines for continuous features and factors for categorical
        numeric_cols = X_train.select_dtypes(include=[np.number]).columns
        categorical_cols = X_train.select_dtypes(include=['object', 'category']).columns
        
        # Create formula
        formula_terms = []
        for i, col in enumerate(numeric_cols):
            formula_terms.append(s(i, n_splines=n_splines, lam=lam))
        
        # For categorical, use factor terms
        cat_offset = len(numeric_cols)
        for i, col in enumerate(categorical_cols):
            formula_terms.append(f(cat_offset + i, lam=lam))
        
        # Combine numeric and categorical data
        X_train_prepared = self._prepare_data(X_train)
        X_val_prepared = self._prepare_data(X_val)
        
        # Fit model
        try:
            gam_terms = formula_terms[0]
            for term in formula_terms[1:]:
                gam_terms += term
            gam = LogisticGAM(terms=gam_terms, max_iter=100)
            gam.gridsearch(X_train_prepared.values, y_train.values, progress=False)
            
            # Predict
            y_score = gam.predict_proba(X_val_prepared.values)
            roc_auc = metrics.roc_auc_score(y_true=y_val, y_score=y_score)
            
            return roc_auc
        except Exception as e:
            print(f"Error in GAM fitting: {e}")
            return 0.5  # Return baseline score on error
    
    def _prepare_data(self, X: pd.DataFrame) -> pd.DataFrame:
        """
        Prepare data for GAM
        """
        X_prep = X.copy()
        
        # Encode categorical variables as numeric
        categorical_cols = X_prep.select_dtypes(include=['object', 'category']).columns
        if len(categorical_cols) > 0:
            from sklearn.preprocessing import LabelEncoder
            for col in categorical_cols:
                le = LabelEncoder()
                X_prep[col] = le.fit_transform(X_prep[col].astype(str))
        
        return X_prep
    
    def tuning(self, X_train: pd.DataFrame, y_train: pd.Series, 
               X_val: pd.DataFrame, y_val: pd.Series, n_trials: int) -> dict:
        """
        Hyperparameter tuning using Optuna
        """
        study = optuna.create_study(study_name='GAM', direction='maximize')
        study.optimize(lambda trial: self.objective(trial, X_train, y_train, X_val, y_val), 
                      n_trials=n_trials, show_progress_bar=True)
        best_params = study.best_params
        return best_params
    
    def train(self, X_train: pd.DataFrame, y_train: pd.Series, 
              X_val: pd.DataFrame, y_val: pd.Series, best_params: dict):
        """
        Train final GAM model with best parameters
        """
        n_splines = best_params.get('n_splines', 25)
        lam = best_params.get('lam', 0.6)
        
        # Prepare data
        X_train_prep = self._prepare_data(X_train)
        X_val_prep = self._prepare_data(X_val)
        
        # Build formula
        numeric_cols = X_train_prep.select_dtypes(include=[np.number]).columns
        formula_terms = [s(i, n_splines=n_splines, lam=lam) for i in range(len(numeric_cols))]
        gam_terms = formula_terms[0]
        for term in formula_terms[1:]:
            gam_terms += term
        
        # Fit model
        gam = LogisticGAM(terms=gam_terms, max_iter=100)
        gam.gridsearch(X_train_prep.values, y_train.values, progress=False)
        
        return gam


# Cross-validation function for GAM
def cross_validate_gam_with_oof(X, y, n_splits=5, n_trials=20):
    """
    Cross-validation with OOF predictions for GAM
    """
    kfold = KFold(n_splits=n_splits, shuffle=True, random_state=123)
    
    fold_numbers = np.zeros(len(X))
    oof_predictions_proba = np.zeros(len(X))
    oof_predictions_class = np.zeros(len(X))
    
    fold_results = []
    best_params_per_fold = []
    
    for fold_idx, (train_idx, val_idx) in enumerate(kfold.split(X)):
        print(f"\n{'='*70}")
        print(f"Fold {fold_idx + 1}/{n_splits}")
        print(f"{'='*70}")
        
        fold_numbers[val_idx] = fold_idx + 1
        
        X_train_fold = X.iloc[train_idx]
        X_val_fold = X.iloc[val_idx]
        y_train_fold = y.iloc[train_idx]
        y_val_fold = y.iloc[val_idx]
        
        # Split for tuning
        X_train_tune, X_val_tune, y_train_tune, y_val_tune = train_test_split(
            X_train_fold, y_train_fold, test_size=0.2, random_state=123, stratify=y_train_fold
        )
        
        # Tune
        model_gam = ModelGAM()
        best_params = model_gam.tuning(
            X_train_tune, y_train_tune,
            X_val_tune, y_val_tune,
            n_trials=n_trials
        )
        
        print(f"Best params: {best_params}")
        best_params_per_fold.append(best_params)
        
        # Train
        final_model = model_gam.train(
            X_train_fold, y_train_fold,
            X_val_fold, y_val_fold,
            best_params
        )
        
        # Predict
        X_val_prep = model_gam._prepare_data(X_val_fold)
        y_pred_proba = final_model.predict_proba(X_val_prep.values)
        y_pred_class = (y_pred_proba > 0.5).astype(int)
        
        oof_predictions_proba[val_idx] = y_pred_proba
        oof_predictions_class[val_idx] = y_pred_class
        
        # Metrics
        roc_auc = metrics.roc_auc_score(y_val_fold, y_pred_proba)
        accuracy = metrics.accuracy_score(y_val_fold, y_pred_class)
        
        fold_results.append({
            'fold': fold_idx + 1,
            'roc_auc': roc_auc,
            'accuracy': accuracy,
            'n_train': len(train_idx),
            'n_val': len(val_idx)
        })
        
        print(f"Fold {fold_idx + 1} ROC-AUC: {roc_auc:.4f}")
        print(f"Fold {fold_idx + 1} Accuracy: {accuracy:.4f}")
    
    results_df = pd.DataFrame(fold_results)
    
    print(f"\n{'='*70}")
    print("Cross-Validation Summary")
    print(f"{'='*70}")
    print(f"Mean ROC-AUC: {results_df['roc_auc'].mean():.4f} (+/- {results_df['roc_auc'].std():.4f})")
    print(f"Mean Accuracy: {results_df['accuracy'].mean():.4f} (+/- {results_df['accuracy'].std():.4f})")
    
    overall_roc_auc = metrics.roc_auc_score(y, oof_predictions_proba)
    print(f"\nOverall OOF ROC-AUC: {overall_roc_auc:.4f}")
    
    return fold_numbers, oof_predictions_proba, results_df, best_params_per_fold

In [327]:
df_middle_glm_gam = filter_middle_advanced(
    df_sub,
    numeric_filters={
        'X_age': {'multiplier': 1.5, 'method': 'iqr'},
        'X_policy_premium': {'multiplier': 2.0, 'method': 'iqr'},
        'X_upcoming_premium':{'multiplier':2.0,'method':'iqr'},
        'X_vehicle_age': {'method': 'percentile', 'lower_q': 0.05, 'upper_q': 0.95},
        'X_cur_renewal_perc':{'method': 'percentile', 'lower_q': 0.05, 'upper_q': 0.95}
    },
    categorical_filters={
        'X_distr_channel': {'max_categories':12},
        'X_risk_code': {'max_categories': 6},
        'X_vehicle_type': {'max_categories': 8}  # explicit list
    },
    keep_id_cols=['encoded_policy_number']
)

X_age: [8.50, 100.50]
X_policy_premium: [-14.06, 444.14]
X_upcoming_premium: [-15.07, 480.13]
X_vehicle_age: [4.00, 31.00]
X_cur_renewal_perc: [-0.02, 0.11]
X_distr_channel: Kept 12 categories
X_risk_code: Kept 6 categories
X_vehicle_type: Kept 8 categories

Total: 463400 → 194373 rows

In [328]:
from sklearn.preprocessing import LabelEncoder
for cat in cat_cols:
    le = LabelEncoder()
    le.fit(df_middle_glm_gam[cat])
    df_middle_glm_gam[cat] = le.transform(df_middle_glm_gam[cat])

In [329]:
df_middle_glm_gam['U'] = (df_middle_glm_gam['X_upcoming_premium'] - df_middle_glm_gam['X_policy_premium']) / df_middle_glm_gam['X_policy_premium']

In [330]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression


class ModelGLM():
    """GLM replacement using sklearn Logistic Regression."""

    def __init__(self):
        self.categorical_cols = []
        self.numeric_cols = []

    def _build_model(self, C: float) -> Pipeline:
        numeric_transformer = Pipeline(steps=[
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler()),
        ])

        categorical_transformer = Pipeline(steps=[
            ("imputer", SimpleImputer(strategy="most_frequent")),
            ("onehot", OneHotEncoder(handle_unknown="ignore")),
        ])

        preprocessor = ColumnTransformer(
            transformers=[
                ("num", numeric_transformer, self.numeric_cols),
                ("cat", categorical_transformer, self.categorical_cols),
            ],
            remainder="drop",
        )

        clf = LogisticRegression(
            C=C,
            max_iter=1000,
            solver="lbfgs",
            random_state=123,
        )

        return Pipeline(steps=[
            ("preprocessor", preprocessor),
            ("classifier", clf),
        ])

    def objective(self, trial, X_train, y_train, X_val, y_val):
        C = trial.suggest_float("C", 1e-3, 100.0, log=True)

        self.categorical_cols = X_train.select_dtypes(include=["object", "category"]).columns.tolist()
        self.numeric_cols = [c for c in X_train.columns if c not in self.categorical_cols]

        model = self._build_model(C=C)
        model.fit(X_train, y_train)
        y_score = model.predict_proba(X_val)[:, 1]
        return metrics.roc_auc_score(y_true=y_val, y_score=y_score)

    def tuning(self, X_train, y_train, X_val, y_val, n_trials):
        study = optuna.create_study(study_name="LogisticRegression", direction="maximize")
        study.optimize(
            lambda trial: self.objective(trial, X_train, y_train, X_val, y_val),
            n_trials=n_trials,
            show_progress_bar=True,
        )
        return study.best_params

    def train(self, X_train, y_train, X_val, y_val, best_params):
        C = best_params.get("C", 1.0)
        self.categorical_cols = X_train.select_dtypes(include=["object", "category"]).columns.tolist()
        self.numeric_cols = [c for c in X_train.columns if c not in self.categorical_cols]

        model = self._build_model(C=C)
        model.fit(X_train, y_train)
        return model

In [331]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import KFold
from sklearn import metrics
import pandas as pd
import numpy as np


class ModelLinearRegressor:
    """Baseline linear regression model."""

    def train(self, X_train: pd.DataFrame, y_train: pd.Series):
        model = LinearRegression()
        model.fit(X_train, y_train)
        return model


def cross_validate_linear_regression(X, y, n_splits=5):
    """
    Run Linear Regression with KFold cross-validation.
    FeatureProcessor is fit on each training fold and applied to both train and val
    to prevent data leakage. U is kept untouched (not processed).
    """
    kfold = KFold(n_splits=n_splits, shuffle=True, random_state=123)

    lin_fold_numbers = np.zeros(len(X))
    lin_oof = np.zeros(len(X))
    lin_results = []

    # Identify columns to keep untouched (U)
    u_cols = [col for col in ["U"] if col in X.columns]
    x_feature_cols = [col for col in X.columns if col not in u_cols]

    for fold_idx, (train_idx, val_idx) in enumerate(kfold.split(X), 1):
        print(f"\n{'='*70}")
        print(f"Fold {fold_idx}/{n_splits}")
        print(f"{'='*70}")

        X_train_fold = X.iloc[train_idx].reset_index(drop=True)
        X_val_fold = X.iloc[val_idx].reset_index(drop=True)
        y_train_fold = y.iloc[train_idx].reset_index(drop=True)
        y_val_fold = y.iloc[val_idx].reset_index(drop=True)

        lin_fold_numbers[val_idx] = fold_idx

        # --- Separate U from other features ---
        if u_cols:
            U_train = X_train_fold[u_cols].copy()
            U_val = X_val_fold[u_cols].copy()
            X_train_raw = X_train_fold[x_feature_cols].copy()
            X_val_raw = X_val_fold[x_feature_cols].copy()
        else:
            X_train_raw = X_train_fold.copy()
            X_val_raw = X_val_fold.copy()

        # --- Fit preprocessor on train fold only (no leakage) ---
        fp = FeatureProcessor()
        X_train_proc = fp.fit_transform(X_train_raw)
        X_val_proc = fp.transform(X_val_raw)

        # --- Concatenate U back with processed features ---
        if u_cols:
            X_train_proc = pd.concat([U_train.reset_index(drop=True), X_train_proc.reset_index(drop=True)], axis=1)
            X_val_proc = pd.concat([U_val.reset_index(drop=True), X_val_proc.reset_index(drop=True)], axis=1)

        # Linear regression
        linear_model = ModelLinearRegressor().train(X_train_proc, y_train_fold)
        lin_pred = linear_model.predict(X_val_proc)
        lin_oof[val_idx] = lin_pred

        lin_mae = metrics.mean_absolute_error(y_val_fold, lin_pred)
        lin_rmse = np.sqrt(metrics.mean_squared_error(y_val_fold, lin_pred))
        lin_r2 = metrics.r2_score(y_val_fold, lin_pred)

        lin_results.append({
            "fold": fold_idx,
            "model": "LinearRegression",
            "mae": lin_mae,
            "rmse": lin_rmse,
            "r2": lin_r2,
            "n_train": len(train_idx),
            "n_val": len(val_idx),
        })

        print(f"LinearRegression -> MAE: {lin_mae:.4f}, RMSE: {lin_rmse:.4f}, R2: {lin_r2:.4f}")

    lin_df = pd.DataFrame(lin_results)

    print(f"\n{'='*70}")
    print("Overall OOF Metrics")
    print(f"{'='*70}")

    lin_oof_mae = metrics.mean_absolute_error(y, lin_oof)
    lin_oof_rmse = np.sqrt(metrics.mean_squared_error(y, lin_oof))
    lin_oof_r2 = metrics.r2_score(y, lin_oof)

    print(f"LinearRegression OOF -> MAE: {lin_oof_mae:.4f}, RMSE: {lin_oof_rmse:.4f}, R2: {lin_oof_r2:.4f}")

    linear_results = {
        "fold_numbers": lin_fold_numbers,
        "oof_predictions": lin_oof,
        "results_df": lin_df,
        "oof_metrics": {"mae": lin_oof_mae, "rmse": lin_oof_rmse, "r2": lin_oof_r2},
    }

    return linear_results

## Section 15 — Linear Regression: Policy Premium (5-Fold OOF)

### `ModelLinearRegressor`
Plain **sklearn `LinearRegression`** with no hyperparameters — serves as the interpretable baseline for premium prediction.

### `cross_validate_linear_regression`
- 5-fold KFold with no tuning overhead
- Reports MAE, RMSE, R² per fold and overall OOF metrics
- Stores OOF predictions as `linear_reg_oof_prediction` → renamed to `Y_hat`

**Dataset:** `df_middle_reg_linear` — same filtering thresholds as other datasets, with label-encoded categoricals.  
`U = (upcoming_premium − Y) / Y` is computed after column renaming.

**Exported to:** `df_exp_financial_loss_linear_black_box.csv`  
Schema: `id, features, Y (premium), U, Y_hat (predicted premium)`

In [332]:
df_middle_reg_linear = filter_middle_advanced(
    df_sub,
    numeric_filters={
        'X_age': {'multiplier': 1.5, 'method': 'iqr'},
        'X_policy_premium': {'multiplier': 2.0, 'method': 'iqr'},
        'X_upcoming_premium':{'multiplier':2.0,'method':'iqr'},
        'X_vehicle_age': {'method': 'percentile', 'lower_q': 0.05, 'upper_q': 0.95},
        'X_cur_renewal_perc':{'method': 'percentile', 'lower_q': 0.05, 'upper_q': 0.95}
    },
    categorical_filters={
        'X_distr_channel': {'max_categories':12},
        'X_risk_code': {'max_categories': 6},
        'X_vehicle_type': {'max_categories': 8}  # explicit list
    },
    keep_id_cols=['encoded_policy_number']
)

X_age: [8.50, 100.50]
X_policy_premium: [-14.06, 444.14]
X_upcoming_premium: [-15.07, 480.13]
X_vehicle_age: [4.00, 31.00]
X_cur_renewal_perc: [-0.02, 0.11]
X_distr_channel: Kept 12 categories
X_risk_code: Kept 6 categories
X_vehicle_type: Kept 8 categories

Total: 463400 → 194373 rows

In [333]:
from sklearn.preprocessing import LabelEncoder
for cat in cat_cols:
    le = LabelEncoder()
    le.fit(df_middle_reg_linear[cat])
    df_middle_reg_linear[cat] = le.transform(df_middle_reg_linear[cat])

In [334]:
model_features_reg

['X_age',
 'X_bonus_malus_rating',
 'X_distr_channel',
 'X_vehicle_type',
 'X_ttm_claims',
 'X_policy_count',
 'X_risk_code',
 'X_vehicle_age',
 'X_policy_tenure']

In [335]:
# Regression setup (Linear Regression only)
X_reg = df_middle_reg_linear.loc[:,model_features_reg]
y_reg = df_middle_reg_linear['X_policy_premium']

linear_results = cross_validate_linear_regression(
    X_reg, y_reg, n_splits=5
)

# Save OOF outputs for downstream analysis
df_middle_reg_linear['linear_reg_oof_prediction'] = linear_results['oof_predictions']

======================================================================
Fold 1/5
======================================================================
LinearRegression -> MAE: 36.4032, RMSE: 51.5802, R2: 0.2525

======================================================================
Fold 2/5
======================================================================
LinearRegression -> MAE: 36.0190, RMSE: 50.7388, R2: 0.2541

======================================================================
Fold 3/5
======================================================================
LinearRegression -> MAE: 36.0655, RMSE: 50.9690, R2: 0.2527

======================================================================
Fold 4/5
======================================================================
LinearRegression -> MAE: 36.0176, RMSE: 50.6448, R2: 0.2541

======================================================================
Fold 5/5
======================================================================
LinearRegression -> MAE: 36.0272, RMSE: 50.6479, R2: 0.2555

======================================================================
Overall OOF Metrics
======================================================================
LinearRegression OOF -> MAE: 36.1065, RMSE: 50.9174, R2: 0.2538

In [336]:
df_middle_reg_linear.columns

Index(['id', 'X_age', 'X_bonus_malus_rating', 'X_distr_channel',
       'X_vehicle_type', 'X_ttm_claims', 'X_policy_count', 'X_risk_code',
       'X_vehicle_age', 'X_policy_tenure', 'X_policy_premium',
       'X_prev_renewal_perc', 'X_upcoming_premium', 'X_cur_renewal_perc',
       'year', 'is_churn', 'linear_reg_oof_prediction'],
      dtype='str')

In [337]:
df_middle_reg_linear.columns = ['id','X_age', 'X_bonus_malus_rating', 'X_distr_channel',
       'X_vehicle_type', 'X_ttm_claims', 'X_policy_count', 'X_risk_code',
       'X_vehicle_age', 'X_policy_tenure', 'Y', 'X_prev_renewal_perc',
       'X_upcoming_premium', 'X_cur_renewal_perc', 'X_year', '1-Z','Y_hat']

In [338]:
df_middle_reg_linear['U'] = (df_middle_reg_linear['X_upcoming_premium'] - df_middle_reg_linear['Y']) / df_middle_reg_linear['Y']

In [339]:
df_middle_reg_linear['U+1'] = 1 + df_middle_reg_linear['U']

In [345]:
df_middle_reg_linear.columns

Index(['id', 'X_age', 'X_bonus_malus_rating', 'X_distr_channel',
       'X_vehicle_type', 'X_ttm_claims', 'X_policy_count', 'X_risk_code',
       'X_vehicle_age', 'X_policy_tenure', 'Y', 'X_prev_renewal_perc',
       'X_upcoming_premium', 'X_cur_renewal_perc', 'X_year', '1-Z', 'Y_hat',
       'U', 'U+1'],
      dtype='str')

In [346]:
df_middle_reg_linear.loc[:,['id', 'X_age','X_bonus_malus_rating','X_distr_channel','X_vehicle_type','X_ttm_claims','X_policy_count','X_risk_code','X_vehicle_age','X_policy_tenure',
                     'Y','U','U+1','Y_hat']].to_csv('df_exp_financial_loss_linear_black_box_feat_preprocessor.csv',sep=';')

## Section 16 — Model Serialisation

Trained models are persisted as **pickle files** in the `artifacts/` directory for reuse without retraining.

### Saved models

| File | Model | Task |
|---|---|---|
| `artifacts/xgb_classifier_churn.pkl` | XGBoost classifier | Churn probability |
| `artifacts/xgb_regressor_policy_premium.pkl` | XGBoost regressor | Policy premium |
| `artifacts/glm_logistic_churn.pkl` | Logistic Regression (GLM) | Churn probability |
| `artifacts/linear_regression_policy_premium.pkl` | Linear Regression | Policy premium |

Models are loaded and retrained only if not already present in the kernel namespace (`globals()` check), enabling fast re-runs of downstream cells without full retraining.

> **Note:** Feature order must be preserved when loading models for inference.  
> Use `model.feature_names_in_` (available on sklearn estimators) to validate column alignment.

In [350]:
import pickle
from pathlib import Path

import numpy as np
import pandas as pd
import xgboost as xgb
from sklearn.model_selection import train_test_split


ARTIFACTS_DIR = Path("artifacts_preproc_pipeline")
ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)

CLS_PICKLE_PATH = ARTIFACTS_DIR / "xgb_classifier_no_preprocessor.pkl"
REG_PICKLE_PATH = ARTIFACTS_DIR / "xgb_regressor_no_preprocessor.pkl"


def _is_xgb_fitted(model) -> bool:
    try:
        _ = model.get_booster()
        return True
    except Exception:
        return False


# ---------------------------
# 1) Build / retrieve classifier
# ---------------------------
if "xgb_classifier_model" in globals() and isinstance(globals()["xgb_classifier_model"], xgb.XGBClassifier):
    xgb_classifier_model = globals()["xgb_classifier_model"]
else:
    X_cls = df_middle_class.loc[:, model_features_class].copy()
    y_cls = df_middle_class["1-Z"].astype(int).copy()

    Xc_train, Xc_val, yc_train, yc_val = train_test_split(
        X_cls,
        y_cls,
        test_size=0.2,
        random_state=123,
        stratify=y_cls,
    )

    cls_params = {
        "random_state": 123,
        "n_estimators": 250,
        "max_depth": 4,
        "learning_rate": 0.05,
        "subsample": 0.9,
        "colsample_bytree": 0.9,
        "eval_metric": "logloss",
        "enable_categorical": True,
        "early_stopping_rounds": 20,
    }
    xgb_classifier_model = xgb.XGBClassifier(**cls_params)
    xgb_classifier_model.fit(Xc_train, yc_train, eval_set=[(Xc_val, yc_val)], verbose=0)


# ---------------------------
# 2) Build / retrieve regressor
# ---------------------------
if "xgb_model" in globals() and isinstance(globals()["xgb_model"], xgb.XGBRegressor):
    xgb_regressor_model = globals()["xgb_model"]
else:
    xgb_regressor_model = None

# If the existing regressor is not fitted, fit one now.
if xgb_regressor_model is None or not _is_xgb_fitted(xgb_regressor_model):
    X_reg = df_middle.loc[:, model_features_reg].copy()
    y_reg_local = df_middle["Y"].copy()

    Xr_train, Xr_val, yr_train, yr_val = train_test_split(
        X_reg,
        y_reg_local,
        test_size=0.2,
        random_state=123,
    )

    reg_params = {
        "random_state": 123,
        "n_estimators": 300,
        "max_depth": 4,
        "learning_rate": 0.05,
        "subsample": 0.9,
        "colsample_bytree": 0.9,
        "objective": "reg:squarederror",
        "enable_categorical": True,
        "early_stopping_rounds": 20,
    }
    xgb_regressor_model = xgb.XGBRegressor(**reg_params)
    xgb_regressor_model.fit(Xr_train, yr_train, eval_set=[(Xr_val, yr_val)], verbose=0)


# ---------------------------
# 3) Save to pickle
# ---------------------------
with open(CLS_PICKLE_PATH, "wb") as f:
    pickle.dump(xgb_classifier_model, f)

with open(REG_PICKLE_PATH, "wb") as f:
    pickle.dump(xgb_regressor_model, f)

print(f"Saved classifier to: {CLS_PICKLE_PATH.resolve()}")
print(f"Saved regressor to:  {REG_PICKLE_PATH.resolve()}")

Saved classifier to: C:\Users\malosett\OneDrive - Assicurazioni Generali S.p.A\coding\pricing_optim\artifacts_preproc_pipeline\xgb_classifier_no_preprocessor.pkl
Saved regressor to:  C:\Users\malosett\OneDrive - Assicurazioni Generali S.p.A\coding\pricing_optim\artifacts_preproc_pipeline\xgb_regressor_no_preprocessor.pkl

In [351]:
model_features_class

['X_age',
 'X_bonus_malus_rating',
 'X_distr_channel',
 'X_vehicle_type',
 'X_ttm_claims',
 'X_policy_count',
 'X_risk_code',
 'X_vehicle_age',
 'X_policy_tenure',
 'X_policy_premium',
 'U']

In [349]:
model_features_reg

['X_age',
 'X_bonus_malus_rating',
 'X_distr_channel',
 'X_vehicle_type',
 'X_ttm_claims',
 'X_policy_count',
 'X_risk_code',
 'X_vehicle_age',
 'X_policy_tenure']

## Section 17 — Single-Record Inference (Smoke Test)

Loads the serialised XGBoost classifier and regressor from `artifacts/` and runs a single-record prediction to verify the pickle round-trip is correct.

**Features:**
- **FeatureProcessor with PCA Whitening**: Each model pipeline includes preprocessing that applies multivariate whitening
- **Mahalanobis Distance**: Whitening ensures Euclidean distance in transformed space = Mahalanobis distance in original space
- **U Column Handling**: The premium change ratio `U` is kept untouched (not preprocessed)
- **Dimensionality Reduction**: Components are selected to explain 95% of variance
- **Complete Pipeline**: Each pickle contains `{preprocessor, model, u_cols, x_feature_cols}` for reproducible inference

**Checks performed:**
- Classifier: outputs churn probability and hard class label
- Regressor: outputs predicted policy premium
- Both: preprocessing is applied consistently using saved FeatureProcessor
- Displays both original and preprocessed (PCA-whitened) features

This cell is intended as a **quick sanity check** before handing off models to production or the optimisation module.

## Section 18 — Save All Four Models with FeatureProcessor (PCA Whitening)

Final cell: trains and serialises all four models with integrated **FeatureProcessor** featuring **PCA whitening**:

1. **XGBClassifier** — churn (on `df_middle_class`) + PCA preprocessing
2. **XGBRegressor** — premium (on `df_middle`) + PCA preprocessing
3. **GLM logistic** — churn (on `df_middle_glm`) + PCA preprocessing
4. **LinearRegression** — premium (on `df_middle_reg_linear`) + PCA preprocessing

**Preprocessing pipeline (`FeatureProcessor` with `use_pca=True`):**
- **Whitening**: Transforms data so covariance matrix = Identity
- **Dimensionality reduction**: Retains components explaining 95% of variance
- **U preservation**: Premium change ratio `U` is excluded from processing and preserved in original scale
- **Variance reporting**: Displays number of components kept and variance explained for each model

Each model is saved as a **complete pipeline** containing:
- `preprocessor`: fitted FeatureProcessor with PCA whitening
- `model`: trained sklearn/xgboost model
- `u_cols`: list of untouched columns (e.g., ['U'])
- `x_feature_cols`: list of feature columns to preprocess

**Benefits:**
- **Consistent preprocessing**: Same transformations applied in training and inference
- **No data leakage**: Preprocessor fitted only on training data
- **Mahalanobis distance**: Whitening makes distance metrics more meaningful
- **Production-ready**: Single pickle file contains everything needed for inference

In [356]:
import pickle
from pathlib import Path

import pandas as pd


ARTIFACTS_DIR = Path("artifacts_preproc_pipeline")
CLS_PICKLE_PATH = ARTIFACTS_DIR / "xgb_classifier_churn_feat_preproc.pkl"
REG_PICKLE_PATH = ARTIFACTS_DIR / "xgb_regressor_policy_premium_feat_preproc.pkl"


# 1) Load model pipelines from pickle
with open(CLS_PICKLE_PATH, "rb") as f:
    cls_pipeline = pickle.load(f)

with open(REG_PICKLE_PATH, "rb") as f:
    reg_pipeline = pickle.load(f)

print("Loaded XGBClassifier pipeline components:")
print(f"  - Preprocessor: {type(cls_pipeline['preprocessor']).__name__}")
print(f"  - Model: {type(cls_pipeline['model']).__name__}")
print(f"  - U columns: {cls_pipeline['u_cols']}")
print(f"  - Feature columns: {len(cls_pipeline['x_feature_cols'])} features\n")

print("Loaded XGBRegressor pipeline components:")
print(f"  - Preprocessor: {type(reg_pipeline['preprocessor']).__name__}")
print(f"  - Model: {type(reg_pipeline['model']).__name__}")
print(f"  - U columns: {reg_pipeline['u_cols']}")
print(f"  - Feature columns: {len(reg_pipeline['x_feature_cols'])} features\n")


# 2) Build a single-record input for each model
single_cls_record = df_middle_class.loc[:, model_features_class].iloc[[0]].copy()
single_reg_record = df_middle.loc[:, model_features_reg].iloc[[0]].copy()


# 3) Preprocess inputs using the saved preprocessors
def preprocess_for_inference(X, pipeline):
    """Apply preprocessing pipeline for inference"""
    u_cols = pipeline['u_cols']
    x_feature_cols = pipeline['x_feature_cols']
    preprocessor = pipeline['preprocessor']
    
    if u_cols:
        U_data = X[u_cols].copy()
        X_features = X[x_feature_cols].copy()
    else:
        X_features = X.copy()
    
    # Transform features
    X_proc = preprocessor.transform(X_features)
    
    # Concatenate U back if present
    if u_cols:
        X_preprocessed = pd.concat([U_data.reset_index(drop=True), X_proc.reset_index(drop=True)], axis=1)
    else:
        X_preprocessed = X_proc
    
    return X_preprocessed


# Preprocess classifier input
single_cls_preprocessed = preprocess_for_inference(single_cls_record, cls_pipeline)

# Preprocess regressor input
single_reg_preprocessed = preprocess_for_inference(single_reg_record, reg_pipeline)


# 4) Inference on preprocessed data
cls_prob = float(cls_pipeline['model'].predict_proba(single_cls_preprocessed)[:, 1][0])
cls_pred = int(cls_pipeline['model'].predict(single_cls_preprocessed)[0])
reg_pred = float(reg_pipeline['model'].predict(single_reg_preprocessed)[0])

print("="*70)
print("Single-record classifier inference (with PCA whitening preprocessing):")
print("="*70)
print(f"  Predicted churn probability: {cls_prob:.6f}")
print(f"  Predicted churn class:       {cls_pred}")

print("\n" + "="*70)
print("Single-record regressor inference (with PCA whitening preprocessing):")
print("="*70)
print(f"  Predicted premium:           {reg_pred:.6f}")

print("\n" + "="*70)
print("Input record used for classifier (original):")
print("="*70)
print(single_cls_record)

print("\n" + "="*70)
print("Input record used for classifier (preprocessed with PCA):")
print("="*70)
print(single_cls_preprocessed)

print("\n" + "="*70)
print("Input record used for regressor (original):")
print("="*70)
print(single_reg_record)

print("\n" + "="*70)
print("Input record used for regressor (preprocessed with PCA):")
print("="*70)
print(single_reg_preprocessed)

Loaded XGBClassifier pipeline components:
  - Preprocessor: FeatureProcessor
  - Model: XGBClassifier
  - U columns: ['U']
  - Feature columns: 10 features

Loaded XGBRegressor pipeline components:
  - Preprocessor: FeatureProcessor
  - Model: XGBRegressor
  - U columns: []
  - Feature columns: 9 features

======================================================================
Single-record classifier inference (with PCA whitening preprocessing):
======================================================================
  Predicted churn probability: 0.232544
  Predicted churn class:       0

======================================================================
Single-record regressor inference (with PCA whitening preprocessing):
======================================================================
  Predicted premium:           200.003983

======================================================================
Input record used for classifier (original):
======================================================================
   X_age  X_bonus_malus_rating  X_distr_channel  X_vehicle_type  X_ttm_claims  \
7   93.0                  45.0                5               7             0

   X_policy_count  X_risk_code  X_vehicle_age  X_policy_tenure  \
7               1            0           24.0             24.0

   X_policy_premium         U
7          175.7725  0.123099

======================================================================
Input record used for classifier (preprocessed with PCA):
======================================================================
          U       PC1       PC2
0  0.123099  0.459083 -2.540587

======================================================================
Input record used for regressor (original):
======================================================================
   X_age  X_bonus_malus_rating  X_distr_channel  X_vehicle_type  X_ttm_claims  \
7   93.0                  45.0                5               7             0

   X_policy_count  X_risk_code  X_vehicle_age  X_policy_tenure
7               1            0           24.0             24.0

======================================================================
Input record used for regressor (preprocessed with PCA):
======================================================================
        PC1       PC2       PC3       PC4
7 -2.552622  0.562873 -0.562701  5.357872

In [242]:
df_middle_reg.columns

Index(['id', 'X_age', 'X_bonus_malus_rating', 'X_distr_channel',
       'X_vehicle_type', 'X_ttm_claims', 'X_policy_count', 'X_risk_code',
       'X_vehicle_age', 'X_policy_tenure', 'X_policy_premium',
       'X_prev_renewal_perc', 'X_upcoming_premium', 'X_cur_renewal_perc',
       'year', 'is_churn', 'U'],
      dtype='str')

In [357]:
# Save all requested models as pickle WITH FeatureProcessor (PCA whitening):
# 1) XGBClassifier (churn) + preprocessor
# 2) XGBRegressor (premium) + preprocessor
# 3) GLM logistic model (churn) + preprocessor
# 4) Linear model (premium) + preprocessor

import pickle
from pathlib import Path

import numpy as np
import pandas as pd
import xgboost as xgb
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split


ARTIFACTS_DIR = Path("artifacts_preproc_pipeline")
ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)

PATH_XGB_CLASSIFIER = ARTIFACTS_DIR / "xgb_classifier_churn_feat_preproc.pkl"
PATH_XGB_REGRESSOR = ARTIFACTS_DIR / "xgb_regressor_policy_premium_feat_preproc.pkl"
PATH_GLM_LOGISTIC = ARTIFACTS_DIR / "glm_logistic_churn_feat_preproc.pkl"
PATH_LINEAR_MODEL = ARTIFACTS_DIR / "linear_regression_policy_premium_feat_preproc.pkl"


def _to_xgb_compatible(df: pd.DataFrame) -> pd.DataFrame:
    df2 = df.copy()
    obj_cols = df2.select_dtypes(include=["object"]).columns
    for col in obj_cols:
        df2[col] = df2[col].astype("category")
    return df2


def _is_fitted_xgb(model) -> bool:
    try:
        _ = model.get_booster()
        return True
    except Exception:
        return False


def preprocess_with_U_separation(X, use_pca=True, n_components=None, explained_variance_threshold=0.95):
    """
    Preprocess features with FeatureProcessor, keeping U untouched.
    
    Returns:
    --------
    X_preprocessed : DataFrame with U (if present) + processed features
    preprocessor : fitted FeatureProcessor
    """
    # Identify U column
    u_cols = [col for col in ["U"] if col in X.columns]
    x_feature_cols = [col for col in X.columns if col not in u_cols]
    
    if u_cols:
        U_data = X[u_cols].copy()
        X_raw = X[x_feature_cols].copy()
    else:
        X_raw = X.copy()
    
    # Fit FeatureProcessor with PCA whitening
    preprocessor = FeatureProcessor(
        use_pca=use_pca,
        n_components=n_components,
        explained_variance_threshold=explained_variance_threshold
    )
    X_proc = preprocessor.fit_transform(X_raw)
    
    # Concatenate U back
    if u_cols:
        X_preprocessed = pd.concat([U_data.reset_index(drop=True), X_proc.reset_index(drop=True)], axis=1)
    else:
        X_preprocessed = X_proc
    
    return X_preprocessed, preprocessor


# ----------------------------
# XGB Classifier (churn)
# ----------------------------
print("="*70)
print("Training XGBClassifier with FeatureProcessor (PCA whitening)...")
print("="*70)

X_cls = df_middle_class.loc[:, model_features_class].copy()
y_cls = df_middle_class["1-Z"].astype(int).copy()

# Split first
Xc_train_raw, Xc_val_raw, yc_train, yc_val = train_test_split(
    X_cls, y_cls, test_size=0.2, random_state=123, stratify=y_cls
)

# Preprocess with U separation and PCA whitening
Xc_train_proc, cls_preprocessor = preprocess_with_U_separation(
    Xc_train_raw, 
    use_pca=True, 
    explained_variance_threshold=0.95
)

# Transform validation set with fitted preprocessor
u_cols_cls = [col for col in ["U"] if col in Xc_val_raw.columns]
x_feature_cols_cls = [col for col in Xc_val_raw.columns if col not in u_cols_cls]

if u_cols_cls:
    U_val = Xc_val_raw[u_cols_cls].copy()
    Xc_val_raw_features = Xc_val_raw[x_feature_cols_cls].copy()
else:
    Xc_val_raw_features = Xc_val_raw.copy()

Xc_val_proc = cls_preprocessor.transform(Xc_val_raw_features)

if u_cols_cls:
    Xc_val_proc = pd.concat([U_val.reset_index(drop=True), Xc_val_proc.reset_index(drop=True)], axis=1)

# Convert to XGB compatible format
Xc_train_proc = _to_xgb_compatible(Xc_train_proc)
Xc_val_proc = _to_xgb_compatible(Xc_val_proc)

# Train XGBClassifier
xgb_classifier_model = xgb.XGBClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=4,
    subsample=0.9,
    colsample_bytree=0.9,
    eval_metric="logloss",
    random_state=123,
    enable_categorical=True,
    early_stopping_rounds=20,
)
xgb_classifier_model.fit(Xc_train_proc, yc_train, eval_set=[(Xc_val_proc, yc_val)], verbose=0)

# Get variance info
var_info_cls = cls_preprocessor.get_explained_variance_info()
print(f"Classifier - Components kept: {var_info_cls['n_components_kept']}")
print(f"Classifier - Variance explained: {var_info_cls['cumulative_variance_ratio'][var_info_cls['n_components_kept']-1]:.4f}")


# ----------------------------
# XGB Regressor (policy_premium)
# ----------------------------
print("\n" + "="*70)
print("Training XGBRegressor with FeatureProcessor (PCA whitening)...")
print("="*70)

X_reg = df_middle.loc[:, model_features_reg].copy()
y_reg_local = df_middle["Y"].copy()

# Split first
Xr_train_raw, Xr_val_raw, yr_train, yr_val = train_test_split(
    X_reg, y_reg_local, test_size=0.2, random_state=123
)

# Preprocess with PCA whitening (no U for regressor)
Xr_train_proc, reg_preprocessor = preprocess_with_U_separation(
    Xr_train_raw, 
    use_pca=True, 
    explained_variance_threshold=0.95
)

# Transform validation set
Xr_val_proc = reg_preprocessor.transform(Xr_val_raw)

# Convert to XGB compatible format
Xr_train_proc = _to_xgb_compatible(Xr_train_proc)
Xr_val_proc = _to_xgb_compatible(Xr_val_proc)

# Train XGBRegressor
xgb_regressor_model = xgb.XGBRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=4,
    subsample=0.9,
    colsample_bytree=0.9,
    objective="reg:squarederror",
    random_state=123,
    enable_categorical=True,
    early_stopping_rounds=20,
)
xgb_regressor_model.fit(Xr_train_proc, yr_train, eval_set=[(Xr_val_proc, yr_val)], verbose=0)

# Get variance info
var_info_reg = reg_preprocessor.get_explained_variance_info()
print(f"Regressor - Components kept: {var_info_reg['n_components_kept']}")
print(f"Regressor - Variance explained: {var_info_reg['cumulative_variance_ratio'][var_info_reg['n_components_kept']-1]:.4f}")


# ----------------------------
# GLM logistic model (churn)
# ----------------------------
print("\n" + "="*70)
print("Training GLM Logistic with FeatureProcessor (PCA whitening)...")
print("="*70)

X_glm = df_middle_glm.loc[:, model_features_class].copy()
y_glm = df_middle_glm["1-Z"].astype(int).copy()

# Split first
Xg_train_raw, Xg_val_raw, yg_train, yg_val = train_test_split(
    X_glm, y_glm, test_size=0.2, random_state=123, stratify=y_glm
)

# Preprocess with U separation and PCA whitening
Xg_train_proc, glm_preprocessor = preprocess_with_U_separation(
    Xg_train_raw, 
    use_pca=True, 
    explained_variance_threshold=0.95
)

# Transform validation set
u_cols_glm = [col for col in ["U"] if col in Xg_val_raw.columns]
x_feature_cols_glm = [col for col in Xg_val_raw.columns if col not in u_cols_glm]

if u_cols_glm:
    U_val_glm = Xg_val_raw[u_cols_glm].copy()
    Xg_val_raw_features = Xg_val_raw[x_feature_cols_glm].copy()
else:
    Xg_val_raw_features = Xg_val_raw.copy()

Xg_val_proc = glm_preprocessor.transform(Xg_val_raw_features)

if u_cols_glm:
    Xg_val_proc = pd.concat([U_val_glm.reset_index(drop=True), Xg_val_proc.reset_index(drop=True)], axis=1)

# Train GLM
glm_model_obj = ModelGLM()
glm_logistic_model = glm_model_obj.train(
    Xg_train_proc,
    yg_train,
    Xg_val_proc,
    yg_val,
    {"C": 1.0},
)

var_info_glm = glm_preprocessor.get_explained_variance_info()
print(f"GLM - Components kept: {var_info_glm['n_components_kept']}")
print(f"GLM - Variance explained: {var_info_glm['cumulative_variance_ratio'][var_info_glm['n_components_kept']-1]:.4f}")


# ----------------------------
# Linear model (policy_premium)
# ----------------------------
print("\n" + "="*70)
print("Training Linear Regression with FeatureProcessor (PCA whitening)...")
print("="*70)

if "df_middle_reg_linear" in globals():
    X_lin = df_middle_reg_linear.loc[:, model_features_reg].copy()
    y_lin = df_middle_reg_linear["Y"].copy()
else:
    X_lin = df_middle.loc[:, model_features_reg].copy()
    y_lin = df_middle["Y"].copy()

# Preprocess with PCA whitening (no U for regressor)
X_lin_proc, linear_preprocessor = preprocess_with_U_separation(
    X_lin, 
    use_pca=True, 
    explained_variance_threshold=0.95
)

# Train Linear Regression
linear_model = LinearRegression()
linear_model.fit(X_lin_proc, y_lin)

var_info_lin = linear_preprocessor.get_explained_variance_info()
print(f"Linear - Components kept: {var_info_lin['n_components_kept']}")
print(f"Linear - Variance explained: {var_info_lin['cumulative_variance_ratio'][var_info_lin['n_components_kept']-1]:.4f}")


# ----------------------------
# Save all models WITH PREPROCESSING
# ----------------------------
print("\n" + "="*70)
print("Saving models with preprocessors...")
print("="*70)

# Save as dictionary with both model and preprocessor
xgb_cls_pipeline = {
    "preprocessor": cls_preprocessor,
    "model": xgb_classifier_model,
    "u_cols": u_cols_cls,
    "x_feature_cols": x_feature_cols_cls,
}

xgb_reg_pipeline = {
    "preprocessor": reg_preprocessor,
    "model": xgb_regressor_model,
    "u_cols": [],  # No U for regressor
    "x_feature_cols": model_features_reg,
}

glm_pipeline = {
    "preprocessor": glm_preprocessor,
    "model": glm_logistic_model,
    "u_cols": u_cols_glm,
    "x_feature_cols": x_feature_cols_glm,
}

linear_pipeline = {
    "preprocessor": linear_preprocessor,
    "model": linear_model,
    "u_cols": [],  # No U for regressor
    "x_feature_cols": model_features_reg,
}

with open(PATH_XGB_CLASSIFIER, "wb") as f:
    pickle.dump(xgb_cls_pipeline, f)

with open(PATH_XGB_REGRESSOR, "wb") as f:
    pickle.dump(xgb_reg_pipeline, f)

with open(PATH_GLM_LOGISTIC, "wb") as f:
    pickle.dump(glm_pipeline, f)

with open(PATH_LINEAR_MODEL, "wb") as f:
    pickle.dump(linear_pipeline, f)

print(f"\n✓ Saved: {PATH_XGB_CLASSIFIER.resolve()}")
print(f"✓ Saved: {PATH_XGB_REGRESSOR.resolve()}")
print(f"✓ Saved: {PATH_GLM_LOGISTIC.resolve()}")
print(f"✓ Saved: {PATH_LINEAR_MODEL.resolve()}")
print("\nAll models saved with FeatureProcessor (PCA whitening)!")
print("Each pickle contains: {'preprocessor', 'model', 'u_cols', 'x_feature_cols'}")

======================================================================
Training XGBClassifier with FeatureProcessor (PCA whitening)...
======================================================================
Classifier - Components kept: 2
Classifier - Variance explained: 0.9545

======================================================================
Training XGBRegressor with FeatureProcessor (PCA whitening)...
======================================================================
Regressor - Components kept: 4
Regressor - Variance explained: 0.9626

======================================================================
Training GLM Logistic with FeatureProcessor (PCA whitening)...
======================================================================
GLM - Components kept: 2
GLM - Variance explained: 0.9545

======================================================================
Training Linear Regression with FeatureProcessor (PCA whitening)...
======================================================================
Linear - Components kept: 4
Linear - Variance explained: 0.9628

======================================================================
Saving models with preprocessors...
======================================================================

✓ Saved: C:\Users\malosett\OneDrive - Assicurazioni Generali S.p.A\coding\pricing_optim\artifacts_preproc_pipeline\xgb_classifier_churn_feat_preproc.pkl
✓ Saved: C:\Users\malosett\OneDrive - Assicurazioni Generali S.p.A\coding\pricing_optim\artifacts_preproc_pipeline\xgb_regressor_policy_premium_feat_preproc.pkl
✓ Saved: C:\Users\malosett\OneDrive - Assicurazioni Generali S.p.A\coding\pricing_optim\artifacts_preproc_pipeline\glm_logistic_churn_feat_preproc.pkl
✓ Saved: C:\Users\malosett\OneDrive - Assicurazioni Generali S.p.A\coding\pricing_optim\artifacts_preproc_pipeline\linear_regression_policy_premium_feat_preproc.pkl

All models saved with FeatureProcessor (PCA whitening)!
Each pickle contains: {'preprocessor', 'model', 'u_cols', 'x_feature_cols'}